// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: event_schema_versions_queries.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const eventSubscriptionSchemaVersionsSet = `-- name: EventSubscriptionSchemaVersionsSet :exec
UPDATE event_subscriptions SET schema_versions=$1::text[],updated_at=clock_timestamp() WHERE id=$2::uuid
`

type EventSubscriptionSchemaVersionsSetParams struct {
	SchemaVersions []string
	SubscriptionID pgtype.UUID
}

func (q *Queries) EventSubscriptionSchemaVersionsSet(ctx context.Context, db DBTX, arg EventSubscriptionSchemaVersionsSetParams) error {
	_, err := db.Exec(ctx, eventSubscriptionSchemaVersionsSet, arg.SchemaVersions, arg.SubscriptionID)
	return err
}
