// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: event_replay_preview_queries.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const eventReplayPreviewCandidates = `-- name: EventReplayPreviewCandidates :many
SELECT o.id, o.created_at, o.payload,
       CASE WHEN o.recipient_snapshot IS NULL THEN 'unknown'
            WHEN EXISTS (SELECT 1 FROM jsonb_array_elements(o.recipient_snapshot) s(recipient)
                         WHERE s.recipient->>'id'=$1::text
                           AND s.recipient->>'app_id'=$2::text)
            THEN 'captured' ELSE 'not_captured' END::text AS original_recipient
FROM event_fanout_outbox o
WHERE o.account_id=$3::uuid
  AND o.created_at >= $4::timestamptz AND o.created_at < $5::timestamptz
  AND (o.created_at,o.id) > ($6::timestamptz,$7::bigint)
ORDER BY o.created_at, o.id LIMIT $8::integer
`

type EventReplayPreviewCandidatesParams struct {
	SubscriptionID string
	AppID          string
	AccountID      pgtype.UUID
	FromAt         pgtype.Timestamptz
	CutoffAt       pgtype.Timestamptz
	AfterAt        pgtype.Timestamptz
	AfterID        int64
	PageLimit      int32
}

type EventReplayPreviewCandidatesRow struct {
	ID                int64
	CreatedAt         pgtype.Timestamptz
	Payload           []byte
	OriginalRecipient string
}

func (q *Queries) EventReplayPreviewCandidates(ctx context.Context, db DBTX, arg EventReplayPreviewCandidatesParams) ([]EventReplayPreviewCandidatesRow, error) {
	rows, err := db.Query(ctx, eventReplayPreviewCandidates,
		arg.SubscriptionID,
		arg.AppID,
		arg.AccountID,
		arg.FromAt,
		arg.CutoffAt,
		arg.AfterAt,
		arg.AfterID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EventReplayPreviewCandidatesRow{}
	for rows.Next() {
		var i EventReplayPreviewCandidatesRow
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.Payload,
			&i.OriginalRecipient,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const eventReplayPreviewEarliestRetained = `-- name: EventReplayPreviewEarliestRetained :one
SELECT created_at FROM event_fanout_outbox WHERE account_id=$1::uuid
ORDER BY created_at, id LIMIT 1
`

func (q *Queries) EventReplayPreviewEarliestRetained(ctx context.Context, db DBTX, accountID pgtype.UUID) (pgtype.Timestamptz, error) {
	row := db.QueryRow(ctx, eventReplayPreviewEarliestRetained, accountID)
	var created_at pgtype.Timestamptz
	err := row.Scan(&created_at)
	return created_at, err
}

const eventReplayPreviewTarget = `-- name: EventReplayPreviewTarget :one
SELECT s.id, s.account_id, s.app_id, s.source, s.type, s.filter, s.enabled, s.created_at, s.updated_at, a.slug AS app_slug,
       EXISTS (SELECT 1 FROM event_subscription_work_bindings b WHERE b.subscription_id=s.id) AS work_bound
FROM event_subscriptions s JOIN apps a ON a.id=s.app_id AND a.account_id=s.account_id
WHERE s.id=$1::uuid AND s.app_id=$2::uuid
  AND s.account_id=$3::uuid AND a.status <> 'deleted'
`

type EventReplayPreviewTargetParams struct {
	SubscriptionID pgtype.UUID
	AppID          pgtype.UUID
	AccountID      pgtype.UUID
}

type EventReplayPreviewTargetRow struct {
	ID        pgtype.UUID
	AccountID pgtype.UUID
	AppID     pgtype.UUID
	Source    string
	Type      string
	Filter    []byte
	Enabled   bool
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
	AppSlug   string
	WorkBound bool
}

func (q *Queries) EventReplayPreviewTarget(ctx context.Context, db DBTX, arg EventReplayPreviewTargetParams) (EventReplayPreviewTargetRow, error) {
	row := db.QueryRow(ctx, eventReplayPreviewTarget, arg.SubscriptionID, arg.AppID, arg.AccountID)
	var i EventReplayPreviewTargetRow
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.AppID,
		&i.Source,
		&i.Type,
		&i.Filter,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AppSlug,
		&i.WorkBound,
	)
	return i, err
}
