// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: event_receipt_queries.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const eventReceiptAcceptedAt = `-- name: EventReceiptAcceptedAt :one
SELECT created_at FROM event_fanout_outbox
WHERE account_id=$1::uuid AND source=$2::text AND event_id=$3::text
`

type EventReceiptAcceptedAtParams struct {
	AccountID   pgtype.UUID
	EventSource string
	EventID     string
}

func (q *Queries) EventReceiptAcceptedAt(ctx context.Context, db DBTX, arg EventReceiptAcceptedAtParams) (pgtype.Timestamptz, error) {
	row := db.QueryRow(ctx, eventReceiptAcceptedAt, arg.AccountID, arg.EventSource, arg.EventID)
	var created_at pgtype.Timestamptz
	err := row.Scan(&created_at)
	return created_at, err
}

const eventReceiptCancellations = `-- name: EventReceiptCancellations :many
SELECT c.id, c.app_id, c.cancelled_count, c.created_at
FROM invocation_work_cancellations c JOIN apps a ON a.id=c.app_id
WHERE a.account_id=$1::uuid AND c.id=ANY($2::uuid[])
  AND c.created_at >= $3::timestamptz
`

type EventReceiptCancellationsParams struct {
	AccountID     pgtype.UUID
	InvocationIds []pgtype.UUID
	AcceptedAt    pgtype.Timestamptz
}

type EventReceiptCancellationsRow struct {
	ID             pgtype.UUID
	AppID          pgtype.UUID
	CancelledCount int64
	CreatedAt      pgtype.Timestamptz
}

func (q *Queries) EventReceiptCancellations(ctx context.Context, db DBTX, arg EventReceiptCancellationsParams) ([]EventReceiptCancellationsRow, error) {
	rows, err := db.Query(ctx, eventReceiptCancellations, arg.AccountID, arg.InvocationIds, arg.AcceptedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EventReceiptCancellationsRow{}
	for rows.Next() {
		var i EventReceiptCancellationsRow
		if err := rows.Scan(
			&i.ID,
			&i.AppID,
			&i.CancelledCount,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const eventReceiptInvocations = `-- name: EventReceiptInvocations :many
SELECT i.id, i.app_id, i.state, i.attempts, i.replay_generation, coalesce(i.last_error, '')::text AS last_error,
       i.due_at, i.created_at, i.completed_at, coalesce(i.work_policy_name, '')::text AS work_policy_name,
       i.queue_binding_id, i.work_expires_at, i.start_deadline_at,
       EXISTS (SELECT 1 FROM invocation_keyed_replays r WHERE r.parent_invocation_id=i.id) AS keyed_replay_created,
       EXISTS (SELECT 1 FROM invocation_plain_replays r WHERE r.parent_invocation_id=i.id) AS plain_replay_created
FROM invocations i JOIN apps a ON a.id=i.app_id AND a.account_id=i.account_id
WHERE i.account_id=$1::uuid AND i.id=ANY($2::uuid[])
  AND i.created_at >= $3::timestamptz
`

type EventReceiptInvocationsParams struct {
	AccountID     pgtype.UUID
	InvocationIds []pgtype.UUID
	AcceptedAt    pgtype.Timestamptz
}

type EventReceiptInvocationsRow struct {
	ID                 pgtype.UUID
	AppID              pgtype.UUID
	State              string
	Attempts           int32
	ReplayGeneration   int64
	LastError          string
	DueAt              pgtype.Timestamptz
	CreatedAt          pgtype.Timestamptz
	CompletedAt        pgtype.Timestamptz
	WorkPolicyName     string
	QueueBindingID     pgtype.UUID
	WorkExpiresAt      pgtype.Timestamptz
	StartDeadlineAt    pgtype.Timestamptz
	KeyedReplayCreated bool
	PlainReplayCreated bool
}

func (q *Queries) EventReceiptInvocations(ctx context.Context, db DBTX, arg EventReceiptInvocationsParams) ([]EventReceiptInvocationsRow, error) {
	rows, err := db.Query(ctx, eventReceiptInvocations, arg.AccountID, arg.InvocationIds, arg.AcceptedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EventReceiptInvocationsRow{}
	for rows.Next() {
		var i EventReceiptInvocationsRow
		if err := rows.Scan(
			&i.ID,
			&i.AppID,
			&i.State,
			&i.Attempts,
			&i.ReplayGeneration,
			&i.LastError,
			&i.DueAt,
			&i.CreatedAt,
			&i.CompletedAt,
			&i.WorkPolicyName,
			&i.QueueBindingID,
			&i.WorkExpiresAt,
			&i.StartDeadlineAt,
			&i.KeyedReplayCreated,
			&i.PlainReplayCreated,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const eventReceiptMetadata = `-- name: EventReceiptMetadata :one
SELECT o.id, o.account_id, o.source, o.event_id, o.event_type,
       coalesce(o.payload->>'accountid', o.payload->>'account_id', o.account_id::text)::text AS invocation_account_id,
       coalesce(o.schema_version, '')::text AS schema_version, o.created_at, o.delivered_at,
       o.state, o.recipient_claims, (o.recipient_snapshot IS NOT NULL)::boolean AS snapshot_captured,
       jsonb_array_length(coalesce(o.recipient_snapshot, '[]'::jsonb))::integer AS recipient_count,
       coalesce((SELECT jsonb_object_agg(counts.state, counts.n) FROM (
           SELECT coalesce(r.state, o.recipient_progress -> (s.recipient->>'id') ->>'state', 'pending') AS state, count(*) AS n
           FROM jsonb_array_elements(coalesce(o.recipient_snapshot, '[]'::jsonb)) s(recipient)
           LEFT JOIN event_fanout_recipients r ON r.outbox_id=o.id AND r.subscription_id=s.recipient->>'id'
           GROUP BY 1
       ) counts), '{}'::jsonb)::jsonb AS routing_summary
FROM event_fanout_outbox o
WHERE o.account_id=$1::uuid AND o.source=$2::text AND o.event_id=$3::text
`

type EventReceiptMetadataParams struct {
	AccountID   pgtype.UUID
	EventSource string
	EventID     string
}

type EventReceiptMetadataRow struct {
	ID                  int64
	AccountID           pgtype.UUID
	Source              string
	EventID             string
	EventType           string
	InvocationAccountID string
	SchemaVersion       string
	CreatedAt           pgtype.Timestamptz
	DeliveredAt         pgtype.Timestamptz
	State               string
	RecipientClaims     bool
	SnapshotCaptured    bool
	RecipientCount      int32
	RoutingSummary      []byte
}

func (q *Queries) EventReceiptMetadata(ctx context.Context, db DBTX, arg EventReceiptMetadataParams) (EventReceiptMetadataRow, error) {
	row := db.QueryRow(ctx, eventReceiptMetadata, arg.AccountID, arg.EventSource, arg.EventID)
	var i EventReceiptMetadataRow
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Source,
		&i.EventID,
		&i.EventType,
		&i.InvocationAccountID,
		&i.SchemaVersion,
		&i.CreatedAt,
		&i.DeliveredAt,
		&i.State,
		&i.RecipientClaims,
		&i.SnapshotCaptured,
		&i.RecipientCount,
		&i.RoutingSummary,
	)
	return i, err
}

const eventReceiptRecipients = `-- name: EventReceiptRecipients :many
SELECT s.position::bigint, s.recipient::jsonb,
       coalesce(a.slug, '')::text AS app_slug, (a.id IS NOT NULL AND a.status <> 'deleted')::boolean AS target_available,
       coalesce(o.recipient_progress -> (s.recipient->>'id'), '{}'::jsonb)::jsonb AS progress,
       coalesce(r.state, o.recipient_progress -> (s.recipient->>'id') ->>'state', 'pending')::text AS routing_state,
       coalesce(r.total_attempts, (o.recipient_progress -> (s.recipient->>'id') ->>'attempts')::integer, 0)::integer AS routing_attempts,
       coalesce(r.generation_capacity_deferrals,0)::integer AS generation_capacity_deferrals,
       coalesce(r.generation, 0)::bigint AS generation, coalesce(r.attempts, 0)::integer AS generation_attempts,
       CASE WHEN coalesce(r.state, o.recipient_progress -> (s.recipient->>'id') ->>'state', 'pending')='pending'
            THEN CASE WHEN o.recipient_claims THEN r.available_at ELSE coalesce((o.recipient_progress -> (s.recipient->>'id')->>'next_attempt_at')::timestamptz,CASE WHEN o.state='pending' THEN o.available_at END) END END::timestamptz AS next_attempt_at,
       r.lease_until,
       (SELECT count(*) FROM event_fanout_attempt_history h WHERE h.outbox_id=o.id AND h.subscription_id=s.recipient->>'id' AND h.action='operator_replay')::bigint AS replay_count,
       (SELECT max(h.occurred_at) FROM event_fanout_attempt_history h WHERE h.outbox_id=o.id AND h.subscription_id=s.recipient->>'id' AND h.action='operator_replay')::timestamptz AS last_replayed_at
FROM event_fanout_outbox o
CROSS JOIN LATERAL jsonb_array_elements(coalesce(o.recipient_snapshot, '[]'::jsonb)) WITH ORDINALITY s(recipient, position)
LEFT JOIN event_fanout_recipients r ON r.outbox_id=o.id AND r.subscription_id=s.recipient->>'id'
LEFT JOIN apps a ON a.id=(s.recipient->>'app_id')::uuid AND a.account_id=o.account_id
WHERE o.id=$1::bigint AND o.account_id=$2::uuid AND s.position > $3::bigint
ORDER BY s.position LIMIT $4::integer
`

type EventReceiptRecipientsParams struct {
	OutboxID      int64
	AccountID     pgtype.UUID
	AfterPosition int64
	PageLimit     int32
}

type EventReceiptRecipientsRow struct {
	SPosition                   int64
	SRecipient                  []byte
	AppSlug                     string
	TargetAvailable             bool
	Progress                    []byte
	RoutingState                string
	RoutingAttempts             int32
	GenerationCapacityDeferrals int32
	Generation                  int64
	GenerationAttempts          int32
	NextAttemptAt               pgtype.Timestamptz
	LeaseUntil                  pgtype.Timestamptz
	ReplayCount                 int64
	LastReplayedAt              pgtype.Timestamptz
}

func (q *Queries) EventReceiptRecipients(ctx context.Context, db DBTX, arg EventReceiptRecipientsParams) ([]EventReceiptRecipientsRow, error) {
	rows, err := db.Query(ctx, eventReceiptRecipients,
		arg.OutboxID,
		arg.AccountID,
		arg.AfterPosition,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EventReceiptRecipientsRow{}
	for rows.Next() {
		var i EventReceiptRecipientsRow
		if err := rows.Scan(
			&i.SPosition,
			&i.SRecipient,
			&i.AppSlug,
			&i.TargetAvailable,
			&i.Progress,
			&i.RoutingState,
			&i.RoutingAttempts,
			&i.GenerationCapacityDeferrals,
			&i.Generation,
			&i.GenerationAttempts,
			&i.NextAttemptAt,
			&i.LeaseUntil,
			&i.ReplayCount,
			&i.LastReplayedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const eventReceiptReplayHistory = `-- name: EventReceiptReplayHistory :many
SELECT i.id, i.state, i.attempts, i.replay_generation, i.replayed_from_invocation_id,
       coalesce(i.last_error, '')::text AS last_error, i.due_at, i.created_at, i.completed_at
FROM invocations i JOIN apps a ON a.id=i.app_id AND a.account_id=i.account_id
WHERE i.account_id=$1::uuid AND i.app_id=$2::uuid
  AND i.replay_root_invocation_id=$3::uuid
  AND i.replay_root_created_at >= $4::timestamptz
  AND ($5::timestamptz IS NULL OR
       (i.created_at, i.id)<($5::timestamptz, $6::uuid))
ORDER BY i.created_at DESC, i.id DESC LIMIT $7::integer
`

type EventReceiptReplayHistoryParams struct {
	AccountID        pgtype.UUID
	AppID            pgtype.UUID
	RootInvocationID pgtype.UUID
	AcceptedAt       pgtype.Timestamptz
	AfterCreatedAt   pgtype.Timestamptz
	AfterID          pgtype.UUID
	PageLimit        int32
}

type EventReceiptReplayHistoryRow struct {
	ID                       pgtype.UUID
	State                    string
	Attempts                 int32
	ReplayGeneration         int64
	ReplayedFromInvocationID pgtype.UUID
	LastError                string
	DueAt                    pgtype.Timestamptz
	CreatedAt                pgtype.Timestamptz
	CompletedAt              pgtype.Timestamptz
}

func (q *Queries) EventReceiptReplayHistory(ctx context.Context, db DBTX, arg EventReceiptReplayHistoryParams) ([]EventReceiptReplayHistoryRow, error) {
	rows, err := db.Query(ctx, eventReceiptReplayHistory,
		arg.AccountID,
		arg.AppID,
		arg.RootInvocationID,
		arg.AcceptedAt,
		arg.AfterCreatedAt,
		arg.AfterID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EventReceiptReplayHistoryRow{}
	for rows.Next() {
		var i EventReceiptReplayHistoryRow
		if err := rows.Scan(
			&i.ID,
			&i.State,
			&i.Attempts,
			&i.ReplayGeneration,
			&i.ReplayedFromInvocationID,
			&i.LastError,
			&i.DueAt,
			&i.CreatedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const eventReceiptReplaySummaries = `-- name: EventReceiptReplaySummaries :many
SELECT roots.id::uuid AS root_id, latest.id, latest.app_id, latest.state, latest.attempts, latest.replay_generation, latest.replayed_from_invocation_id, latest.last_error, latest.due_at, latest.created_at, latest.completed_at, latest.work_policy_name, latest.queue_binding_id, latest.work_expires_at, latest.start_deadline_at, latest.keyed_replay_created, latest.plain_replay_created, latest.retained_replay_count FROM unnest($1::uuid[]) roots(id)
CROSS JOIN LATERAL (
  SELECT i.id, i.app_id, i.state, i.attempts, i.replay_generation, i.replayed_from_invocation_id,
         coalesce(i.last_error, '')::text AS last_error, i.due_at, i.created_at, i.completed_at,
         coalesce(i.work_policy_name, '')::text AS work_policy_name, i.queue_binding_id, i.work_expires_at, i.start_deadline_at,
         EXISTS (SELECT 1 FROM invocation_keyed_replays r WHERE r.parent_invocation_id=i.id) AS keyed_replay_created,
         EXISTS (SELECT 1 FROM invocation_plain_replays r WHERE r.parent_invocation_id=i.id) AS plain_replay_created,
         count(*) OVER ()::bigint AS retained_replay_count
  FROM invocations i JOIN apps a ON a.id=i.app_id AND a.account_id=i.account_id
  WHERE i.account_id=$2::uuid AND i.replay_root_invocation_id=roots.id
    AND i.replay_root_created_at >= $3::timestamptz
  ORDER BY i.created_at DESC, i.id DESC LIMIT 1
) latest
`

type EventReceiptReplaySummariesParams struct {
	InvocationIds []pgtype.UUID
	AccountID     pgtype.UUID
	AcceptedAt    pgtype.Timestamptz
}

type EventReceiptReplaySummariesRow struct {
	RootID                   pgtype.UUID
	ID                       pgtype.UUID
	AppID                    pgtype.UUID
	State                    string
	Attempts                 int32
	ReplayGeneration         int64
	ReplayedFromInvocationID pgtype.UUID
	LastError                string
	DueAt                    pgtype.Timestamptz
	CreatedAt                pgtype.Timestamptz
	CompletedAt              pgtype.Timestamptz
	WorkPolicyName           string
	QueueBindingID           pgtype.UUID
	WorkExpiresAt            pgtype.Timestamptz
	StartDeadlineAt          pgtype.Timestamptz
	KeyedReplayCreated       bool
	PlainReplayCreated       bool
	RetainedReplayCount      int64
}

func (q *Queries) EventReceiptReplaySummaries(ctx context.Context, db DBTX, arg EventReceiptReplaySummariesParams) ([]EventReceiptReplaySummariesRow, error) {
	rows, err := db.Query(ctx, eventReceiptReplaySummaries, arg.InvocationIds, arg.AccountID, arg.AcceptedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EventReceiptReplaySummariesRow{}
	for rows.Next() {
		var i EventReceiptReplaySummariesRow
		if err := rows.Scan(
			&i.RootID,
			&i.ID,
			&i.AppID,
			&i.State,
			&i.Attempts,
			&i.ReplayGeneration,
			&i.ReplayedFromInvocationID,
			&i.LastError,
			&i.DueAt,
			&i.CreatedAt,
			&i.CompletedAt,
			&i.WorkPolicyName,
			&i.QueueBindingID,
			&i.WorkExpiresAt,
			&i.StartDeadlineAt,
			&i.KeyedReplayCreated,
			&i.PlainReplayCreated,
			&i.RetainedReplayCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const eventReceiptReplayTarget = `-- name: EventReceiptReplayTarget :one
SELECT a.id AS app_id FROM event_fanout_outbox o
CROSS JOIN LATERAL jsonb_array_elements(coalesce(o.recipient_snapshot, '[]'::jsonb)) s(recipient)
JOIN apps a ON a.id=(s.recipient->>'app_id')::uuid AND a.account_id=o.account_id
WHERE o.id=$1::bigint AND o.account_id=$2::uuid
  AND s.recipient->>'id'=$3::text
`

type EventReceiptReplayTargetParams struct {
	OutboxID       int64
	AccountID      pgtype.UUID
	SubscriptionID string
}

func (q *Queries) EventReceiptReplayTarget(ctx context.Context, db DBTX, arg EventReceiptReplayTargetParams) (pgtype.UUID, error) {
	row := db.QueryRow(ctx, eventReceiptReplayTarget, arg.OutboxID, arg.AccountID, arg.SubscriptionID)
	var app_id pgtype.UUID
	err := row.Scan(&app_id)
	return app_id, err
}

const eventStorageAcceptedCharge = `-- name: EventStorageAcceptedCharge :one
SELECT customer_storage_bytes FROM event_fanout_outbox
WHERE account_id=$1::uuid AND source=$2::text AND event_id=$3::text
`

type EventStorageAcceptedChargeParams struct {
	AccountID pgtype.UUID
	Source    string
	EventID   string
}

func (q *Queries) EventStorageAcceptedCharge(ctx context.Context, db DBTX, arg EventStorageAcceptedChargeParams) (int64, error) {
	row := db.QueryRow(ctx, eventStorageAcceptedCharge, arg.AccountID, arg.Source, arg.EventID)
	var customer_storage_bytes int64
	err := row.Scan(&customer_storage_bytes)
	return customer_storage_bytes, err
}

const eventStorageAccountPlan = `-- name: EventStorageAccountPlan :one
SELECT plan FROM accounts WHERE id=$1::uuid FOR SHARE
`

func (q *Queries) EventStorageAccountPlan(ctx context.Context, db DBTX, accountID pgtype.UUID) (string, error) {
	row := db.QueryRow(ctx, eventStorageAccountPlan, accountID)
	var plan string
	err := row.Scan(&plan)
	return plan, err
}

const eventStorageAppend = `-- name: EventStorageAppend :exec
INSERT INTO events(actor,kind,subject,data,trace_id,at)
VALUES($1::text,'event.published',$2::uuid,$3::jsonb,
       $4::text,coalesce($5::timestamptz,now()))
`

type EventStorageAppendParams struct {
	Actor      string
	AccountID  pgtype.UUID
	Payload    []byte
	TraceID    pgtype.Text
	OccurredAt pgtype.Timestamptz
}

func (q *Queries) EventStorageAppend(ctx context.Context, db DBTX, arg EventStorageAppendParams) error {
	_, err := db.Exec(ctx, eventStorageAppend,
		arg.Actor,
		arg.AccountID,
		arg.Payload,
		arg.TraceID,
		arg.OccurredAt,
	)
	return err
}

const eventStorageIdentity = `-- name: EventStorageIdentity :one
SELECT (event_type=$1::text AND coalesce(schema_version,'')=$2::text
        AND event_data=$3::jsonb)::boolean AS content_matches
FROM event_fanout_outbox
WHERE account_id=$4::uuid AND source=$5::text AND event_id=$6::text
FOR SHARE
`

type EventStorageIdentityParams struct {
	EventType     string
	SchemaVersion string
	EventData     []byte
	AccountID     pgtype.UUID
	Source        string
	EventID       string
}

func (q *Queries) EventStorageIdentity(ctx context.Context, db DBTX, arg EventStorageIdentityParams) (bool, error) {
	row := db.QueryRow(ctx, eventStorageIdentity,
		arg.EventType,
		arg.SchemaVersion,
		arg.EventData,
		arg.AccountID,
		arg.Source,
		arg.EventID,
	)
	var content_matches bool
	err := row.Scan(&content_matches)
	return content_matches, err
}

const eventStorageLockAccount = `-- name: EventStorageLockAccount :exec
INSERT INTO event_storage_admission(account_id) VALUES($1::uuid)
ON CONFLICT(account_id) DO UPDATE SET account_id=excluded.account_id
`

func (q *Queries) EventStorageLockAccount(ctx context.Context, db DBTX, accountID pgtype.UUID) error {
	_, err := db.Exec(ctx, eventStorageLockAccount, accountID)
	return err
}

const eventStoragePublicUsage = `-- name: EventStoragePublicUsage :one
SELECT a.plan, coalesce(u.retained_events,0)::bigint AS retained_events,
       coalesce(u.retained_bytes,0)::bigint AS retained_bytes, coalesce(u.pending_events,0)::bigint AS pending_events,
       u.oldest_pending_at::timestamptz AS oldest_pending_at
FROM accounts a
LEFT JOIN LATERAL (
    SELECT count(*)::bigint AS retained_events, coalesce(sum(o.customer_storage_bytes),0)::bigint AS retained_bytes,
           count(*) FILTER (WHERE o.state <> 'delivered')::bigint AS pending_events,
           min(o.created_at) FILTER (WHERE o.state <> 'delivered') AS oldest_pending_at
    FROM event_fanout_outbox o WHERE o.account_id=a.id AND o.customer_storage_bytes>0
) u ON true WHERE a.id=$1::uuid
`

type EventStoragePublicUsageRow struct {
	Plan            string
	RetainedEvents  int64
	RetainedBytes   int64
	PendingEvents   int64
	OldestPendingAt pgtype.Timestamptz
}

func (q *Queries) EventStoragePublicUsage(ctx context.Context, db DBTX, accountID pgtype.UUID) (EventStoragePublicUsageRow, error) {
	row := db.QueryRow(ctx, eventStoragePublicUsage, accountID)
	var i EventStoragePublicUsageRow
	err := row.Scan(
		&i.Plan,
		&i.RetainedEvents,
		&i.RetainedBytes,
		&i.PendingEvents,
		&i.OldestPendingAt,
	)
	return i, err
}

const eventStorageUsage = `-- name: EventStorageUsage :one
SELECT count(*)::bigint AS retained_events, coalesce(sum(customer_storage_bytes),0)::bigint AS retained_bytes
FROM event_fanout_outbox WHERE account_id=$1::uuid AND customer_storage_bytes>0
`

type EventStorageUsageRow struct {
	RetainedEvents int64
	RetainedBytes  int64
}

func (q *Queries) EventStorageUsage(ctx context.Context, db DBTX, accountID pgtype.UUID) (EventStorageUsageRow, error) {
	row := db.QueryRow(ctx, eventStorageUsage, accountID)
	var i EventStorageUsageRow
	err := row.Scan(&i.RetainedEvents, &i.RetainedBytes)
	return i, err
}
