// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: event_retention_queries.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const eventRetentionHealth = `-- name: EventRetentionHealth :one
WITH scoped AS MATERIALIZED (
 SELECT o.id,o.source,o.event_id,o.created_at,o.customer_storage_bytes,
  o.state='delivered' AS settled,
  CASE WHEN o.state='delivered' THEN o.delivered_at + $3::bigint * interval '1 second' END AS retain_until,
  CASE WHEN o.state='delivered' THEN event_receipt_retention_hold(o.account_id,o.id,o.created_at,$4::timestamptz) ELSE '' END AS hold_reason
 FROM event_fanout_outbox o WHERE o.account_id=$5::uuid
 AND ($6::text='' OR o.source=$6::text)
 AND ($7::text='' OR
  EXISTS (SELECT 1 FROM jsonb_array_elements(coalesce(o.recipient_snapshot,'[]'::jsonb)) r WHERE r->>'app_id'=$7::text)
  OR EXISTS (SELECT 1 FROM event_fanout_recipients r WHERE r.outbox_id=o.id AND r.app_id=nullif($7::text,'')::uuid))
), sampled AS (
 SELECT source AS event_source,event_id,created_at AS accepted_at,retain_until,customer_storage_bytes AS retained_bytes,hold_reason,
 CASE WHEN hold_reason<>'' THEN 'held' WHEN retain_until<$1::timestamptz THEN 'eligible_for_pruning' ELSE 'expiring' END AS status
 FROM scoped WHERE settled AND retain_until<=$2::timestamptz
 ORDER BY retain_until,source,event_id LIMIT $8::integer
)
SELECT count(*)::bigint AS retained_receipts,coalesce(sum(customer_storage_bytes),0)::bigint AS retained_bytes,
 count(*) FILTER (WHERE NOT settled)::bigint AS unsettled_receipts,
 count(*) FILTER (WHERE settled AND retain_until IS NULL)::bigint AS unknown_deadline_receipts,
 count(*) FILTER (WHERE hold_reason<>'')::bigint AS held_receipts,
 count(*) FILTER (WHERE hold_reason='backfill_running')::bigint AS running_backfill_holds,
 count(*) FILTER (WHERE hold_reason='backfill_retryable')::bigint AS retryable_backfill_holds,
 count(*) FILTER (WHERE hold_reason<>'' AND retain_until<$1::timestamptz)::bigint AS held_due_receipts,
 count(*) FILTER (WHERE settled AND hold_reason='' AND retain_until<$1::timestamptz)::bigint AS eligible_for_pruning,
 count(*) FILTER (WHERE settled AND hold_reason='' AND retain_until>=$1::timestamptz AND retain_until<=$2::timestamptz)::bigint AS expiring_receipts,
 coalesce((SELECT jsonb_agg(to_jsonb(sampled) ORDER BY retain_until,event_source,event_id) FROM sampled),'[]'::jsonb)::jsonb AS sample
FROM scoped
`

type EventRetentionHealthParams struct {
	NowAt            pgtype.Timestamptz
	WindowEnd        pgtype.Timestamptz
	RetentionSeconds int64
	JobCutoffAt      pgtype.Timestamptz
	AccountID        pgtype.UUID
	EventSource      string
	AppID            string
	SampleLimit      int32
}

type EventRetentionHealthRow struct {
	RetainedReceipts        int64
	RetainedBytes           int64
	UnsettledReceipts       int64
	UnknownDeadlineReceipts int64
	HeldReceipts            int64
	RunningBackfillHolds    int64
	RetryableBackfillHolds  int64
	HeldDueReceipts         int64
	EligibleForPruning      int64
	ExpiringReceipts        int64
	Sample                  []byte
}

func (q *Queries) EventRetentionHealth(ctx context.Context, db DBTX, arg EventRetentionHealthParams) (EventRetentionHealthRow, error) {
	row := db.QueryRow(ctx, eventRetentionHealth,
		arg.NowAt,
		arg.WindowEnd,
		arg.RetentionSeconds,
		arg.JobCutoffAt,
		arg.AccountID,
		arg.EventSource,
		arg.AppID,
		arg.SampleLimit,
	)
	var i EventRetentionHealthRow
	err := row.Scan(
		&i.RetainedReceipts,
		&i.RetainedBytes,
		&i.UnsettledReceipts,
		&i.UnknownDeadlineReceipts,
		&i.HeldReceipts,
		&i.RunningBackfillHolds,
		&i.RetryableBackfillHolds,
		&i.HeldDueReceipts,
		&i.EligibleForPruning,
		&i.ExpiringReceipts,
		&i.Sample,
	)
	return i, err
}
