// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: event_recipient_queries.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const eventDeliveryCounts = `-- name: EventDeliveryCounts :one
SELECT count(*)::bigint AS account_count,
 count(*) FILTER (WHERE s.app_id=$1::uuid)::bigint AS app_count,
 count(*) FILTER (WHERE s.app_id=$1::uuid AND s.subscription_id=$2::text)::bigint AS consumer_count
FROM event_delivery_slots s JOIN invocations i ON i.id=s.invocation_id
WHERE s.account_id=$3::uuid AND i.state IN ('pending','dispatching')
 AND NOT ($4::boolean AND i.state='pending' AND i.app_id=$1::uuid
   AND coalesce(i.work_policy_name,'')=$5::text AND i.work_key_digest=$6::bytea)
`

type EventDeliveryCountsParams struct {
	AppID          pgtype.UUID
	SubscriptionID string
	AccountID      pgtype.UUID
	ReplacePending bool
	PolicyName     string
	KeyDigest      []byte
}

type EventDeliveryCountsRow struct {
	AccountCount  int64
	AppCount      int64
	ConsumerCount int64
}

func (q *Queries) EventDeliveryCounts(ctx context.Context, db DBTX, arg EventDeliveryCountsParams) (EventDeliveryCountsRow, error) {
	row := db.QueryRow(ctx, eventDeliveryCounts,
		arg.AppID,
		arg.SubscriptionID,
		arg.AccountID,
		arg.ReplacePending,
		arg.PolicyName,
		arg.KeyDigest,
	)
	var i EventDeliveryCountsRow
	err := row.Scan(&i.AccountCount, &i.AppCount, &i.ConsumerCount)
	return i, err
}

const eventDeliveryInsertSlot = `-- name: EventDeliveryInsertSlot :exec
INSERT INTO event_delivery_slots (invocation_id,account_id,app_id,subscription_id)
VALUES ($1::uuid,$2::uuid,$3::uuid,$4::text)
ON CONFLICT DO NOTHING
`

type EventDeliveryInsertSlotParams struct {
	InvocationID   pgtype.UUID
	AccountID      pgtype.UUID
	AppID          pgtype.UUID
	SubscriptionID string
}

func (q *Queries) EventDeliveryInsertSlot(ctx context.Context, db DBTX, arg EventDeliveryInsertSlotParams) error {
	_, err := db.Exec(ctx, eventDeliveryInsertSlot,
		arg.InvocationID,
		arg.AccountID,
		arg.AppID,
		arg.SubscriptionID,
	)
	return err
}

const eventDeliveryLockCapacity = `-- name: EventDeliveryLockCapacity :exec
INSERT INTO event_delivery_capacity (account_id,consumer_limit,app_limit,account_limit)
VALUES ($1::uuid,$2::integer,$3::integer,$4::integer)
ON CONFLICT (account_id) DO UPDATE SET consumer_limit=excluded.consumer_limit,app_limit=excluded.app_limit,account_limit=excluded.account_limit
`

type EventDeliveryLockCapacityParams struct {
	AccountID     pgtype.UUID
	ConsumerLimit int32
	AppLimit      int32
	AccountLimit  int32
}

func (q *Queries) EventDeliveryLockCapacity(ctx context.Context, db DBTX, arg EventDeliveryLockCapacityParams) error {
	_, err := db.Exec(ctx, eventDeliveryLockCapacity,
		arg.AccountID,
		arg.ConsumerLimit,
		arg.AppLimit,
		arg.AccountLimit,
	)
	return err
}

const eventDeliveryReplayAccount = `-- name: EventDeliveryReplayAccount :one
SELECT s.account_id,a.plan FROM event_delivery_slots s JOIN accounts a ON a.id=s.account_id
WHERE s.invocation_id=$1::uuid
`

type EventDeliveryReplayAccountRow struct {
	AccountID pgtype.UUID
	Plan      string
}

func (q *Queries) EventDeliveryReplayAccount(ctx context.Context, db DBTX, invocationID pgtype.UUID) (EventDeliveryReplayAccountRow, error) {
	row := db.QueryRow(ctx, eventDeliveryReplayAccount, invocationID)
	var i EventDeliveryReplayAccountRow
	err := row.Scan(&i.AccountID, &i.Plan)
	return i, err
}

const eventHistoryCompact = `-- name: EventHistoryCompact :execrows
WITH ranked AS (
 SELECT h.id,h.occurred_at,
   h.id IN (s.latest_id,s.latest_failure_id,s.latest_replay_id) AS protected,
   row_number() OVER (ORDER BY (h.id IN (s.latest_id,s.latest_failure_id,s.latest_replay_id)) DESC,h.id DESC) AS position,
   sum(h.history_bytes) OVER (ORDER BY (h.id IN (s.latest_id,s.latest_failure_id,s.latest_replay_id)) DESC,h.id DESC) AS bytes
 FROM event_fanout_attempt_history h JOIN event_fanout_history_summaries s
  ON s.outbox_id=h.outbox_id AND s.subscription_id=h.subscription_id
 WHERE h.outbox_id=$1::bigint AND h.subscription_id=$2::text
), removed AS (
 DELETE FROM event_fanout_attempt_history h USING ranked r WHERE h.id=r.id AND
 (r.position>$3::bigint OR r.bytes>$4::bigint OR
  (NOT r.protected AND r.occurred_at<=$5::timestamptz))
 RETURNING h.id,h.occurred_at
)
UPDATE event_fanout_history_summaries SET
 compacted_outcomes=compacted_outcomes+(SELECT count(*) FROM removed),
 compacted_through_id=greatest(compacted_through_id,coalesce((SELECT max(id) FROM removed),0)),
 compacted_through_at=greatest(compacted_through_at,(SELECT max(occurred_at) FROM removed))
WHERE outbox_id=$1::bigint AND subscription_id=$2::text
`

type EventHistoryCompactParams struct {
	OutboxID       int64
	SubscriptionID string
	MaxRows        int64
	MaxBytes       int64
	BeforeAt       pgtype.Timestamptz
}

func (q *Queries) EventHistoryCompact(ctx context.Context, db DBTX, arg EventHistoryCompactParams) (int64, error) {
	result, err := db.Exec(ctx, eventHistoryCompact,
		arg.OutboxID,
		arg.SubscriptionID,
		arg.MaxRows,
		arg.MaxBytes,
		arg.BeforeAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const eventHistoryDueRecipients = `-- name: EventHistoryDueRecipients :many
SELECT subscription_id FROM event_fanout_history_summaries
WHERE outbox_id=$1::bigint AND next_prune_at<=$2::timestamptz
ORDER BY subscription_id LIMIT $3::integer
`

type EventHistoryDueRecipientsParams struct {
	OutboxID   int64
	NowAt      pgtype.Timestamptz
	BatchLimit int32
}

func (q *Queries) EventHistoryDueRecipients(ctx context.Context, db DBTX, arg EventHistoryDueRecipientsParams) ([]string, error) {
	rows, err := db.Query(ctx, eventHistoryDueRecipients, arg.OutboxID, arg.NowAt, arg.BatchLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var subscription_id string
		if err := rows.Scan(&subscription_id); err != nil {
			return nil, err
		}
		items = append(items, subscription_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const eventHistoryList = `-- name: EventHistoryList :many
SELECT h.id, h.outbox_id, h.app_id, h.subscription_id, h.action, h.state, h.attempts, h.failure_code, h.retryable, h.last_error, h.occurred_at, h.capacity_scope, h.capacity_deferrals, h.details_truncated, h.history_bytes,o.event_id,o.source AS event_source,o.event_type
FROM event_fanout_attempt_history h JOIN event_fanout_outbox o ON o.id=h.outbox_id
JOIN apps a ON a.id=h.app_id AND a.account_id=o.account_id
WHERE h.app_id=$1::uuid AND ($2::text='' OR o.source=$2::text) AND ($3::text='' OR o.event_id=$3::text)
 AND ($4::text='' OR h.subscription_id=$4::text)
 AND ($5::bigint=0 OR h.id<$5::bigint)
ORDER BY h.id DESC LIMIT $6::integer
`

type EventHistoryListParams struct {
	AppID          pgtype.UUID
	EventSource    string
	EventID        string
	SubscriptionID string
	BeforeID       int64
	PageLimit      int32
}

type EventHistoryListRow struct {
	ID                int64
	OutboxID          int64
	AppID             pgtype.UUID
	SubscriptionID    string
	Action            string
	State             string
	Attempts          int32
	FailureCode       string
	Retryable         bool
	LastError         string
	OccurredAt        pgtype.Timestamptz
	CapacityScope     string
	CapacityDeferrals int64
	DetailsTruncated  bool
	HistoryBytes      int64
	EventID           string
	EventSource       string
	EventType         string
}

func (q *Queries) EventHistoryList(ctx context.Context, db DBTX, arg EventHistoryListParams) ([]EventHistoryListRow, error) {
	rows, err := db.Query(ctx, eventHistoryList,
		arg.AppID,
		arg.EventSource,
		arg.EventID,
		arg.SubscriptionID,
		arg.BeforeID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EventHistoryListRow{}
	for rows.Next() {
		var i EventHistoryListRow
		if err := rows.Scan(
			&i.ID,
			&i.OutboxID,
			&i.AppID,
			&i.SubscriptionID,
			&i.Action,
			&i.State,
			&i.Attempts,
			&i.FailureCode,
			&i.Retryable,
			&i.LastError,
			&i.OccurredAt,
			&i.CapacityScope,
			&i.CapacityDeferrals,
			&i.DetailsTruncated,
			&i.HistoryBytes,
			&i.EventID,
			&i.EventSource,
			&i.EventType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const eventHistoryMarkDetail = `-- name: EventHistoryMarkDetail :exec
UPDATE event_fanout_history_summaries SET latest_id=$1::bigint,
 latest_failure_id=CASE WHEN $2::boolean THEN $1::bigint ELSE latest_failure_id END,
 latest_replay_id=CASE WHEN $3::boolean THEN $1::bigint ELSE latest_replay_id END
WHERE outbox_id=$4::bigint AND subscription_id=$5::text
`

type EventHistoryMarkDetailParams struct {
	HistoryID      int64
	IsFailure      bool
	IsReplay       bool
	OutboxID       int64
	SubscriptionID string
}

func (q *Queries) EventHistoryMarkDetail(ctx context.Context, db DBTX, arg EventHistoryMarkDetailParams) error {
	_, err := db.Exec(ctx, eventHistoryMarkDetail,
		arg.HistoryID,
		arg.IsFailure,
		arg.IsReplay,
		arg.OutboxID,
		arg.SubscriptionID,
	)
	return err
}

const eventHistoryObserve = `-- name: EventHistoryObserve :one
INSERT INTO event_fanout_history_summaries AS s
 (outbox_id,subscription_id,app_id,observed_outcomes,capacity_deferrals,
  first_capacity_wait_at,last_capacity_wait_at,last_capacity_scope,last_outcome_capacity_scope)
VALUES ($1::bigint,$2::text,$3::uuid,1,
 $4::bigint,
 CASE WHEN $5::text<>'' THEN $6::timestamptz END,
 CASE WHEN $5::text<>'' THEN $6::timestamptz END,
 $5::text,$5::text)
ON CONFLICT (outbox_id,subscription_id) DO UPDATE SET
 observed_outcomes=s.observed_outcomes+1,
 capacity_deferrals=greatest(s.capacity_deferrals,excluded.capacity_deferrals),
 first_capacity_wait_at=coalesce(s.first_capacity_wait_at,excluded.first_capacity_wait_at),
 last_capacity_wait_at=coalesce(excluded.last_capacity_wait_at,s.last_capacity_wait_at),
 last_capacity_scope=CASE WHEN excluded.last_capacity_scope<>'' THEN excluded.last_capacity_scope ELSE s.last_capacity_scope END,
 last_was_coalesced=excluded.last_outcome_capacity_scope<>'' AND s.last_outcome_capacity_scope=excluded.last_outcome_capacity_scope,
 coalesced_outcomes=s.coalesced_outcomes+CASE WHEN excluded.last_outcome_capacity_scope<>'' AND s.last_outcome_capacity_scope=excluded.last_outcome_capacity_scope THEN 1 ELSE 0 END,
 last_outcome_capacity_scope=excluded.last_outcome_capacity_scope
RETURNING last_was_coalesced
`

type EventHistoryObserveParams struct {
	OutboxID          int64
	SubscriptionID    string
	AppID             pgtype.UUID
	CapacityDeferrals int64
	WaitScope         string
	OccurredAt        pgtype.Timestamptz
}

func (q *Queries) EventHistoryObserve(ctx context.Context, db DBTX, arg EventHistoryObserveParams) (bool, error) {
	row := db.QueryRow(ctx, eventHistoryObserve,
		arg.OutboxID,
		arg.SubscriptionID,
		arg.AppID,
		arg.CapacityDeferrals,
		arg.WaitScope,
		arg.OccurredAt,
	)
	var last_was_coalesced bool
	err := row.Scan(&last_was_coalesced)
	return last_was_coalesced, err
}

const eventHistoryPruneCandidates = `-- name: EventHistoryPruneCandidates :many
SELECT o.id FROM event_fanout_history_summaries s
JOIN event_fanout_outbox o ON o.id=s.outbox_id
WHERE s.next_prune_at<=$1::timestamptz
ORDER BY s.next_prune_at,s.outbox_id,s.subscription_id
LIMIT $2::integer FOR UPDATE OF o SKIP LOCKED
`

type EventHistoryPruneCandidatesParams struct {
	NowAt      pgtype.Timestamptz
	BatchLimit int32
}

// Take parent locks before summary/detail locks, matching routing and replay.
func (q *Queries) EventHistoryPruneCandidates(ctx context.Context, db DBTX, arg EventHistoryPruneCandidatesParams) ([]int64, error) {
	rows, err := db.Query(ctx, eventHistoryPruneCandidates, arg.NowAt, arg.BatchLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const eventHistorySchedulePrune = `-- name: EventHistorySchedulePrune :exec
UPDATE event_fanout_history_summaries s SET next_prune_at=(
 SELECT min(h.occurred_at)+$1::bigint * interval '1 second'
 FROM event_fanout_attempt_history h WHERE h.outbox_id=s.outbox_id AND h.subscription_id=s.subscription_id
 AND h.id NOT IN (s.latest_id,s.latest_failure_id,s.latest_replay_id))
WHERE s.outbox_id=$2::bigint AND s.subscription_id=$3::text
`

type EventHistorySchedulePruneParams struct {
	RetentionSeconds int64
	OutboxID         int64
	SubscriptionID   string
}

func (q *Queries) EventHistorySchedulePrune(ctx context.Context, db DBTX, arg EventHistorySchedulePruneParams) error {
	_, err := db.Exec(ctx, eventHistorySchedulePrune, arg.RetentionSeconds, arg.OutboxID, arg.SubscriptionID)
	return err
}

const eventHistorySummaries = `-- name: EventHistorySummaries :many
SELECT s.outbox_id, s.subscription_id, s.app_id, s.observed_outcomes, s.capacity_deferrals, s.coalesced_outcomes, s.compacted_outcomes, s.compacted_through_id, s.compacted_through_at, s.first_capacity_wait_at, s.last_capacity_wait_at, s.last_capacity_scope, s.last_outcome_capacity_scope, s.last_was_coalesced, s.latest_id, s.latest_failure_id, s.latest_replay_id, s.next_prune_at, (SELECT count(*) FROM event_fanout_attempt_history h WHERE h.outbox_id=s.outbox_id AND h.subscription_id=s.subscription_id)::bigint AS retained_records,
 (SELECT coalesce(sum(h.history_bytes),0)::bigint FROM event_fanout_attempt_history h WHERE h.outbox_id=s.outbox_id AND h.subscription_id=s.subscription_id)::bigint AS retained_bytes
FROM event_fanout_history_summaries s JOIN event_fanout_outbox o ON o.id=s.outbox_id
JOIN apps a ON a.id=s.app_id AND a.account_id=o.account_id
WHERE s.app_id=$1::uuid AND ($2::text='' OR o.source=$2::text) AND ($3::text='' OR o.event_id=$3::text)
 AND ($4::text='' OR s.subscription_id=$4::text)
ORDER BY s.subscription_id
`

type EventHistorySummariesParams struct {
	AppID          pgtype.UUID
	EventSource    string
	EventID        string
	SubscriptionID string
}

type EventHistorySummariesRow struct {
	OutboxID                 int64
	SubscriptionID           string
	AppID                    pgtype.UUID
	ObservedOutcomes         int64
	CapacityDeferrals        int64
	CoalescedOutcomes        int64
	CompactedOutcomes        int64
	CompactedThroughID       int64
	CompactedThroughAt       pgtype.Timestamptz
	FirstCapacityWaitAt      pgtype.Timestamptz
	LastCapacityWaitAt       pgtype.Timestamptz
	LastCapacityScope        string
	LastOutcomeCapacityScope string
	LastWasCoalesced         bool
	LatestID                 int64
	LatestFailureID          int64
	LatestReplayID           int64
	NextPruneAt              pgtype.Timestamptz
	RetainedRecords          int64
	RetainedBytes            int64
}

func (q *Queries) EventHistorySummaries(ctx context.Context, db DBTX, arg EventHistorySummariesParams) ([]EventHistorySummariesRow, error) {
	rows, err := db.Query(ctx, eventHistorySummaries,
		arg.AppID,
		arg.EventSource,
		arg.EventID,
		arg.SubscriptionID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EventHistorySummariesRow{}
	for rows.Next() {
		var i EventHistorySummariesRow
		if err := rows.Scan(
			&i.OutboxID,
			&i.SubscriptionID,
			&i.AppID,
			&i.ObservedOutcomes,
			&i.CapacityDeferrals,
			&i.CoalescedOutcomes,
			&i.CompactedOutcomes,
			&i.CompactedThroughID,
			&i.CompactedThroughAt,
			&i.FirstCapacityWaitAt,
			&i.LastCapacityWaitAt,
			&i.LastCapacityScope,
			&i.LastOutcomeCapacityScope,
			&i.LastWasCoalesced,
			&i.LatestID,
			&i.LatestFailureID,
			&i.LatestReplayID,
			&i.NextPruneAt,
			&i.RetainedRecords,
			&i.RetainedBytes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const eventRecipientAppendHistory = `-- name: EventRecipientAppendHistory :one
INSERT INTO event_fanout_attempt_history
    (outbox_id, app_id, subscription_id, action, state, attempts, failure_code, retryable, last_error, occurred_at,
     capacity_scope,capacity_deferrals,details_truncated)
VALUES ($1::bigint, $2::uuid, $3::text,
        $4::text, $5::text, $6::integer,
        $7::text, $8::boolean, $9::text,
        $10::timestamptz,$11::text,
        $12::bigint,$13::boolean)
RETURNING id
`

type EventRecipientAppendHistoryParams struct {
	OutboxID          int64
	AppID             pgtype.UUID
	SubscriptionID    string
	Action            string
	State             string
	Attempts          int32
	FailureCode       string
	Retryable         bool
	LastError         string
	OccurredAt        pgtype.Timestamptz
	CapacityScope     string
	CapacityDeferrals int64
	DetailsTruncated  bool
}

func (q *Queries) EventRecipientAppendHistory(ctx context.Context, db DBTX, arg EventRecipientAppendHistoryParams) (int64, error) {
	row := db.QueryRow(ctx, eventRecipientAppendHistory,
		arg.OutboxID,
		arg.AppID,
		arg.SubscriptionID,
		arg.Action,
		arg.State,
		arg.Attempts,
		arg.FailureCode,
		arg.Retryable,
		arg.LastError,
		arg.OccurredAt,
		arg.CapacityScope,
		arg.CapacityDeferrals,
		arg.DetailsTruncated,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const eventRecipientClaim = `-- name: EventRecipientClaim :one
WITH candidate AS (
    SELECT r.outbox_id, r.subscription_id
    FROM event_fanout_recipients r
    JOIN event_fanout_outbox o ON o.id=r.outbox_id
    LEFT JOIN event_routing_fairness fa ON fa.account_id=o.account_id AND fa.subscription_id=''
    LEFT JOIN event_routing_fairness fc ON fc.account_id=o.account_id AND fc.subscription_id=r.subscription_id
    WHERE ((r.state = 'pending' AND r.available_at <= $1::timestamptz)
       OR (r.state = 'processing' AND r.lease_until <= $1::timestamptz))
      AND (r.backfill_job_id IS NULL OR EXISTS (
          SELECT 1 FROM event_replay_jobs j JOIN event_replay_job_items i ON i.job_id=j.id
          WHERE j.id=r.backfill_job_id AND j.state='running' AND i.outbox_id=r.outbox_id
            AND i.state IN ('pending','processing')))
    ORDER BY coalesce(fa.last_claimed_at,'epoch'::timestamptz),
      coalesce(fc.last_claimed_at,'epoch'::timestamptz), r.available_at, r.outbox_id, r.subscription_id
    FOR UPDATE OF r SKIP LOCKED LIMIT 1
), claimed AS (
    UPDATE event_fanout_recipients r
    SET state = 'processing', claim_token = gen_random_uuid(),
        lease_until = $1::timestamptz + interval '5 minutes',
        attempts = r.attempts + 1, total_attempts = r.total_attempts + 1
    FROM candidate c
    WHERE r.outbox_id = c.outbox_id AND r.subscription_id = c.subscription_id
    RETURNING r.outbox_id, r.subscription_id, r.app_id, r.recipient, r.state, r.generation, r.attempts, r.total_attempts, r.available_at, r.claim_token, r.lease_until, r.capacity_deferrals, r.generation_capacity_deferrals, r.backfill_job_id
), replay_item AS (
    UPDATE event_replay_job_items i SET state='processing', attempts=c.total_attempts, updated_at=clock_timestamp()
    FROM claimed c WHERE c.backfill_job_id=i.job_id AND c.outbox_id=i.outbox_id
      AND i.state IN ('pending','processing')
    RETURNING i.job_id
), fairness AS (
 INSERT INTO event_routing_fairness
 SELECT o.account_id,v.subscription_id,clock_timestamp() FROM claimed c
 JOIN event_fanout_outbox o ON o.id=c.outbox_id
 CROSS JOIN LATERAL (VALUES (''::text),(c.subscription_id)) v(subscription_id)
 ORDER BY o.account_id,v.subscription_id
 ON CONFLICT (account_id,subscription_id) DO UPDATE SET last_claimed_at=excluded.last_claimed_at
 RETURNING account_id
)
SELECT c.outbox_id, c.recipient, c.claim_token, c.generation, c.attempts,
       c.capacity_deferrals,c.generation_capacity_deferrals,
       c.total_attempts, c.available_at, c.lease_until, o.payload, c.backfill_job_id
FROM claimed c JOIN event_fanout_outbox o ON o.id = c.outbox_id
`

type EventRecipientClaimRow struct {
	OutboxID                    int64
	Recipient                   []byte
	ClaimToken                  pgtype.UUID
	Generation                  int64
	Attempts                    int32
	CapacityDeferrals           int32
	GenerationCapacityDeferrals int32
	TotalAttempts               int32
	AvailableAt                 pgtype.Timestamptz
	LeaseUntil                  pgtype.Timestamptz
	Payload                     []byte
	BackfillJobID               pgtype.UUID
}

func (q *Queries) EventRecipientClaim(ctx context.Context, db DBTX, nowAt pgtype.Timestamptz) (EventRecipientClaimRow, error) {
	row := db.QueryRow(ctx, eventRecipientClaim, nowAt)
	var i EventRecipientClaimRow
	err := row.Scan(
		&i.OutboxID,
		&i.Recipient,
		&i.ClaimToken,
		&i.Generation,
		&i.Attempts,
		&i.CapacityDeferrals,
		&i.GenerationCapacityDeferrals,
		&i.TotalAttempts,
		&i.AvailableAt,
		&i.LeaseUntil,
		&i.Payload,
		&i.BackfillJobID,
	)
	return i, err
}

const eventRecipientFinish = `-- name: EventRecipientFinish :execrows
UPDATE event_fanout_recipients
SET state = $1::text, available_at = $2::timestamptz,
    claim_token = NULL, lease_until = NULL,
    capacity_deferrals=capacity_deferrals+CASE WHEN $3::boolean THEN 1 ELSE 0 END,
    generation_capacity_deferrals=generation_capacity_deferrals+CASE WHEN $3::boolean THEN 1 ELSE 0 END
WHERE outbox_id = $4::bigint AND subscription_id = $5::text
  AND state = 'processing' AND claim_token = $6::uuid
  AND generation = $7::bigint AND lease_until > clock_timestamp()
`

type EventRecipientFinishParams struct {
	State            string
	AvailableAt      pgtype.Timestamptz
	CapacityDeferred bool
	OutboxID         int64
	SubscriptionID   string
	ClaimToken       pgtype.UUID
	Generation       int64
}

func (q *Queries) EventRecipientFinish(ctx context.Context, db DBTX, arg EventRecipientFinishParams) (int64, error) {
	result, err := db.Exec(ctx, eventRecipientFinish,
		arg.State,
		arg.AvailableAt,
		arg.CapacityDeferred,
		arg.OutboxID,
		arg.SubscriptionID,
		arg.ClaimToken,
		arg.Generation,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const eventRecipientInitializeReceipt = `-- name: EventRecipientInitializeReceipt :execrows
UPDATE event_fanout_outbox
SET recipient_claims = true, claim_token = NULL, lease_until = NULL
WHERE id = $1::bigint AND NOT recipient_claims
  AND state = 'processing' AND claim_token = $2::uuid
  AND lease_until > clock_timestamp() AND recipient_snapshot IS NOT NULL
`

type EventRecipientInitializeReceiptParams struct {
	ID         int64
	ClaimToken pgtype.UUID
}

func (q *Queries) EventRecipientInitializeReceipt(ctx context.Context, db DBTX, arg EventRecipientInitializeReceiptParams) (int64, error) {
	result, err := db.Exec(ctx, eventRecipientInitializeReceipt, arg.ID, arg.ClaimToken)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const eventRecipientInsert = `-- name: EventRecipientInsert :exec
INSERT INTO event_fanout_recipients
    (outbox_id, subscription_id, app_id, recipient, state, attempts, total_attempts, capacity_deferrals, available_at)
VALUES ($1::bigint, $2::text, $3::uuid,
        $4::jsonb, $5::text, 0,
        $6::integer, $7::integer, $8::timestamptz)
ON CONFLICT (outbox_id, subscription_id) DO NOTHING
`

type EventRecipientInsertParams struct {
	OutboxID          int64
	SubscriptionID    string
	AppID             pgtype.UUID
	Recipient         []byte
	State             string
	TotalAttempts     int32
	CapacityDeferrals int32
	AvailableAt       pgtype.Timestamptz
}

func (q *Queries) EventRecipientInsert(ctx context.Context, db DBTX, arg EventRecipientInsertParams) error {
	_, err := db.Exec(ctx, eventRecipientInsert,
		arg.OutboxID,
		arg.SubscriptionID,
		arg.AppID,
		arg.Recipient,
		arg.State,
		arg.TotalAttempts,
		arg.CapacityDeferrals,
		arg.AvailableAt,
	)
	return err
}

const eventRecipientLockReceipt = `-- name: EventRecipientLockReceipt :one
SELECT id FROM event_fanout_outbox
WHERE id = $1::bigint AND recipient_claims FOR UPDATE
`

func (q *Queries) EventRecipientLockReceipt(ctx context.Context, db DBTX, id int64) (int64, error) {
	row := db.QueryRow(ctx, eventRecipientLockReceipt, id)
	var id_2 int64
	err := row.Scan(&id_2)
	return id_2, err
}

const eventRecipientReplay = `-- name: EventRecipientReplay :execrows
UPDATE event_fanout_recipients
SET state = 'pending', generation = generation + 1, attempts = 0, generation_capacity_deferrals=0,
    available_at = $1::timestamptz, claim_token = NULL, lease_until = NULL
WHERE outbox_id = $2::bigint AND subscription_id = $3::text
  AND state = 'failed'
`

type EventRecipientReplayParams struct {
	NowAt          pgtype.Timestamptz
	OutboxID       int64
	SubscriptionID string
}

func (q *Queries) EventRecipientReplay(ctx context.Context, db DBTX, arg EventRecipientReplayParams) (int64, error) {
	result, err := db.Exec(ctx, eventRecipientReplay, arg.NowAt, arg.OutboxID, arg.SubscriptionID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const eventRecipientReplayCandidates = `-- name: EventRecipientReplayCandidates :many
SELECT o.id, o.recipient_claims, (r.recipient->>'id')::text AS subscription_id,
       (o.recipient_progress -> (r.recipient->>'id'))::jsonb AS progress
FROM event_fanout_outbox o
JOIN apps a ON a.id = $1::uuid AND a.account_id = o.account_id
CROSS JOIN LATERAL jsonb_array_elements(COALESCE(o.recipient_snapshot, '[]'::jsonb)) r(recipient)
WHERE o.account_id = $2::uuid AND r.recipient->>'app_id' = a.id::text
  AND (o.recipient_claims OR o.state IN ('delivered', 'pending'))
  AND (o.recipient_progress -> (r.recipient->>'id'))->>'state' = 'failed'
  AND coalesce(((o.recipient_progress -> (r.recipient->>'id'))->>'retryable')::boolean, false)
  AND (($3::text = '' AND $4::text = '') OR
       (o.source = $3::text AND o.event_id = $4::text))
ORDER BY coalesce((o.recipient_progress -> (r.recipient->>'id')->>'updated_at')::timestamptz, o.created_at), o.id, r.recipient->>'id'
LIMIT $5::integer FOR UPDATE OF o SKIP LOCKED
`

type EventRecipientReplayCandidatesParams struct {
	AppID       pgtype.UUID
	AccountID   pgtype.UUID
	EventSource string
	EventID     string
	PageLimit   int32
}

type EventRecipientReplayCandidatesRow struct {
	ID              int64
	RecipientClaims bool
	SubscriptionID  string
	Progress        []byte
}

func (q *Queries) EventRecipientReplayCandidates(ctx context.Context, db DBTX, arg EventRecipientReplayCandidatesParams) ([]EventRecipientReplayCandidatesRow, error) {
	rows, err := db.Query(ctx, eventRecipientReplayCandidates,
		arg.AppID,
		arg.AccountID,
		arg.EventSource,
		arg.EventID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EventRecipientReplayCandidatesRow{}
	for rows.Next() {
		var i EventRecipientReplayCandidatesRow
		if err := rows.Scan(
			&i.ID,
			&i.RecipientClaims,
			&i.SubscriptionID,
			&i.Progress,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const eventRecipientReplayHasMore = `-- name: EventRecipientReplayHasMore :one
SELECT EXISTS (
    SELECT 1 FROM event_fanout_outbox o
    CROSS JOIN LATERAL jsonb_array_elements(COALESCE(o.recipient_snapshot, '[]'::jsonb)) r(recipient)
    WHERE o.account_id = $1::uuid AND r.recipient->>'app_id' = $2::text
      AND (o.recipient_progress -> (r.recipient->>'id'))->>'state' = 'failed'
      AND coalesce(((o.recipient_progress -> (r.recipient->>'id'))->>'retryable')::boolean, false)
      AND (($3::text = '' AND $4::text = '') OR
           (o.source = $3::text AND o.event_id = $4::text))
) AS has_more
`

type EventRecipientReplayHasMoreParams struct {
	AccountID   pgtype.UUID
	AppID       string
	EventSource string
	EventID     string
}

func (q *Queries) EventRecipientReplayHasMore(ctx context.Context, db DBTX, arg EventRecipientReplayHasMoreParams) (bool, error) {
	row := db.QueryRow(ctx, eventRecipientReplayHasMore,
		arg.AccountID,
		arg.AppID,
		arg.EventSource,
		arg.EventID,
	)
	var has_more bool
	err := row.Scan(&has_more)
	return has_more, err
}

const eventRecipientReplayLegacy = `-- name: EventRecipientReplayLegacy :execrows
UPDATE event_fanout_outbox
SET state = 'pending', available_at = $1::timestamptz,
    delivered_at = NULL, claim_token = NULL, lease_until = NULL
WHERE id = $2::bigint AND NOT recipient_claims AND state IN ('delivered', 'pending')
  AND (recipient_progress -> $3::text)->>'state' = 'failed'
`

type EventRecipientReplayLegacyParams struct {
	NowAt          pgtype.Timestamptz
	ID             int64
	SubscriptionID string
}

func (q *Queries) EventRecipientReplayLegacy(ctx context.Context, db DBTX, arg EventRecipientReplayLegacyParams) (int64, error) {
	result, err := db.Exec(ctx, eventRecipientReplayLegacy, arg.NowAt, arg.ID, arg.SubscriptionID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const eventRecipientReplayReceipt = `-- name: EventRecipientReplayReceipt :one
SELECT o.id, o.recipient_claims,
       (o.recipient_progress -> $1::text)::jsonb AS progress
FROM event_fanout_outbox o
CROSS JOIN LATERAL jsonb_array_elements(COALESCE(o.recipient_snapshot, '[]'::jsonb)) r(recipient)
WHERE o.account_id = $2::uuid AND o.source = $3::text
  AND o.event_id = $4::text AND r.recipient->>'app_id' = $5::text
  AND r.recipient->>'id' = $1::text
FOR UPDATE OF o
`

type EventRecipientReplayReceiptParams struct {
	SubscriptionID string
	AccountID      pgtype.UUID
	EventSource    string
	EventID        string
	AppID          string
}

type EventRecipientReplayReceiptRow struct {
	ID              int64
	RecipientClaims bool
	Progress        []byte
}

func (q *Queries) EventRecipientReplayReceipt(ctx context.Context, db DBTX, arg EventRecipientReplayReceiptParams) (EventRecipientReplayReceiptRow, error) {
	row := db.QueryRow(ctx, eventRecipientReplayReceipt,
		arg.SubscriptionID,
		arg.AccountID,
		arg.EventSource,
		arg.EventID,
		arg.AppID,
	)
	var i EventRecipientReplayReceiptRow
	err := row.Scan(&i.ID, &i.RecipientClaims, &i.Progress)
	return i, err
}

const eventRecipientSettleReceipt = `-- name: EventRecipientSettleReceipt :exec
UPDATE event_fanout_outbox o
SET state = CASE WHEN EXISTS (SELECT 1 FROM event_fanout_recipients r
        WHERE r.outbox_id = o.id AND r.state IN ('pending', 'processing')) THEN 'processing' ELSE 'delivered' END,
    delivered_at = CASE WHEN EXISTS (SELECT 1 FROM event_fanout_recipients r
        WHERE r.outbox_id = o.id AND r.state IN ('pending', 'processing')) THEN NULL ELSE now() END
WHERE o.id = $1::bigint AND o.recipient_claims
`

func (q *Queries) EventRecipientSettleReceipt(ctx context.Context, db DBTX, id int64) error {
	_, err := db.Exec(ctx, eventRecipientSettleReceipt, id)
	return err
}

const eventRecipientUpdateProgress = `-- name: EventRecipientUpdateProgress :exec
UPDATE event_fanout_outbox o
SET recipient_progress = jsonb_set(o.recipient_progress, ARRAY[$1::text], $2::jsonb, true),
    last_error = (SELECT left('subscription ' || p.key || ': ' || coalesce(p.value->>'last_error', 'recipient failed'), 1024)
        FROM jsonb_each(jsonb_set(o.recipient_progress, ARRAY[$1::text], $2::jsonb, true)) p
        WHERE p.value->>'state' = 'failed' ORDER BY p.key LIMIT 1)
WHERE o.id = $3::bigint
`

type EventRecipientUpdateProgressParams struct {
	SubscriptionID string
	Progress       []byte
	ID             int64
}

func (q *Queries) EventRecipientUpdateProgress(ctx context.Context, db DBTX, arg EventRecipientUpdateProgressParams) error {
	_, err := db.Exec(ctx, eventRecipientUpdateProgress, arg.SubscriptionID, arg.Progress, arg.ID)
	return err
}

const eventRoutingClaimReceipt = `-- name: EventRoutingClaimReceipt :one
WITH candidate AS (
 SELECT o.id FROM event_fanout_outbox o
 LEFT JOIN event_routing_fairness fa ON fa.account_id=o.account_id AND fa.subscription_id=''
 LEFT JOIN LATERAL (
   SELECT min(coalesce(fc.last_claimed_at,'epoch'::timestamptz)) AS last_claimed_at
   FROM jsonb_array_elements(coalesce(o.recipient_snapshot,'[]'::jsonb)) r
   LEFT JOIN event_routing_fairness fc ON fc.account_id=o.account_id AND fc.subscription_id=r->>'id'
   WHERE coalesce(o.recipient_progress->(r->>'id')->>'state','pending') NOT IN ('enqueued','filtered','failed')
     AND coalesce((o.recipient_progress->(r->>'id')->>'next_attempt_at')::timestamptz,'epoch'::timestamptz)<=$1::timestamptz
 ) cf ON true
 WHERE NOT o.recipient_claims AND ((o.state='pending' AND o.available_at<=$1::timestamptz)
   OR (o.state='processing' AND o.lease_until<=$1::timestamptz))
 ORDER BY coalesce(fa.last_claimed_at,'epoch'::timestamptz),
   coalesce(cf.last_claimed_at,fa.last_claimed_at,'epoch'::timestamptz),o.id
 FOR UPDATE OF o SKIP LOCKED LIMIT 1
), claimed AS (
 UPDATE event_fanout_outbox o SET state='processing',claim_token=gen_random_uuid(),
 lease_until=$1::timestamptz+interval '5 minutes',attempts=o.attempts+1
 FROM candidate c WHERE o.id=c.id RETURNING o.id, o.account_id, o.source, o.event_id, o.event_type, o.schema_version, o.event_data, o.payload, o.state, o.attempts, o.available_at, o.lease_until, o.claim_token, o.last_error, o.created_at, o.delivered_at, o.recipient_snapshot, o.recipient_progress, o.recipient_claims, o.customer_storage_bytes
), fairness AS (
 INSERT INTO event_routing_fairness
 SELECT c.account_id,v.subscription_id,clock_timestamp() FROM claimed c
 CROSS JOIN LATERAL (
   SELECT ''::text AS subscription_id UNION
   SELECT r->>'id' FROM jsonb_array_elements(coalesce(c.recipient_snapshot,'[]'::jsonb)) r
   WHERE coalesce(c.recipient_progress->(r->>'id')->>'state','pending') NOT IN ('enqueued','filtered','failed')
     AND coalesce((c.recipient_progress->(r->>'id')->>'next_attempt_at')::timestamptz,'epoch'::timestamptz)<=$1::timestamptz
 ) v
 ORDER BY c.account_id,v.subscription_id
 ON CONFLICT (account_id,subscription_id) DO UPDATE SET last_claimed_at=excluded.last_claimed_at RETURNING account_id
)
SELECT c.id, c.account_id, c.source, c.event_id, c.event_type, c.schema_version, c.event_data, c.payload, c.state, c.attempts, c.available_at, c.lease_until, c.claim_token, c.last_error, c.created_at, c.delivered_at, c.recipient_snapshot, c.recipient_progress, c.recipient_claims, c.customer_storage_bytes FROM claimed c WHERE EXISTS (SELECT 1 FROM fairness f WHERE f.account_id=c.account_id)
`

type EventRoutingClaimReceiptRow struct {
	ID                   int64
	AccountID            pgtype.UUID
	Source               string
	EventID              string
	EventType            string
	SchemaVersion        pgtype.Text
	EventData            []byte
	Payload              []byte
	State                string
	Attempts             int32
	AvailableAt          pgtype.Timestamptz
	LeaseUntil           pgtype.Timestamptz
	ClaimToken           pgtype.UUID
	LastError            pgtype.Text
	CreatedAt            pgtype.Timestamptz
	DeliveredAt          pgtype.Timestamptz
	RecipientSnapshot    []byte
	RecipientProgress    []byte
	RecipientClaims      bool
	CustomerStorageBytes int64
}

func (q *Queries) EventRoutingClaimReceipt(ctx context.Context, db DBTX, nowAt pgtype.Timestamptz) (EventRoutingClaimReceiptRow, error) {
	row := db.QueryRow(ctx, eventRoutingClaimReceipt, nowAt)
	var i EventRoutingClaimReceiptRow
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Source,
		&i.EventID,
		&i.EventType,
		&i.SchemaVersion,
		&i.EventData,
		&i.Payload,
		&i.State,
		&i.Attempts,
		&i.AvailableAt,
		&i.LeaseUntil,
		&i.ClaimToken,
		&i.LastError,
		&i.CreatedAt,
		&i.DeliveredAt,
		&i.RecipientSnapshot,
		&i.RecipientProgress,
		&i.RecipientClaims,
		&i.CustomerStorageBytes,
	)
	return i, err
}

const eventRoutingClaimValid = `-- name: EventRoutingClaimValid :one
SELECT CASE WHEN o.recipient_claims THEN EXISTS (
    SELECT 1 FROM event_fanout_recipients r WHERE r.outbox_id=o.id
      AND r.subscription_id=$1::text AND r.state='processing'
      AND r.generation=$2::bigint AND r.claim_token=$3::uuid
      AND r.lease_until>clock_timestamp())
    ELSE $2::bigint=0 AND o.state='processing'
      AND o.claim_token=$3::uuid AND o.lease_until>clock_timestamp() END::boolean AS valid
FROM event_fanout_outbox o WHERE o.id=$4::bigint
`

type EventRoutingClaimValidParams struct {
	SubscriptionID string
	Generation     int64
	ClaimToken     pgtype.UUID
	ID             int64
}

// Evaluate the wall clock only after all admission locks have been acquired.
func (q *Queries) EventRoutingClaimValid(ctx context.Context, db DBTX, arg EventRoutingClaimValidParams) (bool, error) {
	row := db.QueryRow(ctx, eventRoutingClaimValid,
		arg.SubscriptionID,
		arg.Generation,
		arg.ClaimToken,
		arg.ID,
	)
	var valid bool
	err := row.Scan(&valid)
	return valid, err
}

const eventRoutingDeferReceipt = `-- name: EventRoutingDeferReceipt :execrows
UPDATE event_fanout_outbox o SET state='pending',claim_token=NULL,lease_until=NULL,
 available_at=coalesce((SELECT min(coalesce((p.value->>'next_attempt_at')::timestamptz,
 clock_timestamp()+interval '5 seconds')) FROM jsonb_each(o.recipient_progress) p WHERE p.value->>'state'='pending'),clock_timestamp()+interval '5 seconds')
WHERE o.id=$1::bigint AND o.claim_token=$2::uuid
 AND o.state='processing' AND NOT o.recipient_claims AND o.lease_until>clock_timestamp()
`

type EventRoutingDeferReceiptParams struct {
	ID         int64
	ClaimToken pgtype.UUID
}

func (q *Queries) EventRoutingDeferReceipt(ctx context.Context, db DBTX, arg EventRoutingDeferReceiptParams) (int64, error) {
	result, err := db.Exec(ctx, eventRoutingDeferReceipt, arg.ID, arg.ClaimToken)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const eventRoutingHealth = `-- name: EventRoutingHealth :one
SELECT count(*) FILTER (WHERE coalesce(p.value->>'capacity_scope','')<>'')::bigint AS capacity_waiting,
 coalesce(extract(epoch FROM clock_timestamp()-min(o.created_at)),0)::double precision AS oldest_pending_seconds
FROM event_fanout_outbox o
CROSS JOIN LATERAL jsonb_array_elements(coalesce(o.recipient_snapshot,'[]'::jsonb)) r
CROSS JOIN LATERAL (SELECT coalesce(o.recipient_progress->(r->>'id'),'{}'::jsonb) AS value) p
WHERE o.state<>'delivered' AND coalesce(p.value->>'state','pending') IN ('pending','processing')
`

type EventRoutingHealthRow struct {
	CapacityWaiting      int64
	OldestPendingSeconds float64
}

func (q *Queries) EventRoutingHealth(ctx context.Context, db DBTX) (EventRoutingHealthRow, error) {
	row := db.QueryRow(ctx, eventRoutingHealth)
	var i EventRoutingHealthRow
	err := row.Scan(&i.CapacityWaiting, &i.OldestPendingSeconds)
	return i, err
}

const eventRoutingLockApp = `-- name: EventRoutingLockApp :one
SELECT id FROM apps WHERE id=$1::uuid AND account_id=$2::uuid
    AND status <> 'deleted' FOR SHARE
`

type EventRoutingLockAppParams struct {
	AppID     pgtype.UUID
	AccountID pgtype.UUID
}

func (q *Queries) EventRoutingLockApp(ctx context.Context, db DBTX, arg EventRoutingLockAppParams) (pgtype.UUID, error) {
	row := db.QueryRow(ctx, eventRoutingLockApp, arg.AppID, arg.AccountID)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const eventRoutingLockReceipt = `-- name: EventRoutingLockReceipt :one
SELECT id, account_id, source, event_id, event_type, schema_version, event_data, payload, state, attempts, available_at, lease_until, claim_token, last_error, created_at, delivered_at, recipient_snapshot, recipient_progress, recipient_claims, customer_storage_bytes FROM event_fanout_outbox WHERE id=$1::bigint FOR UPDATE
`

func (q *Queries) EventRoutingLockReceipt(ctx context.Context, db DBTX, id int64) (EventFanoutOutbox, error) {
	row := db.QueryRow(ctx, eventRoutingLockReceipt, id)
	var i EventFanoutOutbox
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Source,
		&i.EventID,
		&i.EventType,
		&i.SchemaVersion,
		&i.EventData,
		&i.Payload,
		&i.State,
		&i.Attempts,
		&i.AvailableAt,
		&i.LeaseUntil,
		&i.ClaimToken,
		&i.LastError,
		&i.CreatedAt,
		&i.DeliveredAt,
		&i.RecipientSnapshot,
		&i.RecipientProgress,
		&i.RecipientClaims,
		&i.CustomerStorageBytes,
	)
	return i, err
}

const eventRoutingLockRecipient = `-- name: EventRoutingLockRecipient :one
SELECT outbox_id, subscription_id, app_id, recipient, state, generation, attempts, total_attempts, available_at, claim_token, lease_until, capacity_deferrals, generation_capacity_deferrals, backfill_job_id FROM event_fanout_recipients
WHERE outbox_id=$1::bigint AND subscription_id=$2::text FOR UPDATE
`

type EventRoutingLockRecipientParams struct {
	OutboxID       int64
	SubscriptionID string
}

func (q *Queries) EventRoutingLockRecipient(ctx context.Context, db DBTX, arg EventRoutingLockRecipientParams) (EventFanoutRecipient, error) {
	row := db.QueryRow(ctx, eventRoutingLockRecipient, arg.OutboxID, arg.SubscriptionID)
	var i EventFanoutRecipient
	err := row.Scan(
		&i.OutboxID,
		&i.SubscriptionID,
		&i.AppID,
		&i.Recipient,
		&i.State,
		&i.Generation,
		&i.Attempts,
		&i.TotalAttempts,
		&i.AvailableAt,
		&i.ClaimToken,
		&i.LeaseUntil,
		&i.CapacityDeferrals,
		&i.GenerationCapacityDeferrals,
		&i.BackfillJobID,
	)
	return i, err
}

const eventRoutingReceipt = `-- name: EventRoutingReceipt :one
SELECT id, account_id, source, event_id, event_type, schema_version, event_data, payload, state, attempts, available_at, lease_until, claim_token, last_error, created_at, delivered_at, recipient_snapshot, recipient_progress, recipient_claims, customer_storage_bytes FROM event_fanout_outbox WHERE id=$1::bigint
`

func (q *Queries) EventRoutingReceipt(ctx context.Context, db DBTX, id int64) (EventFanoutOutbox, error) {
	row := db.QueryRow(ctx, eventRoutingReceipt, id)
	var i EventFanoutOutbox
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Source,
		&i.EventID,
		&i.EventType,
		&i.SchemaVersion,
		&i.EventData,
		&i.Payload,
		&i.State,
		&i.Attempts,
		&i.AvailableAt,
		&i.LeaseUntil,
		&i.ClaimToken,
		&i.LastError,
		&i.CreatedAt,
		&i.DeliveredAt,
		&i.RecipientSnapshot,
		&i.RecipientProgress,
		&i.RecipientClaims,
		&i.CustomerStorageBytes,
	)
	return i, err
}

const eventRoutingRecordProgress = `-- name: EventRoutingRecordProgress :one
UPDATE event_fanout_outbox o
SET recipient_progress=jsonb_set(o.recipient_progress,ARRAY[$1::text],$2::jsonb,true),
    last_error=CASE WHEN $2::jsonb->>'state'='failed'
      THEN left('subscription ' || $1::text || ': ' || coalesce($2::jsonb->>'last_error','recipient failed'),1024)
      ELSE o.last_error END
WHERE o.id=$3::bigint AND o.claim_token=$4::uuid
    AND o.state='processing' AND NOT o.recipient_claims AND o.lease_until>clock_timestamp()
    AND coalesce(o.recipient_progress->$1::text->>'state','pending') NOT IN ('enqueued','filtered')
    AND coalesce((o.recipient_progress->$1::text->>'capacity_deferrals')::integer,0)
      <=coalesce(($2::jsonb->>'capacity_deferrals')::integer,0)
    AND EXISTS (SELECT 1 FROM jsonb_array_elements(o.recipient_snapshot) r WHERE r->>'id'=$1::text)
RETURNING (SELECT r->>'app_id' FROM jsonb_array_elements(o.recipient_snapshot) r WHERE r->>'id'=$1::text LIMIT 1)::text AS app_id
`

type EventRoutingRecordProgressParams struct {
	SubscriptionID string
	Progress       []byte
	ID             int64
	ClaimToken     pgtype.UUID
}

// An uncertain commit response must not overwrite its durable admission proof.
func (q *Queries) EventRoutingRecordProgress(ctx context.Context, db DBTX, arg EventRoutingRecordProgressParams) (string, error) {
	row := db.QueryRow(ctx, eventRoutingRecordProgress,
		arg.SubscriptionID,
		arg.Progress,
		arg.ID,
		arg.ClaimToken,
	)
	var app_id string
	err := row.Scan(&app_id)
	return app_id, err
}

const eventRoutingSettleSnapshot = `-- name: EventRoutingSettleSnapshot :one
UPDATE event_fanout_outbox o SET state='delivered',delivered_at=clock_timestamp(),claim_token=NULL,lease_until=NULL
WHERE o.id=$1::bigint AND NOT o.recipient_claims
  AND NOT EXISTS (SELECT 1 FROM jsonb_array_elements(o.recipient_snapshot) r
    WHERE coalesce(o.recipient_progress -> (r->>'id')->>'state','pending') NOT IN ('enqueued','filtered','failed'))
RETURNING id
`

func (q *Queries) EventRoutingSettleSnapshot(ctx context.Context, db DBTX, id int64) (int64, error) {
	row := db.QueryRow(ctx, eventRoutingSettleSnapshot, id)
	var id_2 int64
	err := row.Scan(&id_2)
	return id_2, err
}
