// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: financial_budget_queries.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const financialBudgetAccountLock = `-- name: FinancialBudgetAccountLock :one
SELECT id FROM accounts WHERE id = $1::uuid FOR UPDATE
`

// ADR-431. Policy mutations serialize per account and publish an atomic audit.
func (q *Queries) FinancialBudgetAccountLock(ctx context.Context, db DBTX, accountID pgtype.UUID) (pgtype.UUID, error) {
	row := db.QueryRow(ctx, financialBudgetAccountLock, accountID)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const financialBudgetAppActionEligible = `-- name: FinancialBudgetAppActionEligible :one
SELECT EXISTS(
  SELECT 1 FROM apps WHERE id = $1::uuid AND account_id = $2::uuid
    AND status != 'deleted'
    AND CASE $3::text
      WHEN 'stop_previews' THEN preview_of_slug IS NOT NULL AND preview_of_slug != ''
      WHEN 'suspend_background' THEN workload_class IN ('worker','job')
      ELSE true END
)::boolean AS eligible
`

type FinancialBudgetAppActionEligibleParams struct {
	AppID     pgtype.UUID
	AccountID pgtype.UUID
	Action    string
}

func (q *Queries) FinancialBudgetAppActionEligible(ctx context.Context, db DBTX, arg FinancialBudgetAppActionEligibleParams) (bool, error) {
	row := db.QueryRow(ctx, financialBudgetAppActionEligible, arg.AppID, arg.AccountID, arg.Action)
	var eligible bool
	err := row.Scan(&eligible)
	return eligible, err
}

const financialBudgetCount = `-- name: FinancialBudgetCount :one
SELECT count(*)::bigint FROM financial_budget_policies WHERE account_id = $1::uuid AND deleted_at IS NULL
`

func (q *Queries) FinancialBudgetCount(ctx context.Context, db DBTX, accountID pgtype.UUID) (int64, error) {
	row := db.QueryRow(ctx, financialBudgetCount, accountID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const financialBudgetDelete = `-- name: FinancialBudgetDelete :one
UPDATE financial_budget_policies
SET deleted_at = clock_timestamp(), updated_at = clock_timestamp(), revision = revision + 1
WHERE account_id = $1::uuid AND id = $2::uuid
  AND revision = $3::bigint AND deleted_at IS NULL
RETURNING id, account_id, revision, spec, created_at, updated_at, deleted_at
`

type FinancialBudgetDeleteParams struct {
	AccountID        pgtype.UUID
	ID               pgtype.UUID
	ExpectedRevision int64
}

func (q *Queries) FinancialBudgetDelete(ctx context.Context, db DBTX, arg FinancialBudgetDeleteParams) (FinancialBudgetPolicy, error) {
	row := db.QueryRow(ctx, financialBudgetDelete, arg.AccountID, arg.ID, arg.ExpectedRevision)
	var i FinancialBudgetPolicy
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Revision,
		&i.Spec,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const financialBudgetGet = `-- name: FinancialBudgetGet :one
SELECT id, account_id, revision, spec, created_at, updated_at, deleted_at
FROM financial_budget_policies WHERE account_id = $1::uuid AND id = $2::uuid
`

type FinancialBudgetGetParams struct {
	AccountID pgtype.UUID
	ID        pgtype.UUID
}

func (q *Queries) FinancialBudgetGet(ctx context.Context, db DBTX, arg FinancialBudgetGetParams) (FinancialBudgetPolicy, error) {
	row := db.QueryRow(ctx, financialBudgetGet, arg.AccountID, arg.ID)
	var i FinancialBudgetPolicy
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Revision,
		&i.Spec,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const financialBudgetInsert = `-- name: FinancialBudgetInsert :one
INSERT INTO financial_budget_policies(id, account_id, revision, spec)
VALUES($1::uuid, $2::uuid, 1, $3::jsonb)
RETURNING id, account_id, revision, spec, created_at, updated_at, deleted_at
`

type FinancialBudgetInsertParams struct {
	ID        pgtype.UUID
	AccountID pgtype.UUID
	Spec      []byte
}

func (q *Queries) FinancialBudgetInsert(ctx context.Context, db DBTX, arg FinancialBudgetInsertParams) (FinancialBudgetPolicy, error) {
	row := db.QueryRow(ctx, financialBudgetInsert, arg.ID, arg.AccountID, arg.Spec)
	var i FinancialBudgetPolicy
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Revision,
		&i.Spec,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const financialBudgetList = `-- name: FinancialBudgetList :many
SELECT id, account_id, revision, spec, created_at, updated_at, deleted_at
FROM financial_budget_policies
WHERE account_id = $1::uuid AND deleted_at IS NULL
ORDER BY id LIMIT $2::integer
`

type FinancialBudgetListParams struct {
	AccountID pgtype.UUID
	PageSize  int32
}

func (q *Queries) FinancialBudgetList(ctx context.Context, db DBTX, arg FinancialBudgetListParams) ([]FinancialBudgetPolicy, error) {
	rows, err := db.Query(ctx, financialBudgetList, arg.AccountID, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FinancialBudgetPolicy{}
	for rows.Next() {
		var i FinancialBudgetPolicy
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.Revision,
			&i.Spec,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const financialBudgetRevisionInsert = `-- name: FinancialBudgetRevisionInsert :exec
INSERT INTO financial_budget_revisions(account_id, policy_id, revision, actor, mutation, spec)
VALUES($1::uuid, $2::uuid, $3::bigint, $4::text, $5::text, $6::jsonb)
`

type FinancialBudgetRevisionInsertParams struct {
	AccountID pgtype.UUID
	PolicyID  pgtype.UUID
	Revision  int64
	Actor     string
	Mutation  string
	Spec      []byte
}

func (q *Queries) FinancialBudgetRevisionInsert(ctx context.Context, db DBTX, arg FinancialBudgetRevisionInsertParams) error {
	_, err := db.Exec(ctx, financialBudgetRevisionInsert,
		arg.AccountID,
		arg.PolicyID,
		arg.Revision,
		arg.Actor,
		arg.Mutation,
		arg.Spec,
	)
	return err
}

const financialBudgetRevisionList = `-- name: FinancialBudgetRevisionList :many
SELECT account_id, policy_id, revision, actor, mutation, spec, recorded_at
FROM financial_budget_revisions
WHERE account_id = $1::uuid AND policy_id = $2::uuid
  AND revision > $3::bigint
ORDER BY revision LIMIT $4::integer
`

type FinancialBudgetRevisionListParams struct {
	AccountID     pgtype.UUID
	PolicyID      pgtype.UUID
	AfterRevision int64
	PageSize      int32
}

func (q *Queries) FinancialBudgetRevisionList(ctx context.Context, db DBTX, arg FinancialBudgetRevisionListParams) ([]FinancialBudgetRevision, error) {
	rows, err := db.Query(ctx, financialBudgetRevisionList,
		arg.AccountID,
		arg.PolicyID,
		arg.AfterRevision,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FinancialBudgetRevision{}
	for rows.Next() {
		var i FinancialBudgetRevision
		if err := rows.Scan(
			&i.AccountID,
			&i.PolicyID,
			&i.Revision,
			&i.Actor,
			&i.Mutation,
			&i.Spec,
			&i.RecordedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const financialBudgetScopeOwned = `-- name: FinancialBudgetScopeOwned :one
SELECT CASE $1::text
  WHEN 'account' THEN EXISTS(SELECT 1 FROM accounts WHERE id = $2::uuid)
  WHEN 'app' THEN EXISTS(SELECT 1 FROM apps WHERE id = $3::uuid AND account_id = $2::uuid AND status != 'deleted')
  WHEN 'job' THEN EXISTS(SELECT 1 FROM jobs WHERE id = $3::uuid AND account_id = $2::uuid AND status != 'deleted')
  WHEN 'project' THEN EXISTS(SELECT 1 FROM projects WHERE id = $3::uuid AND account_id = $2::uuid)
  WHEN 'environment' THEN EXISTS(SELECT 1 FROM project_environments WHERE id = $3::uuid AND account_id = $2::uuid)
  ELSE false END::boolean AS owned
`

type FinancialBudgetScopeOwnedParams struct {
	ScopeKind string
	AccountID pgtype.UUID
	ScopeID   pgtype.UUID
}

func (q *Queries) FinancialBudgetScopeOwned(ctx context.Context, db DBTX, arg FinancialBudgetScopeOwnedParams) (bool, error) {
	row := db.QueryRow(ctx, financialBudgetScopeOwned, arg.ScopeKind, arg.AccountID, arg.ScopeID)
	var owned bool
	err := row.Scan(&owned)
	return owned, err
}

const financialBudgetUpdate = `-- name: FinancialBudgetUpdate :one
UPDATE financial_budget_policies
SET spec = $1::jsonb, revision = revision + 1, updated_at = clock_timestamp()
WHERE account_id = $2::uuid AND id = $3::uuid
  AND revision = $4::bigint AND deleted_at IS NULL
RETURNING id, account_id, revision, spec, created_at, updated_at, deleted_at
`

type FinancialBudgetUpdateParams struct {
	Spec             []byte
	AccountID        pgtype.UUID
	ID               pgtype.UUID
	ExpectedRevision int64
}

func (q *Queries) FinancialBudgetUpdate(ctx context.Context, db DBTX, arg FinancialBudgetUpdateParams) (FinancialBudgetPolicy, error) {
	row := db.QueryRow(ctx, financialBudgetUpdate,
		arg.Spec,
		arg.AccountID,
		arg.ID,
		arg.ExpectedRevision,
	)
	var i FinancialBudgetPolicy
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Revision,
		&i.Spec,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
