// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: profile_periodic_queries.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimProfilePeriodicMonitor = `-- name: ClaimProfilePeriodicMonitor :one
WITH picked AS (
 SELECT j.id FROM profile_periodic_monitors j JOIN deployments d ON d.id=j.deployment_id JOIN apps a ON a.id=j.app_id
 JOIN profile_deployment_policies p ON p.app_id=j.app_id JOIN accounts ac ON ac.id=j.account_id
 WHERE j.next_attempt_at<=$3::timestamptz AND (j.lease_until IS NULL OR j.lease_until<=$3::timestamptz)
 AND p.enabled AND jsonb_typeof(p.config->'periodic')='object' AND p.revision=j.policy_revision AND p.config->'options'->'routes' ? j.route
 AND a.account_id=j.account_id AND a.status<>'deleted' AND d.app_id=a.id AND d.status='live' AND d.rollout_state='complete' AND d.deleted_at IS NULL
 AND ac.plan IN ('hobby','pro','scale') AND ac.status IN ('active','past_due') AND ac.abuse_hold_at IS NULL
 ORDER BY j.next_attempt_at,j.id FOR UPDATE OF j SKIP LOCKED LIMIT 1
)
UPDATE profile_periodic_monitors j SET lease_token=$1::text::uuid,lease_until=$2::timestamptz,attempts=LEAST(j.attempts+1,6)
FROM picked WHERE j.id=picked.id
RETURNING jsonb_build_object('monitor',j.data || jsonb_build_object('attempts',j.attempts,'next_attempt_at',j.next_attempt_at),'account_id',j.account_id) AS work
`

type ClaimProfilePeriodicMonitorParams struct {
	Token      string
	LeaseUntil pgtype.Timestamptz
	ObservedAt pgtype.Timestamptz
}

func (q *Queries) ClaimProfilePeriodicMonitor(ctx context.Context, db DBTX, arg ClaimProfilePeriodicMonitorParams) ([]byte, error) {
	row := db.QueryRow(ctx, claimProfilePeriodicMonitor, arg.Token, arg.LeaseUntil, arg.ObservedAt)
	var work []byte
	err := row.Scan(&work)
	return work, err
}

const discoverProfilePeriodicCandidates = `-- name: DiscoverProfilePeriodicCandidates :many
SELECT jsonb_build_object('deployment_id',d.id,'app_id',d.app_id,'account_id',p.account_id,'scope',d.scope,'completed_at',d.rollout_completed_at,'route',r.route,
 'policy',jsonb_build_object('app_id',p.app_id,'revision',p.revision,'config',p.config,'updated_at',p.updated_at)) AS candidate
FROM deployments d JOIN apps a ON a.id=d.app_id JOIN profile_deployment_policies p ON p.app_id=a.id JOIN accounts ac ON ac.id=p.account_id
CROSS JOIN LATERAL jsonb_array_elements_text(p.config->'options'->'routes') r(route)
WHERE p.enabled AND jsonb_typeof(p.config->'periodic')='object' AND a.account_id=p.account_id AND a.status<>'deleted'
 AND ac.plan IN ('hobby','pro','scale') AND ac.status IN ('active','past_due') AND ac.abuse_hold_at IS NULL
 AND d.status='live' AND d.rollout_state='complete' AND d.deleted_at IS NULL AND d.rollout_completed_at IS NOT NULL
 AND NOT EXISTS(SELECT 1 FROM profile_periodic_monitors j WHERE j.deployment_id=d.id AND j.policy_revision=p.revision AND j.route=r.route)
ORDER BY d.id,r.route LIMIT $1::int
`

func (q *Queries) DiscoverProfilePeriodicCandidates(ctx context.Context, db DBTX, maxRows int32) ([][]byte, error) {
	rows, err := db.Query(ctx, discoverProfilePeriodicCandidates, maxRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := [][]byte{}
	for rows.Next() {
		var candidate []byte
		if err := rows.Scan(&candidate); err != nil {
			return nil, err
		}
		items = append(items, candidate)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const enqueueProfilePeriodicMonitor = `-- name: EnqueueProfilePeriodicMonitor :exec
INSERT INTO profile_periodic_monitors(id,app_id,account_id,deployment_id,policy_revision,route,data,next_attempt_at,updated_at)
SELECT $1::text::uuid,a.id,a.account_id,d.id,p.revision,$2::text,$3::jsonb,$4::timestamptz,$5::timestamptz
FROM deployments d JOIN apps a ON a.id=d.app_id JOIN profile_deployment_policies p ON p.app_id=a.id
WHERE d.id=$6::text::uuid AND a.id=$7::text::uuid AND a.account_id=$8::text::uuid AND a.status<>'deleted'
 AND d.status='live' AND d.rollout_state='complete' AND d.deleted_at IS NULL AND p.revision=$9 AND p.enabled AND jsonb_typeof(p.config->'periodic')='object'
 AND p.config->'options'->'routes' ? $2::text
ON CONFLICT(deployment_id,policy_revision,route) DO NOTHING
`

type EnqueueProfilePeriodicMonitorParams struct {
	ID             string
	Route          string
	Data           []byte
	Due            pgtype.Timestamptz
	ObservedAt     pgtype.Timestamptz
	DeploymentID   string
	AppID          string
	AccountID      string
	PolicyRevision int64
}

func (q *Queries) EnqueueProfilePeriodicMonitor(ctx context.Context, db DBTX, arg EnqueueProfilePeriodicMonitorParams) error {
	_, err := db.Exec(ctx, enqueueProfilePeriodicMonitor,
		arg.ID,
		arg.Route,
		arg.Data,
		arg.Due,
		arg.ObservedAt,
		arg.DeploymentID,
		arg.AppID,
		arg.AccountID,
		arg.PolicyRevision,
	)
	return err
}

const finishProfilePeriodicMonitor = `-- name: FinishProfilePeriodicMonitor :exec
UPDATE profile_periodic_monitors SET data=$1::jsonb,next_attempt_at=$2::timestamptz,attempts=$3::int,
 lease_token=NULL,lease_until=NULL,updated_at=$4::timestamptz
WHERE id=$5::text::uuid AND lease_token=$6::text::uuid
`

type FinishProfilePeriodicMonitorParams struct {
	Data       []byte
	Due        pgtype.Timestamptz
	Attempts   int32
	ObservedAt pgtype.Timestamptz
	ID         string
	Token      string
}

func (q *Queries) FinishProfilePeriodicMonitor(ctx context.Context, db DBTX, arg FinishProfilePeriodicMonitorParams) error {
	_, err := db.Exec(ctx, finishProfilePeriodicMonitor,
		arg.Data,
		arg.Due,
		arg.Attempts,
		arg.ObservedAt,
		arg.ID,
		arg.Token,
	)
	return err
}

const listProfilePeriodicMonitors = `-- name: ListProfilePeriodicMonitors :many
SELECT (j.data || jsonb_build_object('attempts',j.attempts,'next_attempt_at',j.next_attempt_at,'active',coalesce(p.enabled AND p.revision=j.policy_revision AND jsonb_typeof(p.config->'periodic')='object' AND d.status='live' AND d.rollout_state='complete' AND d.deleted_at IS NULL AND ac.plan IN ('hobby','pro','scale') AND ac.status IN ('active','past_due') AND ac.abuse_hold_at IS NULL,false)))::jsonb AS monitor
FROM profile_periodic_monitors j JOIN apps a ON a.id=j.app_id JOIN deployments d ON d.id=j.deployment_id JOIN accounts ac ON ac.id=j.account_id LEFT JOIN profile_deployment_policies p ON p.app_id=j.app_id
WHERE j.app_id=$1::text::uuid AND j.account_id=$2::text::uuid AND a.account_id=j.account_id AND a.status<>'deleted'
ORDER BY j.updated_at DESC,j.id LIMIT $3::int
`

type ListProfilePeriodicMonitorsParams struct {
	AppID     string
	AccountID string
	MaxRows   int32
}

func (q *Queries) ListProfilePeriodicMonitors(ctx context.Context, db DBTX, arg ListProfilePeriodicMonitorsParams) ([][]byte, error) {
	rows, err := db.Query(ctx, listProfilePeriodicMonitors, arg.AppID, arg.AccountID, arg.MaxRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := [][]byte{}
	for rows.Next() {
		var monitor []byte
		if err := rows.Scan(&monitor); err != nil {
			return nil, err
		}
		items = append(items, monitor)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockProfilePeriodicMonitor = `-- name: LockProfilePeriodicMonitor :one
SELECT (j.data || jsonb_build_object('attempts',j.attempts,'next_attempt_at',j.next_attempt_at))::jsonb AS monitor
FROM profile_periodic_monitors j JOIN deployments d ON d.id=j.deployment_id JOIN profile_deployment_policies p ON p.app_id=j.app_id JOIN accounts ac ON ac.id=j.account_id
WHERE j.id=$1::text::uuid AND j.app_id=$2::text::uuid AND j.account_id=$3::text::uuid
 AND j.lease_token=$4::text::uuid AND j.lease_until>$5::timestamptz
 AND d.status='live' AND d.rollout_state='complete' AND d.deleted_at IS NULL AND p.enabled AND p.revision=j.policy_revision AND jsonb_typeof(p.config->'periodic')='object'
 AND ac.plan IN ('hobby','pro','scale') AND ac.status IN ('active','past_due') AND ac.abuse_hold_at IS NULL
FOR UPDATE OF j
`

type LockProfilePeriodicMonitorParams struct {
	ID         string
	AppID      string
	AccountID  string
	Token      string
	ObservedAt pgtype.Timestamptz
}

func (q *Queries) LockProfilePeriodicMonitor(ctx context.Context, db DBTX, arg LockProfilePeriodicMonitorParams) ([]byte, error) {
	row := db.QueryRow(ctx, lockProfilePeriodicMonitor,
		arg.ID,
		arg.AppID,
		arg.AccountID,
		arg.Token,
		arg.ObservedAt,
	)
	var monitor []byte
	err := row.Scan(&monitor)
	return monitor, err
}

const pruneProfilePeriodicMonitors = `-- name: PruneProfilePeriodicMonitors :exec
DELETE FROM profile_periodic_monitors WHERE id IN (
 SELECT j.id FROM profile_periodic_monitors j WHERE j.updated_at<$1::timestamptz
 AND NOT EXISTS(SELECT 1 FROM profile_deployment_policies p JOIN deployments d ON d.app_id=p.app_id JOIN accounts ac ON ac.id=p.account_id
 WHERE d.id=j.deployment_id AND d.status='live' AND d.rollout_state='complete' AND d.deleted_at IS NULL AND ac.plan IN ('hobby','pro','scale') AND ac.status IN ('active','past_due') AND ac.abuse_hold_at IS NULL AND p.enabled AND p.revision=j.policy_revision AND jsonb_typeof(p.config->'periodic')='object' AND p.config->'options'->'routes' ? j.route)
 ORDER BY j.updated_at,j.id LIMIT $2::int
)
`

type PruneProfilePeriodicMonitorsParams struct {
	Cutoff  pgtype.Timestamptz
	MaxRows int32
}

func (q *Queries) PruneProfilePeriodicMonitors(ctx context.Context, db DBTX, arg PruneProfilePeriodicMonitorsParams) error {
	_, err := db.Exec(ctx, pruneProfilePeriodicMonitors, arg.Cutoff, arg.MaxRows)
	return err
}
