// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: telemetry_coverage_queries.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const lockRouteRemovalCoverage = `-- name: LockRouteRemovalCoverage :exec
SELECT lock_route_removal_coverage($1::uuid)
`

func (q *Queries) LockRouteRemovalCoverage(ctx context.Context, db DBTX, appID pgtype.UUID) error {
	_, err := db.Exec(ctx, lockRouteRemovalCoverage, appID)
	return err
}

const recordTelemetryCoverage = `-- name: RecordTelemetryCoverage :exec
SELECT record_telemetry_coverage($1::text, $2::uuid, $3::bigint,
 $4::boolean, $5::integer, $6::bigint,
 $7::integer, $8::timestamptz,
 $9::boolean,$10::bigint,$11::jsonb)
`

type RecordTelemetryCoverageParams struct {
	NodeName                 string
	BootID                   pgtype.UUID
	Sequence                 int64
	Enabled                  bool
	SamplingBasisPoints      int32
	DroppedTotal             int64
	PendingCount             int32
	SourceAt                 pgtype.Timestamptz
	AppScoped                bool
	UnattributedDroppedTotal int64
	AppGaps                  []byte
}

func (q *Queries) RecordTelemetryCoverage(ctx context.Context, db DBTX, arg RecordTelemetryCoverageParams) error {
	_, err := db.Exec(ctx, recordTelemetryCoverage,
		arg.NodeName,
		arg.BootID,
		arg.Sequence,
		arg.Enabled,
		arg.SamplingBasisPoints,
		arg.DroppedTotal,
		arg.PendingCount,
		arg.SourceAt,
		arg.AppScoped,
		arg.UnattributedDroppedTotal,
		arg.AppGaps,
	)
	return err
}

const routeRemovalCoverageBlockers = `-- name: RouteRemovalCoverageBlockers :one
SELECT route_removal_coverage_blockers($1::uuid,$2::timestamptz, $3::timestamptz)::jsonb
`

type RouteRemovalCoverageBlockersParams struct {
	AppID       pgtype.UUID
	WindowFrom  pgtype.Timestamptz
	WindowUntil pgtype.Timestamptz
}

func (q *Queries) RouteRemovalCoverageBlockers(ctx context.Context, db DBTX, arg RouteRemovalCoverageBlockersParams) ([]byte, error) {
	row := db.QueryRow(ctx, routeRemovalCoverageBlockers, arg.AppID, arg.WindowFrom, arg.WindowUntil)
	var column_1 []byte
	err := row.Scan(&column_1)
	return column_1, err
}
