// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: work_admission_queries.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const workAdmissionCancel = `-- name: WorkAdmissionCancel :execrows
UPDATE invocations SET state='cancelled',completed_at=clock_timestamp()
WHERE app_id=$1::uuid AND work_policy_name=$2::text
    AND work_key_digest=$3::bytea AND state='pending'
`

type WorkAdmissionCancelParams struct {
	AppID      pgtype.UUID
	PolicyName string
	KeyDigest  []byte
}

func (q *Queries) WorkAdmissionCancel(ctx context.Context, db DBTX, arg WorkAdmissionCancelParams) (int64, error) {
	result, err := db.Exec(ctx, workAdmissionCancel, arg.AppID, arg.PolicyName, arg.KeyDigest)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const workAdmissionCancelBroker = `-- name: WorkAdmissionCancelBroker :execrows
UPDATE trigger_records tr SET state='cancelled',last_error='cancelled by work policy',claim_expires_at=NULL
FROM triggers t WHERE t.id=tr.trigger_id AND t.app_id=$1::uuid
    AND tr.work_policy_name=$2::text AND tr.work_key_digest=$3::bytea
    AND tr.state IN ('pending','retry')
`

type WorkAdmissionCancelBrokerParams struct {
	AppID      pgtype.UUID
	PolicyName string
	KeyDigest  []byte
}

func (q *Queries) WorkAdmissionCancelBroker(ctx context.Context, db DBTX, arg WorkAdmissionCancelBrokerParams) (int64, error) {
	result, err := db.Exec(ctx, workAdmissionCancelBroker, arg.AppID, arg.PolicyName, arg.KeyDigest)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const workAdmissionCancellation = `-- name: WorkAdmissionCancellation :one
SELECT id, app_id, policy_name, key_digest, cancelled_count, created_at FROM invocation_work_cancellations WHERE id=$1::uuid
`

func (q *Queries) WorkAdmissionCancellation(ctx context.Context, db DBTX, id pgtype.UUID) (InvocationWorkCancellation, error) {
	row := db.QueryRow(ctx, workAdmissionCancellation, id)
	var i InvocationWorkCancellation
	err := row.Scan(
		&i.ID,
		&i.AppID,
		&i.PolicyName,
		&i.KeyDigest,
		&i.CancelledCount,
		&i.CreatedAt,
	)
	return i, err
}

const workAdmissionEnsureLane = `-- name: WorkAdmissionEnsureLane :exec
INSERT INTO invocation_work_lanes (app_id, policy_name, key_digest)
VALUES ($1::uuid, $2::text, $3::bytea)
ON CONFLICT DO NOTHING
`

type WorkAdmissionEnsureLaneParams struct {
	AppID      pgtype.UUID
	PolicyName string
	KeyDigest  []byte
}

func (q *Queries) WorkAdmissionEnsureLane(ctx context.Context, db DBTX, arg WorkAdmissionEnsureLaneParams) error {
	_, err := db.Exec(ctx, workAdmissionEnsureLane, arg.AppID, arg.PolicyName, arg.KeyDigest)
	return err
}

const workAdmissionFinishCancellation = `-- name: WorkAdmissionFinishCancellation :one
UPDATE invocation_work_cancellations SET cancelled_count=$1::bigint
WHERE id=$2::uuid RETURNING id, app_id, policy_name, key_digest, cancelled_count, created_at
`

type WorkAdmissionFinishCancellationParams struct {
	CancelledCount int64
	ID             pgtype.UUID
}

func (q *Queries) WorkAdmissionFinishCancellation(ctx context.Context, db DBTX, arg WorkAdmissionFinishCancellationParams) (InvocationWorkCancellation, error) {
	row := db.QueryRow(ctx, workAdmissionFinishCancellation, arg.CancelledCount, arg.ID)
	var i InvocationWorkCancellation
	err := row.Scan(
		&i.ID,
		&i.AppID,
		&i.PolicyName,
		&i.KeyDigest,
		&i.CancelledCount,
		&i.CreatedAt,
	)
	return i, err
}

const workAdmissionInsertCancellation = `-- name: WorkAdmissionInsertCancellation :one
INSERT INTO invocation_work_cancellations (id,app_id,policy_name,key_digest)
VALUES ($1::uuid,$2::uuid,$3::text,$4::bytea)
ON CONFLICT (id) DO NOTHING RETURNING id
`

type WorkAdmissionInsertCancellationParams struct {
	ID         pgtype.UUID
	AppID      pgtype.UUID
	PolicyName string
	KeyDigest  []byte
}

func (q *Queries) WorkAdmissionInsertCancellation(ctx context.Context, db DBTX, arg WorkAdmissionInsertCancellationParams) (pgtype.UUID, error) {
	row := db.QueryRow(ctx, workAdmissionInsertCancellation,
		arg.ID,
		arg.AppID,
		arg.PolicyName,
		arg.KeyDigest,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const workAdmissionInvocation = `-- name: WorkAdmissionInvocation :one
SELECT id, app_id, account_id, source, state, payload, headers, due_at, method, path, cron_id, scheduled_at, ack_url, result, lease_expires_at, received_at, completed_at, instance_id, attempts, last_error, created_at, org_id, outcome, deadline_at, retry_policy, result_retention_until, replayed_from_invocation_id, last_replayed_at, on_success_destination_id, on_failure_destination_id, queue_name, quota_reserved, work_policy_name, work_key_digest, work_expires_at, work_sequence, work_policy_revision, work_fairness_digest, work_fairness_limit, platform_tenant_id, failure_rules, occurrence_id, start_deadline_at, work_decision, operation_id, deployment_scope, queue_binding_id, replay_generation, outcome_code, replay_root_invocation_id, replay_root_created_at FROM invocations WHERE id=$1::uuid
`

func (q *Queries) WorkAdmissionInvocation(ctx context.Context, db DBTX, id pgtype.UUID) (Invocation, error) {
	row := db.QueryRow(ctx, workAdmissionInvocation, id)
	var i Invocation
	err := row.Scan(
		&i.ID,
		&i.AppID,
		&i.AccountID,
		&i.Source,
		&i.State,
		&i.Payload,
		&i.Headers,
		&i.DueAt,
		&i.Method,
		&i.Path,
		&i.CronID,
		&i.ScheduledAt,
		&i.AckUrl,
		&i.Result,
		&i.LeaseExpiresAt,
		&i.ReceivedAt,
		&i.CompletedAt,
		&i.InstanceID,
		&i.Attempts,
		&i.LastError,
		&i.CreatedAt,
		&i.OrgID,
		&i.Outcome,
		&i.DeadlineAt,
		&i.RetryPolicy,
		&i.ResultRetentionUntil,
		&i.ReplayedFromInvocationID,
		&i.LastReplayedAt,
		&i.OnSuccessDestinationID,
		&i.OnFailureDestinationID,
		&i.QueueName,
		&i.QuotaReserved,
		&i.WorkPolicyName,
		&i.WorkKeyDigest,
		&i.WorkExpiresAt,
		&i.WorkSequence,
		&i.WorkPolicyRevision,
		&i.WorkFairnessDigest,
		&i.WorkFairnessLimit,
		&i.PlatformTenantID,
		&i.FailureRules,
		&i.OccurrenceID,
		&i.StartDeadlineAt,
		&i.WorkDecision,
		&i.OperationID,
		&i.DeploymentScope,
		&i.QueueBindingID,
		&i.ReplayGeneration,
		&i.OutcomeCode,
		&i.ReplayRootInvocationID,
		&i.ReplayRootCreatedAt,
	)
	return i, err
}

const workAdmissionSupersede = `-- name: WorkAdmissionSupersede :exec
UPDATE invocations SET state='superseded', outcome='superseded', completed_at=clock_timestamp(),
    last_error='superseded by newer work'
WHERE app_id=$1::uuid AND work_policy_name=$2::text
    AND work_key_digest=$3::bytea AND state='pending'
`

type WorkAdmissionSupersedeParams struct {
	AppID      pgtype.UUID
	PolicyName string
	KeyDigest  []byte
}

func (q *Queries) WorkAdmissionSupersede(ctx context.Context, db DBTX, arg WorkAdmissionSupersedeParams) error {
	_, err := db.Exec(ctx, workAdmissionSupersede, arg.AppID, arg.PolicyName, arg.KeyDigest)
	return err
}

const workAdmissionSupersedeBroker = `-- name: WorkAdmissionSupersedeBroker :exec
UPDATE trigger_records tr SET state='superseded', last_error='superseded by newer work', claim_expires_at=NULL
FROM triggers t WHERE t.id=tr.trigger_id AND t.app_id=$1::uuid
    AND tr.work_policy_name=$2::text AND tr.work_key_digest=$3::bytea
    AND tr.state IN ('pending','retry')
`

type WorkAdmissionSupersedeBrokerParams struct {
	AppID      pgtype.UUID
	PolicyName string
	KeyDigest  []byte
}

func (q *Queries) WorkAdmissionSupersedeBroker(ctx context.Context, db DBTX, arg WorkAdmissionSupersedeBrokerParams) error {
	_, err := db.Exec(ctx, workAdmissionSupersedeBroker, arg.AppID, arg.PolicyName, arg.KeyDigest)
	return err
}
