// job_supervisor_linux.go — guest-init's job-task entrypoint (ADR-099 PR-C).
//
// JobTaskSupervisor runs INSIDE the task VM (cold-booted by
// schedd.Engine.WakeJob) and is responsible for:
//
//   1. Reading /etc/job/task.env (mounted by vmmd at boot; carries
//      {JOB_ID, RUN_ID, TASK_INDEX, ATTEMPT, TASK_TIMEOUT_S,
//      IMAGE_REF, TASK_COMMAND}). The TASK_COMMAND is the
//      user-provided shell command to run; on missing /etc/job
//      the supervisor exits 78 (EX_CONFIG) per the runbook.
//
//   2. Forking the command under a process group, capturing
//      stdout/stderr to the supervisor log buffer.
//
//   3. On the foreground command's exit, sending the job_exit
//      DGRAM (vsock port 1026, msg_type=4) with the
//      {exit_code:u32 LE, signal:u32 LE, epoch_ns:u64 LE} payload.
//      Same port as the characterization probe (mutually exclusive
//      in time — the supervisor runs AFTER characterization).
//
//   4. Powering off the VM via the guest's halt syscall.
//
// The supervisor is launched by main_linux.go on the job-task
// boot path; the wake path's `Runtime: "job"` AppSpec field
// (pkg/sched/jobs.go) is what triggers this entrypoint instead
// of the customer HTTP server path.
package init

import (
	"bytes"
	"encoding/binary"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"syscall"
	"time"

	"golang.org/x/sys/unix"

	"github.com/onebox-faas/faas/pkg/api"
)

// VsockJobExitPort (ADR-099 PR-C) is the host-side AF_VSOCK port
// the supervisor dials for job_exit. Matches
// pkg/fcvm/vmm.go::VsockCharacterizationHostPort (=1026). The
// port is shared between characterization and job_exit (the
// msg_type discriminator routes each frame to the right
// parser). Distinct from VsockResumePort (1024) and
// VsockStatelessAdvisoryPort (1025).
//
// ADR-099 §3.2 reserves the vsock port map as:
//   1024 resume
//   1025 stateless
//   1026 characterization + job_exit (msg_type=3 / =4)
//   1027 framework/sidecar
//   1028 liveness
const VsockJobExitPort uint32 = 1026

// VsockJobExitMsgType (ADR-099 PR-C) is the wire-format
// discriminator for a guest→host job_exit report. Matches
// pkg/fcvm/vmm.go::VsockJobExitMsgType (=4). Distinct from
// VsockCharacterizationMsgType (=3) so a misrouted frame is
// caught at the type byte.
const VsockJobExitMsgType uint32 = 4

// JobTaskEnvironment is the typed /etc/job/task.env shape.
// Fields are all strings (the env file is shell-sourceable
// and the supervisor reads it via os.Getenv-style helpers).
type JobTaskEnvironment struct {
	JOB_ID        string
	RUN_ID        string
	TASK_INDEX    string
	ATTEMPT       string
	TASK_TIMEOUT_S string
	IMAGE_REF     string
	TASK_COMMAND  string
}

// ReadJobTaskEnv reads /etc/job/task.env and returns the parsed
// struct. Returns an error on missing file or missing TASK_COMMAND
// (the latter exits 78 — EX_CONFIG — to surface "job misconfigured"
// to the customer).
func ReadJobTaskEnv(path string) (JobTaskEnvironment, error) {
	var env JobTaskEnvironment
	data, err := os.ReadFile(path)
	if err != nil {
		return env, fmt.Errorf("job_supervisor: read %s: %w", path, err)
	}
	// Naive KEY=VALUE parser. Comments (#) and quoting are
	// NOT handled (the file is generated by vmmd from the
	// validated run row; if a future migration widens the
	// shape, this parser grows alongside it).
	for _, line := range bytes.Split(data, []byte{'\n'}) {
		line = bytes.TrimSpace(line)
		if len(line) == 0 || line[0] == '#' {
			continue
		}
		eq := bytes.IndexByte(line, '=')
		if eq < 0 {
			continue
		}
		key := string(bytes.TrimSpace(line[:eq]))
		val := string(bytes.TrimSpace(line[eq+1:]))
		switch key {
		case "JOB_ID":
			env.JOB_ID = val
		case "RUN_ID":
			env.RUN_ID = val
		case "TASK_INDEX":
			env.TASK_INDEX = val
		case "ATTEMPT":
			env.ATTEMPT = val
		case "TASK_TIMEOUT_S":
			env.TASK_TIMEOUT_S = val
		case "IMAGE_REF":
			env.IMAGE_REF = val
		case "TASK_COMMAND":
			env.TASK_COMMAND = val
		}
	}
	if env.TASK_COMMAND == "" {
		return env, fmt.Errorf("job_supervisor: %s missing TASK_COMMAND", path)
	}
	return env, nil
}

// RunJobTask is the supervisor's entrypoint. It reads the env,
// forks the task command, waits for it, ships the job_exit DGRAM,
// and powers off. The function does not return — VM powers off.
//
// timeoutS is the per-task wall-clock budget (the
// sched-side watchdog's deadline). On overrun the supervisor
// kills the task process group and ships the exit anyway
// (signal=SIGKILL, exit_code=-1). The watchdog at the host
// side is the canonical authority on the deadline — the
// supervisor's local kill is just a cleanup.
func RunJobTask(envPath string, timeoutS int, log *slogLogger) {
	env, err := ReadJobTaskEnv(envPath)
	if err != nil {
		// EX_CONFIG — misconfigured run row. Ship the
		// exit and let the host record the failure.
		log.Warn("job_supervisor: env read", "err", err)
		shipJobExit(78, 0)
		poweroff()
		return
	}

	// Fork the task command. /bin/sh -c "$TASK_COMMAND"
	// matches the customer-facing contract (the command is a
	// shell string, not an argv list — same shape as
	// CronCommand).
	cmd := exec.Command("/bin/sh", "-c", env.TASK_COMMAND)
	cmd.Stdout = os.Stdout
	cmd.Stderr = os.Stderr
	cmd.SysProcAttr = &syscall.SysProcAttr{
		// New process group so the supervisor can SIGKILL
		// the whole subtree on timeout.
		Setpgid: true,
	}
	if err := cmd.Start(); err != nil {
		log.Warn("job_supervisor: start", "err", err)
		shipJobExit(126, 0) // 126 = "command found but not executable"
		poweroff()
		return
	}

	// Wait with a per-task timeout. The supervisor's local
	// deadline matches the host watchdog's deadline plus a
	// small grace (the watchdog has its own timer; this is
	// belt-and-braces).
	done := make(chan error, 1)
	go func() { done <- cmd.Wait() } }
	var exitCode int32
	var signal int32
	select {
	case werr := <-done:
		// Normal exit. Translate the error into the
		// {exit_code, signal} pair.
		if werr != nil {
			if ee, ok := werr.(*exec.ExitError); ok {
				exitCode = int32(ee.ExitCode())
				if ws, ok := ee.Sys().(syscall.WaitStatus); ok {
					if ws.Signaled() {
						signal = int32(ws.Signal())
						exitCode = -1
					}
				}
			} else {
				exitCode = 1
			}
		}
	case <-time.After(time.Duration(timeoutS+5) * time.Second):
		// Local timeout tripped. Kill the process group
		// and record SIGKILL.
		_ = syscall.Kill(-cmd.Process.Pid, syscall.SIGKILL)
		<-done
		exitCode = -1
		signal = int32(syscall.SIGKILL)
	}

	shipJobExit(int(exitCode), int(signal))
	poweroff()
}

// shipJobExit dials host CID 2 at VsockJobExitPort and writes
// [msg_type 4 BE][exit_code 4 LE][signal 4 LE][epoch_ns 8 LE].
// The 4-byte msg_type prefix matches the characterization
// framing; the payload is little-endian to match the host's
// WaitJobExit decoder.
//
// Best-effort: a connect failure (host gone, vsock transport
// glitch) is logged at Warn but doesn't change the supervisor's
// exit path. The host watchdog's stale-task sweep is the
// ultimate authority on liveness.
func shipJobExit(exitCode, signal int) {
	conn, err := unix.Socket(unix.AF_VSOCK, unix.SOCK_STREAM|unix.SOCK_CLOEXEC, 0)
	if err != nil {
		return
	}
	defer func() { _ = unix.Close(conn) }()
	addr := &unix.SockaddrVM{
		CID:  unix.VMADDR_CID_HOST,
		Port: VsockJobExitPort,
	}
	_ = unix.Connect(conn, addr)

	var hdr [4]byte
	binary.BigEndian.PutUint32(hdr[:], VsockJobExitMsgType)
	if _, err := unix.Write(conn, hdr[:]); err != nil {
		return
	}
	var payload [16]byte
	binary.LittleEndian.PutUint32(payload[0:4], uint32(int32(exitCode)))
	binary.LittleEndian.PutUint32(payload[4:8], uint32(int32(signal)))
	binary.LittleEndian.PutUint64(payload[8:16], uint64(time.Now().UnixNano()))
	_, _ = unix.Write(conn, payload[:])
}

// poweroff halts the VM via the ACPI poweroff path (same as the
// resume hook's exit path). Returns nothing because the kernel
// never returns from this syscall in normal operation.
func poweroff() {
	_ = unix.Reboot(unix.LINUX_REBOOT_CMD_POWER_OFF)
	// Defensive: if the reboot syscall fails (rare; only on a
	// non-ACPI host), exit the supervisor process and let the
	// guest-init PID-1 reap. A second-best outcome is a leaked
	// VM the host watchdog will clean up.
	os.Exit(0)
}

// slogLogger is the minimal slog surface the supervisor uses.
// We avoid importing log/slog directly to keep the guest-init
// import surface small — main_linux.go wires a real *slog.Logger
// at process init time and we accept the same shape here.
type slogLogger = struct {
	Info  func(msg string, args ...any)
	Warn  func(msg string, args ...any)
	Debug func(msg string, args ...any)
	Error func(msg string, args ...any)
}

// _ keeps api + filepath imports live for the surrounding code
// (the supervisor's command parsing may grow to use api helpers
// in a follow-up; filepath is used by the env-file lookup).
var _ = api.PlanFree
var _ = filepath.Join
