from typing import Literal

AlertRuleResponseMetric = Literal[
    "account_spend_eur",
    "api_up",
    "cert_expiry_seconds",
    "cert_issuance_failed",
    "cold_start_pct",
    "cold_wake_rate_pct",
    "daily_cost_cents",
    "deployment_failed",
    "error_rate_pct",
    "event_completion_latency_p95_seconds",
    "event_drain_rate_per_second",
    "event_execution_dead_letter_rate_per_second",
    "event_execution_dead_letters",
    "event_handler_failure_pct",
    "event_oldest_pending_seconds",
    "event_paused_seconds",
    "event_pending_recipients",
    "event_recovery_capacity_wait_jobs",
    "event_recovery_expiring_jobs",
    "event_recovery_stalled_jobs",
    "event_retry_rate_per_second",
    "event_routing_latency_p95_seconds",
    "event_terminal_failure_pct",
    "failed_invocations",
    "latency_p50_ms",
    "latency_p95_ms",
    "latency_p99_ms",
    "new_error_fingerprint",
    "pre_auth_target_signal_gap_pct",
    "pre_auth_target_threshold",
    "queue_depth",
    "request_count",
    "slo_burn_rate",
    "synthetic_check_consecutive_failures",
    "synthetic_check_latency_p95_ms",
    "workflow_due_age_seconds",
    "workflow_failures",
    "workflow_pending_age_seconds",
    "workflow_schedule_quota_skips",
    "workflow_waiting_age_seconds",
]

ALERT_RULE_RESPONSE_METRIC_VALUES: set[AlertRuleResponseMetric] = {
    "account_spend_eur",
    "api_up",
    "cert_expiry_seconds",
    "cert_issuance_failed",
    "cold_start_pct",
    "cold_wake_rate_pct",
    "daily_cost_cents",
    "deployment_failed",
    "error_rate_pct",
    "event_completion_latency_p95_seconds",
    "event_drain_rate_per_second",
    "event_execution_dead_letter_rate_per_second",
    "event_execution_dead_letters",
    "event_handler_failure_pct",
    "event_oldest_pending_seconds",
    "event_paused_seconds",
    "event_pending_recipients",
    "event_recovery_capacity_wait_jobs",
    "event_recovery_expiring_jobs",
    "event_recovery_stalled_jobs",
    "event_retry_rate_per_second",
    "event_routing_latency_p95_seconds",
    "event_terminal_failure_pct",
    "failed_invocations",
    "latency_p50_ms",
    "latency_p95_ms",
    "latency_p99_ms",
    "new_error_fingerprint",
    "pre_auth_target_signal_gap_pct",
    "pre_auth_target_threshold",
    "queue_depth",
    "request_count",
    "slo_burn_rate",
    "synthetic_check_consecutive_failures",
    "synthetic_check_latency_p95_ms",
    "workflow_due_age_seconds",
    "workflow_failures",
    "workflow_pending_age_seconds",
    "workflow_schedule_quota_skips",
    "workflow_waiting_age_seconds",
}


def check_alert_rule_response_metric(value: str) -> AlertRuleResponseMetric:
    if value in ALERT_RULE_RESPONSE_METRIC_VALUES:
        return value
    raise TypeError(f"Unexpected value {value!r}. Expected one of {ALERT_RULE_RESPONSE_METRIC_VALUES!r}")
