from typing import Literal

UpdateAlertRuleRequestMetric = Literal[
    "account_spend_eur",
    "api_up",
    "cert_expiry_seconds",
    "cert_issuance_failed",
    "cold_start_pct",
    "cold_wake_rate_pct",
    "daily_cost_cents",
    "deployment_failed",
    "error_rate_pct",
    "event_completion_latency_p95_seconds",
    "event_drain_rate_per_second",
    "event_execution_dead_letter_rate_per_second",
    "event_execution_dead_letters",
    "event_handler_failure_pct",
    "event_oldest_pending_seconds",
    "event_paused_seconds",
    "event_pending_recipients",
    "event_recovery_capacity_wait_jobs",
    "event_recovery_execution_prolonged_wait_jobs",
    "event_recovery_execution_retention_risk_jobs",
    "event_recovery_execution_unknown_jobs",
    "event_recovery_execution_waiting_jobs",
    "event_recovery_expiring_jobs",
    "event_recovery_stalled_jobs",
    "event_retention_expiring_receipts",
    "event_retry_rate_per_second",
    "event_routing_latency_p95_seconds",
    "event_storage_utilization_pct",
    "event_terminal_failure_pct",
    "failed_invocations",
    "latency_p50_ms",
    "latency_p95_ms",
    "latency_p99_ms",
    "new_error_fingerprint",
    "pre_auth_target_signal_gap_pct",
    "pre_auth_target_threshold",
    "queue_depth",
    "request_count",
    "slo_burn_rate",
]

UPDATE_ALERT_RULE_REQUEST_METRIC_VALUES: set[UpdateAlertRuleRequestMetric] = {
    "account_spend_eur",
    "api_up",
    "cert_expiry_seconds",
    "cert_issuance_failed",
    "cold_start_pct",
    "cold_wake_rate_pct",
    "daily_cost_cents",
    "deployment_failed",
    "error_rate_pct",
    "event_completion_latency_p95_seconds",
    "event_drain_rate_per_second",
    "event_execution_dead_letter_rate_per_second",
    "event_execution_dead_letters",
    "event_handler_failure_pct",
    "event_oldest_pending_seconds",
    "event_paused_seconds",
    "event_pending_recipients",
    "event_recovery_capacity_wait_jobs",
    "event_recovery_execution_prolonged_wait_jobs",
    "event_recovery_execution_retention_risk_jobs",
    "event_recovery_execution_unknown_jobs",
    "event_recovery_execution_waiting_jobs",
    "event_recovery_expiring_jobs",
    "event_recovery_stalled_jobs",
    "event_retention_expiring_receipts",
    "event_retry_rate_per_second",
    "event_routing_latency_p95_seconds",
    "event_storage_utilization_pct",
    "event_terminal_failure_pct",
    "failed_invocations",
    "latency_p50_ms",
    "latency_p95_ms",
    "latency_p99_ms",
    "new_error_fingerprint",
    "pre_auth_target_signal_gap_pct",
    "pre_auth_target_threshold",
    "queue_depth",
    "request_count",
    "slo_burn_rate",
}


def check_update_alert_rule_request_metric(value: str) -> UpdateAlertRuleRequestMetric:
    if value in UPDATE_ALERT_RULE_REQUEST_METRIC_VALUES:
        return value
    raise TypeError(f"Unexpected value {value!r}. Expected one of {UPDATE_ALERT_RULE_REQUEST_METRIC_VALUES!r}")
