from typing import Literal

UpdateAppWebhookRequestEventFilterItem = Literal[
    "app.health.changed",
    "app.parked",
    "app.woken",
    "automation.paused",
    "debug.regression.detected",
    "debug.regression.resolved",
    "deployment.failed",
    "deployment.live",
    "event_recovery.cancelled",
    "event_recovery.completed",
    "event_recovery.expired",
    "issue.assigned",
    "issue.created",
    "issue.ignored",
    "issue.impact_threshold_reached",
    "issue.regressed",
    "issue.reopened",
    "issue.resolved",
    "job.finished",
    "operation.effect",
    "operation.finished",
    "profile.route_recovered",
    "profile.route_regressed",
    "rollout.aborted",
    "rollout.completed",
    "routes.health.aborted",
    "routes.health.blocked",
    "routes.health.resumed",
    "routes.monitor.escalated",
    "routes.monitor.recovered",
    "routes.monitor.violated",
    "routes.requirements.changed",
    "routes.requirements.recovered",
    "routes.requirements.violated",
    "usage_statement.finalized",
    "workflow.finished",
]

UPDATE_APP_WEBHOOK_REQUEST_EVENT_FILTER_ITEM_VALUES: set[UpdateAppWebhookRequestEventFilterItem] = {
    "app.health.changed",
    "app.parked",
    "app.woken",
    "automation.paused",
    "debug.regression.detected",
    "debug.regression.resolved",
    "deployment.failed",
    "deployment.live",
    "event_recovery.cancelled",
    "event_recovery.completed",
    "event_recovery.expired",
    "issue.assigned",
    "issue.created",
    "issue.ignored",
    "issue.impact_threshold_reached",
    "issue.regressed",
    "issue.reopened",
    "issue.resolved",
    "job.finished",
    "operation.effect",
    "operation.finished",
    "profile.route_recovered",
    "profile.route_regressed",
    "rollout.aborted",
    "rollout.completed",
    "routes.health.aborted",
    "routes.health.blocked",
    "routes.health.resumed",
    "routes.monitor.escalated",
    "routes.monitor.recovered",
    "routes.monitor.violated",
    "routes.requirements.changed",
    "routes.requirements.recovered",
    "routes.requirements.violated",
    "usage_statement.finalized",
    "workflow.finished",
}


def check_update_app_webhook_request_event_filter_item(value: str) -> UpdateAppWebhookRequestEventFilterItem:
    if value in UPDATE_APP_WEBHOOK_REQUEST_EVENT_FILTER_ITEM_VALUES:
        return value
    raise TypeError(
        f"Unexpected value {value!r}. Expected one of {UPDATE_APP_WEBHOOK_REQUEST_EVENT_FILTER_ITEM_VALUES!r}"
    )
