// gatewayd egress producer service (ADR-046 PR-2). One streaming
// RPC: `StreamBytes` server-streaming from gatewayd to meterd.
// Each chunk is one (instance_id, minute, bytes) drained from the
// in-memory per-instance ring buffer
// (pkg/gateway/egresssink.EgressSink). The meterd side reads,
// keys on (instance_id, minute), folds into the egress aggregator
// (cmd/meterd/main.go:gatewayEgressAdapter), and the next sample
// tick appends to usage_minutes.tx_bytes.
//
// Why a separate proto rather than reusing pkg/gateway/vmmd's
// existing v1 surface:
//
//   wire-stable enum isolation (spec §14): touching the
//   existing vmmd/schedd packages to add an ADR-046-specific RPC
//   would have inflated their envelope, and a follow-up slice
//   that swaps an existing field's type would have required a
//   version bump across every consumer. Mirroring the existing
//   onebox.faas.{schedd,vmmd,githubd}.v1 convention
//   (api/proto/onebox/faas/<daemon>/v1/<svc>.proto) keeps the
//   egress surface additive and independently versionable.
//
// Why a single StreamBytes RPC rather than two (one for the
// current-minute tail, one for replay):
//
//   The drain shape — (instance_id, truncated_minute, bytes) —
//   is the same shape whether the row is current or historical.
//   Splitting into "current" vs "replay" would force meterd to
//   reconcile two streams on every reconnect; a single monotonic
//   stream (one chunk per drained bucket) lets the consumer
//   treat a re-subscribe as a fresh pull from minute 0. The
//   ring buffer's drain-eviction policy keeps the per-instance
//   window bounded at BucketsToKeep minutes (3) so a missed
//   reconnect never accumulates an unbounded backlog.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// source: onebox/faas/egress/v1/egress.proto

package egresspb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	EgressTxService_StreamBytes_FullMethodName = "/onebox.faas.egress.v1.EgressTxService/StreamBytes"
)

// EgressTxServiceClient is the client API for EgressTxService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// EgressTxService is the gRPC service gatewayd exposes for the
// egress-producer channel (ADR-046 PR-2). Served on the same
// unix socket as cmd/gatewayd/synth.go's SynthServer
// (FAAS_GATEWAY_SYNTH_SOCKET, default /run/faas/gatewayd-
// internal.sock); the unix-socket DAC auth (ADR-015) is the
// only authentication for v1 — only meterd is in the `faas`
// group, so the socket IS the auth. Multiple service definitions
// on a single *grpc.Server is the gRPC-native shape; the synth
// service stays co-resident, the egress service comes up
// alongside, and operators see one process on the box.
type EgressTxServiceClient interface {
	// StreamBytes (ADR-046 PR-2 producer channel) emits one
	// egress frame per drained (instance_id, minute) bucket.
	// The server pushes frames as fast as the underlying
	// EgressSink.DrainRecords produces them; the client (meterd)
	// reads at its own cadence (one minute-by-minute accumulation
	// per SampleAndRoll tick). Server-side backpressure is gRPC's
	// natural flow control — the gateway never blocks; the meterd
	// dialer pulls at its own rate. Empty stream = nothing to
	// drain this turn (the ring buffer has no observed bytes);
	// the client MUST tolerate empty returns. End-of-stream is
	// driven by ctx cancellation (server side) or by
	// deadline-exceeded (client side); there is no
	// "complete" marker because the drain is naturally lossy
	// (an instance that parks between two drains loses its
	// last-partial bucket, by design — see egressSink eviction
	// comment).
	StreamBytes(ctx context.Context, in *StreamBytesRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[BytesFrame], error)
}

type egressTxServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewEgressTxServiceClient(cc grpc.ClientConnInterface) EgressTxServiceClient {
	return &egressTxServiceClient{cc}
}

func (c *egressTxServiceClient) StreamBytes(ctx context.Context, in *StreamBytesRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[BytesFrame], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &EgressTxService_ServiceDesc.Streams[0], EgressTxService_StreamBytes_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamBytesRequest, BytesFrame]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type EgressTxService_StreamBytesClient = grpc.ServerStreamingClient[BytesFrame]

// EgressTxServiceServer is the server API for EgressTxService service.
// All implementations must embed UnimplementedEgressTxServiceServer
// for forward compatibility.
//
// EgressTxService is the gRPC service gatewayd exposes for the
// egress-producer channel (ADR-046 PR-2). Served on the same
// unix socket as cmd/gatewayd/synth.go's SynthServer
// (FAAS_GATEWAY_SYNTH_SOCKET, default /run/faas/gatewayd-
// internal.sock); the unix-socket DAC auth (ADR-015) is the
// only authentication for v1 — only meterd is in the `faas`
// group, so the socket IS the auth. Multiple service definitions
// on a single *grpc.Server is the gRPC-native shape; the synth
// service stays co-resident, the egress service comes up
// alongside, and operators see one process on the box.
type EgressTxServiceServer interface {
	// StreamBytes (ADR-046 PR-2 producer channel) emits one
	// egress frame per drained (instance_id, minute) bucket.
	// The server pushes frames as fast as the underlying
	// EgressSink.DrainRecords produces them; the client (meterd)
	// reads at its own cadence (one minute-by-minute accumulation
	// per SampleAndRoll tick). Server-side backpressure is gRPC's
	// natural flow control — the gateway never blocks; the meterd
	// dialer pulls at its own rate. Empty stream = nothing to
	// drain this turn (the ring buffer has no observed bytes);
	// the client MUST tolerate empty returns. End-of-stream is
	// driven by ctx cancellation (server side) or by
	// deadline-exceeded (client side); there is no
	// "complete" marker because the drain is naturally lossy
	// (an instance that parks between two drains loses its
	// last-partial bucket, by design — see egressSink eviction
	// comment).
	StreamBytes(*StreamBytesRequest, grpc.ServerStreamingServer[BytesFrame]) error
	mustEmbedUnimplementedEgressTxServiceServer()
}

// UnimplementedEgressTxServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedEgressTxServiceServer struct{}

func (UnimplementedEgressTxServiceServer) StreamBytes(*StreamBytesRequest, grpc.ServerStreamingServer[BytesFrame]) error {
	return status.Error(codes.Unimplemented, "method StreamBytes not implemented")
}
func (UnimplementedEgressTxServiceServer) mustEmbedUnimplementedEgressTxServiceServer() {}
func (UnimplementedEgressTxServiceServer) testEmbeddedByValue()                         {}

// UnsafeEgressTxServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EgressTxServiceServer will
// result in compilation errors.
type UnsafeEgressTxServiceServer interface {
	mustEmbedUnimplementedEgressTxServiceServer()
}

func RegisterEgressTxServiceServer(s grpc.ServiceRegistrar, srv EgressTxServiceServer) {
	// If the following call panics, it indicates UnimplementedEgressTxServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&EgressTxService_ServiceDesc, srv)
}

func _EgressTxService_StreamBytes_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamBytesRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(EgressTxServiceServer).StreamBytes(m, &grpc.GenericServerStream[StreamBytesRequest, BytesFrame]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type EgressTxService_StreamBytesServer = grpc.ServerStreamingServer[BytesFrame]

// EgressTxService_ServiceDesc is the grpc.ServiceDesc for EgressTxService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EgressTxService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "onebox.faas.egress.v1.EgressTxService",
	HandlerType: (*EgressTxServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamBytes",
			Handler:       _EgressTxService_StreamBytes_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "onebox/faas/egress/v1/egress.proto",
}
