package faas

import "github.com/poyrazK/faas/sdk/go/internal/api"

type PromoteProjectEnvironmentRequest = api.PromoteProjectEnvironmentRequest
type ProjectEnvironmentPromotionResponse = api.ProjectEnvironmentPromotionResponse
type ProjectEnvironmentPromotionWorkloadResponse = api.ProjectEnvironmentPromotionWorkloadResponse
type ProjectEnvironmentPromotionStatusResponse = api.ProjectEnvironmentPromotionStatusResponse
type ProjectEnvironmentPromotionStatusWorkloadResponse = api.ProjectEnvironmentPromotionStatusWorkloadResponse
type ProjectEnvironmentPromotionReleaseGraphResponse = api.ProjectEnvironmentPromotionReleaseGraphResponse
type ProjectEnvironmentPromotionPreviewResponse = api.ProjectEnvironmentPromotionPreviewResponse
type ProjectEnvironmentPromotionChange = api.ProjectEnvironmentPromotionChange
type ProjectEnvironmentConfigDiffResponse = api.ProjectEnvironmentConfigDiffResponse
type CreateProjectEnvironmentApprovalRequest = api.CreateProjectEnvironmentApprovalRequest
type ProjectEnvironmentApprovalResponse = api.ProjectEnvironmentApprovalResponse
