// Package realtime owns Gregale's managed realtime data plane.
//
// Managed realtime is deliberately separate from the gateway's raw Upgrade
// bridge. The raw bridge forwards bytes to an application-owned socket; this
// package terminates WebSocket connections at Gregale, keeps the connection
// registry in the process that owns the sockets, and exposes message delivery
// as ordinary callback events.
package realtime

import (
	"bytes"
	"context"
	"crypto/subtle"
	"encoding/base64"
	"encoding/json"
	"errors"
	"fmt"
	"net/http"
	"net/url"
	"sort"
	"strings"
	"sync"
	"sync/atomic"
	"time"

	"github.com/google/uuid"
	"github.com/gorilla/websocket"
	"github.com/onebox-faas/faas/pkg/api"
	"github.com/onebox-faas/faas/pkg/state"
)

const (
	// ManagedPathPrefix is the reserved ingress namespace for managed
	// realtime endpoints. gatewayd-internal routes this prefix before VM
	// admission, so an open managed connection never pins an application VM.
	ManagedPathPrefix = "/__gregale/realtime/"

	defaultMaxConnections     = 10_000
	defaultMaxMessageSize     = 1 << 20 // 1 MiB
	defaultOutboundQueue      = 64
	defaultOutboundQueueBytes = 4 << 20 // 4 MiB per connection, including an in-flight write
	defaultHeartbeat          = 30 * time.Second
	defaultPongWait           = 10 * time.Second
	defaultWriteWait          = 5 * time.Second
	defaultMaxAge             = 24 * time.Hour
	defaultCallbackWait       = 30 * time.Second

	maxChannelLength        = 256
	maxAllowedOrigins       = 16
	maxOriginBytes          = 2048
	maxEndpointConnections  = 10_000
	maxEndpointMessageBytes = 1 << 20
	maxEndpointAge          = 7 * 24 * time.Hour
)

var (
	ErrEndpointNotFound                 = errors.New("realtime: endpoint not found")
	ErrConnectionNotFound               = errors.New("realtime: connection not found")
	ErrTooManyConnections               = errors.New("realtime: connection limit reached")
	ErrOutboundQueueFull                = errors.New("realtime: outbound queue full")
	ErrConnectionClosed                 = errors.New("realtime: connection closed")
	ErrUnauthorized                     = errors.New("realtime: connection unauthorized")
	ErrInvalidChannel                   = errors.New("realtime: invalid channel")
	ErrInvalidPrincipal                 = errors.New("realtime: invalid principal")
	ErrInvalidDirectMessageID           = errors.New("realtime: invalid direct message ID")
	ErrDirectMessageReceiptsUnavailable = errors.New("realtime: direct message receipts unavailable")
	ErrCallbackNotPersisted             = errors.New("realtime: callback was not persisted")
)

const maxPendingDirectMessageReceipts = 256

// EventType is the callback event discriminator delivered to an application.
type EventType string

const (
	EventConnect    EventType = "realtime.connect"
	EventMessage    EventType = "realtime.message"
	EventDisconnect EventType = "realtime.disconnect"
	// EventAuthorizeChannel is a synchronous authorization request. It is
	// never queued in the durable callback outbox: a missed decision cannot
	// safely grant channel access later.
	EventAuthorizeChannel EventType = "realtime.authorize_channel"
)

// Message is a frame sent to a managed connection. Data is copied before it
// enters the bounded output queue, so callers may safely reuse their buffer.
type pendingSignalKey struct{ channel, member, name string }
type pendingSignal struct{ message Message }

type Message struct {
	signalKey     pendingSignalKey
	signalToken   *pendingSignal
	signalUpdated time.Time
	signalExpires *time.Time

	ExpectedSequence *int64            `json:"-"`
	Metadata         map[string]string `json:"metadata,omitempty"`
	Data             []byte
	Binary           bool
}

// PublishStatus describes recipient outcomes for one endpoint/channel publish.
// Queued is admission to in-memory output queues, not client receipt.
type PublishStatus struct {
	Subscribers int `json:"subscribers"`
	Queued      int `json:"queued"`
	QueueFull   int `json:"queue_full"`
	Failed      int `json:"failed"`
}

// PrincipalSendStatus reports per-connection queue outcomes for a direct
// message. Recipients includes v2 connections that have not negotiated the
// direct-message frame and are counted as Unsupported.
type PrincipalSendStatus struct {
	MessageID   string `json:"message_id"`
	Recipients  int    `json:"recipients"`
	Queued      int    `json:"queued"`
	Unsupported int    `json:"unsupported"`
	QueueFull   int    `json:"queue_full"`
	Failed      int    `json:"failed"`
}

// Event is the ordinary HTTP-handler payload generated by a managed
// connection. Data is copied before a hook is called and must be treated as
// immutable by hook implementations.
type Event struct {
	ActivityParentChannel string    `json:"activity_parent_channel,omitempty"`
	ActivityScope         string    `json:"activity_scope,omitempty"`
	ID                    string    `json:"id"`
	Type                  EventType `json:"type"`
	EndpointID            string    `json:"endpoint_id"`
	AppID                 string    `json:"app_id"`
	AccountID             string    `json:"account_id"`
	ConnectionID          string    `json:"connection_id"`
	Principal             string    `json:"principal,omitempty"`
	Channel               string    `json:"channel,omitempty"`
	Permission            string    `json:"permission,omitempty"`
	Sequence              uint64    `json:"sequence"`
	Binary                bool      `json:"binary"`
	Data                  []byte    `json:"data,omitempty"`
	CloseCode             int       `json:"close_code,omitempty"`
	CloseReason           string    `json:"close_reason,omitempty"`
	At                    time.Time `json:"at"`
	CallbackURL           string    `json:"-"`
	CallbackPath          string    `json:"callback_path,omitempty"`
	CallbackAuthToken     string    `json:"-"`
}

// Endpoint describes one managed realtime ingress. The endpoint ID is an
// opaque path component and must be unique within a realtime daemon.
type Endpoint struct {
	ID             string
	AppID          string
	AccountID      string
	CallbackURL    string
	ConnectPath    string
	MessagePath    string
	DisconnectPath string
	// CallbackAuthToken is an optional bearer credential sent only to the
	// configured callback handler. It is never serialized into an Event.
	CallbackAuthToken string
	// AuthToken is a narrow bootstrap credential for local development and
	// controlled single-node deployments. Production should use Authorize
	// backed by the app's configured auth provider; this token is never emitted
	// in events or registry snapshots.
	AuthToken string
	// AuthTokenPrevious is accepted only until AuthTokenPreviousExpiresAt. It
	// supports zero-downtime static bearer rotation and is never emitted in
	// events or registry snapshots.
	AuthTokenPrevious          string
	AuthTokenPreviousExpiresAt time.Time
	// ClientAuth is the explicit per-endpoint client authentication policy.
	// Empty mode preserves the legacy inference from AuthToken.
	ClientAuth AuthPolicy

	// Authorize runs before the WebSocket handshake. It should validate the
	// client credential and return a stable principal identifier. A nil
	// Authorize function permits the request; production wiring should normally
	// install an app-specific authorizer.
	Authorize func(context.Context, *http.Request) (principal string, err error)

	// CheckOrigin is optional. When nil, the manager accepts all origins and
	// leaves origin policy to Authorize. Browser-facing endpoints should set an
	// explicit allowlist.
	CheckOrigin func(*http.Request) bool

	// AllowedOrigins is an exact-match browser origin allowlist. Empty keeps
	// the legacy allow-all behavior for backwards compatibility; non-empty
	// values are normalized and enforced by the WebSocket upgrader.
	AllowedOrigins []string

	// Per-endpoint limits. Zero values inherit the daemon-wide Config limits.
	MaxConnections   int
	MaxMessageBytes  int64
	MaxConnectionAge time.Duration
}

// Hooks receives connection lifecycle events. Connect is synchronous with
// connection admission and may reject the connection. Message and Disconnect
// are called after the connection has been admitted; production hooks should
// persist events before delivery and keep callback work bounded.
type Hooks interface {
	Connect(context.Context, Event) (accept bool, err error)
	Message(context.Context, Event) error
	Disconnect(context.Context, Event) error
}

// ChannelAuthorizer is an optional, fail-closed extension used only by the
// versioned subscription protocol. Legacy management subscriptions keep their
// existing account-scoped authorization path.
type ChannelAuthorizer interface {
	AuthorizeChannel(context.Context, Event) (bool, error)
}

// NopHooks is a convenient default for embedding the data plane before the
// durable callback dispatcher is wired.
type NopHooks struct{}

func (NopHooks) Connect(context.Context, Event) (bool, error) { return true, nil }
func (NopHooks) Message(context.Context, Event) error         { return nil }
func (NopHooks) Disconnect(context.Context, Event) error      { return nil }

// Config contains bounded resource and lifecycle settings. Zero values use
// conservative defaults; all limits are enforced at the data-plane boundary.
type Config struct {
	MaxConnections  int
	MaxMessageBytes int64
	OutboundQueue   int // Maximum queued frames per connection.
	// Maximum outbound payload bytes per connection, including a frame being
	// written. Zero selects the conservative default.
	OutboundQueueBytes int64
	Heartbeat          time.Duration
	PongWait           time.Duration
	WriteWait          time.Duration
	MaxConnectionAge   time.Duration
	CallbackTimeout    time.Duration
	// JWTAuthorizer verifies endpoint policies using oidc_jwt. A nil authorizer
	// deliberately fails closed for JWT-configured endpoints.
	JWTAuthorizer JWTAuthorizer
	// ResumePreview admits the opt-in v2 protocol only when a private history
	// reader and synchronous channel authorizer are available.
	ResumePreview      bool
	HistoryReader      ManagedRealtimeHistoryReader
	ResumePollInterval time.Duration
	// ChannelRouteReporter updates the shared apid route directory promptly
	// when a resumable route appears or disappears. Snapshot reconciliation
	// repairs failed reports.
	ChannelRouteReporter      ManagedRealtimeChannelRouteReporter
	ChannelRouteReportFailure func(error)
	// FleetClient stores short-lived presence leases and relays transient v2
	// events through apid. A nil client keeps embedded managers process-local.
	FleetClient                ManagedRealtimeFleetClient
	PresenceSyncInterval       time.Duration
	PresenceLeaseRenewInterval time.Duration
	FleetReportFailure         func(error)
}

func (c Config) withDefaults() Config {
	if c.MaxConnections <= 0 {
		c.MaxConnections = defaultMaxConnections
	}
	if c.MaxMessageBytes <= 0 {
		c.MaxMessageBytes = defaultMaxMessageSize
	}
	if c.OutboundQueue <= 0 {
		c.OutboundQueue = defaultOutboundQueue
	}
	if c.OutboundQueueBytes <= 0 {
		c.OutboundQueueBytes = defaultOutboundQueueBytes
	}
	if c.Heartbeat <= 0 {
		c.Heartbeat = defaultHeartbeat
	}
	if c.PongWait <= 0 {
		c.PongWait = defaultPongWait
	}
	if c.WriteWait <= 0 {
		c.WriteWait = defaultWriteWait
	}
	if c.MaxConnectionAge <= 0 {
		c.MaxConnectionAge = defaultMaxAge
	}
	if c.CallbackTimeout <= 0 {
		c.CallbackTimeout = defaultCallbackWait
	}
	if c.ResumePollInterval <= 0 {
		c.ResumePollInterval = 5 * time.Second
	}
	if c.PresenceSyncInterval <= 0 {
		c.PresenceSyncInterval = 5 * time.Second
	}
	if c.PresenceLeaseRenewInterval <= 0 {
		c.PresenceLeaseRenewInterval = 15 * time.Second
	}
	return c
}

// ConnectionInfo is the safe, non-socket portion of a registry entry.
type ConnectionInfo struct {
	ID         string    `json:"id"`
	EndpointID string    `json:"endpoint_id"`
	AppID      string    `json:"app_id"`
	AccountID  string    `json:"account_id"`
	Principal  string    `json:"principal,omitempty"`
	Connected  time.Time `json:"connected_at"`
	LastSeen   time.Time `json:"last_seen_at"`
	Expires    time.Time `json:"expires_at"`
	Channels   []string  `json:"channels,omitempty"`
}

// ChannelRoute is one endpoint-scoped channel with at least one local legacy
// or resumable subscriber. It is the compact projection used to refresh fleet
// routing hints without copying every connection record.
type ChannelRoute struct {
	EndpointID string `json:"endpoint_id"`
	Channel    string `json:"channel"`
}

// ChannelRouteRevision identifies route-set changes in one realtime process's
// local subscriber indexes. A process instance change tells apid to refresh
// its full route snapshot after a realtime restart.
type ChannelRouteRevision struct {
	InstanceID string `json:"instance_id"`
	Revision   uint64 `json:"revision"`
}

// ConnectionInventory is a point-in-time fleet snapshot. NodesQueried counts
// nodes that returned a snapshot; NodesUnavailable records active nodes that
// could not be reached. A partial inventory is still useful to operators and
// must be surfaced to callers instead of being mistaken for an empty fleet.
type ConnectionInventory struct {
	Connections      []ConnectionInfo
	NodesQueried     int
	NodesUnavailable int
}

// EndpointInventory contains node-local registrations observed by the
// control plane. It contains IDs only; credentials never leave the node.
type EndpointInventory struct {
	IDs              []string
	NodesQueried     int
	NodesUnavailable int
}

// Stats is a point-in-time view of the bounded realtime data plane. Counters
// are process-local; operators should aggregate them across realtimed nodes.
type Stats struct {
	CurrentConnections                 uint64  `json:"current_connections"`
	CurrentResumeSubscriptions         uint64  `json:"current_resume_subscriptions"`
	AcceptedConnections                uint64  `json:"accepted_connections"`
	RejectedConnections                uint64  `json:"rejected_connections"`
	ReceivedMessages                   uint64  `json:"received_messages"`
	ReceivedBytes                      uint64  `json:"received_bytes"`
	SentMessages                       uint64  `json:"sent_messages"`
	SentBytes                          uint64  `json:"sent_bytes"`
	DroppedMessages                    uint64  `json:"dropped_messages"`
	OutboundPendingBytes               uint64  `json:"outbound_pending_bytes"`
	OutboundQueueBytesLimit            uint64  `json:"outbound_queue_bytes_limit"`
	OutboundQueueCountDrops            uint64  `json:"outbound_queue_count_drops"`
	OutboundQueueByteDrops             uint64  `json:"outbound_queue_byte_drops"`
	CallbackErrors                     uint64  `json:"callback_errors"`
	CallbackOutboxFull                 uint64  `json:"callback_outbox_full"`
	CallbackOutboxAdmissionErrors      uint64  `json:"callback_outbox_admission_errors"`
	CallbackUnpersistedFailures        uint64  `json:"callback_unpersisted_failures"`
	CallbackPending                    uint64  `json:"callback_pending"`
	CallbackPendingBytes               uint64  `json:"callback_pending_bytes"`
	CallbackPendingCapacityBytes       uint64  `json:"callback_pending_capacity_bytes"`
	CallbackReplayReady                uint64  `json:"callback_replay_ready"`
	CallbackReplayDelayed              uint64  `json:"callback_replay_delayed"`
	CallbackReplayAttempts             uint64  `json:"callback_replay_attempts"`
	CallbackReplayDeliveries           uint64  `json:"callback_replay_deliveries"`
	CallbackOldestPendingAgeSeconds    float64 `json:"callback_oldest_pending_age_seconds"`
	CallbackDeadLetters                uint64  `json:"callback_dead_letters"`
	CallbackDeadLetterBytes            uint64  `json:"callback_dead_letter_bytes"`
	CallbackDeadLetterCapacityBytes    uint64  `json:"callback_dead_letter_capacity_bytes"`
	CallbackDeadLetterEvictions        uint64  `json:"callback_dead_letter_evictions"`
	CallbackDeadLetterLastEvictionUnix int64   `json:"callback_dead_letter_last_eviction_unix"`
	CallbackDeadLetterDiscards         uint64  `json:"callback_dead_letter_discards"`
}

type connection struct {
	info ConnectionInfo
	// presenceID is a per-connection candidate member ID. Principal-scoped
	// subscriptions may receive a shared opaque member ID from the lease store.
	presenceID string
	// endpoint is retained so lifecycle callbacks can finish after revocation.
	endpoint     Endpoint
	state        *endpointState
	callbackAuth atomic.Pointer[callbackAuthSnapshot]
	ws           *websocket.Conn
	m            *Manager

	outbound       chan Message
	outboundMu     sync.Mutex
	outboundBytes  int64
	outboundClosed bool
	pendingSignals map[pendingSignalKey]*pendingSignal
	done           chan struct{}
	closeOne       sync.Once

	sequence                atomic.Uint64
	mu                      sync.RWMutex
	channels                map[string]struct{}
	closeCode               int
	closeReason             string
	v2                      bool
	directMessages          bool
	pendingDirectMessages   map[string]time.Time
	recentDirectMessageAcks map[string]time.Time
	resumeSubs              map[string]*resumeSubscription
	inboxSub                *inboxSubscription
	readReceipts            bool
	readWindow              time.Time
	readCount               int
	signalWindow            time.Time
	signalCount             int
	presenceWindow          time.Time
	presenceCount           int
}

type callbackAuthSnapshot struct {
	token string
}

type channelKey struct {
	endpointID string
	channel    string
}

type endpointState struct {
	config atomic.Pointer[Endpoint]
	gate   sync.Mutex
	// reserved is shared across policy refreshes so live connections continue
	// to release against the count used during admission.
	reserved *atomic.Int64
	revoked  atomic.Bool
}

// Manager is the owner of managed realtime sockets for one process/node.
// The registry is intentionally process-local; connections cannot be moved
// between nodes. The Snapshot method is suitable for publishing a leased
// directory view to the control plane.
type Manager struct {
	cfg   Config
	hooks Hooks

	ctx    context.Context
	cancel context.CancelFunc

	endpoints   sync.Map // map[string]*endpointState
	endpointsMu sync.Mutex
	// mu protects connection indexes, subscribers, and route revision.
	// Subscription changes also take connection.mu after mu so snapshots see
	// consistent channel membership.
	mu                      sync.RWMutex
	conns                   map[string]*connection
	endpointConns           map[string]map[string]*connection
	subscribers             map[channelKey]map[string]struct{}
	resumeSubscribers       map[channelKey]map[string]struct{}
	presenceMembers         map[channelKey]map[string]*presenceMember
	fleetPresence           map[channelKey]map[string]PresenceMember
	fleetPresenceTombstones map[channelKey]map[string]time.Time
	fleetPresenceLastSync   map[channelKey]time.Time
	resumeSignalRates       map[channelKey]*resumeSignalRate
	routeReportMu           sync.Mutex
	channelRouteInstance    string
	channelRouteRevision    uint64
	reserved                atomic.Int64
	resumeCount             atomic.Int64
	resumeMetrics           *resumeMetrics
	closed                  atomic.Bool

	upgrader websocket.Upgrader

	acceptedConnections           atomic.Uint64
	rejectedConnections           atomic.Uint64
	receivedMessages              atomic.Uint64
	receivedBytes                 atomic.Uint64
	sentMessages                  atomic.Uint64
	sentBytes                     atomic.Uint64
	droppedMessages               atomic.Uint64
	outboundPendingBytes          atomic.Int64
	outboundQueueCountDrops       atomic.Uint64
	outboundQueueByteDrops        atomic.Uint64
	callbackErrors                atomic.Uint64
	callbackOutboxFull            atomic.Uint64
	callbackOutboxAdmissionErrors atomic.Uint64
	callbackUnpersistedFailures   atomic.Uint64
	authOutcomes                  authOutcomeCounters
}

// NewManager creates a managed realtime owner. Call Close during daemon
// shutdown to close all sockets and stop callback contexts.
func NewManager(cfg Config, hooks Hooks) *Manager {
	cfg = cfg.withDefaults()
	if hooks == nil {
		hooks = NopHooks{}
	}
	ctx, cancel := context.WithCancel(context.Background())
	return &Manager{
		cfg:                     cfg,
		hooks:                   hooks,
		ctx:                     ctx,
		cancel:                  cancel,
		conns:                   make(map[string]*connection),
		endpointConns:           make(map[string]map[string]*connection),
		subscribers:             make(map[channelKey]map[string]struct{}),
		resumeSubscribers:       make(map[channelKey]map[string]struct{}),
		presenceMembers:         make(map[channelKey]map[string]*presenceMember),
		fleetPresence:           make(map[channelKey]map[string]PresenceMember),
		fleetPresenceTombstones: make(map[channelKey]map[string]time.Time),
		fleetPresenceLastSync:   make(map[channelKey]time.Time),
		resumeSignalRates:       make(map[channelKey]*resumeSignalRate),
		channelRouteInstance:    uuid.NewString(),
		resumeMetrics:           newResumeMetrics(),
		upgrader: websocket.Upgrader{
			ReadBufferSize:  4096,
			WriteBufferSize: 4096,
			CheckOrigin:     func(*http.Request) bool { return true },
		},
	}
}

// RegisterEndpoint publishes an endpoint to the local ingress route.
func (m *Manager) RegisterEndpoint(e Endpoint) error {
	if m == nil || m.closed.Load() {
		return ErrConnectionClosed
	}
	if strings.TrimSpace(e.ID) != e.ID || e.ID == "" || e.ID == "." || e.ID == ".." || strings.ContainsAny(e.ID, "/?#") {
		return fmt.Errorf("realtime: invalid endpoint id %q", e.ID)
	}
	auth, err := normalizeAuthPolicy(e.ClientAuth, e.AuthToken != "")
	if err != nil {
		return err
	}
	if e.AuthTokenPrevious != "" {
		if auth.Mode != AuthModeStaticBearer {
			return fmt.Errorf("realtime: previous auth token requires static_bearer mode")
		}
		if e.AuthTokenPreviousExpiresAt.IsZero() {
			return fmt.Errorf("realtime: previous auth token requires an expiry")
		}
	}
	e.ClientAuth = auth
	for name, path := range map[string]string{
		"connect_path":    e.ConnectPath,
		"message_path":    e.MessagePath,
		"disconnect_path": e.DisconnectPath,
	} {
		if path == "" {
			continue
		}
		if strings.ContainsAny(path, "?#\r\n") {
			return fmt.Errorf("realtime: invalid %s %q", name, path)
		}
		for _, segment := range strings.Split(path, "/") {
			if segment == "." || segment == ".." {
				return fmt.Errorf("realtime: invalid %s %q", name, path)
			}
		}
	}
	if len(e.AllowedOrigins) > maxAllowedOrigins {
		return fmt.Errorf("realtime: too many allowed origins")
	}
	allowedOrigins := make([]string, 0, len(e.AllowedOrigins))
	for _, raw := range e.AllowedOrigins {
		if len(raw) == 0 || len(raw) > maxOriginBytes || strings.TrimSpace(raw) != raw {
			return fmt.Errorf("realtime: invalid allowed origin %q", raw)
		}
		normalized, err := normalizeOrigin(raw)
		if err != nil {
			return fmt.Errorf("realtime: invalid allowed origin %q: %w", raw, err)
		}
		for _, existing := range allowedOrigins {
			if existing == normalized {
				return fmt.Errorf("realtime: duplicate allowed origin %q", raw)
			}
		}
		allowedOrigins = append(allowedOrigins, normalized)
	}
	e.AllowedOrigins = allowedOrigins
	if e.MaxConnections <= 0 || e.MaxConnections > m.cfg.MaxConnections {
		e.MaxConnections = m.cfg.MaxConnections
	}
	if e.MaxMessageBytes <= 0 || e.MaxMessageBytes > m.cfg.MaxMessageBytes {
		e.MaxMessageBytes = m.cfg.MaxMessageBytes
	}
	if e.MaxConnectionAge <= 0 || e.MaxConnectionAge > m.cfg.MaxConnectionAge {
		e.MaxConnectionAge = m.cfg.MaxConnectionAge
	}
	if e.MaxConnections > maxEndpointConnections {
		e.MaxConnections = maxEndpointConnections
	}
	if e.MaxMessageBytes > maxEndpointMessageBytes {
		e.MaxMessageBytes = maxEndpointMessageBytes
	}
	if e.MaxConnectionAge > maxEndpointAge {
		e.MaxConnectionAge = maxEndpointAge
	}
	if e.CheckOrigin == nil && len(e.AllowedOrigins) > 0 {
		e.CheckOrigin = checkAllowedOrigins(e.AllowedOrigins)
	}
	m.endpointsMu.Lock()
	defer m.endpointsMu.Unlock()
	updater, canUpdateCallbacks := m.hooks.(interface {
		updateCallbackAuthToken(string, string) error
	})
	if existing, ok := m.endpoints.Load(e.ID); ok {
		// Reconciliation updates the immutable policy snapshot without
		// resetting the count held by connections admitted under an older one.
		state := existing.(*endpointState)
		state.gate.Lock()
		defer state.gate.Unlock()
		if canUpdateCallbacks {
			if err := updater.updateCallbackAuthToken(e.ID, e.CallbackAuthToken); err != nil {
				return err
			}
		}
		previous := state.config.Load()
		state.config.Store(&e)
		if previous == nil || previous.CallbackAuthToken != e.CallbackAuthToken {
			m.mu.RLock()
			for _, conn := range m.conns {
				if conn.state == state {
					conn.callbackAuth.Store(&callbackAuthSnapshot{token: e.CallbackAuthToken})
				}
			}
			m.mu.RUnlock()
		}
		return nil
	}
	if canUpdateCallbacks {
		if err := updater.updateCallbackAuthToken(e.ID, e.CallbackAuthToken); err != nil {
			return err
		}
	}
	state := &endpointState{reserved: new(atomic.Int64)}
	state.config.Store(&e)
	m.endpoints.Store(e.ID, state)
	return nil
}

// RemoveEndpoint revokes admission and closes existing sockets. A deletion or
// disable is a security boundary, including for clients already connected.
func (m *Manager) RemoveEndpoint(id string) {
	if m == nil {
		return
	}
	m.endpointsMu.Lock()
	value, ok := m.endpoints.Load(id)
	if ok {
		state := value.(*endpointState)
		state.gate.Lock()
		state.revoked.Store(true)
		m.endpoints.Delete(id)
		state.gate.Unlock()
	}
	m.endpointsMu.Unlock()
	if updater, ok := m.hooks.(interface{ removeCallbackAuthToken(string) }); ok {
		updater.removeCallbackAuthToken(id)
	}
	m.mu.RLock()
	connections := make([]*connection, 0)
	for _, c := range m.conns {
		if ok && c.state == value.(*endpointState) {
			connections = append(connections, c)
		}
	}
	m.mu.RUnlock()
	for _, c := range connections {
		// Revocation must not wait for a slow client's control-frame write.
		// Closing the transport unblocks the read pump and persists its
		// disconnect callback through the normal lifecycle path.
		c.terminate(websocket.ClosePolicyViolation, "endpoint removed")
	}
}

// EndpointIDs returns the node-local registration inventory without exposing
// credentials or policy. The control plane compares it to durable intent.
func (m *Manager) EndpointIDs() []string {
	if m == nil {
		return nil
	}
	ids := make([]string, 0)
	m.endpoints.Range(func(key, _ any) bool {
		ids = append(ids, key.(string))
		return true
	})
	sort.Strings(ids)
	return ids
}

// Handler returns the HTTP handler mounted at ManagedPathPrefix.
func (m *Manager) Handler() http.Handler { return m }

// ServeHTTP upgrades /__gregale/realtime/{endpoint_id} and owns the resulting
// WebSocket until the client, endpoint, or manager closes it.
func (m *Manager) ServeHTTP(w http.ResponseWriter, r *http.Request) {
	if m == nil || m.closed.Load() {
		http.Error(w, "realtime service unavailable", http.StatusServiceUnavailable)
		return
	}
	if r.Method != http.MethodGet {
		http.Error(w, "method not allowed", http.StatusMethodNotAllowed)
		return
	}
	endpointID, ok := endpointIDFromPath(r.URL.Path)
	if !ok {
		http.NotFound(w, r)
		return
	}
	value, ok := m.endpoints.Load(endpointID)
	if !ok {
		m.rejectedConnections.Add(1)
		http.NotFound(w, r)
		return
	}
	state := value.(*endpointState)
	endpoint := *state.config.Load()
	protocols := websocket.Subprotocols(r)
	wantsResume := false
	for _, protocol := range protocols {
		if protocol == ResumeSubprotocol {
			wantsResume = true
			break
		}
	}
	browserToken, browserCredential, invalidCredential, remainingProtocols := resumeBearerFromProtocols(protocols)
	if browserCredential {
		// Browser credentials require an explicit endpoint origin policy. The
		// normal WebSocket origin default allows non-browser clients without an
		// Origin header, so it is insufficient for this credential carrier.
		if !wantsResume || invalidCredential || len(r.Header.Values("Authorization")) != 0 {
			m.recordAuthOutcome(authMetricModeForEndpoint(endpoint), authMetricOutcomeRejected)
			m.rejectedConnections.Add(1)
			http.Error(w, "invalid realtime browser authentication", http.StatusBadRequest)
			return
		}
		if len(endpoint.AllowedOrigins) == 0 || r.Header.Get("Origin") == "" || !checkAllowedOrigins(endpoint.AllowedOrigins)(r) {
			m.recordAuthOutcome(authMetricModeForEndpoint(endpoint), authMetricOutcomeRejected)
			m.rejectedConnections.Add(1)
			http.Error(w, "realtime browser origin forbidden", http.StatusForbidden)
			return
		}
		// Neither a custom authorization hook nor the upgrader should see or
		// return the credential-bearing subprotocol.
		r.Header.Del("Sec-WebSocket-Protocol")
		if len(remainingProtocols) > 0 {
			r.Header.Set("Sec-WebSocket-Protocol", strings.Join(remainingProtocols, ", "))
		}
	}
	if wantsResume {
		if !m.cfg.ResumePreview || m.cfg.HistoryReader == nil {
			http.Error(w, "realtime resume unavailable", http.StatusServiceUnavailable)
			return
		}
		if endpoint.ClientAuth.Mode != AuthModeOIDCJWT {
			http.Error(w, "realtime resume requires OIDC authentication", http.StatusForbidden)
			return
		}
		if _, ok := m.hooks.(ChannelAuthorizer); !ok {
			http.Error(w, "realtime channel authorization unavailable", http.StatusServiceUnavailable)
			return
		}
	}
	authMetricMode := authMetricModeForEndpoint(endpoint)
	principal := ""
	switch endpoint.ClientAuth.Mode {
	case AuthModeStaticBearer:
		token, ok := bearerToken(r)
		valid := ok && subtle.ConstantTimeCompare([]byte(token), []byte(endpoint.AuthToken)) == 1
		if !valid && ok && endpoint.AuthTokenPrevious != "" &&
			(endpoint.AuthTokenPreviousExpiresAt.IsZero() || time.Now().Before(endpoint.AuthTokenPreviousExpiresAt)) {
			valid = subtle.ConstantTimeCompare([]byte(token), []byte(endpoint.AuthTokenPrevious)) == 1
		}
		if !valid {
			m.recordAuthOutcome(authMetricMode, authMetricOutcomeRejected)
			m.rejectedConnections.Add(1)
			http.Error(w, "unauthorized", http.StatusUnauthorized)
			return
		}
		principal = "token"
	case AuthModeOIDCJWT:
		token, ok := bearerToken(r)
		if browserCredential {
			token, ok = browserToken, true
		}
		if !ok || m.cfg.JWTAuthorizer == nil {
			m.recordAuthOutcome(authMetricMode, authMetricOutcomeRejected)
			m.rejectedConnections.Add(1)
			http.Error(w, "unauthorized", http.StatusUnauthorized)
			return
		}
		var err error
		principal, err = m.cfg.JWTAuthorizer.Authorize(r.Context(), token, endpoint.ClientAuth)
		if err != nil || strings.TrimSpace(principal) == "" {
			m.recordAuthOutcome(authMetricMode, authMetricOutcomeRejected)
			m.rejectedConnections.Add(1)
			http.Error(w, "unauthorized", http.StatusUnauthorized)
			return
		}
	}
	if endpoint.Authorize != nil {
		var err error
		principal, err = endpoint.Authorize(r.Context(), r)
		if err != nil {
			m.recordAuthOutcome(authMetricMode, authMetricOutcomeRejected)
			m.rejectedConnections.Add(1)
			http.Error(w, "unauthorized", http.StatusUnauthorized)
			return
		}
	}
	if wantsResume && strings.TrimSpace(principal) == "" {
		m.recordAuthOutcome(authMetricMode, authMetricOutcomeRejected)
		m.rejectedConnections.Add(1)
		http.Error(w, "realtime resume requires a stable principal", http.StatusUnauthorized)
		return
	}
	m.recordAuthOutcome(authMetricMode, authMetricOutcomeAccepted)
	upgrader := m.upgrader
	if wantsResume {
		upgrader.Subprotocols = []string{ResumeSubprotocol}
	}
	if endpoint.CheckOrigin != nil {
		upgrader.CheckOrigin = endpoint.CheckOrigin
	}
	if !m.tryReserve(state) {
		m.rejectedConnections.Add(1)
		http.Error(w, "realtime connection limit reached", http.StatusTooManyRequests)
		return
	}
	defer m.release(state)

	ws, err := upgrader.Upgrade(w, r, nil)
	if err != nil {
		m.rejectedConnections.Add(1)
		return
	}
	state.gate.Lock()
	if state.revoked.Load() {
		state.gate.Unlock()
		_ = ws.WriteControl(websocket.CloseMessage, websocket.FormatCloseMessage(websocket.ClosePolicyViolation, "endpoint removed"), time.Now().Add(m.cfg.WriteWait))
		_ = ws.Close()
		return
	}
	conn := m.addConnectionWithProtocol(state, endpoint, principal, ws, wantsResume)
	state.gate.Unlock()
	m.runConnection(r.Context(), conn)
}

func (m *Manager) tryReserve(state *endpointState) bool {
	if state.revoked.Load() {
		return false
	}
	for {
		current := m.reserved.Load()
		if current >= int64(m.cfg.MaxConnections) {
			return false
		}
		if m.reserved.CompareAndSwap(current, current+1) {
			for {
				endpointCurrent := state.reserved.Load()
				if state.revoked.Load() || endpointCurrent >= int64(state.config.Load().MaxConnections) {
					m.reserved.Add(-1)
					return false
				}
				if state.reserved.CompareAndSwap(endpointCurrent, endpointCurrent+1) {
					return true
				}
			}
		}
	}
}

func (m *Manager) release(state *endpointState) {
	m.reserved.Add(-1)
	state.reserved.Add(-1)
}

func normalizeOrigin(raw string) (string, error) {
	u, err := url.Parse(raw)
	if err != nil || u.Host == "" || (u.Scheme != "http" && u.Scheme != "https") || u.User != nil || (u.Path != "" && u.Path != "/") || u.RawQuery != "" || u.Fragment != "" {
		return "", errors.New("origin must be an absolute http(s) origin without paths or credentials")
	}
	return strings.ToLower(u.Scheme) + "://" + strings.ToLower(u.Host), nil
}

func checkAllowedOrigins(allowed []string) func(*http.Request) bool {
	return func(r *http.Request) bool {
		origin := r.Header.Get("Origin")
		if origin == "" {
			return true
		}
		normalized, err := normalizeOrigin(origin)
		if err != nil {
			return false
		}
		for _, candidate := range allowed {
			if candidate == normalized {
				return true
			}
		}
		return false
	}
}

func endpointIDFromPath(path string) (string, bool) {
	if !strings.HasPrefix(path, ManagedPathPrefix) {
		return "", false
	}
	rest := strings.TrimPrefix(path, ManagedPathPrefix)
	if rest == "" || strings.Contains(rest, "/") {
		return "", false
	}
	return rest, true
}

func (m *Manager) addConnection(state *endpointState, endpoint Endpoint, principal string, ws *websocket.Conn) *connection {
	return m.addConnectionWithProtocol(state, endpoint, principal, ws, false)
}

func (m *Manager) addConnectionWithProtocol(state *endpointState, endpoint Endpoint, principal string, ws *websocket.Conn, v2 bool) *connection {
	now := time.Now().UTC()
	id := "rt_" + strings.ReplaceAll(uuid.NewString(), "-", "")
	conn := &connection{
		info: ConnectionInfo{
			ID:         id,
			EndpointID: endpoint.ID,
			AppID:      endpoint.AppID,
			AccountID:  endpoint.AccountID,
			Principal:  principal,
			Connected:  now,
			LastSeen:   now,
			Expires:    now.Add(endpoint.MaxConnectionAge),
		},
		presenceID:              uuid.NewString(),
		ws:                      ws,
		v2:                      v2,
		endpoint:                endpoint,
		state:                   state,
		m:                       m,
		outbound:                make(chan Message, m.cfg.OutboundQueue),
		done:                    make(chan struct{}),
		channels:                make(map[string]struct{}),
		pendingDirectMessages:   make(map[string]time.Time),
		recentDirectMessageAcks: make(map[string]time.Time),
		resumeSubs:              make(map[string]*resumeSubscription),
	}
	if current := state.config.Load(); current != nil {
		conn.callbackAuth.Store(&callbackAuthSnapshot{token: current.CallbackAuthToken})
	}
	m.mu.Lock()
	m.conns[id] = conn
	m.mu.Unlock()
	m.acceptedConnections.Add(1)
	return conn
}

func (m *Manager) runConnection(ctx context.Context, c *connection) {
	defer m.removeConnection(ctx, c)

	go c.writePump()

	connect := Event{
		ID:           "evt_" + strings.ReplaceAll(uuid.NewString(), "-", ""),
		Type:         EventConnect,
		EndpointID:   c.info.EndpointID,
		AppID:        c.info.AppID,
		AccountID:    c.info.AccountID,
		ConnectionID: c.info.ID,
		Principal:    c.info.Principal,
		At:           time.Now().UTC(),
	}
	connect.CallbackURL = c.endpoint.CallbackURL
	connect.CallbackPath = c.endpoint.ConnectPath
	connect.CallbackAuthToken = c.currentCallbackAuthToken()
	accepted, err := m.callConnect(ctx, connect)
	if err != nil {
		m.callbackErrors.Add(1)
	}
	if err != nil || !accepted {
		m.rejectedConnections.Add(1)
		_ = c.close(websocket.ClosePolicyViolation, "connection rejected")
		return
	}

	c.ws.SetReadLimit(c.endpoint.MaxMessageBytes)
	if c.v2 {
		c.ws.SetReadLimit(api.RealtimeResumeClientFrameMaxBytes)
	}
	// Give the client until the first heartbeat plus a pong window. Setting
	// only PongWait here would close an otherwise healthy idle socket before
	// the first ping when Heartbeat is larger than PongWait (the defaults are
	// 30s and 10s respectively).
	_ = c.ws.SetReadDeadline(time.Now().Add(m.cfg.Heartbeat + m.cfg.PongWait))
	c.ws.SetPongHandler(func(string) error {
		// The next ping arrives after Heartbeat; PongWait alone would
		// disconnect a healthy idle client between heartbeats.
		return c.ws.SetReadDeadline(time.Now().Add(m.cfg.Heartbeat + m.cfg.PongWait))
	})
	if c.v2 {
		m.runResumeConnection(ctx, c)
		return
	}

	for {
		kind, data, err := c.ws.ReadMessage()
		if err != nil {
			var closeErr *websocket.CloseError
			if errors.As(err, &closeErr) {
				c.recordClose(closeErr.Code, closeErr.Text)
			}
			return
		}
		lastSeen := time.Now().UTC()
		c.mu.Lock()
		c.info.LastSeen = lastSeen
		c.mu.Unlock()
		event := Event{
			ID:           "evt_" + strings.ReplaceAll(uuid.NewString(), "-", ""),
			Type:         EventMessage,
			EndpointID:   c.info.EndpointID,
			AppID:        c.info.AppID,
			AccountID:    c.info.AccountID,
			ConnectionID: c.info.ID,
			Principal:    c.info.Principal,
			Sequence:     c.sequence.Add(1),
			Binary:       kind == websocket.BinaryMessage,
			Data:         append([]byte(nil), data...),
			At:           lastSeen,
		}
		event.CallbackURL = c.endpoint.CallbackURL
		event.CallbackPath = c.endpoint.MessagePath
		event.CallbackAuthToken = c.currentCallbackAuthToken()
		m.receivedMessages.Add(1)
		m.receivedBytes.Add(uint64(len(data)))
		callbackCtx, cancel := context.WithTimeout(ctx, m.cfg.CallbackTimeout)
		callbackErr := m.hooks.Message(callbackCtx, event)
		cancel()
		if callbackErr != nil {
			m.callbackErrors.Add(1)
			if errors.Is(callbackErr, ErrCallbackNotPersisted) {
				if errors.Is(callbackErr, ErrCallbackOutboxFull) {
					m.callbackOutboxFull.Add(1)
					_ = c.close(websocket.CloseTryAgainLater, "callback capacity reached")
				} else if errors.Is(callbackErr, ErrCallbackOutboxAdmission) {
					m.callbackOutboxAdmissionErrors.Add(1)
					_ = c.close(websocket.CloseTryAgainLater, "callback could not be persisted")
				} else {
					m.callbackUnpersistedFailures.Add(1)
					_ = c.close(websocket.CloseTryAgainLater, "callback delivery unavailable")
				}
				return
			}
		}
	}
}

func (m *Manager) callConnect(ctx context.Context, event Event) (bool, error) {
	ctx, cancel := context.WithTimeout(ctx, m.cfg.CallbackTimeout)
	defer cancel()
	return m.hooks.Connect(ctx, event)
}

func (c *connection) writePump() {
	heartbeat := time.NewTicker(c.m.cfg.Heartbeat)
	defer heartbeat.Stop()
	age := time.NewTimer(time.Until(c.info.Expires))
	defer age.Stop()
	for {
		select {
		case msg := <-c.outbound:
			c.outboundMu.Lock()
			msg = c.resolvePendingSignalLocked(msg)
			c.outboundMu.Unlock()
			if msg.signalExpires != nil && msg.signalExpires.After(msg.signalUpdated) && !msg.signalExpires.After(time.Now()) {
				c.releaseOutboundBytes(int64(len(msg.Data)))
				continue
			}
			err := c.write(msg)
			c.releaseOutboundBytes(int64(len(msg.Data)))
			if err != nil {
				_ = c.close(websocket.CloseGoingAway, "write failed")
				return
			}
		case <-heartbeat.C:
			if err := c.ws.WriteControl(websocket.PingMessage, []byte("gregale"), time.Now().Add(c.m.cfg.WriteWait)); err != nil {
				_ = c.close(websocket.CloseGoingAway, "heartbeat failed")
				return
			}
		case <-age.C:
			_ = c.close(websocket.ClosePolicyViolation, "connection lifetime exceeded")
			return
		case <-c.done:
			return
		case <-c.m.ctx.Done():
			return
		}
	}
}

func (c *connection) write(msg Message) error {
	deadline := time.Now().Add(c.m.cfg.WriteWait)
	if err := c.ws.SetWriteDeadline(deadline); err != nil {
		return err
	}
	kind := websocket.TextMessage
	if msg.Binary {
		kind = websocket.BinaryMessage
	}
	return c.ws.WriteMessage(kind, msg.Data)
}

func (m *Manager) removeConnection(ctx context.Context, c *connection) {
	type removedPresenceLease struct {
		channel  string
		memberID string
	}
	var removedResumeRoutes []channelKey
	var removedPresence []removedPresenceLease
	var fullPresenceQueues []*connection
	c.state.gate.Lock()
	m.mu.Lock()
	if current, ok := m.conns[c.info.ID]; ok && current == c {
		c.mu.Lock()
		if c.inboxSub != nil {
			c.inboxSub.cancel()
			c.inboxSub = nil
		}
		for channel, subscription := range c.resumeSubs {
			subscription.cancel()
			key := channelKey{endpointID: c.info.EndpointID, channel: channel}
			member := m.presenceMembers[key][c.info.ID]
			if member != nil {
				removed := removedPresenceLease{channel: channel}
				if member.announced {
					removed.memberID = member.memberID
				}
				removedPresence = append(removedPresence, removed)
				if m.cfg.FleetClient == nil {
					leftAt := time.Now().UTC()
					delete(m.fleetPresence[key], member.memberID)
					m.recordFleetPresenceTombstoneLocked(key, member.memberID, leftAt)
				}
				delete(m.presenceMembers[key], c.info.ID)
				if len(m.presenceMembers[key]) == 0 {
					delete(m.presenceMembers, key)
				}
			}
			hadSubscribers := m.hasChannelSubscribersLocked(key)
			members := m.resumeSubscribers[key]
			if _, subscribed := members[c.info.ID]; subscribed {
				delete(members, c.info.ID)
				if len(members) == 0 {
					delete(m.resumeSubscribers, key)
					delete(m.resumeSignalRates, key)
					delete(m.fleetPresence, key)
					delete(m.fleetPresenceTombstones, key)
					delete(m.fleetPresenceLastSync, key)
				}
				if hadSubscribers && !m.hasChannelSubscribersLocked(key) {
					m.channelRouteRevision++
					removedResumeRoutes = append(removedResumeRoutes, key)
					delete(m.resumeSignalRates, key)
				}
			}
			if member != nil && member.announced && m.cfg.FleetClient == nil {
				fullPresenceQueues = append(fullPresenceQueues, m.queueEphemeralToSubscribersLocked(ctx, key, c.info.ID,
					resumeServerFrame{Type: "presence", Channel: channel, Event: "left", MemberID: member.memberID, UpdatedAt: time.Now().UTC()})...)
			}
		}
		for channel := range c.channels {
			key := channelKey{endpointID: c.info.EndpointID, channel: channel}
			hadSubscribers := m.hasChannelSubscribersLocked(key)
			members := m.subscribers[key]
			if _, subscribed := members[c.info.ID]; subscribed {
				delete(members, c.info.ID)
				if len(members) == 0 {
					delete(m.subscribers, key)
				}
				if hadSubscribers && !m.hasChannelSubscribersLocked(key) {
					m.channelRouteRevision++
				}
			}
		}
		c.mu.Unlock()
		delete(m.conns, c.info.ID)
	}
	callbackAuthToken := c.currentCallbackAuthToken()
	m.mu.Unlock()
	c.state.gate.Unlock()
	for _, slow := range fullPresenceQueues {
		m.closeResumeOnQueueFull(slow, ErrOutboundQueueFull)
	}
	for _, key := range removedResumeRoutes {
		m.reportChannelRoute(ctx, key, false)
	}
	for _, removed := range removedPresence {
		m.deleteFleetPresence(ctx, c, removed.channel, removed.memberID)
	}
	c.closeOne.Do(func() {
		c.closeOutboundQueue()
		_ = c.ws.Close()
	})
	c.mu.RLock()
	closeCode, closeReason := c.closeCode, c.closeReason
	c.mu.RUnlock()
	disconnect := Event{
		ID:           "evt_" + strings.ReplaceAll(uuid.NewString(), "-", ""),
		Type:         EventDisconnect,
		EndpointID:   c.info.EndpointID,
		AppID:        c.info.AppID,
		AccountID:    c.info.AccountID,
		ConnectionID: c.info.ID,
		Principal:    c.info.Principal,
		Sequence:     c.sequence.Load(),
		CloseCode:    closeCode,
		CloseReason:  closeReason,
		At:           time.Now().UTC(),
	}
	disconnect.CallbackURL = c.endpoint.CallbackURL
	disconnect.CallbackPath = c.endpoint.DisconnectPath
	disconnect.CallbackAuthToken = callbackAuthToken
	ctx, cancel := context.WithTimeout(context.WithoutCancel(ctx), m.cfg.CallbackTimeout)
	defer cancel()
	if err := m.hooks.Disconnect(ctx, disconnect); err != nil {
		m.callbackErrors.Add(1)
		if errors.Is(err, ErrCallbackNotPersisted) {
			if errors.Is(err, ErrCallbackOutboxFull) {
				m.callbackOutboxFull.Add(1)
			} else if errors.Is(err, ErrCallbackOutboxAdmission) {
				m.callbackOutboxAdmissionErrors.Add(1)
			} else {
				m.callbackUnpersistedFailures.Add(1)
			}
		}
	}
}

func (c *connection) currentCallbackAuthToken() string {
	if current := c.callbackAuth.Load(); current != nil {
		return current.token
	}
	return ""
}

func (c *connection) close(code int, reason string) error {
	var err error
	c.closeOne.Do(func() {
		if c.v2 && reason == resumeOutputQueueFullReason {
			c.m.resumeMetrics.slowConsumerDisconnects.Add(1)
		}
		c.recordClose(code, reason)
		c.closeOutboundQueue()
		deadline := time.Now().Add(c.m.cfg.WriteWait)
		err = c.ws.WriteControl(websocket.CloseMessage, websocket.FormatCloseMessage(code, reason), deadline)
		closeErr := c.ws.Close()
		if err == nil {
			err = closeErr
		}
	})
	return err
}

func (c *connection) terminate(code int, reason string) {
	c.closeOne.Do(func() {
		c.recordClose(code, reason)
		c.closeOutboundQueue()
		_ = c.ws.Close()
	})
}

func (c *connection) recordClose(code int, reason string) {
	c.mu.Lock()
	if c.closeCode == 0 {
		c.closeCode = code
		c.closeReason = reason
	}
	c.mu.Unlock()
}

// Send queues one bounded message for a live connection.
func (m *Manager) Send(ctx context.Context, connectionID string, msg Message) error {
	c, ok := m.connection(connectionID)
	if !ok {
		return ErrConnectionNotFound
	}
	if c.v2 {
		return ErrUnauthorized
	}
	if int64(len(msg.Data)) > c.endpoint.MaxMessageBytes {
		return fmt.Errorf("realtime: message exceeds %d bytes", c.endpoint.MaxMessageBytes)
	}
	if err := m.queueOutbound(ctx, c, msg); err != nil {
		return err
	}
	m.sentMessages.Add(1)
	m.sentBytes.Add(uint64(len(msg.Data)))
	return nil
}

// SendToPrincipal queues a live-only message to active connections on this
// endpoint whose verified principal matches. V2 clients must advertise direct
// message support in a subscribe frame; older v2 clients are counted as
// unsupported and remain connected.
func (m *Manager) SendToPrincipal(ctx context.Context, endpointID, principal, messageID string, requestReceipt bool, msg Message) (PrincipalSendStatus, error) {
	if err := api.ValidateRealtimePrincipal(principal); err != nil {
		return PrincipalSendStatus{}, fmt.Errorf("%w: %v", ErrInvalidPrincipal, err)
	}
	if messageID == "" && !requestReceipt {
		messageID = uuid.NewString()
	}
	if err := api.ValidateRealtimeDirectMessageID(messageID); err != nil {
		return PrincipalSendStatus{}, fmt.Errorf("%w: %v", ErrInvalidDirectMessageID, err)
	}
	value, ok := m.endpoints.Load(endpointID)
	if !ok || value.(*endpointState).revoked.Load() {
		return PrincipalSendStatus{}, ErrEndpointNotFound
	}
	endpoint := value.(*endpointState)
	maxMessageBytes := min(int64(api.RealtimePrincipalMessageMaxBytes), endpoint.config.Load().MaxMessageBytes)
	if int64(len(msg.Data)) > maxMessageBytes {
		return PrincipalSendStatus{}, fmt.Errorf("realtime: principal message exceeds %d bytes", maxMessageBytes)
	}
	m.mu.RLock()
	targets := make([]*connection, 0)
	for _, c := range m.conns {
		if c.info.EndpointID == endpointID && c.info.Principal == principal {
			targets = append(targets, c)
		}
	}
	m.mu.RUnlock()

	status := PrincipalSendStatus{MessageID: messageID, Recipients: len(targets)}
	newTargets := make(map[string]struct{}, len(targets))
	receiptClient, canTrackReceipts := m.cfg.FleetClient.(ManagedRealtimeDirectMessageReceiptClient)
	if requestReceipt && len(targets) > 0 {
		if !canTrackReceipts {
			return status, ErrDirectMessageReceiptsUnavailable
		}
		registrations := make([]state.ManagedRealtimeDirectMessageTarget, len(targets))
		for i, c := range targets {
			c.mu.RLock()
			registrations[i] = state.ManagedRealtimeDirectMessageTarget{ConnectionID: c.info.ID, AckSupported: c.v2 && c.directMessages}
			c.mu.RUnlock()
		}
		registerCtx, cancel := context.WithTimeout(ctx, realtimeChannelRouteReportTimeout)
		created, err := receiptClient.RegisterDirectMessageTargets(registerCtx, endpointID, messageID, registrations)
		cancel()
		if err != nil {
			m.reportFleetFailure(err)
			return status, fmt.Errorf("%w: %v", ErrDirectMessageReceiptsUnavailable, err)
		}
		for _, connectionID := range created {
			newTargets[connectionID] = struct{}{}
		}
	}
	results := make([]state.ManagedRealtimeDirectMessageDeliveryResult, 0, len(targets))
	for _, c := range targets {
		if requestReceipt {
			if _, created := newTargets[c.info.ID]; !created {
				continue
			}
		}
		c.mu.RLock()
		v2, supportsDirect := c.v2, c.directMessages
		c.mu.RUnlock()
		if v2 && !supportsDirect {
			status.Unsupported++
			if requestReceipt {
				results = append(results, state.ManagedRealtimeDirectMessageDeliveryResult{ConnectionID: c.info.ID, QueueStatus: state.ManagedRealtimeDirectQueueUnsupported})
			}
			continue
		}
		if v2 && requestReceipt {
			c.mu.Lock()
			now := time.Now().UTC()
			for messageID, queuedAt := range c.pendingDirectMessages {
				if now.Sub(queuedAt) > 2*state.ManagedRealtimeDirectMessageAckTimeout {
					delete(c.pendingDirectMessages, messageID)
				}
			}
			if len(c.pendingDirectMessages) >= maxPendingDirectMessageReceipts {
				c.mu.Unlock()
				status.QueueFull++
				results = append(results, state.ManagedRealtimeDirectMessageDeliveryResult{ConnectionID: c.info.ID, QueueStatus: state.ManagedRealtimeDirectQueueFull})
				continue
			}
			c.pendingDirectMessages[messageID] = now
			c.mu.Unlock()
		}
		var err error
		if v2 {
			err = m.queueResume(ctx, c, resumeServerFrame{
				Type: "direct_message", MessageID: messageID, ReceiptRequested: requestReceipt,
				DataBase64: base64.StdEncoding.EncodeToString(msg.Data), Binary: msg.Binary,
			})
		} else {
			err = m.Send(ctx, c.info.ID, msg)
		}
		queueStatus := state.ManagedRealtimeDirectQueueQueued
		switch {
		case err == nil:
			status.Queued++
			if requestReceipt && !v2 {
				status.Unsupported++
			}
		case errors.Is(err, ErrOutboundQueueFull):
			status.QueueFull++
			queueStatus = state.ManagedRealtimeDirectQueueFull
		default:
			status.Failed++
			queueStatus = state.ManagedRealtimeDirectQueueFailed
		}
		if requestReceipt {
			if err != nil && v2 {
				c.mu.Lock()
				delete(c.pendingDirectMessages, messageID)
				c.mu.Unlock()
			}
			results = append(results, state.ManagedRealtimeDirectMessageDeliveryResult{ConnectionID: c.info.ID, QueueStatus: queueStatus})
		}
	}
	if requestReceipt && len(results) > 0 {
		updateCtx, cancel := context.WithTimeout(context.WithoutCancel(ctx), realtimeChannelRouteReportTimeout)
		if err := receiptClient.UpdateDirectMessageDeliveries(updateCtx, endpointID, messageID, results); err != nil {
			m.reportFleetFailure(err)
		}
		cancel()
	}
	return status, nil
}

// queueOutbound applies both the item-count and byte budgets to legacy and
// resumable protocol frames. The byte budget includes a frame currently being
// written, bounding buffered payload memory per connection.
func (m *Manager) queueOutbound(ctx context.Context, c *connection, msg Message) error {
	if err := ctx.Err(); err != nil {
		return err
	}
	size := int64(len(msg.Data))
	c.outboundMu.Lock()
	defer c.outboundMu.Unlock()
	if err := ctx.Err(); err != nil {
		return err
	}
	if c.outboundClosed {
		return ErrConnectionClosed
	}
	if msg.signalKey.name != "" {
		if pending := c.pendingSignals[msg.signalKey]; pending != nil {
			if msg.signalUpdated.Before(pending.message.signalUpdated) {
				return nil
			}
			delta := size - int64(len(pending.message.Data))
			if delta > 0 && c.outboundBytes > m.cfg.OutboundQueueBytes-delta {
				m.droppedMessages.Add(1)
				m.outboundQueueByteDrops.Add(1)
				return ErrOutboundQueueFull
			}
			msg.Data = append([]byte(nil), msg.Data...)
			pending.message = msg
			c.outboundBytes += delta
			m.outboundPendingBytes.Add(delta)
			return nil
		}
	}
	if len(c.outbound) >= cap(c.outbound) {
		m.droppedMessages.Add(1)
		m.outboundQueueCountDrops.Add(1)
		return ErrOutboundQueueFull
	}
	if size > m.cfg.OutboundQueueBytes || c.outboundBytes > m.cfg.OutboundQueueBytes-size {
		m.droppedMessages.Add(1)
		m.outboundQueueByteDrops.Add(1)
		return ErrOutboundQueueFull
	}
	msg.Data = append([]byte(nil), msg.Data...)
	queued := msg
	var pending *pendingSignal
	if msg.signalKey.name != "" {
		pending = &pendingSignal{message: msg}
		queued = Message{signalKey: msg.signalKey, signalToken: pending}
	}
	select {
	case c.outbound <- queued:
		if pending != nil {
			if c.pendingSignals == nil {
				c.pendingSignals = make(map[pendingSignalKey]*pendingSignal)
			}
			c.pendingSignals[msg.signalKey] = pending
		}
		c.outboundBytes += size
		m.outboundPendingBytes.Add(size)
		return nil
	case <-ctx.Done():
		return ctx.Err()
	case <-c.done:
		return ErrConnectionClosed
	default:
		m.droppedMessages.Add(1)
		m.outboundQueueCountDrops.Add(1)
		return ErrOutboundQueueFull
	}
}

// Resolve a single queue token to its latest payload under outboundMu.
func (c *connection) resolvePendingSignalLocked(msg Message) Message {
	if msg.signalToken == nil {
		return msg
	}
	pending := msg.signalToken
	if c.pendingSignals[msg.signalKey] == pending {
		delete(c.pendingSignals, msg.signalKey)
	}
	return pending.message
}

func (c *connection) releaseOutboundBytes(size int64) {
	c.outboundMu.Lock()
	if size > c.outboundBytes {
		size = c.outboundBytes
	}
	c.outboundBytes -= size
	c.m.outboundPendingBytes.Add(-size)
	c.outboundMu.Unlock()
}

func (c *connection) closeOutboundQueue() {
	c.outboundMu.Lock()
	if !c.outboundClosed {
		c.outboundClosed = true
		close(c.done)
	}
	for {
		select {
		case msg := <-c.outbound:
			msg = c.resolvePendingSignalLocked(msg)
			size := int64(len(msg.Data))
			if size > c.outboundBytes {
				size = c.outboundBytes
			}
			c.outboundBytes -= size
			c.m.outboundPendingBytes.Add(-size)
		default:
			c.outboundMu.Unlock()
			return
		}
	}
}

// CloseConnection closes one live socket and emits its disconnect event.
func (m *Manager) CloseConnection(connectionID, reason string) error {
	c, ok := m.connection(connectionID)
	if !ok {
		return ErrConnectionNotFound
	}
	select {
	case <-c.done:
		return ErrConnectionClosed
	default:
	}
	return c.close(websocket.CloseNormalClosure, reason)
}

// Subscribe adds a channel membership to a live connection.
func (m *Manager) Subscribe(connectionID, channel string) error {
	if !validChannel(channel) {
		return ErrInvalidChannel
	}
	m.mu.Lock()
	defer m.mu.Unlock()
	c, ok := m.conns[connectionID]
	if !ok {
		return ErrConnectionNotFound
	}
	if c.v2 {
		return ErrUnauthorized
	}
	select {
	case <-c.done:
		return ErrConnectionClosed
	default:
	}
	c.mu.Lock()
	if _, subscribed := c.channels[channel]; !subscribed {
		c.channels[channel] = struct{}{}
		key := channelKey{endpointID: c.info.EndpointID, channel: channel}
		members := m.subscribers[key]
		if members == nil {
			members = make(map[string]struct{})
			m.subscribers[key] = members
		}
		members[connectionID] = struct{}{}
	}
	c.mu.Unlock()
	return nil
}

// Unsubscribe removes a channel membership from a live connection.
func (m *Manager) Unsubscribe(connectionID, channel string) error {
	_, err := m.UnsubscribeWithRouteState(connectionID, channel)
	return err
}

// UnsubscribeWithRouteState removes a channel membership and reports whether
// any local connection still subscribes to the endpoint/channel pair.
func (m *Manager) UnsubscribeWithRouteState(connectionID, channel string) (bool, error) {
	if !validChannel(channel) {
		return false, ErrInvalidChannel
	}
	m.mu.Lock()
	defer m.mu.Unlock()
	c, ok := m.conns[connectionID]
	if !ok {
		return false, ErrConnectionNotFound
	}
	if c.v2 {
		return false, ErrUnauthorized
	}
	select {
	case <-c.done:
		return false, ErrConnectionClosed
	default:
	}
	c.mu.Lock()
	key := channelKey{endpointID: c.info.EndpointID, channel: channel}
	if _, subscribed := c.channels[channel]; subscribed {
		hadSubscribers := m.hasChannelSubscribersLocked(key)
		delete(c.channels, channel)
		members := m.subscribers[key]
		delete(members, connectionID)
		if len(members) == 0 {
			delete(m.subscribers, key)
		}
		if hadSubscribers && !m.hasChannelSubscribersLocked(key) {
			m.channelRouteRevision++
		}
	}
	c.mu.Unlock()
	return m.hasChannelSubscribersLocked(key), nil
}

// Publish queues a message to all local connections subscribed to channel on
// endpointID. It returns the number of successfully queued messages; an
// individual slow consumer does not prevent other subscribers from receiving.
func (m *Manager) Publish(ctx context.Context, endpointID, channel string, msg Message) (int, error) {
	status, err := m.PublishWithStatus(ctx, endpointID, channel, msg)
	return status.Queued, err
}

// PublishWithStatus reports per-connection queue admission and failures for
// the local endpoint owner. It does not wait for clients to read the messages.
func (m *Manager) PublishWithStatus(ctx context.Context, endpointID, channel string, msg Message) (PublishStatus, error) {
	if !validChannel(channel) {
		return PublishStatus{}, ErrInvalidChannel
	}
	value, endpointRegistered := m.endpoints.Load(endpointID)
	if !endpointRegistered || value.(*endpointState).revoked.Load() {
		return PublishStatus{}, ErrEndpointNotFound
	}
	state := value.(*endpointState)
	maxMessageBytes := state.config.Load().MaxMessageBytes
	m.mu.RLock()
	members := m.subscribers[channelKey{endpointID: endpointID, channel: channel}]
	connections := make([]string, 0, len(members))
	for id := range members {
		connections = append(connections, id)
	}
	m.mu.RUnlock()
	if int64(len(msg.Data)) > maxMessageBytes {
		return PublishStatus{}, fmt.Errorf("realtime: message exceeds %d bytes", maxMessageBytes)
	}
	status := PublishStatus{Subscribers: len(connections)}
	for _, id := range connections {
		switch err := m.Send(ctx, id, msg); {
		case err == nil:
			status.Queued++
		case errors.Is(err, ErrOutboundQueueFull):
			status.QueueFull++
		default:
			status.Failed++
		}
	}
	return status, nil
}

// BroadcastEphemeral fans one transient v2 presence or signal frame to local
// resumable subscribers. It never reaches legacy subscriptions or history.
func (m *Manager) BroadcastEphemeral(ctx context.Context, endpointID, channel string, frame EphemeralFrame) error {
	if !validChannel(channel) || !ValidateEphemeralFrame(frame) {
		return ErrInvalidChannel
	}
	value, ok := m.endpoints.Load(endpointID)
	if !ok || value.(*endpointState).revoked.Load() {
		return ErrEndpointNotFound
	}
	if frame.Type == "read_receipt" && frame.Inbox {
		if channel != frame.MemberID {
			return ErrInvalidChannel
		}
		m.broadcastInboxRead(ctx, endpointID, frame)
		return nil
	}
	key := channelKey{endpointID: endpointID, channel: channel}
	serverFrame := resumeServerFrame{
		Type: frame.Type, Channel: channel, Event: frame.Event, MemberID: frame.MemberID, Name: frame.Name, ExpiresAt: frame.ExpiresAt,
		State: append(json.RawMessage(nil), frame.State...), Data: append(json.RawMessage(nil), frame.Data...),
		ConnectionCount: frame.ConnectionCount, UpdatedAt: frame.UpdatedAt, Inbox: frame.Inbox, Sequence: frame.Sequence, Unread: frame.Unread, OldestSequence: frame.OldestSequence, LatestSequence: frame.LatestSequence, HistoryUnavailable: frame.HistoryUnavailable,
	}
	if frame.Type == "read_receipt" {
		m.broadcastEphemeral(ctx, key, "", serverFrame)
		return nil
	}
	if frame.Type == "signal" {
		// Expired updates have no value to a receiving node. Zero-lifetime
		// frames are explicit clears and must still reach subscribers.
		if frame.ExpiresAt != nil && frame.ExpiresAt.After(frame.UpdatedAt) && !frame.ExpiresAt.After(time.Now().UTC()) {
			return nil
		}
		m.broadcastEphemeral(ctx, key, "", serverFrame)
		return nil
	}
	if serverFrame.UpdatedAt.IsZero() {
		serverFrame.UpdatedAt = time.Now().UTC()
	}
	var fullQueues []*connection
	m.mu.Lock()
	if m.resumeSubscribers[key] == nil {
		m.mu.Unlock()
		return nil
	}
	known := m.fleetPresence[key][frame.MemberID]
	tombstone := m.fleetPresenceTombstones[key][frame.MemberID]
	if !tombstone.IsZero() && !serverFrame.UpdatedAt.After(tombstone) {
		m.mu.Unlock()
		return nil
	}
	if known.MemberID != "" && known.UpdatedAt.After(serverFrame.UpdatedAt) {
		m.mu.Unlock()
		return nil
	}
	if frame.Event == "left" {
		delete(m.fleetPresence[key], frame.MemberID)
		m.recordFleetPresenceTombstoneLocked(key, frame.MemberID, serverFrame.UpdatedAt)
		if known.MemberID != "" {
			fullQueues = m.queueEphemeralToSubscribersLocked(ctx, key, "", serverFrame)
		}
	} else {
		if known.MemberID != "" && bytes.Equal(known.State, frame.State) && known.ConnectionCount == frame.ConnectionCount {
			m.setFleetPresenceLocked(key, PresenceMember{MemberID: frame.MemberID, State: frame.State,
				ConnectionCount: frame.ConnectionCount, UpdatedAt: serverFrame.UpdatedAt})
			m.mu.Unlock()
			return nil
		}
		if known.MemberID != "" {
			serverFrame.Event = "updated"
		} else {
			serverFrame.Event = "joined"
		}
		m.setFleetPresenceLocked(key, PresenceMember{MemberID: frame.MemberID, State: frame.State,
			ConnectionCount: frame.ConnectionCount, UpdatedAt: serverFrame.UpdatedAt})
		fullQueues = m.queueEphemeralToSubscribersLocked(ctx, key, "", serverFrame)
	}
	m.mu.Unlock()
	for _, slow := range fullQueues {
		m.closeResumeOnQueueFull(slow, ErrOutboundQueueFull)
	}
	return nil
}

func validChannel(channel string) bool {
	if _, _, err := api.ParseRealtimeActivityScope(channel); err != nil {
		return false
	}
	return channel != "" && len(channel) <= maxChannelLength &&
		strings.TrimSpace(channel) == channel && !strings.ContainsAny(channel, "/?#\r\n")
}

func validDurableSubscription(subscription string) bool {
	return subscription != "" && len(subscription) <= 128 &&
		strings.TrimSpace(subscription) == subscription && !strings.ContainsAny(subscription, "\x00\r\n")
}

// ValidateChannel reports whether channel is valid for endpoint-scoped
// subscriptions and publishes. It is exported so public API handlers can
// reject malformed path values before forwarding them to an owner node.
func ValidateChannel(channel string) bool { return validChannel(channel) }

func (m *Manager) connection(id string) (*connection, bool) {
	m.mu.RLock()
	c, ok := m.conns[id]
	m.mu.RUnlock()
	if ok && c.state.revoked.Load() {
		return nil, false
	}
	return c, ok
}

// Snapshot returns a stable copy of the live connection directory.
func (m *Manager) Snapshot() []ConnectionInfo {
	m.mu.RLock()
	defer m.mu.RUnlock()
	result := make([]ConnectionInfo, 0, len(m.conns))
	for _, c := range m.conns {
		c.mu.RLock()
		info := c.info
		if len(c.channels) > 0 {
			info.Channels = make([]string, 0, len(c.channels))
			for channel := range c.channels {
				info.Channels = append(info.Channels, channel)
			}
			sort.Strings(info.Channels)
		}
		result = append(result, info)
		c.mu.RUnlock()
	}
	return result
}

// hasChannelSubscribersLocked reports whether either local subscriber index
// contains a member. The caller must hold m.mu.
func (m *Manager) hasChannelSubscribersLocked(key channelKey) bool {
	return len(m.subscribers[key]) > 0 || len(m.resumeSubscribers[key]) > 0
}

// ChannelRouteSnapshot returns the unique endpoint/channel pairs currently
// present in either local subscriber index. The manager lock gives the
// snapshot one consistent view while subscriptions and connection closes are
// applied.
func (m *Manager) ChannelRouteSnapshot() []ChannelRoute {
	if m == nil {
		return []ChannelRoute{}
	}
	m.mu.RLock()
	defer m.mu.RUnlock()
	routeKeys := make(map[channelKey]struct{}, len(m.subscribers)+len(m.resumeSubscribers))
	for key, members := range m.subscribers {
		if len(members) == 0 {
			continue
		}
		routeKeys[key] = struct{}{}
	}
	for key, members := range m.resumeSubscribers {
		if len(members) == 0 {
			continue
		}
		routeKeys[key] = struct{}{}
	}
	routes := make([]ChannelRoute, 0, len(routeKeys))
	for key := range routeKeys {
		routes = append(routes, ChannelRoute{EndpointID: key.endpointID, Channel: key.channel})
	}
	sort.Slice(routes, func(i, j int) bool {
		if routes[i].EndpointID == routes[j].EndpointID {
			return routes[i].Channel < routes[j].Channel
		}
		return routes[i].EndpointID < routes[j].EndpointID
	})
	return routes
}

// ChannelRouteRevision returns the local subscriber-index revision. The
// revision changes when an endpoint/channel pair enters or leaves the route
// set.
func (m *Manager) ChannelRouteRevision() ChannelRouteRevision {
	if m == nil {
		return ChannelRouteRevision{}
	}
	m.mu.RLock()
	defer m.mu.RUnlock()
	return ChannelRouteRevision{InstanceID: m.channelRouteInstance, Revision: m.channelRouteRevision}
}

// Stats returns bounded resource and delivery counters for this realtime
// owner. It is safe to call while connections are opening and closing.
func (m *Manager) Stats() Stats {
	if m == nil {
		return Stats{}
	}
	current := m.reserved.Load()
	if current < 0 {
		current = 0
	}
	stats := Stats{
		CurrentConnections:            uint64(current),
		CurrentResumeSubscriptions:    uint64(maxInt64(m.resumeCount.Load(), 0)),
		AcceptedConnections:           m.acceptedConnections.Load(),
		RejectedConnections:           m.rejectedConnections.Load(),
		ReceivedMessages:              m.receivedMessages.Load(),
		ReceivedBytes:                 m.receivedBytes.Load(),
		SentMessages:                  m.sentMessages.Load(),
		SentBytes:                     m.sentBytes.Load(),
		DroppedMessages:               m.droppedMessages.Load(),
		OutboundPendingBytes:          uint64(maxInt64(m.outboundPendingBytes.Load(), 0)),
		OutboundQueueBytesLimit:       uint64(m.cfg.OutboundQueueBytes),
		OutboundQueueCountDrops:       m.outboundQueueCountDrops.Load(),
		OutboundQueueByteDrops:        m.outboundQueueByteDrops.Load(),
		CallbackErrors:                m.callbackErrors.Load(),
		CallbackOutboxFull:            m.callbackOutboxFull.Load(),
		CallbackOutboxAdmissionErrors: m.callbackOutboxAdmissionErrors.Load(),
		CallbackUnpersistedFailures:   m.callbackUnpersistedFailures.Load(),
	}
	if provider, ok := m.hooks.(interface{ OutboxStats() CallbackOutboxStats }); ok {
		outbox := provider.OutboxStats()
		stats.CallbackPending = uint64(maxInt(outbox.Pending, 0))
		stats.CallbackPendingBytes = uint64(maxInt64(outbox.PendingBytes, 0))
		stats.CallbackPendingCapacityBytes = uint64(maxInt64(outbox.CapacityBytes, 0))
		stats.CallbackReplayReady = uint64(maxInt(outbox.ReplayReady, 0))
		stats.CallbackReplayDelayed = uint64(maxInt(outbox.ReplayDelayed, 0))
		stats.CallbackReplayAttempts = outbox.ReplayAttempts
		stats.CallbackReplayDeliveries = outbox.ReplayDeliveries
		stats.CallbackOldestPendingAgeSeconds = outbox.OldestPendingAgeSeconds
		stats.CallbackDeadLetters = uint64(maxInt64(outbox.DeadLetterTotal, 0))
		stats.CallbackDeadLetterBytes = uint64(maxInt64(outbox.DeadLetterBytes, 0))
		stats.CallbackDeadLetterCapacityBytes = uint64(maxInt64(outbox.DeadLetterCapacityBytes, 0))
		stats.CallbackDeadLetterEvictions = outbox.DeadLetterEvictions
		stats.CallbackDeadLetterLastEvictionUnix = outbox.DeadLetterLastEvictionUnix
		stats.CallbackDeadLetterDiscards = outbox.DeadLetterDiscards
	}
	return stats
}

func maxInt(value, floor int) int {
	if value < floor {
		return floor
	}
	return value
}

func maxInt64(value, floor int64) int64 {
	if value < floor {
		return floor
	}
	return value
}

// Close stops admission, closes every socket, and cancels callback contexts.
func (m *Manager) Close() error {
	if m == nil || !m.closed.CompareAndSwap(false, true) {
		return nil
	}
	m.cancel()
	m.mu.RLock()
	connections := make([]*connection, 0, len(m.conns))
	for _, c := range m.conns {
		connections = append(connections, c)
	}
	m.mu.RUnlock()
	for _, c := range connections {
		_ = c.close(websocket.CloseGoingAway, "service shutdown")
	}
	return nil
}
