// Package realtime owns Gregale's managed realtime data plane.
//
// Managed realtime is deliberately separate from the gateway's raw Upgrade
// bridge. The raw bridge forwards bytes to an application-owned socket; this
// package terminates WebSocket connections at Gregale, keeps the connection
// registry in the process that owns the sockets, and exposes message delivery
// as ordinary callback events.
package realtime

import (
	"context"
	"crypto/subtle"
	"errors"
	"fmt"
	"net/http"
	"sort"
	"strings"
	"sync"
	"sync/atomic"
	"time"

	"github.com/google/uuid"
	"github.com/gorilla/websocket"
)

const (
	// ManagedPathPrefix is the reserved ingress namespace for managed
	// realtime endpoints. gatewayd-internal routes this prefix before VM
	// admission, so an open managed connection never pins an application VM.
	ManagedPathPrefix = "/__gregale/realtime/"

	defaultMaxConnections = 10_000
	defaultMaxMessageSize = 1 << 20 // 1 MiB
	defaultOutboundQueue  = 64
	defaultHeartbeat      = 30 * time.Second
	defaultPongWait       = 10 * time.Second
	defaultWriteWait      = 5 * time.Second
	defaultMaxAge         = 24 * time.Hour
	defaultCallbackWait   = 30 * time.Second

	maxChannelLength = 256
)

var (
	ErrEndpointNotFound   = errors.New("realtime: endpoint not found")
	ErrConnectionNotFound = errors.New("realtime: connection not found")
	ErrTooManyConnections = errors.New("realtime: connection limit reached")
	ErrOutboundQueueFull  = errors.New("realtime: outbound queue full")
	ErrConnectionClosed   = errors.New("realtime: connection closed")
	ErrUnauthorized       = errors.New("realtime: connection unauthorized")
	ErrInvalidChannel     = errors.New("realtime: invalid channel")
)

// EventType is the callback event discriminator delivered to an application.
type EventType string

const (
	EventConnect    EventType = "realtime.connect"
	EventMessage    EventType = "realtime.message"
	EventDisconnect EventType = "realtime.disconnect"
)

// Message is a frame sent to a managed connection. Data is copied before it
// enters the bounded output queue, so callers may safely reuse their buffer.
type Message struct {
	Data   []byte
	Binary bool
}

// Event is the ordinary HTTP-handler payload generated by a managed
// connection. Data is copied before a hook is called and must be treated as
// immutable by hook implementations.
type Event struct {
	ID                string    `json:"id"`
	Type              EventType `json:"type"`
	EndpointID        string    `json:"endpoint_id"`
	AppID             string    `json:"app_id"`
	AccountID         string    `json:"account_id"`
	ConnectionID      string    `json:"connection_id"`
	Principal         string    `json:"principal,omitempty"`
	Channel           string    `json:"channel,omitempty"`
	Sequence          uint64    `json:"sequence"`
	Binary            bool      `json:"binary"`
	Data              []byte    `json:"data,omitempty"`
	CloseCode         int       `json:"close_code,omitempty"`
	CloseReason       string    `json:"close_reason,omitempty"`
	At                time.Time `json:"at"`
	CallbackURL       string    `json:"-"`
	CallbackPath      string    `json:"callback_path,omitempty"`
	CallbackAuthToken string    `json:"-"`
}

// Endpoint describes one managed realtime ingress. The endpoint ID is an
// opaque path component and must be unique within a realtime daemon.
type Endpoint struct {
	ID             string
	AppID          string
	AccountID      string
	CallbackURL    string
	ConnectPath    string
	MessagePath    string
	DisconnectPath string
	// CallbackAuthToken is an optional bearer credential sent only to the
	// configured callback handler. It is never serialized into an Event.
	CallbackAuthToken string
	// AuthToken is a narrow bootstrap credential for local development and
	// controlled single-node deployments. Production should use Authorize
	// backed by the app's configured auth provider; this token is never emitted
	// in events or registry snapshots.
	AuthToken string

	// Authorize runs before the WebSocket handshake. It should validate the
	// client credential and return a stable principal identifier. A nil
	// Authorize function permits the request; production wiring should normally
	// install an app-specific authorizer.
	Authorize func(context.Context, *http.Request) (principal string, err error)

	// CheckOrigin is optional. When nil, the manager accepts all origins and
	// leaves origin policy to Authorize. Browser-facing endpoints should set an
	// explicit allowlist.
	CheckOrigin func(*http.Request) bool
}

// Hooks receives connection lifecycle events. Connect is synchronous with
// connection admission and may reject the connection. Message and Disconnect
// are called after the connection has been admitted; production hooks should
// enqueue a durable event and return quickly.
type Hooks interface {
	Connect(context.Context, Event) (accept bool, err error)
	Message(context.Context, Event) error
	Disconnect(context.Context, Event) error
}

// NopHooks is a convenient default for embedding the data plane before the
// durable callback dispatcher is wired.
type NopHooks struct{}

func (NopHooks) Connect(context.Context, Event) (bool, error) { return true, nil }
func (NopHooks) Message(context.Context, Event) error         { return nil }
func (NopHooks) Disconnect(context.Context, Event) error      { return nil }

// Config contains bounded resource and lifecycle settings. Zero values use
// conservative defaults; all limits are enforced at the data-plane boundary.
type Config struct {
	MaxConnections   int
	MaxMessageBytes  int64
	OutboundQueue    int
	Heartbeat        time.Duration
	PongWait         time.Duration
	WriteWait        time.Duration
	MaxConnectionAge time.Duration
	CallbackTimeout  time.Duration
}

func (c Config) withDefaults() Config {
	if c.MaxConnections <= 0 {
		c.MaxConnections = defaultMaxConnections
	}
	if c.MaxMessageBytes <= 0 {
		c.MaxMessageBytes = defaultMaxMessageSize
	}
	if c.OutboundQueue <= 0 {
		c.OutboundQueue = defaultOutboundQueue
	}
	if c.Heartbeat <= 0 {
		c.Heartbeat = defaultHeartbeat
	}
	if c.PongWait <= 0 {
		c.PongWait = defaultPongWait
	}
	if c.WriteWait <= 0 {
		c.WriteWait = defaultWriteWait
	}
	if c.MaxConnectionAge <= 0 {
		c.MaxConnectionAge = defaultMaxAge
	}
	if c.CallbackTimeout <= 0 {
		c.CallbackTimeout = defaultCallbackWait
	}
	return c
}

// ConnectionInfo is the safe, non-socket portion of a registry entry.
type ConnectionInfo struct {
	ID         string    `json:"id"`
	EndpointID string    `json:"endpoint_id"`
	AppID      string    `json:"app_id"`
	AccountID  string    `json:"account_id"`
	Principal  string    `json:"principal,omitempty"`
	Connected  time.Time `json:"connected_at"`
	LastSeen   time.Time `json:"last_seen_at"`
	Expires    time.Time `json:"expires_at"`
	Channels   []string  `json:"channels,omitempty"`
}

// Stats is a point-in-time view of the bounded realtime data plane. Counters
// are process-local; operators should aggregate them across realtimed nodes.
type Stats struct {
	CurrentConnections  uint64 `json:"current_connections"`
	AcceptedConnections uint64 `json:"accepted_connections"`
	RejectedConnections uint64 `json:"rejected_connections"`
	ReceivedMessages    uint64 `json:"received_messages"`
	ReceivedBytes       uint64 `json:"received_bytes"`
	SentMessages        uint64 `json:"sent_messages"`
	SentBytes           uint64 `json:"sent_bytes"`
	DroppedMessages     uint64 `json:"dropped_messages"`
	CallbackErrors      uint64 `json:"callback_errors"`
}

type connection struct {
	info ConnectionInfo
	// endpoint is retained with the connection so removing or replacing an
	// endpoint does not strand lifecycle callbacks for already-open sockets.
	endpoint Endpoint
	ws       *websocket.Conn
	m        *Manager

	outbound chan Message
	done     chan struct{}
	closeOne sync.Once

	sequence    atomic.Uint64
	mu          sync.RWMutex
	channels    map[string]struct{}
	closeCode   int
	closeReason string
}

// Manager is the owner of managed realtime sockets for one process/node.
// The registry is intentionally process-local; connections cannot be moved
// between nodes. The Snapshot method is suitable for publishing a leased
// directory view to the control plane.
type Manager struct {
	cfg   Config
	hooks Hooks

	ctx    context.Context
	cancel context.CancelFunc

	endpoints sync.Map // map[string]Endpoint
	mu        sync.RWMutex
	conns     map[string]*connection
	reserved  atomic.Int64
	closed    atomic.Bool

	upgrader websocket.Upgrader

	acceptedConnections atomic.Uint64
	rejectedConnections atomic.Uint64
	receivedMessages    atomic.Uint64
	receivedBytes       atomic.Uint64
	sentMessages        atomic.Uint64
	sentBytes           atomic.Uint64
	droppedMessages     atomic.Uint64
	callbackErrors      atomic.Uint64
}

// NewManager creates a managed realtime owner. Call Close during daemon
// shutdown to close all sockets and stop callback contexts.
func NewManager(cfg Config, hooks Hooks) *Manager {
	cfg = cfg.withDefaults()
	if hooks == nil {
		hooks = NopHooks{}
	}
	ctx, cancel := context.WithCancel(context.Background())
	return &Manager{
		cfg:    cfg,
		hooks:  hooks,
		ctx:    ctx,
		cancel: cancel,
		conns:  make(map[string]*connection),
		upgrader: websocket.Upgrader{
			ReadBufferSize:  4096,
			WriteBufferSize: 4096,
			CheckOrigin:     func(*http.Request) bool { return true },
		},
	}
}

// RegisterEndpoint publishes an endpoint to the local ingress route.
func (m *Manager) RegisterEndpoint(e Endpoint) error {
	if m == nil || m.closed.Load() {
		return ErrConnectionClosed
	}
	if strings.TrimSpace(e.ID) != e.ID || e.ID == "" || e.ID == "." || e.ID == ".." || strings.ContainsAny(e.ID, "/?#") {
		return fmt.Errorf("realtime: invalid endpoint id %q", e.ID)
	}
	for name, path := range map[string]string{
		"connect_path":    e.ConnectPath,
		"message_path":    e.MessagePath,
		"disconnect_path": e.DisconnectPath,
	} {
		if path == "" {
			continue
		}
		if strings.ContainsAny(path, "?#\r\n") {
			return fmt.Errorf("realtime: invalid %s %q", name, path)
		}
		for _, segment := range strings.Split(path, "/") {
			if segment == "." || segment == ".." {
				return fmt.Errorf("realtime: invalid %s %q", name, path)
			}
		}
	}
	m.endpoints.Store(e.ID, e)
	return nil
}

// RemoveEndpoint stops new connections for an endpoint. Existing connections
// are left alive until their owner or application explicitly closes them.
func (m *Manager) RemoveEndpoint(id string) {
	if m != nil {
		m.endpoints.Delete(id)
	}
}

// Handler returns the HTTP handler mounted at ManagedPathPrefix.
func (m *Manager) Handler() http.Handler { return m }

// ServeHTTP upgrades /__gregale/realtime/{endpoint_id} and owns the resulting
// WebSocket until the client, endpoint, or manager closes it.
func (m *Manager) ServeHTTP(w http.ResponseWriter, r *http.Request) {
	if m == nil || m.closed.Load() {
		http.Error(w, "realtime service unavailable", http.StatusServiceUnavailable)
		return
	}
	if r.Method != http.MethodGet {
		http.Error(w, "method not allowed", http.StatusMethodNotAllowed)
		return
	}
	endpointID, ok := endpointIDFromPath(r.URL.Path)
	if !ok {
		http.NotFound(w, r)
		return
	}
	value, ok := m.endpoints.Load(endpointID)
	if !ok {
		m.rejectedConnections.Add(1)
		http.NotFound(w, r)
		return
	}
	endpoint := value.(Endpoint)
	principal := ""
	if endpoint.AuthToken != "" {
		header := strings.Fields(r.Header.Get("Authorization"))
		if len(header) != 2 || !strings.EqualFold(header[0], "Bearer") ||
			subtle.ConstantTimeCompare([]byte(header[1]), []byte(endpoint.AuthToken)) != 1 {
			m.rejectedConnections.Add(1)
			http.Error(w, "unauthorized", http.StatusUnauthorized)
			return
		}
		principal = "token"
	}
	if endpoint.Authorize != nil {
		var err error
		principal, err = endpoint.Authorize(r.Context(), r)
		if err != nil {
			m.rejectedConnections.Add(1)
			http.Error(w, "unauthorized", http.StatusUnauthorized)
			return
		}
	}
	upgrader := m.upgrader
	if endpoint.CheckOrigin != nil {
		upgrader.CheckOrigin = endpoint.CheckOrigin
	}
	if !m.tryReserve() {
		m.rejectedConnections.Add(1)
		http.Error(w, "realtime connection limit reached", http.StatusTooManyRequests)
		return
	}
	defer m.reserved.Add(-1)

	ws, err := upgrader.Upgrade(w, r, nil)
	if err != nil {
		m.rejectedConnections.Add(1)
		return
	}
	conn := m.addConnection(endpoint, principal, ws)
	m.runConnection(r.Context(), conn)
}

func (m *Manager) tryReserve() bool {
	for {
		current := m.reserved.Load()
		if current >= int64(m.cfg.MaxConnections) {
			return false
		}
		if m.reserved.CompareAndSwap(current, current+1) {
			return true
		}
	}
}

func endpointIDFromPath(path string) (string, bool) {
	if !strings.HasPrefix(path, ManagedPathPrefix) {
		return "", false
	}
	rest := strings.TrimPrefix(path, ManagedPathPrefix)
	if rest == "" || strings.Contains(rest, "/") {
		return "", false
	}
	return rest, true
}

func (m *Manager) addConnection(endpoint Endpoint, principal string, ws *websocket.Conn) *connection {
	now := time.Now().UTC()
	id := "rt_" + strings.ReplaceAll(uuid.NewString(), "-", "")
	conn := &connection{
		info: ConnectionInfo{
			ID:         id,
			EndpointID: endpoint.ID,
			AppID:      endpoint.AppID,
			AccountID:  endpoint.AccountID,
			Principal:  principal,
			Connected:  now,
			LastSeen:   now,
			Expires:    now.Add(m.cfg.MaxConnectionAge),
		},
		ws:       ws,
		endpoint: endpoint,
		m:        m,
		outbound: make(chan Message, m.cfg.OutboundQueue),
		done:     make(chan struct{}),
		channels: make(map[string]struct{}),
	}
	m.mu.Lock()
	m.conns[id] = conn
	m.mu.Unlock()
	m.acceptedConnections.Add(1)
	return conn
}

func (m *Manager) runConnection(ctx context.Context, c *connection) {
	defer m.removeConnection(ctx, c)

	go c.writePump()

	connect := Event{
		ID:           "evt_" + strings.ReplaceAll(uuid.NewString(), "-", ""),
		Type:         EventConnect,
		EndpointID:   c.info.EndpointID,
		AppID:        c.info.AppID,
		AccountID:    c.info.AccountID,
		ConnectionID: c.info.ID,
		Principal:    c.info.Principal,
		At:           time.Now().UTC(),
	}
	connect.CallbackURL = c.endpoint.CallbackURL
	connect.CallbackPath = c.endpoint.ConnectPath
	connect.CallbackAuthToken = c.endpoint.CallbackAuthToken
	accepted, err := m.callConnect(ctx, connect)
	if err != nil {
		m.callbackErrors.Add(1)
	}
	if err != nil || !accepted {
		m.rejectedConnections.Add(1)
		_ = c.close(websocket.ClosePolicyViolation, "connection rejected")
		return
	}

	c.ws.SetReadLimit(m.cfg.MaxMessageBytes)
	// Give the client until the first heartbeat plus a pong window. Setting
	// only PongWait here would close an otherwise healthy idle socket before
	// the first ping when Heartbeat is larger than PongWait (the defaults are
	// 30s and 10s respectively).
	_ = c.ws.SetReadDeadline(time.Now().Add(m.cfg.Heartbeat + m.cfg.PongWait))
	c.ws.SetPongHandler(func(string) error {
		return c.ws.SetReadDeadline(time.Now().Add(m.cfg.PongWait))
	})

	for {
		kind, data, err := c.ws.ReadMessage()
		if err != nil {
			var closeErr *websocket.CloseError
			if errors.As(err, &closeErr) {
				c.recordClose(closeErr.Code, closeErr.Text)
			}
			return
		}
		lastSeen := time.Now().UTC()
		c.mu.Lock()
		c.info.LastSeen = lastSeen
		c.mu.Unlock()
		event := Event{
			ID:           "evt_" + strings.ReplaceAll(uuid.NewString(), "-", ""),
			Type:         EventMessage,
			EndpointID:   c.info.EndpointID,
			AppID:        c.info.AppID,
			AccountID:    c.info.AccountID,
			ConnectionID: c.info.ID,
			Principal:    c.info.Principal,
			Sequence:     c.sequence.Add(1),
			Binary:       kind == websocket.BinaryMessage,
			Data:         append([]byte(nil), data...),
			At:           lastSeen,
		}
		event.CallbackURL = c.endpoint.CallbackURL
		event.CallbackPath = c.endpoint.MessagePath
		event.CallbackAuthToken = c.endpoint.CallbackAuthToken
		m.receivedMessages.Add(1)
		m.receivedBytes.Add(uint64(len(data)))
		callbackCtx, cancel := context.WithTimeout(ctx, m.cfg.CallbackTimeout)
		if err := m.hooks.Message(callbackCtx, event); err != nil {
			m.callbackErrors.Add(1)
		}
		cancel()
	}
}

func (m *Manager) callConnect(ctx context.Context, event Event) (bool, error) {
	ctx, cancel := context.WithTimeout(ctx, m.cfg.CallbackTimeout)
	defer cancel()
	return m.hooks.Connect(ctx, event)
}

func (c *connection) writePump() {
	heartbeat := time.NewTicker(c.m.cfg.Heartbeat)
	defer heartbeat.Stop()
	age := time.NewTimer(time.Until(c.info.Expires))
	defer age.Stop()
	for {
		select {
		case msg := <-c.outbound:
			if err := c.write(msg); err != nil {
				_ = c.close(websocket.CloseGoingAway, "write failed")
				return
			}
		case <-heartbeat.C:
			if err := c.ws.WriteControl(websocket.PingMessage, []byte("gregale"), time.Now().Add(c.m.cfg.WriteWait)); err != nil {
				_ = c.close(websocket.CloseGoingAway, "heartbeat failed")
				return
			}
		case <-age.C:
			_ = c.close(websocket.ClosePolicyViolation, "connection lifetime exceeded")
			return
		case <-c.done:
			return
		case <-c.m.ctx.Done():
			return
		}
	}
}

func (c *connection) write(msg Message) error {
	deadline := time.Now().Add(c.m.cfg.WriteWait)
	if err := c.ws.SetWriteDeadline(deadline); err != nil {
		return err
	}
	kind := websocket.TextMessage
	if msg.Binary {
		kind = websocket.BinaryMessage
	}
	return c.ws.WriteMessage(kind, msg.Data)
}

func (m *Manager) removeConnection(ctx context.Context, c *connection) {
	m.mu.Lock()
	if current, ok := m.conns[c.info.ID]; ok && current == c {
		delete(m.conns, c.info.ID)
	}
	m.mu.Unlock()
	c.closeOne.Do(func() {
		close(c.done)
		_ = c.ws.Close()
	})
	c.mu.RLock()
	closeCode, closeReason := c.closeCode, c.closeReason
	c.mu.RUnlock()
	disconnect := Event{
		ID:           "evt_" + strings.ReplaceAll(uuid.NewString(), "-", ""),
		Type:         EventDisconnect,
		EndpointID:   c.info.EndpointID,
		AppID:        c.info.AppID,
		AccountID:    c.info.AccountID,
		ConnectionID: c.info.ID,
		Principal:    c.info.Principal,
		Sequence:     c.sequence.Load(),
		CloseCode:    closeCode,
		CloseReason:  closeReason,
		At:           time.Now().UTC(),
	}
	disconnect.CallbackURL = c.endpoint.CallbackURL
	disconnect.CallbackPath = c.endpoint.DisconnectPath
	disconnect.CallbackAuthToken = c.endpoint.CallbackAuthToken
	ctx, cancel := context.WithTimeout(context.WithoutCancel(ctx), m.cfg.CallbackTimeout)
	defer cancel()
	if err := m.hooks.Disconnect(ctx, disconnect); err != nil {
		m.callbackErrors.Add(1)
	}
}

func (c *connection) close(code int, reason string) error {
	var err error
	c.closeOne.Do(func() {
		c.recordClose(code, reason)
		close(c.done)
		deadline := time.Now().Add(c.m.cfg.WriteWait)
		err = c.ws.WriteControl(websocket.CloseMessage, websocket.FormatCloseMessage(code, reason), deadline)
		closeErr := c.ws.Close()
		if err == nil {
			err = closeErr
		}
	})
	return err
}

func (c *connection) recordClose(code int, reason string) {
	c.mu.Lock()
	if c.closeCode == 0 {
		c.closeCode = code
		c.closeReason = reason
	}
	c.mu.Unlock()
}

// Send queues one bounded message for a live connection.
func (m *Manager) Send(ctx context.Context, connectionID string, msg Message) error {
	c, ok := m.connection(connectionID)
	if !ok {
		return ErrConnectionNotFound
	}
	if int64(len(msg.Data)) > m.cfg.MaxMessageBytes {
		return fmt.Errorf("realtime: message exceeds %d bytes", m.cfg.MaxMessageBytes)
	}
	msg.Data = append([]byte(nil), msg.Data...)
	select {
	case c.outbound <- msg:
		m.sentMessages.Add(1)
		m.sentBytes.Add(uint64(len(msg.Data)))
		return nil
	case <-c.done:
		return ErrConnectionClosed
	case <-ctx.Done():
		return ctx.Err()
	default:
		m.droppedMessages.Add(1)
		return ErrOutboundQueueFull
	}
}

// CloseConnection closes one live socket and emits its disconnect event.
func (m *Manager) CloseConnection(connectionID, reason string) error {
	c, ok := m.connection(connectionID)
	if !ok {
		return ErrConnectionNotFound
	}
	select {
	case <-c.done:
		return ErrConnectionClosed
	default:
	}
	return c.close(websocket.CloseNormalClosure, reason)
}

// Subscribe adds a channel membership to a live connection.
func (m *Manager) Subscribe(connectionID, channel string) error {
	if !validChannel(channel) {
		return ErrInvalidChannel
	}
	c, ok := m.connection(connectionID)
	if !ok {
		return ErrConnectionNotFound
	}
	select {
	case <-c.done:
		return ErrConnectionClosed
	default:
	}
	c.mu.Lock()
	c.channels[channel] = struct{}{}
	c.mu.Unlock()
	return nil
}

// Unsubscribe removes a channel membership from a live connection.
func (m *Manager) Unsubscribe(connectionID, channel string) error {
	if !validChannel(channel) {
		return ErrInvalidChannel
	}
	c, ok := m.connection(connectionID)
	if !ok {
		return ErrConnectionNotFound
	}
	select {
	case <-c.done:
		return ErrConnectionClosed
	default:
	}
	c.mu.Lock()
	delete(c.channels, channel)
	c.mu.Unlock()
	return nil
}

// Publish queues a message to all local connections subscribed to channel on
// endpointID. It returns the number of successfully queued messages; an
// individual slow consumer does not prevent other subscribers from receiving.
func (m *Manager) Publish(ctx context.Context, endpointID, channel string, msg Message) (int, error) {
	if !validChannel(channel) {
		return 0, ErrInvalidChannel
	}
	_, endpointRegistered := m.endpoints.Load(endpointID)
	if int64(len(msg.Data)) > m.cfg.MaxMessageBytes {
		return 0, fmt.Errorf("realtime: message exceeds %d bytes", m.cfg.MaxMessageBytes)
	}
	m.mu.RLock()
	connections := make([]string, 0, len(m.conns))
	endpointHasConnection := false
	for id, c := range m.conns {
		if c.info.EndpointID != endpointID {
			continue
		}
		endpointHasConnection = true
		c.mu.RLock()
		_, subscribed := c.channels[channel]
		c.mu.RUnlock()
		if subscribed {
			connections = append(connections, id)
		}
	}
	m.mu.RUnlock()
	// Removing an endpoint only stops new handshakes; existing sockets retain
	// their endpoint configuration and remain publishable until closed. An
	// unknown endpoint with no live sockets is still reported as not found.
	if !endpointRegistered && !endpointHasConnection {
		return 0, ErrEndpointNotFound
	}
	queued := 0
	for _, id := range connections {
		if err := m.Send(ctx, id, msg); err == nil {
			queued++
		}
	}
	return queued, nil
}

func validChannel(channel string) bool {
	return channel != "" && len(channel) <= maxChannelLength &&
		strings.TrimSpace(channel) == channel && !strings.ContainsAny(channel, "/?#\r\n")
}

// ValidateChannel reports whether channel is valid for endpoint-scoped
// subscriptions and publishes. It is exported so public API handlers can
// reject malformed path values before forwarding them to an owner node.
func ValidateChannel(channel string) bool { return validChannel(channel) }

func (m *Manager) connection(id string) (*connection, bool) {
	m.mu.RLock()
	c, ok := m.conns[id]
	m.mu.RUnlock()
	return c, ok
}

// Snapshot returns a stable copy of the live connection directory.
func (m *Manager) Snapshot() []ConnectionInfo {
	m.mu.RLock()
	defer m.mu.RUnlock()
	result := make([]ConnectionInfo, 0, len(m.conns))
	for _, c := range m.conns {
		c.mu.RLock()
		info := c.info
		if len(c.channels) > 0 {
			info.Channels = make([]string, 0, len(c.channels))
			for channel := range c.channels {
				info.Channels = append(info.Channels, channel)
			}
			sort.Strings(info.Channels)
		}
		result = append(result, info)
		c.mu.RUnlock()
	}
	return result
}

// Stats returns bounded resource and delivery counters for this realtime
// owner. It is safe to call while connections are opening and closing.
func (m *Manager) Stats() Stats {
	if m == nil {
		return Stats{}
	}
	current := m.reserved.Load()
	if current < 0 {
		current = 0
	}
	return Stats{
		CurrentConnections:  uint64(current),
		AcceptedConnections: m.acceptedConnections.Load(),
		RejectedConnections: m.rejectedConnections.Load(),
		ReceivedMessages:    m.receivedMessages.Load(),
		ReceivedBytes:       m.receivedBytes.Load(),
		SentMessages:        m.sentMessages.Load(),
		SentBytes:           m.sentBytes.Load(),
		DroppedMessages:     m.droppedMessages.Load(),
		CallbackErrors:      m.callbackErrors.Load(),
	}
}

// Close stops admission, closes every socket, and cancels callback contexts.
func (m *Manager) Close() error {
	if m == nil || !m.closed.CompareAndSwap(false, true) {
		return nil
	}
	m.cancel()
	m.mu.RLock()
	connections := make([]*connection, 0, len(m.conns))
	for _, c := range m.conns {
		connections = append(connections, c)
	}
	m.mu.RUnlock()
	for _, c := range connections {
		_ = c.close(websocket.CloseGoingAway, "service shutdown")
	}
	return nil
}
