package api

import (
	"context"
	"net/url"
	"time"
)

// Change timeline sources (ADR-741). The set is closed; clients may rely on it.
const (
	ChangeSourceDeployment    = "deployment"
	ChangeSourceEdgeRule      = "edge_rule"
	ChangeSourceRuntimeConfig = "runtime_config"
	ChangeSourceIncident      = "incident"
	ChangeSourceHealth        = "health"
	ChangeSourceActivity      = "activity"
)

// AppChangeTimelineResponse is GET /v1/apps/{slug}/changes (ADR-741): the
// app's recorded changes and health transitions in [Since, Until), newest
// first and capped at ChangeTimelineMaxEvents.
type AppChangeTimelineResponse struct {
	AppID   string           `json:"app_id"`
	AppSlug string           `json:"app_slug"`
	Since   time.Time        `json:"since"`
	Until   time.Time        `json:"until"`
	Events  []AppChangeEvent `json:"events"`
	// Truncated reports that older events in the window were dropped.
	Truncated bool `json:"truncated"`
	// UnavailableSources names sources that could not be read; their events
	// are missing rather than absent.
	UnavailableSources []string `json:"unavailable_sources"`
}

// AppChangeEvent is one timeline entry. Summary is generated by the platform
// and never contains values, credentials, actors, or raw error text.
type AppChangeEvent struct {
	At           time.Time `json:"at"`
	Source       string    `json:"source"`
	Kind         string    `json:"kind"`
	DeploymentID string    `json:"deployment_id,omitempty"`
	Summary      string    `json:"summary"`
}

// GetAppChangeTimeline returns an app's change timeline. Zero times select the
// server defaults (the last ChangeTimelineDefaultWindow, ending now).
func (c *Client) GetAppChangeTimeline(ctx context.Context, slug string, since, until time.Time) (AppChangeTimelineResponse, error) {
	var out AppChangeTimelineResponse
	path := "/v1/apps/" + url.PathEscape(slug) + "/changes"
	q := url.Values{}
	if !since.IsZero() {
		q.Set("since", since.UTC().Format(time.RFC3339))
	}
	if !until.IsZero() {
		q.Set("until", until.UTC().Format(time.RFC3339))
	}
	if len(q) > 0 {
		path += "?" + q.Encode()
	}
	return out, c.do(ctx, "GET", path, nil, &out)
}
