package api

import "time"

const (
	InboundWebhookTokenPrefix           = "gwh_"
	InboundWebhookSigningSecretMaxBytes = 256
	InboundWebhookNameMaxBytes          = 63
	InboundWebhookDeliveryPathMaxBytes  = 256
)

var AllowedInboundWebhookProviders = []string{"stripe"}

// CreateInboundWebhookEndpointRequest configures a public provider endpoint.
// The signing secret is sealed at rest and never returned. The public routing
// token is generated by Gregale and appears only in the create response.
type CreateInboundWebhookEndpointRequest struct {
	Name          string `json:"name"`
	Provider      string `json:"provider"`
	SigningSecret string `json:"signing_secret"`
	DeliveryPath  string `json:"delivery_path,omitempty"`
	Enabled       *bool  `json:"enabled,omitempty"`
}

// UpdateInboundWebhookEndpointRequest is a partial update. A non-nil signing
// secret rotates the provider secret without changing the public endpoint URL.
type UpdateInboundWebhookEndpointRequest struct {
	SigningSecret *string `json:"signing_secret,omitempty"`
	DeliveryPath  *string `json:"delivery_path,omitempty"`
	Enabled       *bool   `json:"enabled,omitempty"`
}

type InboundWebhookEndpointResponse struct {
	ID                  string `json:"id"`
	AppID               string `json:"app_id"`
	AccountID           string `json:"account_id"`
	Name                string `json:"name"`
	Provider            string `json:"provider"`
	DeliveryPath        string `json:"delivery_path"`
	Enabled             bool   `json:"enabled"`
	SigningSecretMasked string `json:"signing_secret_masked"`
	EndpointURL         string `json:"endpoint_url,omitempty"`
	CreatedAt           string `json:"created_at"`
	UpdatedAt           string `json:"updated_at"`
}

type InboundWebhookEndpointRow struct {
	ID           string
	AppID        string
	AccountID    string
	Name         string
	Provider     string
	DeliveryPath string
	Enabled      bool
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

func InboundWebhookEndpointResponseFromRow(row InboundWebhookEndpointRow) InboundWebhookEndpointResponse {
	return InboundWebhookEndpointResponse{
		ID:                  row.ID,
		AppID:               row.AppID,
		AccountID:           row.AccountID,
		Name:                row.Name,
		Provider:            row.Provider,
		DeliveryPath:        row.DeliveryPath,
		Enabled:             row.Enabled,
		SigningSecretMasked: AppWebhookSecretMasked,
		CreatedAt:           row.CreatedAt.UTC().Format(time.RFC3339),
		UpdatedAt:           row.UpdatedAt.UTC().Format(time.RFC3339),
	}
}

// InboundWebhookReceiptResponse is returned only after the request has been
// verified and the durable invocation insert has committed.
type InboundWebhookReceiptResponse struct {
	ReceiptID  string `json:"receipt_id"`
	Status     string `json:"status"`
	Duplicate  bool   `json:"duplicate"`
	AcceptedAt string `json:"accepted_at"`
}
