-- +goose Up
-- +goose StatementBegin

-- Issue #97 / ADR-025 axis 3 (multi-node schedd): split the implicit
-- "single box" assumption into explicit compute_nodes. Schedd becomes
-- the single placement-decision authority across N vmmd hosts (single-
-- leader CP, no consensus). The migration introduces:
--   1. compute_nodes — capacity + target URL + heartbeat liveness
--   2. instances.node_id — FK routing every wake/park to its node
--   3. A synthetic 'default-local' node seeded with the existing
--      single-host budget so the backfill lands with non-null node_id
--      on every pre-existing row.
--
-- Forward-only: the previous migration (00023) dropped snapshots.path;
-- this migration is append-only on instances (add column + backfill +
-- enforce NOT NULL). Down is loud-fail (drops node_id + the table),
-- matching the posture used by 00010/00013 — once shipped, rollback
-- is a procedural operation with operator sign-off, not a routine.

create table if not exists compute_nodes (
    id                   uuid primary key default gen_random_uuid(),
    name                 text not null unique,
    -- wire.ParseTarget-compatible target string. unix:///run/faas/vmmd.sock
    -- for single-box, tcp://host:50051 for distributed (mTLS-secured).
    target_url           text not null check (target_url ~ '^(unix|tcp|dns)://'),
    -- Capacity model mirrors the legacy single-box budget. The CHECKs
    -- here are sanity; the authoritative caps are the api.LimitsFor(plan)
    -- table in pkg/api/limits.go, applied per admission.
    vpcpus               int  not null check (vpcpus > 0),
    mem_mb               int  not null check (mem_mb > 0),
    max_concurrency      int  not null check (max_concurrency > 0),
    -- Per-node RAM admission ceiling. Defaults to the legacy 47,600 MB
    -- for the synthetic node; a future PR lets operators tune per-node.
    -- Schedd's NodeLedger enforces Σ(ram_mb + 8) over live instances on
    -- each node ≤ this value (spec §6.2-2 re-stated per-node).
    admission_ceiling_mb int  not null check (admission_ceiling_mb > 0),
    active               bool not null default true,
    -- Heartbeat liveness. The schedd watchdog pings each node's vmmd
    -- every HeartbeatInterval and stamps this column; a node whose
    -- last_heartbeat_at is older than the staleness threshold (default
    -- 60s, 2× the heartbeat cadence) gets active=false via a future
    -- gate (out of scope for this migration; the column exists so the
    -- gate has somewhere to write).
    last_heartbeat_at    timestamptz not null default now(),
    created_at           timestamptz not null default now()
);

-- Backfill: insert the synthetic 'default-local' node so every pre-
-- existing instance row can be backfilled with a non-null node_id.
-- The id is generated by the column default (gen_random_uuid); the
-- only stable identifier across the migration + Go code is the
-- name 'default-local'. Callers that need the UUID resolve it via
--   select id from compute_nodes where name = 'default-local'
-- and cache the result — schedd's NodeLedger keeps this cached for
-- the daemon lifetime (cmd/schedd/main.go's runHeartbeat reads it
-- once at startup). The Go-side mirror is pkg/state.DefaultLocalNodeName.
--
-- ON CONFLICT (name) DO NOTHING makes the seed idempotent on
-- re-apply: a second INSERT with the same name skips cleanly
-- rather than racing on the unique index.
--
-- target_url defaults to the legacy /run/faas/vmmd.sock socket path.
-- On a single-box install this matches schedd's existing dial target
-- (cfg.VMMDSocket); on a custom install an operator may override via
-- the FAAS_LOCAL_VMMD_TARGET Postgres GUC (rare — README mentions it).
-- For PR #112 the default is the production path; the GUC escape
-- hatch is for testing on dev boxes that relocate the socket.
insert into compute_nodes
    (name, target_url, vpcpus, mem_mb, max_concurrency, admission_ceiling_mb, active)
values (
    'default-local',
    coalesce(
        nullif(current_setting('FAAS_LOCAL_VMMD_TARGET', true), ''),
        'unix:///run/faas/vmmd.sock'
    ),
    -- Legacy vCPU slot ceiling (spec §1: 8× overcommit → 160).
    160,
    56000,
    200,
    47600,
    true
)
on conflict (name) do nothing;

-- Add node_id to instances. Nullable initially so the column-add is
-- cheap (no table rewrite on Postgres ≥11); backfilled below, then the
-- NOT NULL constraint is enforced. IF NOT EXISTS guards against a
-- partial re-apply on a development DB.
alter table instances add column if not exists node_id uuid
    references compute_nodes(id);

-- Backfill every existing instance row to the synthetic default-local
-- node. The UUID is resolved via subquery (not a literal) so the
-- migration doesn't depend on the gen_random_uuid() value the seed
-- happened to produce — re-runs against a fresh DB always land every
-- pre-existing row on the freshly-inserted default-local row.
-- Idempotent: rerunning on an already-backfilled DB is a no-op (the
-- WHERE node_id is null filter makes UPDATE skip populated rows).
-- New rows created after this migration runs always carry node_id
-- (the NOT NULL below + the engine-side Wake flow set it; PR #113
-- lands the Wake flow but the column-level invariant is safe to
-- land first).
update instances
   set node_id = (select id from compute_nodes where name = 'default-local')
 where node_id is null;

-- NOW enforce NOT NULL. Postgres ADD NOT NULL without DEFAULT on a
-- table that already has rows would scan + lock; the UPDATE above has
-- set every row's node_id by the time we get here so the constraint
-- add is metadata-only on a clean re-apply. (Not guarded by IF NOT
-- EXISTS — Postgres has no such clause; the constraint add is the
-- one DDL step that can't be made truly idempotent in this style of
-- migration. The test pins the post-state via information_schema so a
-- future re-apply doesn't drift the assertion.)
alter table instances alter column node_id set not null;

-- Index for the placement lookup (Wake asks "which active node has
-- the most free RAM headroom?"). The WHERE active = true partial
-- predicate keeps stale rows out of the index — once a watchdog gate
-- flips a node to inactive the planner ignores it without a per-query
-- filter. Used by pkg/sched.ChoosePlacement (PR #113) but the index
-- is safe to land now: another partial-by-active index matches the
-- spec invariant that "only active nodes admit instances".
create index if not exists compute_nodes_active_idx
    on compute_nodes (name)
 where active = true;

-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin

-- Reverse-order teardown. The reverse of the Up section is intentional:
-- node_id is dropped before the table so the FK can't dangle. Installed
-- instances will have to be re-backfilled on a re-up via the same
-- sentinel UUID (regenerated by the operator if the synthetic default-
-- local row was deleted manually). Loud-fail per the 00010/00013
-- posture: down-migrations on shipped platforms require a manual runbook.
alter table instances drop column if exists node_id;
drop table if exists compute_nodes;

-- +goose StatementEnd
