-- filename: 00215_reserve_slot.sql
-- +goose Up
-- +goose StatementBegin
-- Reserve slot 215 for PR feat/scale-to-zero-tier1 (ADR-095
-- instances.request_count). The fence buys turn ordering against
-- any cross-PR that lands on the same slot; the real migration is
-- 00216. See cross-pr-slot-fence-pattern for the convention.
-- Slot 215 is the next free on the worktree's HEAD (00214). On
-- rebase, if main has already moved to 00215 or 00216, renumber
-- via `git mv` to max(real_claims) + 1 (precedent commit 13fa0332).
SELECT 1;
-- +goose StatementEnd
