// Generated by gregale data-api types. Do not edit.
// Schema fingerprint: 912a393029b554d6bf97536f04972c925ea41d65ffde337c0d452801326057cb
export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[]
export type Database = {
  "api": {
    Tables: {
      "comments": {
        Row: {
          "id": number
          "subject": string
          "note_id": number | null
          "body": string
        }
        Insert: {
          "id"?: never
          "subject": string
          "note_id"?: number | null
          "body": string
        }
        Update: {
          "id"?: never
          "subject"?: string
          "note_id"?: number | null
          "body"?: string
        }
        Relationships: [{"foreignKeyName":"comments_note_fkey","columns":["subject","note_id"],"isOneToOne":false,"referencedRelation":"notes","referencedColumns":["subject","id"]}]
      }
      "note_create_receipts": {
        Row: {
          "subject": string
          "request_key": string
          "request": Json
          "response": Json
          "created_at": string
        }
        Insert: {
          "subject": string
          "request_key": string
          "request": Json
          "response": Json
          "created_at"?: string
        }
        Update: {
          "subject"?: string
          "request_key"?: string
          "request"?: Json
          "response"?: Json
          "created_at"?: string
        }
        Relationships: []
      }
      "note_details": {
        Row: {
          "subject": string
          "note_id": number
          "summary": string
        }
        Insert: {
          "subject": string
          "note_id": number
          "summary": string
        }
        Update: {
          "subject"?: string
          "note_id"?: number
          "summary"?: string
        }
        Relationships: [{"foreignKeyName":"note_details_note_fkey","columns":["subject","note_id"],"isOneToOne":true,"referencedRelation":"notes","referencedColumns":["subject","id"]}]
      }
      "note_favorite_tags": {
        Row: {
          "subject": string
          "note_id": number
          "tag_id": number
        }
        Insert: {
          "subject": string
          "note_id": number
          "tag_id": number
        }
        Update: {
          "subject"?: string
          "note_id"?: number
          "tag_id"?: number
        }
        Relationships: [{"foreignKeyName":"note_favorite_tags_note_fkey","columns":["subject","note_id"],"isOneToOne":false,"referencedRelation":"notes","referencedColumns":["subject","id"]},{"foreignKeyName":"note_favorite_tags_tag_fkey","columns":["subject","tag_id"],"isOneToOne":false,"referencedRelation":"tags","referencedColumns":["subject","id"]}]
      }
      "note_tags": {
        Row: {
          "subject": string
          "note_id": number
          "tag_id": number
        }
        Insert: {
          "subject": string
          "note_id": number
          "tag_id": number
        }
        Update: {
          "subject"?: string
          "note_id"?: number
          "tag_id"?: number
        }
        Relationships: [{"foreignKeyName":"note_tags_note_fkey","columns":["subject","note_id"],"isOneToOne":false,"referencedRelation":"notes","referencedColumns":["subject","id"]},{"foreignKeyName":"note_tags_tag_fkey","columns":["subject","tag_id"],"isOneToOne":false,"referencedRelation":"tags","referencedColumns":["subject","id"]}]
      }
      "notes": {
        Row: {
          "id": number
          "subject": string
          "body": string
          "created_at": string
          "priority": number
          "version": number
        }
        Insert: {
          "id"?: never
          "subject": string
          "body": string
          "created_at"?: string
          "priority"?: number
          "version"?: number
        }
        Update: {
          "id"?: never
          "subject"?: string
          "body"?: string
          "created_at"?: string
          "priority"?: number
          "version"?: number
        }
        Relationships: []
      }
      "tags": {
        Row: {
          "id": number
          "subject": string
          "name": string
        }
        Insert: {
          "id"?: never
          "subject": string
          "name": string
        }
        Update: {
          "id"?: never
          "subject"?: string
          "name"?: string
        }
        Relationships: []
      }
    }
    Views: {
    }
    Functions: {
      "create_note_with_tags": {
        Args: {
          "note_body": string | null
          "tag_names"?: (string | null)[] | null
        }
        Returns: Database["api"]["Tables"]["notes"]['Row'][]
      }
      "create_note_with_tags_once": {
        Args: {
          "idempotency_key": string | null
          "note_body": string | null
          "tag_names"?: (string | null)[] | null
        }
        Returns: Database["api"]["Tables"]["notes"]['Row'][]
      }
    }
    Enums: {
    }
    CompositeTypes: Record<string, never>
  }
}
