// Generated by gregale data-api types. Do not edit.
// Schema fingerprint: 702c00d615d0b9603bf70d5675a90ae2f5483f0e43119506cf0f5159137d57b8
export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[]
export type Database = {
  "api": {
    Tables: {
      "comments": {
        Row: {
          "id": number
          "subject": string
          "note_id": number | null
          "body": string
        }
        Insert: {
          "id"?: never
          "subject": string
          "note_id"?: number | null
          "body": string
        }
        Update: {
          "id"?: never
          "subject"?: string
          "note_id"?: number | null
          "body"?: string
        }
        Relationships: [{"foreignKeyName":"comments_note_fkey","columns":["subject","note_id"],"isOneToOne":false,"referencedRelation":"notes","referencedColumns":["subject","id"]}]
      }
      "note_details": {
        Row: {
          "subject": string
          "note_id": number
          "summary": string
        }
        Insert: {
          "subject": string
          "note_id": number
          "summary": string
        }
        Update: {
          "subject"?: string
          "note_id"?: number
          "summary"?: string
        }
        Relationships: [{"foreignKeyName":"note_details_note_fkey","columns":["subject","note_id"],"isOneToOne":true,"referencedRelation":"notes","referencedColumns":["subject","id"]}]
      }
      "notes": {
        Row: {
          "id": number
          "subject": string
          "body": string
          "created_at": string
          "priority": number
        }
        Insert: {
          "id"?: never
          "subject": string
          "body": string
          "created_at"?: string
          "priority"?: number
        }
        Update: {
          "id"?: never
          "subject"?: string
          "body"?: string
          "created_at"?: string
          "priority"?: number
        }
        Relationships: []
      }
    }
    Views: {
    }
    Functions: { [_ in never]: never }
    Enums: {
    }
    CompositeTypes: Record<string, never>
  }
}
