#!/usr/bin/env bash
# Replicate an app layer and its attestation, or an immutable runtime base
# and its content/scan evidence, to the
# control-plane storage root before imaged emits snapshot_prime.
#
# This is an explicitly configured split-box fallback for installations that
# still use FAAS_STORAGE_BACKEND=local. OCI-backed installations should leave
# FAAS_ARTIFACT_REPLICATOR unset: the registry is the shared artifact store.
set -euo pipefail

if [[ $# -ne 2 ]]; then
  echo "usage: $0 <layer-key> <signature-key> | --runtime-release <base-key>" >&2
  exit 64
fi

layer_key="$1"
sig_key="$2"
target="${FAAS_ARTIFACT_SYNC_TARGET:?FAAS_ARTIFACT_SYNC_TARGET is required}"
ssh_user="${FAAS_ARTIFACT_SYNC_USER:-root}"
ssh_port="${FAAS_ARTIFACT_SYNC_PORT:-22}"
ssh_key="${FAAS_ARTIFACT_SYNC_SSH_KEY:-}"
apps_root="${FAAS_APPS_ROOT:-/var/lib/faas/apps}"
storage_root="${FAAS_STORAGE_ROOT:-/srv/fc}"
remote_apps_root="${FAAS_ARTIFACT_SYNC_APPS_ROOT:-/var/lib/faas/apps}"
remote_storage_root="${FAAS_ARTIFACT_SYNC_STORAGE_ROOT:-/srv/fc}"
remote_owner="${FAAS_ARTIFACT_SYNC_DEST_USER:-faas-schedd}"
remote_group="${FAAS_ARTIFACT_SYNC_DEST_GROUP:-faas}"

ssh_args=(
  -o BatchMode=yes
  -o StrictHostKeyChecking=accept-new
  -o ConnectTimeout=20
  -p "$ssh_port"
)
if [[ -n "$ssh_key" ]]; then
  ssh_args+=( -i "$ssh_key" )
fi
remote="$ssh_user@$target"
rsync_args=(
  -a
  --partial
  --delay-updates
  --protect-args
  -e "ssh ${ssh_args[*]}"
)

if [[ "$layer_key" == "--runtime-release" ]]; then
  base_key="$sig_key"
  if [[ ! "$base_key" =~ ^base/releases/runner-(node22|node24|python312|python313|go124|go124-alpine)-(amd64|arm64)-[a-f0-9]{64}\.ext4$ ]]; then
    echo "invalid immutable runtime base key: $base_key" >&2
    exit 65
  fi
  runtime_keys=( "$base_key" "$base_key.content" "scans/${base_key#base/}.scan.json" )
  # Check every required object before starting any transfer. A failed
  # handoff cannot publish the artifact binding or trigger snapshot_prime.
  for artifact_key in "${runtime_keys[@]}"; do
    src="$storage_root/$artifact_key"
    if [[ ! -f "$src" || -L "$src" ]]; then
      echo "runtime artifact not found or not a regular file: $src" >&2
      exit 66
    fi
  done
  for artifact_key in "${runtime_keys[@]}"; do
    src="$storage_root/$artifact_key"
    dst="$remote_storage_root/$artifact_key"
    ssh "${ssh_args[@]}" "$remote" \
      "install -d -o \"$remote_owner\" -g \"$remote_group\" -m 0750 -- \"$(dirname "$dst")\""
    rsync "${rsync_args[@]}" -- "$src" "$remote:$dst"
    ssh "${ssh_args[@]}" "$remote" \
      "chown \"$remote_owner:$remote_group\" -- \"$dst\" && chmod 0640 -- \"$dst\""
  done
  exit 0
fi

# The keys are generated by sched.AppLayerKey / cosign.SigKeyFor. Rejecting
# anything outside that shape keeps the helper safe even if it is invoked
# manually by an operator.
if [[ ! "$layer_key" =~ ^apps/[a-z0-9][a-z0-9-]*/[0-9a-f-]+\.ext4$ ]]; then
  echo "invalid layer key: $layer_key" >&2
  exit 65
fi
if [[ ! "$sig_key" =~ ^sigs/apps/[a-z0-9][a-z0-9-]*/[0-9a-f-]+\.ext4\.sig$ ]]; then
  echo "invalid signature key: $sig_key" >&2
  exit 65
fi

layer_rel="${layer_key#apps/}"
sig_rel="${sig_key#sigs/}"
layer_src="$apps_root/$layer_rel"
sig_src="$storage_root/sigs/$sig_rel"
layer_dst="$remote_apps_root/$layer_rel"
sig_dst="$remote_storage_root/sigs/$sig_rel"

if [[ ! -f "$layer_src" ]]; then
  echo "layer not found: $layer_src" >&2
  exit 66
fi
if [[ ! -f "$sig_src" ]]; then
  echo "signature not found: $sig_src" >&2
  exit 66
fi

ssh "${ssh_args[@]}" "$remote" \
  "install -d -o \"$remote_owner\" -g \"$remote_group\" -m 0750 -- \"$(dirname "$layer_dst")\" \"$(dirname "$sig_dst")\""

rsync "${rsync_args[@]}" -- "$layer_src" "$remote:$layer_dst"
rsync "${rsync_args[@]}" -- "$sig_src" "$remote:$sig_dst"
ssh "${ssh_args[@]}" "$remote" \
  "chown \"$remote_owner:$remote_group\" -- \"$layer_dst\" \"$sig_dst\" && chmod 0640 -- \"$layer_dst\" \"$sig_dst\""
