// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AdvanceQualificationMarker(ctx context.Context, db DBTX, id pgtype.UUID) (int64, error)
	IsDisposableQualificationCatalog(ctx context.Context, db DBTX, expectedSetting string) (bool, error)
	ReadQualificationMarker(ctx context.Context, db DBTX, id pgtype.UUID) (ReadQualificationMarkerRow, error)
	SeedQualificationMarker(ctx context.Context, db DBTX, arg SeedQualificationMarkerParams) error
}

var _ Querier = (*Queries)(nil)
