// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type GregaleCopyDatabaseMaintenanceWindow struct {
	SourceOid            pgtype.Uint32
	TargetOid            pgtype.Uint32
	OwnerID              pgtype.UUID
	PlanFingerprint      string
	PreparationCreatedAt pgtype.Timestamptz
	State                string
	OpenedAt             pgtype.Timestamptz
	ClosedAt             pgtype.Timestamptz
}

type GregaleCopyDatabaseVerificationRetriesWindow struct {
	SourceOid            pgtype.Uint32
	TargetOid            pgtype.Uint32
	OwnerID              pgtype.UUID
	PlanFingerprint      string
	PreparationCreatedAt pgtype.Timestamptz
	State                string
	OpenedAt             pgtype.Timestamptz
	ClosedAt             pgtype.Timestamptz
	ImportOwnerID        pgtype.UUID
	ImportOpenedAt       pgtype.Timestamptz
	ImportClosedAt       pgtype.Timestamptz
	Attempt              int32
	PreviousOwnerID      pgtype.UUID
	PreviousOpenedAt     pgtype.Timestamptz
	PreviousClosedAt     pgtype.Timestamptz
}

type GregaleCopyDatabaseVerificationWindow struct {
	SourceOid            pgtype.Uint32
	TargetOid            pgtype.Uint32
	OwnerID              pgtype.UUID
	PlanFingerprint      string
	PreparationCreatedAt pgtype.Timestamptz
	State                string
	OpenedAt             pgtype.Timestamptz
	ClosedAt             pgtype.Timestamptz
	ImportOwnerID        pgtype.UUID
	ImportOpenedAt       pgtype.Timestamptz
	ImportClosedAt       pgtype.Timestamptz
}

type GregaleCopyDatabasesDatabase struct {
	SourceOid pgtype.Uint32
	TargetOid pgtype.Uint32
	State     string
	ClaimedAt pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
}

type GregaleCopyDatabasesPlan struct {
	Singleton bool
	Version   int32
	Body      []byte
}
