// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	ClaimCopyDatabase(ctx context.Context, db DBTX, dollar_1 pgtype.Uint32) (int64, error)
	CompleteCopyDatabase(ctx context.Context, db DBTX, dollar_1 pgtype.Uint32) (int64, error)
	CopyDatabasePlanBody(ctx context.Context, db DBTX) ([]byte, error)
	CopyDatabaseReceipts(ctx context.Context, db DBTX) ([]GregaleCopyDatabasesDatabase, error)
	CopyDatabaseSchemaExists(ctx context.Context, db DBTX) (bool, error)
	// CREATE DATABASE must execute at top level. This SQLC query is the only
	// statement generator; identifiers/literals are quoted by PostgreSQL format.
	// Parameters come exclusively from the validated immutable plan, pending claim
	// and pinned actor/tablespace identities. Go transmits the returned command whole.
	// Inheriting template0's pinned tablespace needs no extra CREATE grant; explicitly
	// naming even that same tablespace would impose an additional ACL precondition.
	FormatCopyDatabaseCreate(ctx context.Context, db DBTX, arg FormatCopyDatabaseCreateParams) (string, error)
	InsertCopyDatabasePlanBody(ctx context.Context, db DBTX, dollar_1 []byte) error
	InstallCopyDatabasePlan(ctx context.Context, db DBTX) error
	InstallCopyDatabaseReceipts(ctx context.Context, db DBTX) error
	InstallCopyDatabaseSchema(ctx context.Context, db DBTX) error
	// Session ownership covers the top-level nontransactional CREATE DATABASE.
	// Use the same lock key as role/membership materialization to protect seed OIDs.
	LockCopyDatabases(ctx context.Context, db DBTX) error
	PrivateCopyDatabaseJournal(ctx context.Context, db DBTX) (bool, error)
	ReserveCopyDatabase(ctx context.Context, db DBTX, arg ReserveCopyDatabaseParams) error
	UnlockCopyDatabases(ctx context.Context, db DBTX) (bool, error)
}

var _ Querier = (*Queries)(nil)
