// vmmd — the only root component, owns firecracker+jailer (spec §4.4, ADR-013,
// ADR-014, ADR-016). All five RPCs map 1:1 to spec §4.4 line 138. Wire shape
// stays narrow: the caller resolves `(app)` into AppSpec; vmmd never queries
// apid or postgres on its own.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// source: onebox/faas/vmmd/v1/vmmd.proto

package vmmdpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Vmmd_CreateFromSnapshot_FullMethodName      = "/onebox.faas.vmmd.v1.Vmmd/CreateFromSnapshot"
	Vmmd_CreateColdBoot_FullMethodName          = "/onebox.faas.vmmd.v1.Vmmd/CreateColdBoot"
	Vmmd_PauseAndSnapshot_FullMethodName        = "/onebox.faas.vmmd.v1.Vmmd/PauseAndSnapshot"
	Vmmd_WarmSnapshot_FullMethodName            = "/onebox.faas.vmmd.v1.Vmmd/WarmSnapshot"
	Vmmd_FrameworkReady_FullMethodName          = "/onebox.faas.vmmd.v1.Vmmd/FrameworkReady"
	Vmmd_Destroy_FullMethodName                 = "/onebox.faas.vmmd.v1.Vmmd/Destroy"
	Vmmd_StopInstance_FullMethodName            = "/onebox.faas.vmmd.v1.Vmmd/StopInstance"
	Vmmd_Stats_FullMethodName                   = "/onebox.faas.vmmd.v1.Vmmd/Stats"
	Vmmd_Ping_FullMethodName                    = "/onebox.faas.vmmd.v1.Vmmd/Ping"
	Vmmd_Heartbeat_FullMethodName               = "/onebox.faas.vmmd.v1.Vmmd/Heartbeat"
	Vmmd_UpdateEgressAllowlist_FullMethodName   = "/onebox.faas.vmmd.v1.Vmmd/UpdateEgressAllowlist"
	Vmmd_UpdateStaticEgressIP_FullMethodName    = "/onebox.faas.vmmd.v1.Vmmd/UpdateStaticEgressIP"
	Vmmd_SeccompStatus_FullMethodName           = "/onebox.faas.vmmd.v1.Vmmd/SeccompStatus"
	Vmmd_Logs_FullMethodName                    = "/onebox.faas.vmmd.v1.Vmmd/Logs"
	Vmmd_ForwardHTTPStream_FullMethodName       = "/onebox.faas.vmmd.v1.Vmmd/ForwardHTTPStream"
	Vmmd_ForwardRawStream_FullMethodName        = "/onebox.faas.vmmd.v1.Vmmd/ForwardRawStream"
	Vmmd_MountParentExt4ReadOnly_FullMethodName = "/onebox.faas.vmmd.v1.Vmmd/MountParentExt4ReadOnly"
	Vmmd_MaterializeParentExt4_FullMethodName   = "/onebox.faas.vmmd.v1.Vmmd/MaterializeParentExt4"
	Vmmd_UmountParentExt4_FullMethodName        = "/onebox.faas.vmmd.v1.Vmmd/UmountParentExt4"
	Vmmd_MountOverlayParent_FullMethodName      = "/onebox.faas.vmmd.v1.Vmmd/MountOverlayParent"
	Vmmd_UmountOverlayParent_FullMethodName     = "/onebox.faas.vmmd.v1.Vmmd/UmountOverlayParent"
	Vmmd_PrepareLiveMigration_FullMethodName    = "/onebox.faas.vmmd.v1.Vmmd/PrepareLiveMigration"
	Vmmd_AdoptMigratedInstance_FullMethodName   = "/onebox.faas.vmmd.v1.Vmmd/AdoptMigratedInstance"
	Vmmd_AcknowledgeMigration_FullMethodName    = "/onebox.faas.vmmd.v1.Vmmd/AcknowledgeMigration"
	Vmmd_CancelLiveMigration_FullMethodName     = "/onebox.faas.vmmd.v1.Vmmd/CancelLiveMigration"
)

// VmmdClient is the client API for Vmmd service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Vmmd is the gRPC service vmmd exposes on its unix socket. The Unix-socket
// auth model (mode 0660 group `faas`, ADR-015) is the only authentication
// story for v1.0 — Gate-A multi-host replaces it with mTLS.
type VmmdClient interface {
	// CreateFromSnapshot wakes an instance by restoring a previously-parked
	// snapshot. Falls back to cold boot if the snapshot is stale, missing, or
	// fails to load (ADR-005: cold boot always works).
	CreateFromSnapshot(ctx context.Context, in *CreateFromSnapshotRequest, opts ...grpc.CallOption) (*WakeResponse, error)
	// CreateColdBoot primes an instance with no snapshot — the deploy-pipeline
	// first-boot path (M2). Equivalent to Wake with Snapshot == nil.
	CreateColdBoot(ctx context.Context, in *CreateColdBootRequest, opts ...grpc.CallOption) (*WakeResponse, error)
	// PauseAndSnapshot pauses the VM and writes a full snapshot to the
	// requested host-side paths, then destroys the live VM. After return the
	// instance is gone (§6.1: PARKED is zero-RAM).
	PauseAndSnapshot(ctx context.Context, in *PauseAndSnapshotRequest, opts ...grpc.CallOption) (*SnapshotResponse, error)
	// WarmSnapshot (issue #470 / PR #470-FU-A) is the warm-tier
	// capture path. The caller is the schedd engine's
	// captureWarmSnapshotLocked, fired from Engine.Park while the
	// instance is still RUNNING on this vmmd (the runner is alive
	// and can keep serving requests across the pause window). The
	// handler:
	//  1. PATCH /vm {"state":"Paused"} (Firecracker pause).
	//  2. PUT /snapshot/create with the warm-tier storage keys
	//     (mem_file_path, snapshot_path) supplied by the caller.
	//  3. Publish both blobs through the configured StorageBackend
	//     (mem at storage_key, vmstate at vmstate_storage_key).
	//  4. PATCH /vm {"state":"Resumed"} — the VM resumes in place
	//     and the live Instance entries (Manager.m.live, cidToID)
	//     stay intact. The post-resume guest-init entropy re-seed
	//     is intentionally NOT triggered here: the warm snapshot
	//     captured an already-randomised state, and the next
	//     wake restores from a fresh snapshot that owns its own
	//     seeds; firing the hook here would inject duplicate
	//     entropy into a running guest and burn CPU on a no-op.
	//  5. Return the snapshot byte counts (matches
	//     PauseAndSnapshotResponse shape).
	//
	// The RPC is idempotent on a no-op pause? no — a re-fire of
	// WarmSnapshot on a VM that already produced a warm row would
	// create a second row at the same storage key (overwrite path
	// is storage-backend-defined). The engine gates each Park on
	// `framework_ready_at` and inserts the warm row inside the
	// appMu window so duplicate parks are not scheduled; the wire
	// does not need to enforce this.
	//
	// Error mapping: pause / snapshot / resume failures bubble up
	// as Internal with the firecracker side's status / message. The
	// engine's failure path is "Destroy the VM and skip the init
	// capture" — see pkg/sched/engine.go::captureWarmSnapshotLocked.
	WarmSnapshot(ctx context.Context, in *WarmSnapshotRequest, opts ...grpc.CallOption) (*SnapshotResponse, error)
	// FrameworkReady is the vmmd-side receipt of the guest-init
	// "framework ready" vsock DGRAM (port 1027, msg=4) signal
	// (issue #470, PR #470-FU-B). vmmd's host-side DGRAM listener
	// (cmd/vmmd/manager.go) calls this with the instance id and the
	// optional warmup_ms payload; the handler stamps the per-instance
	// `framework_ready_at` column added by migration 00112 so the
	// engine's captureWarmSnapshot (PR #470-FU-A) can decide when
	// the warm-tier PauseAndSnapshot is allowed to run. The RPC is
	// idempotent — re-stamps on every subsequent signal (the engine
	// resets the column to NULL at the start of each warm-capture
	// cycle so a stale stamp doesn't leak across cycles). No
	// back-pressure: the DGRAM transport is fire-and-forget by
	// analogy with the stateless-advisory port 1025 path; a missed
	// DGRAM means the engine's warm-capture wait times out and
	// falls through to init-tier (correctness-preserving).
	FrameworkReady(ctx context.Context, in *FrameworkReadyRequest, opts ...grpc.CallOption) (*FrameworkReadyResponse, error)
	// Destroy tears down a running instance. Idempotent on unknown instances.
	Destroy(ctx context.Context, in *DestroyRequest, opts ...grpc.CallOption) (*DestroyResponse, error)
	// StopInstance is the M-2 / ADR-138 graceful stop sequence: send
	// `signal` to the guest's PID 1, wait up to `grace_period_s`
	// seconds for it to exit cleanly, then SIGKILL on deadline.
	// Wired to `JailerVMM.SignalAndKill` (pkg/fcvm/vmm.go).
	//
	// Distinct from Destroy (which is a hard SIGKILL today) — the two
	// RPCs coexist. schedd.Engine.StopInstance (commit 6) dispatches
	// per Instance.ExecutionMode: worker/job use StopInstance;
	// request/service use the existing snapshotAndPark/Destroy path.
	// The signal value is a standard POSIX signal number (e.g. SIGTERM=15,
	// SIGUSR1=10, SIGHUP=1); 0 means "use the manifest's StopSignal,
	// defaulting to SIGTERM". grace_period_s is the upper bound on
	// clean-shutdown wait; 0 means "no grace, immediate SIGKILL" which
	// is the legacy Destroy shape — a future commit may deprecate it.
	StopInstance(ctx context.Context, in *StopInstanceRequest, opts ...grpc.CallOption) (*StopInstanceResponse, error)
	// Stats returns current liveness + allocator views. Used by schedd's
	// admission ledger (M4) and by Prometheus for the `vmmd_ops_total` /
	// `vmmd_op_duration_seconds` dashboards (ADR-016).
	Stats(ctx context.Context, in *StatsRequest, opts ...grpc.CallOption) (*StatsResponse, error)
	// Ping is a wire-only liveness probe (issue #97 / ADR-025 axis 3,
	// PR #114). Returns the vmmd process's Firecracker version + the
	// server-side timestamp at the moment the handler ran; schedd's
	// heartbeat loop calls this on every active compute_node every
	// HeartbeatInterval (default 30s). A successful round-trip proves
	// both that the gRPC socket is reachable and that vmmd's
	// goroutine scheduler is responsive enough to schedule this
	// handler — the two facts schedd needs to keep last_heartbeat_at
	// fresh. Idempotent + side-effect free; no backing Manager call.
	Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error)
	// Heartbeat lets schedd ping vmmd over the overlay. The reverse
	// direction (vmmd-pushes) was rejected because schedd is the
	// admission authority and shouldn't trust inbound traffic from a
	// box it may have already drained. Empty request, empty response:
	// success is "did it return Unavailable" and the timestamp comes
	// from the caller. See pkg/overlay.DialContext and schedd's
	// heartbeat goroutine (issue #98).
	Heartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error)
	// UpdateEgressAllowlist (ADR-031 + ADR-033, tier-2 PR-B) lets
	// schedd push a fresh per-app egress allowlist into every live
	// netns the vmmd owns without tearing the netns down. The
	// caller passes app_id + the new allowlist (already v4/v6
	// partitioned upstream; the wire is a single repeated string
	// matching the AppSpec.egress_allowlist field 7). vmmd walks
	// its live-instance map and applies the new nft rule in-place
	// via `nft -a list chain` + handle delete + insert at the same
	// offset, reverting to the prior argv snapshot on any error.
	// This is the closure of "live-instance drift" (ADR-033 §Context
	// "the next bigger item"). Idempotent: an empty allowlist
	// flips the chain policy back to accept, a re-pushed identical
	// allowlist is a no-op. Non-blocking on success; the caller
	// uses pg_notify as the delivery mechanism (cmd/schedd egress
	// drift subscriber, pkg/sched/egress_drift.go).
	UpdateEgressAllowlist(ctx context.Context, in *UpdateEgressAllowlistRequest, opts ...grpc.CallOption) (*UpdateEgressAllowlistAck, error)
	// UpdateStaticEgressIP (ADR-119) lets schedd push a fresh
	// per-app static egress IP into every live netns the vmmd
	// owns without tearing the netns down. The caller passes
	// app_id + the new IPv4 (already validated upstream; the
	// DB family=4 CHECK prevents IPv6 from reaching here).
	// Empty ip = clear the pin (mirrors the DELETE wire shape).
	// vmmd walks its live-instance map and applies the new
	// MASQUERADE-sibling rule in-place via the per-netns
	// nftables re-render path (same posture as
	// UpdateEgressAllowlist's handle-delete + insert). The
	// delivery mechanism is pg_notify → schedd's egress_drift
	// subscriber (pkg/sched/egress_drift.go). Idempotent: a
	// re-pushed identical IP is a no-op. Plan-gated upstream by
	// pkg/api/limits.go::Plan.StaticEgressIPAllowed.
	UpdateStaticEgressIP(ctx context.Context, in *UpdateStaticEgressIPRequest, opts ...grpc.CallOption) (*UpdateStaticEgressIPAck, error)
	// SeccompStatus (M8 §11 — jailer seccomp assertion) reports the
	// Linux kernel seccomp state of the jailer child process backing
	// this instance. Spec §11: "Firecracker's default seccomp filter
	// is in place" — jailer is the only parent of the firecracker
	// process, and jailer applies the seccomp filter via
	// --seccomp-filter=<path>. The handler reads /proc/<pid>/status
	// outside the vmmd process and reports the Seccomp: line (0 =
	// disabled, 1 = strict, 2 = filter) plus the filter instruction
	// count when in filter mode. Empty Instance returns InvalidArgument.
	// The presence of a freshly-installed filter (filter_len > 0) is
	// the e2e tripwire: a jailer upgrade that drops the filter is
	// caught here before the snapshot can be considered trustworthy.
	// Not in the hot path — Invoke is from the cmd/e2e seccomp gate
	// and from Prometheus scrapes keyed on the new
	// firecracker_seccomp_status metric.
	SeccompStatus(ctx context.Context, in *SeccompStatusRequest, opts ...grpc.CallOption) (*SeccompStatusResponse, error)
	// Logs (issue #254 / Move 4) streams the per-instance stdout/stderr
	// ring buffer to the caller. Server-streaming: each LogsResponse is
	// one completed line (newline-fragmented by the producer). Frames
	// arrive in seq-ascending order; the buffer retains the last 10 MiB
	// per instance and drops the oldest line on overflow.
	// Backpressure flows through gRPC's natural flow control. NotFound
	// when the instance is not alive on this vmmd (nil ring).
	Logs(ctx context.Context, in *LogsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[LogsResponse], error)
	// ForwardHTTPStream is the rpc declaration; the docstring above
	// the service block (above Ping) describes the protocol and the
	// PR-D state. The repetition kept the comments shipped without
	// surgery on the surrounding service-doc layout.
	ForwardHTTPStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ForwardHTTPStreamRequest, ForwardHTTPStreamResponse], error)
	// ForwardRawStream (issue #676 / ADR-080) is the raw-bytes bridge
	// for Upgrade (WebSocket / h2c / MQTT-over-WS / long-poll) traffic.
	// The legacy ForwardHTTPStream strips Upgrade + Connection as
	// hop-by-hop headers and the shell-script bridge hard-codes
	// Transfer-Encoding: chunked + a Host rewrite — both destroy the
	// raw bytes an Upgrade handshake needs. ForwardRawStream carries
	// the customer's verbatim HTTP request bytes (status line + headers
	// + body) into the guest's netns TCP socket and reads back the
	// raw response — no HTTP parsing, no chunked framing, no header
	// rewriting. The gateway detects Upgrade requests and routes them
	// here; plain HTTP / SSE / chunked stays on ForwardHTTPStream.
	// Wire shape:
	//
	//	client → server: 1× ForwardRawRequestInit (instance, port, max
	//	  request bytes), then N× body_chunk bytes that the bridge
	//	  writes verbatim to the guest TCP socket. Half-close = EOF.
	//	server → client: 1× ForwardRawResponseInit (status + headers
	//	  + error message), then N× body_chunk bytes that the bridge
	//	  read off the guest TCP socket. Server half-closes when the
	//	  guest closes the connection.
	//
	// The bridge that owns the guest TCP socket is the new
	// vmmd-raw-bridge Go binary (cmd/vmmd-raw-bridge/), spawned by
	// vmmd under the stream context. Errors map to Unavailable (guest
	// dial refused), NotFound (unknown instance), InvalidArgument
	// (missing init), Internal (nsenter / bridge crash). The legacy
	// ForwardHTTPStream is unaffected.
	ForwardRawStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ForwardRawRequest, ForwardRawResponse], error)
	// MountParentExt4ReadOnly (ADR-053) is the staging-only path that
	// lets imaged compose the per-runtime base ext4 from a shared
	// debian:12-slim parent. imaged is not root (User=faas-imaged +
	// NoNewPrivileges=yes per spec §11), so it cannot mount the parent
	// ext4 itself; vmmd is the only root component and runs the
	// `mount -o loop,ro,nodev,nosuid,noexec` on imaged's behalf. The
	// returned mountpoint is an absolute host path under
	// /srv/fc/parent/faas-parent-mnt-<id>/ — shared between vmmd and
	// imaged because BOTH daemons carry systemd `PrivateTmp=yes`
	// (deploy/systemd/faas-{vmmd,imaged}.service) and vmmd's /tmp is
	// its own tmpfs, invisible to imaged's mount namespace. The caller
	// (imaged) §4.6-honours the contract by `mkfs.ext4 -d <mountpoint>`
	// directly through the read-only loopback mount — no `cp -a`, no
	// separate staging tree — and immediately calls UmountParentExt4.
	// The mount is read-only so a child re-stage cannot corrupt the
	// parent; vmmd tracks the mount in an in-memory registry and
	// sweeps orphans every ParentMountMaxAge (default 30 min) + at
	// SIGTERM. Storage_key is the canonical StorageBackend key
	// (issue #96 / ADR-025 axis 2), e.g.
	// "base/runner-base-debian-parent-amd64.ext4". Storage_key MUST be
	// in the parent-base allow-list (sched.IsParentBaseKey — host arch
	// + sibling for heterogenous clusters); anything else is rejected
	// with InvalidArgument. Empty storage_key → InvalidArgument.
	// Unknown storage_key (Get returns ErrNotFound) → NotFound. vmmd
	// writes the bytes through its own configured StorageBackend —
	// there is no precedent for imaged→vmmd dialing; CLAUDE.md is
	// amended (ADR-053) to call this out as a deliberate exception to
	// "components talk via Postgres rows + pg_notify, or gRPC on unix
	// sockets in /run/faas/".
	MountParentExt4ReadOnly(ctx context.Context, in *MountParentExt4ReadOnlyRequest, opts ...grpc.CallOption) (*MountParentExt4ReadOnlyResponse, error)
	// MaterializeParentExt4 (ADR-053) copies the read-only parent ext4 tree
	// into a shared staging directory and releases the temporary loopback
	// mount before returning.  The copy is deliberately performed by vmmd:
	// mount visibility is scoped to vmmd's service namespace, while imaged
	// must consume ordinary files from its own namespace.  target_dir MUST
	// live under /dev/shm/faas-base-staging/ and storage_key MUST be the
	// canonical parent-base key.  Empty/foreign paths are InvalidArgument and
	// a missing storage key is NotFound.
	MaterializeParentExt4(ctx context.Context, in *MaterializeParentExt4Request, opts ...grpc.CallOption) (*MaterializeParentExt4Response, error)
	// UmountParentExt4 (ADR-053) releases a mount vmmd previously
	// returned from MountParentExt4ReadOnly. Idempotent on an
	// unknown mountpoint — imaged's call-on-error-defer pattern
	// (mkfs.ext4 errored → umount anyway) is safe. The mountpoint
	// path is validated to live under /srv/fc/parent/faas-parent-mnt-*
	// (vmmdmount.MountRoot) to refuse unmounting an unrelated
	// filesystem (defence in depth against a caller that hands back
	// a path vmmd never issued).
	UmountParentExt4(ctx context.Context, in *UmountParentExt4Request, opts ...grpc.CallOption) (*UmountParentExt4Response, error)
	// MountOverlayParent (DEPLOY-1, ADR-075) is the staging-only path
	// that lets imaged compose the per-runtime base ext4 from a
	// shared parent via overlayfs. The lowerdir is the parent ext4
	// mountpoint vmmd issued at MountParentExt4ReadOnly (read-only,
	// already mounted by vmmd); upperdir + workdir + merged are
	// absolute host paths staged under /dev/shm/faas-base-staging/
	// (tmpfs, kernel tmpfile-permitted). vmmd is the only root
	// component (spec §11) and runs the direct mount(2) syscall on
	// imaged's behalf. imaged (User=faas-imaged + NoNewPrivileges=yes)
	// cannot mount — see capdecl policy in pkg/capdecl and the
	// depguard rule in .golangci.yml that forbids unix.Mount outside
	// pkg/vmmd/. Returns the merged path on success; the caller
	// (imaged) applies its delta OCI layers to the upperdir via
	// rootfs.ApplyLayerGz, then BuildBaseFromStaging(merged) for
	// mkfs + storage. The merged path is registered in
	// vmmdmount.Registry so SIGTERM/30-min orphan sweep can release
	// it. Validation chain:
	//  1. Any empty path → InvalidArgument.
	//  2. lowerdir MUST live under /srv/fc/parent/faas-parent-mnt-*
	//     (vmmdmount.MountRoot) — refuse overlay-mounting an
	//     unrelated read-only path (defence in depth).
	//  3. upperdir/workdir MUST live under
	//     /dev/shm/faas-base-staging/ — refuse overlay-mounting on
	//     ext4 (the regression that broke every cd-controlplane
	//     deploy 2026-08-04 → 2026-08-05; kernel rejects ext4 upper
	//     with "overlayfs: upper fs does not support tmpfile").
	//  4. mount(2) EROFS/EBUSY/ENOSPC/ENOMEM → Internal with the
	//     syscall error wrapped — imaged's logs surface the cause.
	MountOverlayParent(ctx context.Context, in *MountOverlayParentRequest, opts ...grpc.CallOption) (*MountOverlayParentResponse, error)
	// UmountOverlayParent (DEPLOY-1, ADR-075) releases an overlay
	// mount vmmd previously returned from MountOverlayParent.
	// Idempotent on an unknown mountpoint — imaged's
	// defer-after-error pattern (mkfs errored → umount anyway) is
	// safe. The merged path is validated to live under
	// /dev/shm/faas-base-staging/faas-base-*/merged (the staging
	// root the parent-ref path uses) to refuse unmounting an
	// unrelated filesystem.
	UmountOverlayParent(ctx context.Context, in *UmountOverlayParentRequest, opts ...grpc.CallOption) (*UmountOverlayParentResponse, error)
	// PrepareLiveMigration (Tier A5 / ADR-065) is Phase 1 of the
	// four-phase cross-node live-instance handoff. Called by the
	// new owner vmmd's schedd against the DYING vmmd: pauses the
	// running VM, writes a fresh snapshot to the canonical storage
	// backend (so the new owner can pull it over the wire), and
	// returns the snapshot storage keys + a lease_token the new
	// owner carries through Phase 3. The dying vmmd keeps the VM
	// paused but resident; if Phase 3 doesn't commit within
	// MigrateLiveLeaseSeconds (pkg/api/limits.go), the dying vmmd
	// resumes the VM (Phase 4 cancel).
	PrepareLiveMigration(ctx context.Context, in *PrepareLiveMigrationRequest, opts ...grpc.CallOption) (*PrepareLiveMigrationResponse, error)
	// AdoptMigratedInstance (Tier A5 / ADR-065) is Phase 2 of the
	// four-phase handoff. Called by the new owner vmmd's schedd
	// against the NEW owner vmmd: restores the snapshot the dying
	// vmmd wrote at Phase 1, brings the VM up, and returns the new
	// instance's HostIP + GuestUID so schedd can carry them
	// through to the conditional UPDATE at Phase 3.
	AdoptMigratedInstance(ctx context.Context, in *AdoptMigratedInstanceRequest, opts ...grpc.CallOption) (*AdoptMigratedInstanceResponse, error)
	// AcknowledgeMigration (Tier A5 / ADR-065) is Phase 3.5 of
	// the four-phase handoff. Called by the new owner vmmd's
	// schedd against the DYING vmmd AFTER the conditional UPDATE
	// commits at Phase 3: tells the dying vmmd it can safely
	// destroy the paused VM and free its netns/jail. The dying
	// vmmd does not block on this — the conditional UPDATE has
	// already moved the row — but a missing AcknowledgeMigration
	// leaves a paused VM resident on the dying node (an
	// observation metric, not a correctness issue).
	AcknowledgeMigration(ctx context.Context, in *AcknowledgeMigrationRequest, opts ...grpc.CallOption) (*AcknowledgeMigrationResponse, error)
	// CancelLiveMigration (Tier A5 / ADR-065) is Phase 4 of the
	// four-phase handoff. Called by the new owner vmmd's schedd
	// against the DYING vmmd when Phase 3 fails (peer rollback,
	// lease expiry, peer re-owner). The dying vmmd resumes the
	// paused VM and returns it to RUNNING; the snapshot stays
	// where it was (the dying vmmd's drive1 + mem are intact).
	CancelLiveMigration(ctx context.Context, in *CancelLiveMigrationRequest, opts ...grpc.CallOption) (*CancelLiveMigrationResponse, error)
}

type vmmdClient struct {
	cc grpc.ClientConnInterface
}

func NewVmmdClient(cc grpc.ClientConnInterface) VmmdClient {
	return &vmmdClient{cc}
}

func (c *vmmdClient) CreateFromSnapshot(ctx context.Context, in *CreateFromSnapshotRequest, opts ...grpc.CallOption) (*WakeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WakeResponse)
	err := c.cc.Invoke(ctx, Vmmd_CreateFromSnapshot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vmmdClient) CreateColdBoot(ctx context.Context, in *CreateColdBootRequest, opts ...grpc.CallOption) (*WakeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WakeResponse)
	err := c.cc.Invoke(ctx, Vmmd_CreateColdBoot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vmmdClient) PauseAndSnapshot(ctx context.Context, in *PauseAndSnapshotRequest, opts ...grpc.CallOption) (*SnapshotResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SnapshotResponse)
	err := c.cc.Invoke(ctx, Vmmd_PauseAndSnapshot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vmmdClient) WarmSnapshot(ctx context.Context, in *WarmSnapshotRequest, opts ...grpc.CallOption) (*SnapshotResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SnapshotResponse)
	err := c.cc.Invoke(ctx, Vmmd_WarmSnapshot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vmmdClient) FrameworkReady(ctx context.Context, in *FrameworkReadyRequest, opts ...grpc.CallOption) (*FrameworkReadyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FrameworkReadyResponse)
	err := c.cc.Invoke(ctx, Vmmd_FrameworkReady_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vmmdClient) Destroy(ctx context.Context, in *DestroyRequest, opts ...grpc.CallOption) (*DestroyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DestroyResponse)
	err := c.cc.Invoke(ctx, Vmmd_Destroy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vmmdClient) StopInstance(ctx context.Context, in *StopInstanceRequest, opts ...grpc.CallOption) (*StopInstanceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StopInstanceResponse)
	err := c.cc.Invoke(ctx, Vmmd_StopInstance_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vmmdClient) Stats(ctx context.Context, in *StatsRequest, opts ...grpc.CallOption) (*StatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatsResponse)
	err := c.cc.Invoke(ctx, Vmmd_Stats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vmmdClient) Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PingResponse)
	err := c.cc.Invoke(ctx, Vmmd_Ping_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vmmdClient) Heartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HeartbeatResponse)
	err := c.cc.Invoke(ctx, Vmmd_Heartbeat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vmmdClient) UpdateEgressAllowlist(ctx context.Context, in *UpdateEgressAllowlistRequest, opts ...grpc.CallOption) (*UpdateEgressAllowlistAck, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateEgressAllowlistAck)
	err := c.cc.Invoke(ctx, Vmmd_UpdateEgressAllowlist_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vmmdClient) UpdateStaticEgressIP(ctx context.Context, in *UpdateStaticEgressIPRequest, opts ...grpc.CallOption) (*UpdateStaticEgressIPAck, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateStaticEgressIPAck)
	err := c.cc.Invoke(ctx, Vmmd_UpdateStaticEgressIP_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vmmdClient) SeccompStatus(ctx context.Context, in *SeccompStatusRequest, opts ...grpc.CallOption) (*SeccompStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SeccompStatusResponse)
	err := c.cc.Invoke(ctx, Vmmd_SeccompStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vmmdClient) Logs(ctx context.Context, in *LogsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[LogsResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Vmmd_ServiceDesc.Streams[0], Vmmd_Logs_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[LogsRequest, LogsResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Vmmd_LogsClient = grpc.ServerStreamingClient[LogsResponse]

func (c *vmmdClient) ForwardHTTPStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ForwardHTTPStreamRequest, ForwardHTTPStreamResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Vmmd_ServiceDesc.Streams[1], Vmmd_ForwardHTTPStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ForwardHTTPStreamRequest, ForwardHTTPStreamResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Vmmd_ForwardHTTPStreamClient = grpc.BidiStreamingClient[ForwardHTTPStreamRequest, ForwardHTTPStreamResponse]

func (c *vmmdClient) ForwardRawStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ForwardRawRequest, ForwardRawResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Vmmd_ServiceDesc.Streams[2], Vmmd_ForwardRawStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ForwardRawRequest, ForwardRawResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Vmmd_ForwardRawStreamClient = grpc.BidiStreamingClient[ForwardRawRequest, ForwardRawResponse]

func (c *vmmdClient) MountParentExt4ReadOnly(ctx context.Context, in *MountParentExt4ReadOnlyRequest, opts ...grpc.CallOption) (*MountParentExt4ReadOnlyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MountParentExt4ReadOnlyResponse)
	err := c.cc.Invoke(ctx, Vmmd_MountParentExt4ReadOnly_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vmmdClient) MaterializeParentExt4(ctx context.Context, in *MaterializeParentExt4Request, opts ...grpc.CallOption) (*MaterializeParentExt4Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MaterializeParentExt4Response)
	err := c.cc.Invoke(ctx, Vmmd_MaterializeParentExt4_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vmmdClient) UmountParentExt4(ctx context.Context, in *UmountParentExt4Request, opts ...grpc.CallOption) (*UmountParentExt4Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UmountParentExt4Response)
	err := c.cc.Invoke(ctx, Vmmd_UmountParentExt4_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vmmdClient) MountOverlayParent(ctx context.Context, in *MountOverlayParentRequest, opts ...grpc.CallOption) (*MountOverlayParentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MountOverlayParentResponse)
	err := c.cc.Invoke(ctx, Vmmd_MountOverlayParent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vmmdClient) UmountOverlayParent(ctx context.Context, in *UmountOverlayParentRequest, opts ...grpc.CallOption) (*UmountOverlayParentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UmountOverlayParentResponse)
	err := c.cc.Invoke(ctx, Vmmd_UmountOverlayParent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vmmdClient) PrepareLiveMigration(ctx context.Context, in *PrepareLiveMigrationRequest, opts ...grpc.CallOption) (*PrepareLiveMigrationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PrepareLiveMigrationResponse)
	err := c.cc.Invoke(ctx, Vmmd_PrepareLiveMigration_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vmmdClient) AdoptMigratedInstance(ctx context.Context, in *AdoptMigratedInstanceRequest, opts ...grpc.CallOption) (*AdoptMigratedInstanceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AdoptMigratedInstanceResponse)
	err := c.cc.Invoke(ctx, Vmmd_AdoptMigratedInstance_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vmmdClient) AcknowledgeMigration(ctx context.Context, in *AcknowledgeMigrationRequest, opts ...grpc.CallOption) (*AcknowledgeMigrationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AcknowledgeMigrationResponse)
	err := c.cc.Invoke(ctx, Vmmd_AcknowledgeMigration_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vmmdClient) CancelLiveMigration(ctx context.Context, in *CancelLiveMigrationRequest, opts ...grpc.CallOption) (*CancelLiveMigrationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CancelLiveMigrationResponse)
	err := c.cc.Invoke(ctx, Vmmd_CancelLiveMigration_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VmmdServer is the server API for Vmmd service.
// All implementations must embed UnimplementedVmmdServer
// for forward compatibility.
//
// Vmmd is the gRPC service vmmd exposes on its unix socket. The Unix-socket
// auth model (mode 0660 group `faas`, ADR-015) is the only authentication
// story for v1.0 — Gate-A multi-host replaces it with mTLS.
type VmmdServer interface {
	// CreateFromSnapshot wakes an instance by restoring a previously-parked
	// snapshot. Falls back to cold boot if the snapshot is stale, missing, or
	// fails to load (ADR-005: cold boot always works).
	CreateFromSnapshot(context.Context, *CreateFromSnapshotRequest) (*WakeResponse, error)
	// CreateColdBoot primes an instance with no snapshot — the deploy-pipeline
	// first-boot path (M2). Equivalent to Wake with Snapshot == nil.
	CreateColdBoot(context.Context, *CreateColdBootRequest) (*WakeResponse, error)
	// PauseAndSnapshot pauses the VM and writes a full snapshot to the
	// requested host-side paths, then destroys the live VM. After return the
	// instance is gone (§6.1: PARKED is zero-RAM).
	PauseAndSnapshot(context.Context, *PauseAndSnapshotRequest) (*SnapshotResponse, error)
	// WarmSnapshot (issue #470 / PR #470-FU-A) is the warm-tier
	// capture path. The caller is the schedd engine's
	// captureWarmSnapshotLocked, fired from Engine.Park while the
	// instance is still RUNNING on this vmmd (the runner is alive
	// and can keep serving requests across the pause window). The
	// handler:
	//  1. PATCH /vm {"state":"Paused"} (Firecracker pause).
	//  2. PUT /snapshot/create with the warm-tier storage keys
	//     (mem_file_path, snapshot_path) supplied by the caller.
	//  3. Publish both blobs through the configured StorageBackend
	//     (mem at storage_key, vmstate at vmstate_storage_key).
	//  4. PATCH /vm {"state":"Resumed"} — the VM resumes in place
	//     and the live Instance entries (Manager.m.live, cidToID)
	//     stay intact. The post-resume guest-init entropy re-seed
	//     is intentionally NOT triggered here: the warm snapshot
	//     captured an already-randomised state, and the next
	//     wake restores from a fresh snapshot that owns its own
	//     seeds; firing the hook here would inject duplicate
	//     entropy into a running guest and burn CPU on a no-op.
	//  5. Return the snapshot byte counts (matches
	//     PauseAndSnapshotResponse shape).
	//
	// The RPC is idempotent on a no-op pause? no — a re-fire of
	// WarmSnapshot on a VM that already produced a warm row would
	// create a second row at the same storage key (overwrite path
	// is storage-backend-defined). The engine gates each Park on
	// `framework_ready_at` and inserts the warm row inside the
	// appMu window so duplicate parks are not scheduled; the wire
	// does not need to enforce this.
	//
	// Error mapping: pause / snapshot / resume failures bubble up
	// as Internal with the firecracker side's status / message. The
	// engine's failure path is "Destroy the VM and skip the init
	// capture" — see pkg/sched/engine.go::captureWarmSnapshotLocked.
	WarmSnapshot(context.Context, *WarmSnapshotRequest) (*SnapshotResponse, error)
	// FrameworkReady is the vmmd-side receipt of the guest-init
	// "framework ready" vsock DGRAM (port 1027, msg=4) signal
	// (issue #470, PR #470-FU-B). vmmd's host-side DGRAM listener
	// (cmd/vmmd/manager.go) calls this with the instance id and the
	// optional warmup_ms payload; the handler stamps the per-instance
	// `framework_ready_at` column added by migration 00112 so the
	// engine's captureWarmSnapshot (PR #470-FU-A) can decide when
	// the warm-tier PauseAndSnapshot is allowed to run. The RPC is
	// idempotent — re-stamps on every subsequent signal (the engine
	// resets the column to NULL at the start of each warm-capture
	// cycle so a stale stamp doesn't leak across cycles). No
	// back-pressure: the DGRAM transport is fire-and-forget by
	// analogy with the stateless-advisory port 1025 path; a missed
	// DGRAM means the engine's warm-capture wait times out and
	// falls through to init-tier (correctness-preserving).
	FrameworkReady(context.Context, *FrameworkReadyRequest) (*FrameworkReadyResponse, error)
	// Destroy tears down a running instance. Idempotent on unknown instances.
	Destroy(context.Context, *DestroyRequest) (*DestroyResponse, error)
	// StopInstance is the M-2 / ADR-138 graceful stop sequence: send
	// `signal` to the guest's PID 1, wait up to `grace_period_s`
	// seconds for it to exit cleanly, then SIGKILL on deadline.
	// Wired to `JailerVMM.SignalAndKill` (pkg/fcvm/vmm.go).
	//
	// Distinct from Destroy (which is a hard SIGKILL today) — the two
	// RPCs coexist. schedd.Engine.StopInstance (commit 6) dispatches
	// per Instance.ExecutionMode: worker/job use StopInstance;
	// request/service use the existing snapshotAndPark/Destroy path.
	// The signal value is a standard POSIX signal number (e.g. SIGTERM=15,
	// SIGUSR1=10, SIGHUP=1); 0 means "use the manifest's StopSignal,
	// defaulting to SIGTERM". grace_period_s is the upper bound on
	// clean-shutdown wait; 0 means "no grace, immediate SIGKILL" which
	// is the legacy Destroy shape — a future commit may deprecate it.
	StopInstance(context.Context, *StopInstanceRequest) (*StopInstanceResponse, error)
	// Stats returns current liveness + allocator views. Used by schedd's
	// admission ledger (M4) and by Prometheus for the `vmmd_ops_total` /
	// `vmmd_op_duration_seconds` dashboards (ADR-016).
	Stats(context.Context, *StatsRequest) (*StatsResponse, error)
	// Ping is a wire-only liveness probe (issue #97 / ADR-025 axis 3,
	// PR #114). Returns the vmmd process's Firecracker version + the
	// server-side timestamp at the moment the handler ran; schedd's
	// heartbeat loop calls this on every active compute_node every
	// HeartbeatInterval (default 30s). A successful round-trip proves
	// both that the gRPC socket is reachable and that vmmd's
	// goroutine scheduler is responsive enough to schedule this
	// handler — the two facts schedd needs to keep last_heartbeat_at
	// fresh. Idempotent + side-effect free; no backing Manager call.
	Ping(context.Context, *PingRequest) (*PingResponse, error)
	// Heartbeat lets schedd ping vmmd over the overlay. The reverse
	// direction (vmmd-pushes) was rejected because schedd is the
	// admission authority and shouldn't trust inbound traffic from a
	// box it may have already drained. Empty request, empty response:
	// success is "did it return Unavailable" and the timestamp comes
	// from the caller. See pkg/overlay.DialContext and schedd's
	// heartbeat goroutine (issue #98).
	Heartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error)
	// UpdateEgressAllowlist (ADR-031 + ADR-033, tier-2 PR-B) lets
	// schedd push a fresh per-app egress allowlist into every live
	// netns the vmmd owns without tearing the netns down. The
	// caller passes app_id + the new allowlist (already v4/v6
	// partitioned upstream; the wire is a single repeated string
	// matching the AppSpec.egress_allowlist field 7). vmmd walks
	// its live-instance map and applies the new nft rule in-place
	// via `nft -a list chain` + handle delete + insert at the same
	// offset, reverting to the prior argv snapshot on any error.
	// This is the closure of "live-instance drift" (ADR-033 §Context
	// "the next bigger item"). Idempotent: an empty allowlist
	// flips the chain policy back to accept, a re-pushed identical
	// allowlist is a no-op. Non-blocking on success; the caller
	// uses pg_notify as the delivery mechanism (cmd/schedd egress
	// drift subscriber, pkg/sched/egress_drift.go).
	UpdateEgressAllowlist(context.Context, *UpdateEgressAllowlistRequest) (*UpdateEgressAllowlistAck, error)
	// UpdateStaticEgressIP (ADR-119) lets schedd push a fresh
	// per-app static egress IP into every live netns the vmmd
	// owns without tearing the netns down. The caller passes
	// app_id + the new IPv4 (already validated upstream; the
	// DB family=4 CHECK prevents IPv6 from reaching here).
	// Empty ip = clear the pin (mirrors the DELETE wire shape).
	// vmmd walks its live-instance map and applies the new
	// MASQUERADE-sibling rule in-place via the per-netns
	// nftables re-render path (same posture as
	// UpdateEgressAllowlist's handle-delete + insert). The
	// delivery mechanism is pg_notify → schedd's egress_drift
	// subscriber (pkg/sched/egress_drift.go). Idempotent: a
	// re-pushed identical IP is a no-op. Plan-gated upstream by
	// pkg/api/limits.go::Plan.StaticEgressIPAllowed.
	UpdateStaticEgressIP(context.Context, *UpdateStaticEgressIPRequest) (*UpdateStaticEgressIPAck, error)
	// SeccompStatus (M8 §11 — jailer seccomp assertion) reports the
	// Linux kernel seccomp state of the jailer child process backing
	// this instance. Spec §11: "Firecracker's default seccomp filter
	// is in place" — jailer is the only parent of the firecracker
	// process, and jailer applies the seccomp filter via
	// --seccomp-filter=<path>. The handler reads /proc/<pid>/status
	// outside the vmmd process and reports the Seccomp: line (0 =
	// disabled, 1 = strict, 2 = filter) plus the filter instruction
	// count when in filter mode. Empty Instance returns InvalidArgument.
	// The presence of a freshly-installed filter (filter_len > 0) is
	// the e2e tripwire: a jailer upgrade that drops the filter is
	// caught here before the snapshot can be considered trustworthy.
	// Not in the hot path — Invoke is from the cmd/e2e seccomp gate
	// and from Prometheus scrapes keyed on the new
	// firecracker_seccomp_status metric.
	SeccompStatus(context.Context, *SeccompStatusRequest) (*SeccompStatusResponse, error)
	// Logs (issue #254 / Move 4) streams the per-instance stdout/stderr
	// ring buffer to the caller. Server-streaming: each LogsResponse is
	// one completed line (newline-fragmented by the producer). Frames
	// arrive in seq-ascending order; the buffer retains the last 10 MiB
	// per instance and drops the oldest line on overflow.
	// Backpressure flows through gRPC's natural flow control. NotFound
	// when the instance is not alive on this vmmd (nil ring).
	Logs(*LogsRequest, grpc.ServerStreamingServer[LogsResponse]) error
	// ForwardHTTPStream is the rpc declaration; the docstring above
	// the service block (above Ping) describes the protocol and the
	// PR-D state. The repetition kept the comments shipped without
	// surgery on the surrounding service-doc layout.
	ForwardHTTPStream(grpc.BidiStreamingServer[ForwardHTTPStreamRequest, ForwardHTTPStreamResponse]) error
	// ForwardRawStream (issue #676 / ADR-080) is the raw-bytes bridge
	// for Upgrade (WebSocket / h2c / MQTT-over-WS / long-poll) traffic.
	// The legacy ForwardHTTPStream strips Upgrade + Connection as
	// hop-by-hop headers and the shell-script bridge hard-codes
	// Transfer-Encoding: chunked + a Host rewrite — both destroy the
	// raw bytes an Upgrade handshake needs. ForwardRawStream carries
	// the customer's verbatim HTTP request bytes (status line + headers
	// + body) into the guest's netns TCP socket and reads back the
	// raw response — no HTTP parsing, no chunked framing, no header
	// rewriting. The gateway detects Upgrade requests and routes them
	// here; plain HTTP / SSE / chunked stays on ForwardHTTPStream.
	// Wire shape:
	//
	//	client → server: 1× ForwardRawRequestInit (instance, port, max
	//	  request bytes), then N× body_chunk bytes that the bridge
	//	  writes verbatim to the guest TCP socket. Half-close = EOF.
	//	server → client: 1× ForwardRawResponseInit (status + headers
	//	  + error message), then N× body_chunk bytes that the bridge
	//	  read off the guest TCP socket. Server half-closes when the
	//	  guest closes the connection.
	//
	// The bridge that owns the guest TCP socket is the new
	// vmmd-raw-bridge Go binary (cmd/vmmd-raw-bridge/), spawned by
	// vmmd under the stream context. Errors map to Unavailable (guest
	// dial refused), NotFound (unknown instance), InvalidArgument
	// (missing init), Internal (nsenter / bridge crash). The legacy
	// ForwardHTTPStream is unaffected.
	ForwardRawStream(grpc.BidiStreamingServer[ForwardRawRequest, ForwardRawResponse]) error
	// MountParentExt4ReadOnly (ADR-053) is the staging-only path that
	// lets imaged compose the per-runtime base ext4 from a shared
	// debian:12-slim parent. imaged is not root (User=faas-imaged +
	// NoNewPrivileges=yes per spec §11), so it cannot mount the parent
	// ext4 itself; vmmd is the only root component and runs the
	// `mount -o loop,ro,nodev,nosuid,noexec` on imaged's behalf. The
	// returned mountpoint is an absolute host path under
	// /srv/fc/parent/faas-parent-mnt-<id>/ — shared between vmmd and
	// imaged because BOTH daemons carry systemd `PrivateTmp=yes`
	// (deploy/systemd/faas-{vmmd,imaged}.service) and vmmd's /tmp is
	// its own tmpfs, invisible to imaged's mount namespace. The caller
	// (imaged) §4.6-honours the contract by `mkfs.ext4 -d <mountpoint>`
	// directly through the read-only loopback mount — no `cp -a`, no
	// separate staging tree — and immediately calls UmountParentExt4.
	// The mount is read-only so a child re-stage cannot corrupt the
	// parent; vmmd tracks the mount in an in-memory registry and
	// sweeps orphans every ParentMountMaxAge (default 30 min) + at
	// SIGTERM. Storage_key is the canonical StorageBackend key
	// (issue #96 / ADR-025 axis 2), e.g.
	// "base/runner-base-debian-parent-amd64.ext4". Storage_key MUST be
	// in the parent-base allow-list (sched.IsParentBaseKey — host arch
	// + sibling for heterogenous clusters); anything else is rejected
	// with InvalidArgument. Empty storage_key → InvalidArgument.
	// Unknown storage_key (Get returns ErrNotFound) → NotFound. vmmd
	// writes the bytes through its own configured StorageBackend —
	// there is no precedent for imaged→vmmd dialing; CLAUDE.md is
	// amended (ADR-053) to call this out as a deliberate exception to
	// "components talk via Postgres rows + pg_notify, or gRPC on unix
	// sockets in /run/faas/".
	MountParentExt4ReadOnly(context.Context, *MountParentExt4ReadOnlyRequest) (*MountParentExt4ReadOnlyResponse, error)
	// MaterializeParentExt4 (ADR-053) copies the read-only parent ext4 tree
	// into a shared staging directory and releases the temporary loopback
	// mount before returning.  The copy is deliberately performed by vmmd:
	// mount visibility is scoped to vmmd's service namespace, while imaged
	// must consume ordinary files from its own namespace.  target_dir MUST
	// live under /dev/shm/faas-base-staging/ and storage_key MUST be the
	// canonical parent-base key.  Empty/foreign paths are InvalidArgument and
	// a missing storage key is NotFound.
	MaterializeParentExt4(context.Context, *MaterializeParentExt4Request) (*MaterializeParentExt4Response, error)
	// UmountParentExt4 (ADR-053) releases a mount vmmd previously
	// returned from MountParentExt4ReadOnly. Idempotent on an
	// unknown mountpoint — imaged's call-on-error-defer pattern
	// (mkfs.ext4 errored → umount anyway) is safe. The mountpoint
	// path is validated to live under /srv/fc/parent/faas-parent-mnt-*
	// (vmmdmount.MountRoot) to refuse unmounting an unrelated
	// filesystem (defence in depth against a caller that hands back
	// a path vmmd never issued).
	UmountParentExt4(context.Context, *UmountParentExt4Request) (*UmountParentExt4Response, error)
	// MountOverlayParent (DEPLOY-1, ADR-075) is the staging-only path
	// that lets imaged compose the per-runtime base ext4 from a
	// shared parent via overlayfs. The lowerdir is the parent ext4
	// mountpoint vmmd issued at MountParentExt4ReadOnly (read-only,
	// already mounted by vmmd); upperdir + workdir + merged are
	// absolute host paths staged under /dev/shm/faas-base-staging/
	// (tmpfs, kernel tmpfile-permitted). vmmd is the only root
	// component (spec §11) and runs the direct mount(2) syscall on
	// imaged's behalf. imaged (User=faas-imaged + NoNewPrivileges=yes)
	// cannot mount — see capdecl policy in pkg/capdecl and the
	// depguard rule in .golangci.yml that forbids unix.Mount outside
	// pkg/vmmd/. Returns the merged path on success; the caller
	// (imaged) applies its delta OCI layers to the upperdir via
	// rootfs.ApplyLayerGz, then BuildBaseFromStaging(merged) for
	// mkfs + storage. The merged path is registered in
	// vmmdmount.Registry so SIGTERM/30-min orphan sweep can release
	// it. Validation chain:
	//  1. Any empty path → InvalidArgument.
	//  2. lowerdir MUST live under /srv/fc/parent/faas-parent-mnt-*
	//     (vmmdmount.MountRoot) — refuse overlay-mounting an
	//     unrelated read-only path (defence in depth).
	//  3. upperdir/workdir MUST live under
	//     /dev/shm/faas-base-staging/ — refuse overlay-mounting on
	//     ext4 (the regression that broke every cd-controlplane
	//     deploy 2026-08-04 → 2026-08-05; kernel rejects ext4 upper
	//     with "overlayfs: upper fs does not support tmpfile").
	//  4. mount(2) EROFS/EBUSY/ENOSPC/ENOMEM → Internal with the
	//     syscall error wrapped — imaged's logs surface the cause.
	MountOverlayParent(context.Context, *MountOverlayParentRequest) (*MountOverlayParentResponse, error)
	// UmountOverlayParent (DEPLOY-1, ADR-075) releases an overlay
	// mount vmmd previously returned from MountOverlayParent.
	// Idempotent on an unknown mountpoint — imaged's
	// defer-after-error pattern (mkfs errored → umount anyway) is
	// safe. The merged path is validated to live under
	// /dev/shm/faas-base-staging/faas-base-*/merged (the staging
	// root the parent-ref path uses) to refuse unmounting an
	// unrelated filesystem.
	UmountOverlayParent(context.Context, *UmountOverlayParentRequest) (*UmountOverlayParentResponse, error)
	// PrepareLiveMigration (Tier A5 / ADR-065) is Phase 1 of the
	// four-phase cross-node live-instance handoff. Called by the
	// new owner vmmd's schedd against the DYING vmmd: pauses the
	// running VM, writes a fresh snapshot to the canonical storage
	// backend (so the new owner can pull it over the wire), and
	// returns the snapshot storage keys + a lease_token the new
	// owner carries through Phase 3. The dying vmmd keeps the VM
	// paused but resident; if Phase 3 doesn't commit within
	// MigrateLiveLeaseSeconds (pkg/api/limits.go), the dying vmmd
	// resumes the VM (Phase 4 cancel).
	PrepareLiveMigration(context.Context, *PrepareLiveMigrationRequest) (*PrepareLiveMigrationResponse, error)
	// AdoptMigratedInstance (Tier A5 / ADR-065) is Phase 2 of the
	// four-phase handoff. Called by the new owner vmmd's schedd
	// against the NEW owner vmmd: restores the snapshot the dying
	// vmmd wrote at Phase 1, brings the VM up, and returns the new
	// instance's HostIP + GuestUID so schedd can carry them
	// through to the conditional UPDATE at Phase 3.
	AdoptMigratedInstance(context.Context, *AdoptMigratedInstanceRequest) (*AdoptMigratedInstanceResponse, error)
	// AcknowledgeMigration (Tier A5 / ADR-065) is Phase 3.5 of
	// the four-phase handoff. Called by the new owner vmmd's
	// schedd against the DYING vmmd AFTER the conditional UPDATE
	// commits at Phase 3: tells the dying vmmd it can safely
	// destroy the paused VM and free its netns/jail. The dying
	// vmmd does not block on this — the conditional UPDATE has
	// already moved the row — but a missing AcknowledgeMigration
	// leaves a paused VM resident on the dying node (an
	// observation metric, not a correctness issue).
	AcknowledgeMigration(context.Context, *AcknowledgeMigrationRequest) (*AcknowledgeMigrationResponse, error)
	// CancelLiveMigration (Tier A5 / ADR-065) is Phase 4 of the
	// four-phase handoff. Called by the new owner vmmd's schedd
	// against the DYING vmmd when Phase 3 fails (peer rollback,
	// lease expiry, peer re-owner). The dying vmmd resumes the
	// paused VM and returns it to RUNNING; the snapshot stays
	// where it was (the dying vmmd's drive1 + mem are intact).
	CancelLiveMigration(context.Context, *CancelLiveMigrationRequest) (*CancelLiveMigrationResponse, error)
	mustEmbedUnimplementedVmmdServer()
}

// UnimplementedVmmdServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedVmmdServer struct{}

func (UnimplementedVmmdServer) CreateFromSnapshot(context.Context, *CreateFromSnapshotRequest) (*WakeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateFromSnapshot not implemented")
}
func (UnimplementedVmmdServer) CreateColdBoot(context.Context, *CreateColdBootRequest) (*WakeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateColdBoot not implemented")
}
func (UnimplementedVmmdServer) PauseAndSnapshot(context.Context, *PauseAndSnapshotRequest) (*SnapshotResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PauseAndSnapshot not implemented")
}
func (UnimplementedVmmdServer) WarmSnapshot(context.Context, *WarmSnapshotRequest) (*SnapshotResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method WarmSnapshot not implemented")
}
func (UnimplementedVmmdServer) FrameworkReady(context.Context, *FrameworkReadyRequest) (*FrameworkReadyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method FrameworkReady not implemented")
}
func (UnimplementedVmmdServer) Destroy(context.Context, *DestroyRequest) (*DestroyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Destroy not implemented")
}
func (UnimplementedVmmdServer) StopInstance(context.Context, *StopInstanceRequest) (*StopInstanceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StopInstance not implemented")
}
func (UnimplementedVmmdServer) Stats(context.Context, *StatsRequest) (*StatsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Stats not implemented")
}
func (UnimplementedVmmdServer) Ping(context.Context, *PingRequest) (*PingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedVmmdServer) Heartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Heartbeat not implemented")
}
func (UnimplementedVmmdServer) UpdateEgressAllowlist(context.Context, *UpdateEgressAllowlistRequest) (*UpdateEgressAllowlistAck, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateEgressAllowlist not implemented")
}
func (UnimplementedVmmdServer) UpdateStaticEgressIP(context.Context, *UpdateStaticEgressIPRequest) (*UpdateStaticEgressIPAck, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateStaticEgressIP not implemented")
}
func (UnimplementedVmmdServer) SeccompStatus(context.Context, *SeccompStatusRequest) (*SeccompStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SeccompStatus not implemented")
}
func (UnimplementedVmmdServer) Logs(*LogsRequest, grpc.ServerStreamingServer[LogsResponse]) error {
	return status.Error(codes.Unimplemented, "method Logs not implemented")
}
func (UnimplementedVmmdServer) ForwardHTTPStream(grpc.BidiStreamingServer[ForwardHTTPStreamRequest, ForwardHTTPStreamResponse]) error {
	return status.Error(codes.Unimplemented, "method ForwardHTTPStream not implemented")
}
func (UnimplementedVmmdServer) ForwardRawStream(grpc.BidiStreamingServer[ForwardRawRequest, ForwardRawResponse]) error {
	return status.Error(codes.Unimplemented, "method ForwardRawStream not implemented")
}
func (UnimplementedVmmdServer) MountParentExt4ReadOnly(context.Context, *MountParentExt4ReadOnlyRequest) (*MountParentExt4ReadOnlyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method MountParentExt4ReadOnly not implemented")
}
func (UnimplementedVmmdServer) MaterializeParentExt4(context.Context, *MaterializeParentExt4Request) (*MaterializeParentExt4Response, error) {
	return nil, status.Error(codes.Unimplemented, "method MaterializeParentExt4 not implemented")
}
func (UnimplementedVmmdServer) UmountParentExt4(context.Context, *UmountParentExt4Request) (*UmountParentExt4Response, error) {
	return nil, status.Error(codes.Unimplemented, "method UmountParentExt4 not implemented")
}
func (UnimplementedVmmdServer) MountOverlayParent(context.Context, *MountOverlayParentRequest) (*MountOverlayParentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method MountOverlayParent not implemented")
}
func (UnimplementedVmmdServer) UmountOverlayParent(context.Context, *UmountOverlayParentRequest) (*UmountOverlayParentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UmountOverlayParent not implemented")
}
func (UnimplementedVmmdServer) PrepareLiveMigration(context.Context, *PrepareLiveMigrationRequest) (*PrepareLiveMigrationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PrepareLiveMigration not implemented")
}
func (UnimplementedVmmdServer) AdoptMigratedInstance(context.Context, *AdoptMigratedInstanceRequest) (*AdoptMigratedInstanceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AdoptMigratedInstance not implemented")
}
func (UnimplementedVmmdServer) AcknowledgeMigration(context.Context, *AcknowledgeMigrationRequest) (*AcknowledgeMigrationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AcknowledgeMigration not implemented")
}
func (UnimplementedVmmdServer) CancelLiveMigration(context.Context, *CancelLiveMigrationRequest) (*CancelLiveMigrationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CancelLiveMigration not implemented")
}
func (UnimplementedVmmdServer) mustEmbedUnimplementedVmmdServer() {}
func (UnimplementedVmmdServer) testEmbeddedByValue()              {}

// UnsafeVmmdServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to VmmdServer will
// result in compilation errors.
type UnsafeVmmdServer interface {
	mustEmbedUnimplementedVmmdServer()
}

func RegisterVmmdServer(s grpc.ServiceRegistrar, srv VmmdServer) {
	// If the following call panics, it indicates UnimplementedVmmdServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Vmmd_ServiceDesc, srv)
}

func _Vmmd_CreateFromSnapshot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateFromSnapshotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VmmdServer).CreateFromSnapshot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Vmmd_CreateFromSnapshot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VmmdServer).CreateFromSnapshot(ctx, req.(*CreateFromSnapshotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Vmmd_CreateColdBoot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateColdBootRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VmmdServer).CreateColdBoot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Vmmd_CreateColdBoot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VmmdServer).CreateColdBoot(ctx, req.(*CreateColdBootRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Vmmd_PauseAndSnapshot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PauseAndSnapshotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VmmdServer).PauseAndSnapshot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Vmmd_PauseAndSnapshot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VmmdServer).PauseAndSnapshot(ctx, req.(*PauseAndSnapshotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Vmmd_WarmSnapshot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WarmSnapshotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VmmdServer).WarmSnapshot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Vmmd_WarmSnapshot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VmmdServer).WarmSnapshot(ctx, req.(*WarmSnapshotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Vmmd_FrameworkReady_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FrameworkReadyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VmmdServer).FrameworkReady(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Vmmd_FrameworkReady_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VmmdServer).FrameworkReady(ctx, req.(*FrameworkReadyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Vmmd_Destroy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DestroyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VmmdServer).Destroy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Vmmd_Destroy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VmmdServer).Destroy(ctx, req.(*DestroyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Vmmd_StopInstance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StopInstanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VmmdServer).StopInstance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Vmmd_StopInstance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VmmdServer).StopInstance(ctx, req.(*StopInstanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Vmmd_Stats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VmmdServer).Stats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Vmmd_Stats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VmmdServer).Stats(ctx, req.(*StatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Vmmd_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VmmdServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Vmmd_Ping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VmmdServer).Ping(ctx, req.(*PingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Vmmd_Heartbeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HeartbeatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VmmdServer).Heartbeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Vmmd_Heartbeat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VmmdServer).Heartbeat(ctx, req.(*HeartbeatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Vmmd_UpdateEgressAllowlist_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateEgressAllowlistRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VmmdServer).UpdateEgressAllowlist(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Vmmd_UpdateEgressAllowlist_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VmmdServer).UpdateEgressAllowlist(ctx, req.(*UpdateEgressAllowlistRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Vmmd_UpdateStaticEgressIP_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateStaticEgressIPRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VmmdServer).UpdateStaticEgressIP(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Vmmd_UpdateStaticEgressIP_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VmmdServer).UpdateStaticEgressIP(ctx, req.(*UpdateStaticEgressIPRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Vmmd_SeccompStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SeccompStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VmmdServer).SeccompStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Vmmd_SeccompStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VmmdServer).SeccompStatus(ctx, req.(*SeccompStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Vmmd_Logs_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(LogsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(VmmdServer).Logs(m, &grpc.GenericServerStream[LogsRequest, LogsResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Vmmd_LogsServer = grpc.ServerStreamingServer[LogsResponse]

func _Vmmd_ForwardHTTPStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(VmmdServer).ForwardHTTPStream(&grpc.GenericServerStream[ForwardHTTPStreamRequest, ForwardHTTPStreamResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Vmmd_ForwardHTTPStreamServer = grpc.BidiStreamingServer[ForwardHTTPStreamRequest, ForwardHTTPStreamResponse]

func _Vmmd_ForwardRawStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(VmmdServer).ForwardRawStream(&grpc.GenericServerStream[ForwardRawRequest, ForwardRawResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Vmmd_ForwardRawStreamServer = grpc.BidiStreamingServer[ForwardRawRequest, ForwardRawResponse]

func _Vmmd_MountParentExt4ReadOnly_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MountParentExt4ReadOnlyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VmmdServer).MountParentExt4ReadOnly(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Vmmd_MountParentExt4ReadOnly_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VmmdServer).MountParentExt4ReadOnly(ctx, req.(*MountParentExt4ReadOnlyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Vmmd_MaterializeParentExt4_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MaterializeParentExt4Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VmmdServer).MaterializeParentExt4(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Vmmd_MaterializeParentExt4_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VmmdServer).MaterializeParentExt4(ctx, req.(*MaterializeParentExt4Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _Vmmd_UmountParentExt4_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UmountParentExt4Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VmmdServer).UmountParentExt4(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Vmmd_UmountParentExt4_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VmmdServer).UmountParentExt4(ctx, req.(*UmountParentExt4Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _Vmmd_MountOverlayParent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MountOverlayParentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VmmdServer).MountOverlayParent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Vmmd_MountOverlayParent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VmmdServer).MountOverlayParent(ctx, req.(*MountOverlayParentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Vmmd_UmountOverlayParent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UmountOverlayParentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VmmdServer).UmountOverlayParent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Vmmd_UmountOverlayParent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VmmdServer).UmountOverlayParent(ctx, req.(*UmountOverlayParentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Vmmd_PrepareLiveMigration_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PrepareLiveMigrationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VmmdServer).PrepareLiveMigration(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Vmmd_PrepareLiveMigration_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VmmdServer).PrepareLiveMigration(ctx, req.(*PrepareLiveMigrationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Vmmd_AdoptMigratedInstance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdoptMigratedInstanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VmmdServer).AdoptMigratedInstance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Vmmd_AdoptMigratedInstance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VmmdServer).AdoptMigratedInstance(ctx, req.(*AdoptMigratedInstanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Vmmd_AcknowledgeMigration_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AcknowledgeMigrationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VmmdServer).AcknowledgeMigration(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Vmmd_AcknowledgeMigration_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VmmdServer).AcknowledgeMigration(ctx, req.(*AcknowledgeMigrationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Vmmd_CancelLiveMigration_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelLiveMigrationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VmmdServer).CancelLiveMigration(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Vmmd_CancelLiveMigration_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VmmdServer).CancelLiveMigration(ctx, req.(*CancelLiveMigrationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Vmmd_ServiceDesc is the grpc.ServiceDesc for Vmmd service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Vmmd_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "onebox.faas.vmmd.v1.Vmmd",
	HandlerType: (*VmmdServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateFromSnapshot",
			Handler:    _Vmmd_CreateFromSnapshot_Handler,
		},
		{
			MethodName: "CreateColdBoot",
			Handler:    _Vmmd_CreateColdBoot_Handler,
		},
		{
			MethodName: "PauseAndSnapshot",
			Handler:    _Vmmd_PauseAndSnapshot_Handler,
		},
		{
			MethodName: "WarmSnapshot",
			Handler:    _Vmmd_WarmSnapshot_Handler,
		},
		{
			MethodName: "FrameworkReady",
			Handler:    _Vmmd_FrameworkReady_Handler,
		},
		{
			MethodName: "Destroy",
			Handler:    _Vmmd_Destroy_Handler,
		},
		{
			MethodName: "StopInstance",
			Handler:    _Vmmd_StopInstance_Handler,
		},
		{
			MethodName: "Stats",
			Handler:    _Vmmd_Stats_Handler,
		},
		{
			MethodName: "Ping",
			Handler:    _Vmmd_Ping_Handler,
		},
		{
			MethodName: "Heartbeat",
			Handler:    _Vmmd_Heartbeat_Handler,
		},
		{
			MethodName: "UpdateEgressAllowlist",
			Handler:    _Vmmd_UpdateEgressAllowlist_Handler,
		},
		{
			MethodName: "UpdateStaticEgressIP",
			Handler:    _Vmmd_UpdateStaticEgressIP_Handler,
		},
		{
			MethodName: "SeccompStatus",
			Handler:    _Vmmd_SeccompStatus_Handler,
		},
		{
			MethodName: "MountParentExt4ReadOnly",
			Handler:    _Vmmd_MountParentExt4ReadOnly_Handler,
		},
		{
			MethodName: "MaterializeParentExt4",
			Handler:    _Vmmd_MaterializeParentExt4_Handler,
		},
		{
			MethodName: "UmountParentExt4",
			Handler:    _Vmmd_UmountParentExt4_Handler,
		},
		{
			MethodName: "MountOverlayParent",
			Handler:    _Vmmd_MountOverlayParent_Handler,
		},
		{
			MethodName: "UmountOverlayParent",
			Handler:    _Vmmd_UmountOverlayParent_Handler,
		},
		{
			MethodName: "PrepareLiveMigration",
			Handler:    _Vmmd_PrepareLiveMigration_Handler,
		},
		{
			MethodName: "AdoptMigratedInstance",
			Handler:    _Vmmd_AdoptMigratedInstance_Handler,
		},
		{
			MethodName: "AcknowledgeMigration",
			Handler:    _Vmmd_AcknowledgeMigration_Handler,
		},
		{
			MethodName: "CancelLiveMigration",
			Handler:    _Vmmd_CancelLiveMigration_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Logs",
			Handler:       _Vmmd_Logs_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "ForwardHTTPStream",
			Handler:       _Vmmd_ForwardHTTPStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "ForwardRawStream",
			Handler:       _Vmmd_ForwardRawStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "onebox/faas/vmmd/v1/vmmd.proto",
}
