// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type GregaleCopyRolesReceipt struct {
	Singleton    bool
	Version      int32
	Plan         []byte
	CreatedRoles []byte
	SeededAt     pgtype.Timestamptz
}
