// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AbandonConnections(ctx context.Context, db DBTX, arg AbandonConnectionsParams) (bool, error)
	// Inventory the entire source, including templates, databases which refuse
	// connections, and databases owned by another role. Filtering those out would
	// silently omit writers. Only the authenticated private maintenance DB is exempt.
	CheckpointDatabaseNames(ctx context.Context, db DBTX, arg CheckpointDatabaseNamesParams) ([]string, error)
	// Recheck the entire native catalogue against the original OIDs. A database
	// created after selection cannot disappear behind a drained selected subset.
	CheckpointUnselectedDatabaseCount(ctx context.Context, db DBTX, arg CheckpointUnselectedDatabaseCountParams) (int64, error)
	CloseConnections(ctx context.Context, db DBTX, arg CloseConnectionsParams) (bool, error)
	CreateMaintenanceDatabase(ctx context.Context, db DBTX) error
	FenceInstallationVersion(ctx context.Context, db DBTX) (int32, error)
	FenceSchemaExists(ctx context.Context, db DBTX) (bool, error)
	FenceSchemaPrivate(ctx context.Context, db DBTX) (pgtype.Bool, error)
	InstallFenceAbandonFunction(ctx context.Context, db DBTX) error
	InstallFenceActiveIndex(ctx context.Context, db DBTX) error
	InstallFenceCloseFunction(ctx context.Context, db DBTX) error
	InstallFenceDatabaseTable(ctx context.Context, db DBTX) error
	InstallFenceReleaseFunction(ctx context.Context, db DBTX) error
	InstallFenceSchema(ctx context.Context, db DBTX) error
	InstallFenceTable(ctx context.Context, db DBTX) error
	InstallFenceVersion(ctx context.Context, db DBTX) error
	InstallMaintenanceBootstrapFunction(ctx context.Context, db DBTX) error
	LockMaintenanceBootstrap(ctx context.Context, db DBTX) error
	MaintenanceBootstrapAction(ctx context.Context, db DBTX, arg MaintenanceBootstrapActionParams) (string, error)
	// ADR-531: these functions live only in the dedicated bootstrap session's
	// temporary schema. No schema or function is installed in an application DB.
	// The session lock covers CREATE DATABASE, which cannot run in a transaction.
	// All workers must use the same authenticated source database for this lock.
	MaintenanceBootstrapIdentity(ctx context.Context, db DBTX) (MaintenanceBootstrapIdentityRow, error)
	MaintenanceIdentity(ctx context.Context, db DBTX) (MaintenanceIdentityRow, error)
	ReadFence(ctx context.Context, db DBTX, arg ReadFenceParams) (GregaleCheckpointConnectionFence, error)
	ReadFenceDatabases(ctx context.Context, db DBTX, ownerToken pgtype.UUID) ([]ReadFenceDatabasesRow, error)
	ReadMaintenanceBootstrap(ctx context.Context, db DBTX, ownerRole string) (ReadMaintenanceBootstrapRow, error)
	RecordFenceVersion(ctx context.Context, db DBTX) error
	ReleaseConnections(ctx context.Context, db DBTX, arg ReleaseConnectionsParams) (bool, error)
	ResetMaintenanceOwnerRole(ctx context.Context, db DBTX) error
	RevokeFenceAbandonFunction(ctx context.Context, db DBTX) error
	RevokeFenceCloseFunction(ctx context.Context, db DBTX) error
	RevokeFenceReleaseFunction(ctx context.Context, db DBTX) error
	SetMaintenanceOwnerRole(ctx context.Context, db DBTX, ownerRole string) (string, error)
	UnlockMaintenanceBootstrap(ctx context.Context, db DBTX) (bool, error)
}

var _ Querier = (*Queries)(nil)
