// githubd — the GitHub App integration daemon (spec §14 M7.5, ADR-012).
//
// githubd owns: push-webhook receiver, Checks-API status writer, OAuth
// callback handler, per-repo install-token cache. It is the SOLE
// outbound caller to api.github.com (Checks API + install token
// exchange); its inbound public surface is gatewayd at /webhooks/github
// (HMAC-verified at the edge per ADR-012).
//
// Wire discipline mirrors vmmd (ADR-013) and schedd (ADR-018):
// checked-in *.pb.go generated with paths=source_relative, errors
// enveloped through pkg/grpcerr, auth is the unix-socket DAC model
// (mode 0660 group `faas`, ADR-015) on /run/faas/githubd.sock.
//
// Re-evaluation triggers: see ADR-012.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// source: onebox/faas/githubd/v1/githubd.proto

package githubdpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// InstallState is the per-account GitHub App install lifecycle. Maps to
// the dashboard "Connect GitHub" flow state machine (UX spec §5.1).
type InstallState int32

const (
	InstallState_STATE_UNSPECIFIED InstallState = 0
	InstallState_NOT_INSTALLED     InstallState = 1 // no app installation on this account
	InstallState_INSTALLING        InstallState = 2 // OAuth callback in flight, awaiting exchange
	InstallState_INSTALLED         InstallState = 3 // app installed, no repo bound yet
	InstallState_BOUND             InstallState = 4 // app installed and at least one app→repo binding
)

// Enum value maps for InstallState.
var (
	InstallState_name = map[int32]string{
		0: "STATE_UNSPECIFIED",
		1: "NOT_INSTALLED",
		2: "INSTALLING",
		3: "INSTALLED",
		4: "BOUND",
	}
	InstallState_value = map[string]int32{
		"STATE_UNSPECIFIED": 0,
		"NOT_INSTALLED":     1,
		"INSTALLING":        2,
		"INSTALLED":         3,
		"BOUND":             4,
	}
)

func (x InstallState) Enum() *InstallState {
	p := new(InstallState)
	*p = x
	return p
}

func (x InstallState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (InstallState) Descriptor() protoreflect.EnumDescriptor {
	return file_onebox_faas_githubd_v1_githubd_proto_enumTypes[0].Descriptor()
}

func (InstallState) Type() protoreflect.EnumType {
	return &file_onebox_faas_githubd_v1_githubd_proto_enumTypes[0]
}

func (x InstallState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use InstallState.Descriptor instead.
func (InstallState) EnumDescriptor() ([]byte, []int) {
	return file_onebox_faas_githubd_v1_githubd_proto_rawDescGZIP(), []int{0}
}

// CheckPhase is the githubd-side state machine for build progress. Maps
// to GitHub's `status` + `conclusion` via pkg/githubd/checks.go.
type CheckPhase int32

const (
	CheckPhase_PHASE_UNSPECIFIED CheckPhase = 0
	CheckPhase_QUEUED            CheckPhase = 1 // → GitHub status: queued
	CheckPhase_BUILDING          CheckPhase = 2 // → GitHub status: in_progress
	CheckPhase_LIVE              CheckPhase = 3 // → GitHub status: completed, conclusion: success
	CheckPhase_FAILED            CheckPhase = 4 // → GitHub status: completed, conclusion: failure
)

// Enum value maps for CheckPhase.
var (
	CheckPhase_name = map[int32]string{
		0: "PHASE_UNSPECIFIED",
		1: "QUEUED",
		2: "BUILDING",
		3: "LIVE",
		4: "FAILED",
	}
	CheckPhase_value = map[string]int32{
		"PHASE_UNSPECIFIED": 0,
		"QUEUED":            1,
		"BUILDING":          2,
		"LIVE":              3,
		"FAILED":            4,
	}
)

func (x CheckPhase) Enum() *CheckPhase {
	p := new(CheckPhase)
	*p = x
	return p
}

func (x CheckPhase) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CheckPhase) Descriptor() protoreflect.EnumDescriptor {
	return file_onebox_faas_githubd_v1_githubd_proto_enumTypes[1].Descriptor()
}

func (CheckPhase) Type() protoreflect.EnumType {
	return &file_onebox_faas_githubd_v1_githubd_proto_enumTypes[1]
}

func (x CheckPhase) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CheckPhase.Descriptor instead.
func (CheckPhase) EnumDescriptor() ([]byte, []int) {
	return file_onebox_faas_githubd_v1_githubd_proto_rawDescGZIP(), []int{1}
}

type VerifyInstallationRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	InstallationId int64                  `protobuf:"varint,1,opt,name=installation_id,json=installationId,proto3" json:"installation_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *VerifyInstallationRequest) Reset() {
	*x = VerifyInstallationRequest{}
	mi := &file_onebox_faas_githubd_v1_githubd_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyInstallationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyInstallationRequest) ProtoMessage() {}

func (x *VerifyInstallationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_onebox_faas_githubd_v1_githubd_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyInstallationRequest.ProtoReflect.Descriptor instead.
func (*VerifyInstallationRequest) Descriptor() ([]byte, []int) {
	return file_onebox_faas_githubd_v1_githubd_proto_rawDescGZIP(), []int{0}
}

func (x *VerifyInstallationRequest) GetInstallationId() int64 {
	if x != nil {
		return x.InstallationId
	}
	return 0
}

type VerifyInstallationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Verified      bool                   `protobuf:"varint,1,opt,name=verified,proto3" json:"verified,omitempty"`                               // false ⇒ caller should 401/403 the dashboard
	DefaultBranch string                 `protobuf:"bytes,2,opt,name=default_branch,json=defaultBranch,proto3" json:"default_branch,omitempty"` // empty when verified=false
	AccountLogin  string                 `protobuf:"bytes,3,opt,name=account_login,json=accountLogin,proto3" json:"account_login,omitempty"`    // GitHub login of the install's owner (debugging)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyInstallationResponse) Reset() {
	*x = VerifyInstallationResponse{}
	mi := &file_onebox_faas_githubd_v1_githubd_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyInstallationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyInstallationResponse) ProtoMessage() {}

func (x *VerifyInstallationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_onebox_faas_githubd_v1_githubd_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyInstallationResponse.ProtoReflect.Descriptor instead.
func (*VerifyInstallationResponse) Descriptor() ([]byte, []int) {
	return file_onebox_faas_githubd_v1_githubd_proto_rawDescGZIP(), []int{1}
}

func (x *VerifyInstallationResponse) GetVerified() bool {
	if x != nil {
		return x.Verified
	}
	return false
}

func (x *VerifyInstallationResponse) GetDefaultBranch() string {
	if x != nil {
		return x.DefaultBranch
	}
	return ""
}

func (x *VerifyInstallationResponse) GetAccountLogin() string {
	if x != nil {
		return x.AccountLogin
	}
	return ""
}

type GetInstallStateRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// account_id is the accounts.id UUID (apid resolves session→account
	// before calling; githubd never sees the bearer/session).
	AccountId     string `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInstallStateRequest) Reset() {
	*x = GetInstallStateRequest{}
	mi := &file_onebox_faas_githubd_v1_githubd_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInstallStateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInstallStateRequest) ProtoMessage() {}

func (x *GetInstallStateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_onebox_faas_githubd_v1_githubd_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInstallStateRequest.ProtoReflect.Descriptor instead.
func (*GetInstallStateRequest) Descriptor() ([]byte, []int) {
	return file_onebox_faas_githubd_v1_githubd_proto_rawDescGZIP(), []int{2}
}

func (x *GetInstallStateRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

type GetInstallStateResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	State          InstallState           `protobuf:"varint,1,opt,name=state,proto3,enum=onebox.faas.githubd.v1.InstallState" json:"state,omitempty"`
	InstallationId string                 `protobuf:"bytes,2,opt,name=installation_id,json=installationId,proto3" json:"installation_id,omitempty"` // empty unless state >= INSTALLED
	DefaultBranch  string                 `protobuf:"bytes,3,opt,name=default_branch,json=defaultBranch,proto3" json:"default_branch,omitempty"`    // empty unless state >= BOUND
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetInstallStateResponse) Reset() {
	*x = GetInstallStateResponse{}
	mi := &file_onebox_faas_githubd_v1_githubd_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInstallStateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInstallStateResponse) ProtoMessage() {}

func (x *GetInstallStateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_onebox_faas_githubd_v1_githubd_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInstallStateResponse.ProtoReflect.Descriptor instead.
func (*GetInstallStateResponse) Descriptor() ([]byte, []int) {
	return file_onebox_faas_githubd_v1_githubd_proto_rawDescGZIP(), []int{3}
}

func (x *GetInstallStateResponse) GetState() InstallState {
	if x != nil {
		return x.State
	}
	return InstallState_STATE_UNSPECIFIED
}

func (x *GetInstallStateResponse) GetInstallationId() string {
	if x != nil {
		return x.InstallationId
	}
	return ""
}

func (x *GetInstallStateResponse) GetDefaultBranch() string {
	if x != nil {
		return x.DefaultBranch
	}
	return ""
}

type ExchangeOAuthCodeRequest struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	AccountId string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	// code is the GitHub OAuth `code` query param from the callback URL.
	Code string `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	// state is the CSRF token githubd minted at the install URL; githubd
	// verifies it against the cookie/db row before exchanging.
	State         string `protobuf:"bytes,3,opt,name=state,proto3" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExchangeOAuthCodeRequest) Reset() {
	*x = ExchangeOAuthCodeRequest{}
	mi := &file_onebox_faas_githubd_v1_githubd_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExchangeOAuthCodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExchangeOAuthCodeRequest) ProtoMessage() {}

func (x *ExchangeOAuthCodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_onebox_faas_githubd_v1_githubd_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExchangeOAuthCodeRequest.ProtoReflect.Descriptor instead.
func (*ExchangeOAuthCodeRequest) Descriptor() ([]byte, []int) {
	return file_onebox_faas_githubd_v1_githubd_proto_rawDescGZIP(), []int{4}
}

func (x *ExchangeOAuthCodeRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *ExchangeOAuthCodeRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *ExchangeOAuthCodeRequest) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

type ExchangeOAuthCodeResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	InstallationId string                 `protobuf:"bytes,1,opt,name=installation_id,json=installationId,proto3" json:"installation_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ExchangeOAuthCodeResponse) Reset() {
	*x = ExchangeOAuthCodeResponse{}
	mi := &file_onebox_faas_githubd_v1_githubd_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExchangeOAuthCodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExchangeOAuthCodeResponse) ProtoMessage() {}

func (x *ExchangeOAuthCodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_onebox_faas_githubd_v1_githubd_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExchangeOAuthCodeResponse.ProtoReflect.Descriptor instead.
func (*ExchangeOAuthCodeResponse) Descriptor() ([]byte, []int) {
	return file_onebox_faas_githubd_v1_githubd_proto_rawDescGZIP(), []int{5}
}

func (x *ExchangeOAuthCodeResponse) GetInstallationId() string {
	if x != nil {
		return x.InstallationId
	}
	return ""
}

type Repo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FullName      string                 `protobuf:"bytes,1,opt,name=full_name,json=fullName,proto3" json:"full_name,omitempty"`                // "owner/name"
	DefaultBranch string                 `protobuf:"bytes,2,opt,name=default_branch,json=defaultBranch,proto3" json:"default_branch,omitempty"` // "main" | "master" | custom
	Private       bool                   `protobuf:"varint,3,opt,name=private,proto3" json:"private,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Repo) Reset() {
	*x = Repo{}
	mi := &file_onebox_faas_githubd_v1_githubd_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Repo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Repo) ProtoMessage() {}

func (x *Repo) ProtoReflect() protoreflect.Message {
	mi := &file_onebox_faas_githubd_v1_githubd_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Repo.ProtoReflect.Descriptor instead.
func (*Repo) Descriptor() ([]byte, []int) {
	return file_onebox_faas_githubd_v1_githubd_proto_rawDescGZIP(), []int{6}
}

func (x *Repo) GetFullName() string {
	if x != nil {
		return x.FullName
	}
	return ""
}

func (x *Repo) GetDefaultBranch() string {
	if x != nil {
		return x.DefaultBranch
	}
	return ""
}

func (x *Repo) GetPrivate() bool {
	if x != nil {
		return x.Private
	}
	return false
}

type ListInstallableReposRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListInstallableReposRequest) Reset() {
	*x = ListInstallableReposRequest{}
	mi := &file_onebox_faas_githubd_v1_githubd_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListInstallableReposRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListInstallableReposRequest) ProtoMessage() {}

func (x *ListInstallableReposRequest) ProtoReflect() protoreflect.Message {
	mi := &file_onebox_faas_githubd_v1_githubd_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListInstallableReposRequest.ProtoReflect.Descriptor instead.
func (*ListInstallableReposRequest) Descriptor() ([]byte, []int) {
	return file_onebox_faas_githubd_v1_githubd_proto_rawDescGZIP(), []int{7}
}

func (x *ListInstallableReposRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

type ListInstallableReposResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Repos         []*Repo                `protobuf:"bytes,1,rep,name=repos,proto3" json:"repos,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListInstallableReposResponse) Reset() {
	*x = ListInstallableReposResponse{}
	mi := &file_onebox_faas_githubd_v1_githubd_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListInstallableReposResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListInstallableReposResponse) ProtoMessage() {}

func (x *ListInstallableReposResponse) ProtoReflect() protoreflect.Message {
	mi := &file_onebox_faas_githubd_v1_githubd_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListInstallableReposResponse.ProtoReflect.Descriptor instead.
func (*ListInstallableReposResponse) Descriptor() ([]byte, []int) {
	return file_onebox_faas_githubd_v1_githubd_proto_rawDescGZIP(), []int{8}
}

func (x *ListInstallableReposResponse) GetRepos() []*Repo {
	if x != nil {
		return x.Repos
	}
	return nil
}

type BindAppRepoRequest struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	AppId        string                 `protobuf:"bytes,1,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	RepoFullName string                 `protobuf:"bytes,2,opt,name=repo_full_name,json=repoFullName,proto3" json:"repo_full_name,omitempty"` // "owner/name"
	// production_branch defaults to "main" if empty (UX spec §5.2).
	ProductionBranch string `protobuf:"bytes,3,opt,name=production_branch,json=productionBranch,proto3" json:"production_branch,omitempty"`
	AccountId        string `protobuf:"bytes,4,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *BindAppRepoRequest) Reset() {
	*x = BindAppRepoRequest{}
	mi := &file_onebox_faas_githubd_v1_githubd_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BindAppRepoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BindAppRepoRequest) ProtoMessage() {}

func (x *BindAppRepoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_onebox_faas_githubd_v1_githubd_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BindAppRepoRequest.ProtoReflect.Descriptor instead.
func (*BindAppRepoRequest) Descriptor() ([]byte, []int) {
	return file_onebox_faas_githubd_v1_githubd_proto_rawDescGZIP(), []int{9}
}

func (x *BindAppRepoRequest) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *BindAppRepoRequest) GetRepoFullName() string {
	if x != nil {
		return x.RepoFullName
	}
	return ""
}

func (x *BindAppRepoRequest) GetProductionBranch() string {
	if x != nil {
		return x.ProductionBranch
	}
	return ""
}

func (x *BindAppRepoRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

type BindAppRepoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BindingId     string                 `protobuf:"bytes,1,opt,name=binding_id,json=bindingId,proto3" json:"binding_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BindAppRepoResponse) Reset() {
	*x = BindAppRepoResponse{}
	mi := &file_onebox_faas_githubd_v1_githubd_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BindAppRepoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BindAppRepoResponse) ProtoMessage() {}

func (x *BindAppRepoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_onebox_faas_githubd_v1_githubd_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BindAppRepoResponse.ProtoReflect.Descriptor instead.
func (*BindAppRepoResponse) Descriptor() ([]byte, []int) {
	return file_onebox_faas_githubd_v1_githubd_proto_rawDescGZIP(), []int{10}
}

func (x *BindAppRepoResponse) GetBindingId() string {
	if x != nil {
		return x.BindingId
	}
	return ""
}

type UnbindAppRepoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AppId         string                 `protobuf:"bytes,1,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	AccountId     string                 `protobuf:"bytes,2,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnbindAppRepoRequest) Reset() {
	*x = UnbindAppRepoRequest{}
	mi := &file_onebox_faas_githubd_v1_githubd_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnbindAppRepoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnbindAppRepoRequest) ProtoMessage() {}

func (x *UnbindAppRepoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_onebox_faas_githubd_v1_githubd_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnbindAppRepoRequest.ProtoReflect.Descriptor instead.
func (*UnbindAppRepoRequest) Descriptor() ([]byte, []int) {
	return file_onebox_faas_githubd_v1_githubd_proto_rawDescGZIP(), []int{11}
}

func (x *UnbindAppRepoRequest) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *UnbindAppRepoRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

type UnbindAppRepoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnbindAppRepoResponse) Reset() {
	*x = UnbindAppRepoResponse{}
	mi := &file_onebox_faas_githubd_v1_githubd_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnbindAppRepoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnbindAppRepoResponse) ProtoMessage() {}

func (x *UnbindAppRepoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_onebox_faas_githubd_v1_githubd_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnbindAppRepoResponse.ProtoReflect.Descriptor instead.
func (*UnbindAppRepoResponse) Descriptor() ([]byte, []int) {
	return file_onebox_faas_githubd_v1_githubd_proto_rawDescGZIP(), []int{12}
}

type GetAppBindingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AppId         string                 `protobuf:"bytes,1,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	AccountId     string                 `protobuf:"bytes,2,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAppBindingRequest) Reset() {
	*x = GetAppBindingRequest{}
	mi := &file_onebox_faas_githubd_v1_githubd_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAppBindingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAppBindingRequest) ProtoMessage() {}

func (x *GetAppBindingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_onebox_faas_githubd_v1_githubd_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAppBindingRequest.ProtoReflect.Descriptor instead.
func (*GetAppBindingRequest) Descriptor() ([]byte, []int) {
	return file_onebox_faas_githubd_v1_githubd_proto_rawDescGZIP(), []int{13}
}

func (x *GetAppBindingRequest) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *GetAppBindingRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

type GetAppBindingResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	RepoFullName     string                 `protobuf:"bytes,1,opt,name=repo_full_name,json=repoFullName,proto3" json:"repo_full_name,omitempty"`
	ProductionBranch string                 `protobuf:"bytes,2,opt,name=production_branch,json=productionBranch,proto3" json:"production_branch,omitempty"`
	BindingId        string                 `protobuf:"bytes,3,opt,name=binding_id,json=bindingId,proto3" json:"binding_id,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetAppBindingResponse) Reset() {
	*x = GetAppBindingResponse{}
	mi := &file_onebox_faas_githubd_v1_githubd_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAppBindingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAppBindingResponse) ProtoMessage() {}

func (x *GetAppBindingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_onebox_faas_githubd_v1_githubd_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAppBindingResponse.ProtoReflect.Descriptor instead.
func (*GetAppBindingResponse) Descriptor() ([]byte, []int) {
	return file_onebox_faas_githubd_v1_githubd_proto_rawDescGZIP(), []int{14}
}

func (x *GetAppBindingResponse) GetRepoFullName() string {
	if x != nil {
		return x.RepoFullName
	}
	return ""
}

func (x *GetAppBindingResponse) GetProductionBranch() string {
	if x != nil {
		return x.ProductionBranch
	}
	return ""
}

func (x *GetAppBindingResponse) GetBindingId() string {
	if x != nil {
		return x.BindingId
	}
	return ""
}

type CreateDeploymentFromPushRequest struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	RepoFullName string                 `protobuf:"bytes,1,opt,name=repo_full_name,json=repoFullName,proto3" json:"repo_full_name,omitempty"`
	// ref is "refs/heads/main" (githubd strips the refs/heads/ prefix
	// before storing on the deployment row).
	Ref           string `protobuf:"bytes,2,opt,name=ref,proto3" json:"ref,omitempty"`
	CommitSha     string `protobuf:"bytes,3,opt,name=commit_sha,json=commitSha,proto3" json:"commit_sha,omitempty"`
	Pusher        string `protobuf:"bytes,4,opt,name=pusher,proto3" json:"pusher,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateDeploymentFromPushRequest) Reset() {
	*x = CreateDeploymentFromPushRequest{}
	mi := &file_onebox_faas_githubd_v1_githubd_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateDeploymentFromPushRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDeploymentFromPushRequest) ProtoMessage() {}

func (x *CreateDeploymentFromPushRequest) ProtoReflect() protoreflect.Message {
	mi := &file_onebox_faas_githubd_v1_githubd_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDeploymentFromPushRequest.ProtoReflect.Descriptor instead.
func (*CreateDeploymentFromPushRequest) Descriptor() ([]byte, []int) {
	return file_onebox_faas_githubd_v1_githubd_proto_rawDescGZIP(), []int{15}
}

func (x *CreateDeploymentFromPushRequest) GetRepoFullName() string {
	if x != nil {
		return x.RepoFullName
	}
	return ""
}

func (x *CreateDeploymentFromPushRequest) GetRef() string {
	if x != nil {
		return x.Ref
	}
	return ""
}

func (x *CreateDeploymentFromPushRequest) GetCommitSha() string {
	if x != nil {
		return x.CommitSha
	}
	return ""
}

func (x *CreateDeploymentFromPushRequest) GetPusher() string {
	if x != nil {
		return x.Pusher
	}
	return ""
}

type CreateDeploymentFromPushResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// deployment_id is empty when no app is bound to this repo (a
	// redelivered webhook for an unbound repo returns the same empty
	// shape — idempotent).
	DeploymentId  string `protobuf:"bytes,1,opt,name=deployment_id,json=deploymentId,proto3" json:"deployment_id,omitempty"`
	AppId         string `protobuf:"bytes,2,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateDeploymentFromPushResponse) Reset() {
	*x = CreateDeploymentFromPushResponse{}
	mi := &file_onebox_faas_githubd_v1_githubd_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateDeploymentFromPushResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDeploymentFromPushResponse) ProtoMessage() {}

func (x *CreateDeploymentFromPushResponse) ProtoReflect() protoreflect.Message {
	mi := &file_onebox_faas_githubd_v1_githubd_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDeploymentFromPushResponse.ProtoReflect.Descriptor instead.
func (*CreateDeploymentFromPushResponse) Descriptor() ([]byte, []int) {
	return file_onebox_faas_githubd_v1_githubd_proto_rawDescGZIP(), []int{16}
}

func (x *CreateDeploymentFromPushResponse) GetDeploymentId() string {
	if x != nil {
		return x.DeploymentId
	}
	return ""
}

func (x *CreateDeploymentFromPushResponse) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

type WriteCheckRequest struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	RepoFullName string                 `protobuf:"bytes,1,opt,name=repo_full_name,json=repoFullName,proto3" json:"repo_full_name,omitempty"`
	CommitSha    string                 `protobuf:"bytes,2,opt,name=commit_sha,json=commitSha,proto3" json:"commit_sha,omitempty"`
	Phase        CheckPhase             `protobuf:"varint,3,opt,name=phase,proto3,enum=onebox.faas.githubd.v1.CheckPhase" json:"phase,omitempty"`
	// logs_url is the dashboard deep-link for the build log (UX spec §5.2).
	LogsUrl string `protobuf:"bytes,4,opt,name=logs_url,json=logsUrl,proto3" json:"logs_url,omitempty"`
	// summary is one-line human-readable ("Build failed: OOM at 1.4 GB").
	Summary       string `protobuf:"bytes,5,opt,name=summary,proto3" json:"summary,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteCheckRequest) Reset() {
	*x = WriteCheckRequest{}
	mi := &file_onebox_faas_githubd_v1_githubd_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteCheckRequest) ProtoMessage() {}

func (x *WriteCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_onebox_faas_githubd_v1_githubd_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteCheckRequest.ProtoReflect.Descriptor instead.
func (*WriteCheckRequest) Descriptor() ([]byte, []int) {
	return file_onebox_faas_githubd_v1_githubd_proto_rawDescGZIP(), []int{17}
}

func (x *WriteCheckRequest) GetRepoFullName() string {
	if x != nil {
		return x.RepoFullName
	}
	return ""
}

func (x *WriteCheckRequest) GetCommitSha() string {
	if x != nil {
		return x.CommitSha
	}
	return ""
}

func (x *WriteCheckRequest) GetPhase() CheckPhase {
	if x != nil {
		return x.Phase
	}
	return CheckPhase_PHASE_UNSPECIFIED
}

func (x *WriteCheckRequest) GetLogsUrl() string {
	if x != nil {
		return x.LogsUrl
	}
	return ""
}

func (x *WriteCheckRequest) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

type WriteCheckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteCheckResponse) Reset() {
	*x = WriteCheckResponse{}
	mi := &file_onebox_faas_githubd_v1_githubd_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteCheckResponse) ProtoMessage() {}

func (x *WriteCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_onebox_faas_githubd_v1_githubd_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteCheckResponse.ProtoReflect.Descriptor instead.
func (*WriteCheckResponse) Descriptor() ([]byte, []int) {
	return file_onebox_faas_githubd_v1_githubd_proto_rawDescGZIP(), []int{18}
}

var File_onebox_faas_githubd_v1_githubd_proto protoreflect.FileDescriptor

const file_onebox_faas_githubd_v1_githubd_proto_rawDesc = "" +
	"\n" +
	"$onebox/faas/githubd/v1/githubd.proto\x12\x16onebox.faas.githubd.v1\"D\n" +
	"\x19VerifyInstallationRequest\x12'\n" +
	"\x0finstallation_id\x18\x01 \x01(\x03R\x0einstallationId\"\x84\x01\n" +
	"\x1aVerifyInstallationResponse\x12\x1a\n" +
	"\bverified\x18\x01 \x01(\bR\bverified\x12%\n" +
	"\x0edefault_branch\x18\x02 \x01(\tR\rdefaultBranch\x12#\n" +
	"\raccount_login\x18\x03 \x01(\tR\faccountLogin\"7\n" +
	"\x16GetInstallStateRequest\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\"\xa5\x01\n" +
	"\x17GetInstallStateResponse\x12:\n" +
	"\x05state\x18\x01 \x01(\x0e2$.onebox.faas.githubd.v1.InstallStateR\x05state\x12'\n" +
	"\x0finstallation_id\x18\x02 \x01(\tR\x0einstallationId\x12%\n" +
	"\x0edefault_branch\x18\x03 \x01(\tR\rdefaultBranch\"c\n" +
	"\x18ExchangeOAuthCodeRequest\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\x12\x14\n" +
	"\x05state\x18\x03 \x01(\tR\x05state\"D\n" +
	"\x19ExchangeOAuthCodeResponse\x12'\n" +
	"\x0finstallation_id\x18\x01 \x01(\tR\x0einstallationId\"d\n" +
	"\x04Repo\x12\x1b\n" +
	"\tfull_name\x18\x01 \x01(\tR\bfullName\x12%\n" +
	"\x0edefault_branch\x18\x02 \x01(\tR\rdefaultBranch\x12\x18\n" +
	"\aprivate\x18\x03 \x01(\bR\aprivate\"<\n" +
	"\x1bListInstallableReposRequest\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\"R\n" +
	"\x1cListInstallableReposResponse\x122\n" +
	"\x05repos\x18\x01 \x03(\v2\x1c.onebox.faas.githubd.v1.RepoR\x05repos\"\x9d\x01\n" +
	"\x12BindAppRepoRequest\x12\x15\n" +
	"\x06app_id\x18\x01 \x01(\tR\x05appId\x12$\n" +
	"\x0erepo_full_name\x18\x02 \x01(\tR\frepoFullName\x12+\n" +
	"\x11production_branch\x18\x03 \x01(\tR\x10productionBranch\x12\x1d\n" +
	"\n" +
	"account_id\x18\x04 \x01(\tR\taccountId\"4\n" +
	"\x13BindAppRepoResponse\x12\x1d\n" +
	"\n" +
	"binding_id\x18\x01 \x01(\tR\tbindingId\"L\n" +
	"\x14UnbindAppRepoRequest\x12\x15\n" +
	"\x06app_id\x18\x01 \x01(\tR\x05appId\x12\x1d\n" +
	"\n" +
	"account_id\x18\x02 \x01(\tR\taccountId\"\x17\n" +
	"\x15UnbindAppRepoResponse\"L\n" +
	"\x14GetAppBindingRequest\x12\x15\n" +
	"\x06app_id\x18\x01 \x01(\tR\x05appId\x12\x1d\n" +
	"\n" +
	"account_id\x18\x02 \x01(\tR\taccountId\"\x89\x01\n" +
	"\x15GetAppBindingResponse\x12$\n" +
	"\x0erepo_full_name\x18\x01 \x01(\tR\frepoFullName\x12+\n" +
	"\x11production_branch\x18\x02 \x01(\tR\x10productionBranch\x12\x1d\n" +
	"\n" +
	"binding_id\x18\x03 \x01(\tR\tbindingId\"\x90\x01\n" +
	"\x1fCreateDeploymentFromPushRequest\x12$\n" +
	"\x0erepo_full_name\x18\x01 \x01(\tR\frepoFullName\x12\x10\n" +
	"\x03ref\x18\x02 \x01(\tR\x03ref\x12\x1d\n" +
	"\n" +
	"commit_sha\x18\x03 \x01(\tR\tcommitSha\x12\x16\n" +
	"\x06pusher\x18\x04 \x01(\tR\x06pusher\"^\n" +
	" CreateDeploymentFromPushResponse\x12#\n" +
	"\rdeployment_id\x18\x01 \x01(\tR\fdeploymentId\x12\x15\n" +
	"\x06app_id\x18\x02 \x01(\tR\x05appId\"\xc7\x01\n" +
	"\x11WriteCheckRequest\x12$\n" +
	"\x0erepo_full_name\x18\x01 \x01(\tR\frepoFullName\x12\x1d\n" +
	"\n" +
	"commit_sha\x18\x02 \x01(\tR\tcommitSha\x128\n" +
	"\x05phase\x18\x03 \x01(\x0e2\".onebox.faas.githubd.v1.CheckPhaseR\x05phase\x12\x19\n" +
	"\blogs_url\x18\x04 \x01(\tR\alogsUrl\x12\x18\n" +
	"\asummary\x18\x05 \x01(\tR\asummary\"\x14\n" +
	"\x12WriteCheckResponse*b\n" +
	"\fInstallState\x12\x15\n" +
	"\x11STATE_UNSPECIFIED\x10\x00\x12\x11\n" +
	"\rNOT_INSTALLED\x10\x01\x12\x0e\n" +
	"\n" +
	"INSTALLING\x10\x02\x12\r\n" +
	"\tINSTALLED\x10\x03\x12\t\n" +
	"\x05BOUND\x10\x04*S\n" +
	"\n" +
	"CheckPhase\x12\x15\n" +
	"\x11PHASE_UNSPECIFIED\x10\x00\x12\n" +
	"\n" +
	"\x06QUEUED\x10\x01\x12\f\n" +
	"\bBUILDING\x10\x02\x12\b\n" +
	"\x04LIVE\x10\x03\x12\n" +
	"\n" +
	"\x06FAILED\x10\x042\xb1\b\n" +
	"\aGithubd\x12r\n" +
	"\x0fGetInstallState\x12..onebox.faas.githubd.v1.GetInstallStateRequest\x1a/.onebox.faas.githubd.v1.GetInstallStateResponse\x12x\n" +
	"\x11ExchangeOAuthCode\x120.onebox.faas.githubd.v1.ExchangeOAuthCodeRequest\x1a1.onebox.faas.githubd.v1.ExchangeOAuthCodeResponse\x12\x81\x01\n" +
	"\x14ListInstallableRepos\x123.onebox.faas.githubd.v1.ListInstallableReposRequest\x1a4.onebox.faas.githubd.v1.ListInstallableReposResponse\x12f\n" +
	"\vBindAppRepo\x12*.onebox.faas.githubd.v1.BindAppRepoRequest\x1a+.onebox.faas.githubd.v1.BindAppRepoResponse\x12l\n" +
	"\rUnbindAppRepo\x12,.onebox.faas.githubd.v1.UnbindAppRepoRequest\x1a-.onebox.faas.githubd.v1.UnbindAppRepoResponse\x12l\n" +
	"\rGetAppBinding\x12,.onebox.faas.githubd.v1.GetAppBindingRequest\x1a-.onebox.faas.githubd.v1.GetAppBindingResponse\x12\x8d\x01\n" +
	"\x18CreateDeploymentFromPush\x127.onebox.faas.githubd.v1.CreateDeploymentFromPushRequest\x1a8.onebox.faas.githubd.v1.CreateDeploymentFromPushResponse\x12c\n" +
	"\n" +
	"WriteCheck\x12).onebox.faas.githubd.v1.WriteCheckRequest\x1a*.onebox.faas.githubd.v1.WriteCheckResponse\x12{\n" +
	"\x12VerifyInstallation\x121.onebox.faas.githubd.v1.VerifyInstallationRequest\x1a2.onebox.faas.githubd.v1.VerifyInstallationResponseBHZFgithub.com/onebox-faas/faas/api/proto/onebox/faas/githubd/v1;githubdpbb\x06proto3"

var (
	file_onebox_faas_githubd_v1_githubd_proto_rawDescOnce sync.Once
	file_onebox_faas_githubd_v1_githubd_proto_rawDescData []byte
)

func file_onebox_faas_githubd_v1_githubd_proto_rawDescGZIP() []byte {
	file_onebox_faas_githubd_v1_githubd_proto_rawDescOnce.Do(func() {
		file_onebox_faas_githubd_v1_githubd_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_onebox_faas_githubd_v1_githubd_proto_rawDesc), len(file_onebox_faas_githubd_v1_githubd_proto_rawDesc)))
	})
	return file_onebox_faas_githubd_v1_githubd_proto_rawDescData
}

var file_onebox_faas_githubd_v1_githubd_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_onebox_faas_githubd_v1_githubd_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_onebox_faas_githubd_v1_githubd_proto_goTypes = []any{
	(InstallState)(0),                        // 0: onebox.faas.githubd.v1.InstallState
	(CheckPhase)(0),                          // 1: onebox.faas.githubd.v1.CheckPhase
	(*VerifyInstallationRequest)(nil),        // 2: onebox.faas.githubd.v1.VerifyInstallationRequest
	(*VerifyInstallationResponse)(nil),       // 3: onebox.faas.githubd.v1.VerifyInstallationResponse
	(*GetInstallStateRequest)(nil),           // 4: onebox.faas.githubd.v1.GetInstallStateRequest
	(*GetInstallStateResponse)(nil),          // 5: onebox.faas.githubd.v1.GetInstallStateResponse
	(*ExchangeOAuthCodeRequest)(nil),         // 6: onebox.faas.githubd.v1.ExchangeOAuthCodeRequest
	(*ExchangeOAuthCodeResponse)(nil),        // 7: onebox.faas.githubd.v1.ExchangeOAuthCodeResponse
	(*Repo)(nil),                             // 8: onebox.faas.githubd.v1.Repo
	(*ListInstallableReposRequest)(nil),      // 9: onebox.faas.githubd.v1.ListInstallableReposRequest
	(*ListInstallableReposResponse)(nil),     // 10: onebox.faas.githubd.v1.ListInstallableReposResponse
	(*BindAppRepoRequest)(nil),               // 11: onebox.faas.githubd.v1.BindAppRepoRequest
	(*BindAppRepoResponse)(nil),              // 12: onebox.faas.githubd.v1.BindAppRepoResponse
	(*UnbindAppRepoRequest)(nil),             // 13: onebox.faas.githubd.v1.UnbindAppRepoRequest
	(*UnbindAppRepoResponse)(nil),            // 14: onebox.faas.githubd.v1.UnbindAppRepoResponse
	(*GetAppBindingRequest)(nil),             // 15: onebox.faas.githubd.v1.GetAppBindingRequest
	(*GetAppBindingResponse)(nil),            // 16: onebox.faas.githubd.v1.GetAppBindingResponse
	(*CreateDeploymentFromPushRequest)(nil),  // 17: onebox.faas.githubd.v1.CreateDeploymentFromPushRequest
	(*CreateDeploymentFromPushResponse)(nil), // 18: onebox.faas.githubd.v1.CreateDeploymentFromPushResponse
	(*WriteCheckRequest)(nil),                // 19: onebox.faas.githubd.v1.WriteCheckRequest
	(*WriteCheckResponse)(nil),               // 20: onebox.faas.githubd.v1.WriteCheckResponse
}
var file_onebox_faas_githubd_v1_githubd_proto_depIdxs = []int32{
	0,  // 0: onebox.faas.githubd.v1.GetInstallStateResponse.state:type_name -> onebox.faas.githubd.v1.InstallState
	8,  // 1: onebox.faas.githubd.v1.ListInstallableReposResponse.repos:type_name -> onebox.faas.githubd.v1.Repo
	1,  // 2: onebox.faas.githubd.v1.WriteCheckRequest.phase:type_name -> onebox.faas.githubd.v1.CheckPhase
	4,  // 3: onebox.faas.githubd.v1.Githubd.GetInstallState:input_type -> onebox.faas.githubd.v1.GetInstallStateRequest
	6,  // 4: onebox.faas.githubd.v1.Githubd.ExchangeOAuthCode:input_type -> onebox.faas.githubd.v1.ExchangeOAuthCodeRequest
	9,  // 5: onebox.faas.githubd.v1.Githubd.ListInstallableRepos:input_type -> onebox.faas.githubd.v1.ListInstallableReposRequest
	11, // 6: onebox.faas.githubd.v1.Githubd.BindAppRepo:input_type -> onebox.faas.githubd.v1.BindAppRepoRequest
	13, // 7: onebox.faas.githubd.v1.Githubd.UnbindAppRepo:input_type -> onebox.faas.githubd.v1.UnbindAppRepoRequest
	15, // 8: onebox.faas.githubd.v1.Githubd.GetAppBinding:input_type -> onebox.faas.githubd.v1.GetAppBindingRequest
	17, // 9: onebox.faas.githubd.v1.Githubd.CreateDeploymentFromPush:input_type -> onebox.faas.githubd.v1.CreateDeploymentFromPushRequest
	19, // 10: onebox.faas.githubd.v1.Githubd.WriteCheck:input_type -> onebox.faas.githubd.v1.WriteCheckRequest
	2,  // 11: onebox.faas.githubd.v1.Githubd.VerifyInstallation:input_type -> onebox.faas.githubd.v1.VerifyInstallationRequest
	5,  // 12: onebox.faas.githubd.v1.Githubd.GetInstallState:output_type -> onebox.faas.githubd.v1.GetInstallStateResponse
	7,  // 13: onebox.faas.githubd.v1.Githubd.ExchangeOAuthCode:output_type -> onebox.faas.githubd.v1.ExchangeOAuthCodeResponse
	10, // 14: onebox.faas.githubd.v1.Githubd.ListInstallableRepos:output_type -> onebox.faas.githubd.v1.ListInstallableReposResponse
	12, // 15: onebox.faas.githubd.v1.Githubd.BindAppRepo:output_type -> onebox.faas.githubd.v1.BindAppRepoResponse
	14, // 16: onebox.faas.githubd.v1.Githubd.UnbindAppRepo:output_type -> onebox.faas.githubd.v1.UnbindAppRepoResponse
	16, // 17: onebox.faas.githubd.v1.Githubd.GetAppBinding:output_type -> onebox.faas.githubd.v1.GetAppBindingResponse
	18, // 18: onebox.faas.githubd.v1.Githubd.CreateDeploymentFromPush:output_type -> onebox.faas.githubd.v1.CreateDeploymentFromPushResponse
	20, // 19: onebox.faas.githubd.v1.Githubd.WriteCheck:output_type -> onebox.faas.githubd.v1.WriteCheckResponse
	3,  // 20: onebox.faas.githubd.v1.Githubd.VerifyInstallation:output_type -> onebox.faas.githubd.v1.VerifyInstallationResponse
	12, // [12:21] is the sub-list for method output_type
	3,  // [3:12] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_onebox_faas_githubd_v1_githubd_proto_init() }
func file_onebox_faas_githubd_v1_githubd_proto_init() {
	if File_onebox_faas_githubd_v1_githubd_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_onebox_faas_githubd_v1_githubd_proto_rawDesc), len(file_onebox_faas_githubd_v1_githubd_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_onebox_faas_githubd_v1_githubd_proto_goTypes,
		DependencyIndexes: file_onebox_faas_githubd_v1_githubd_proto_depIdxs,
		EnumInfos:         file_onebox_faas_githubd_v1_githubd_proto_enumTypes,
		MessageInfos:      file_onebox_faas_githubd_v1_githubd_proto_msgTypes,
	}.Build()
	File_onebox_faas_githubd_v1_githubd_proto = out.File
	file_onebox_faas_githubd_v1_githubd_proto_goTypes = nil
	file_onebox_faas_githubd_v1_githubd_proto_depIdxs = nil
}
