// githubd — the GitHub App integration daemon (spec §14 M7.5, ADR-012).
//
// githubd owns: push-webhook receiver, Checks-API status writer, OAuth
// callback handler, per-repo install-token cache. It is the SOLE
// outbound caller to api.github.com (Checks API + install token
// exchange); its inbound public surface is gatewayd-public at /webhooks/github
// (HMAC-verified at the edge per ADR-012).
//
// Wire discipline mirrors vmmd (ADR-013) and schedd (ADR-018):
// checked-in *.pb.go generated with paths=source_relative, errors
// enveloped through pkg/grpcerr, auth is the unix-socket DAC model
// (mode 0660 group `faas`, ADR-015) on /run/faas/githubd.sock.
//
// Re-evaluation triggers: see ADR-012.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// source: onebox/faas/githubd/v1/githubd.proto

package githubdpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Githubd_GetInstallState_FullMethodName          = "/onebox.faas.githubd.v1.Githubd/GetInstallState"
	Githubd_ExchangeOAuthCode_FullMethodName        = "/onebox.faas.githubd.v1.Githubd/ExchangeOAuthCode"
	Githubd_ListInstallableRepos_FullMethodName     = "/onebox.faas.githubd.v1.Githubd/ListInstallableRepos"
	Githubd_BindAppRepo_FullMethodName              = "/onebox.faas.githubd.v1.Githubd/BindAppRepo"
	Githubd_UnbindAppRepo_FullMethodName            = "/onebox.faas.githubd.v1.Githubd/UnbindAppRepo"
	Githubd_GetAppBinding_FullMethodName            = "/onebox.faas.githubd.v1.Githubd/GetAppBinding"
	Githubd_CreateDeploymentFromPush_FullMethodName = "/onebox.faas.githubd.v1.Githubd/CreateDeploymentFromPush"
	Githubd_EnqueueBuild_FullMethodName             = "/onebox.faas.githubd.v1.Githubd/EnqueueBuild"
	Githubd_WriteCheck_FullMethodName               = "/onebox.faas.githubd.v1.Githubd/WriteCheck"
	Githubd_VerifyInstallation_FullMethodName       = "/onebox.faas.githubd.v1.Githubd/VerifyInstallation"
	Githubd_MintInstallationToken_FullMethodName    = "/onebox.faas.githubd.v1.Githubd/MintInstallationToken"
	Githubd_StreamSourceRef_FullMethodName          = "/onebox.faas.githubd.v1.Githubd/StreamSourceRef"
	Githubd_ListRecoveryQueueItems_FullMethodName   = "/onebox.faas.githubd.v1.Githubd/ListRecoveryQueueItems"
	Githubd_RetryWebhookDelivery_FullMethodName     = "/onebox.faas.githubd.v1.Githubd/RetryWebhookDelivery"
	Githubd_RetryCheckUpdate_FullMethodName         = "/onebox.faas.githubd.v1.Githubd/RetryCheckUpdate"
)

// GithubdClient is the client API for Githubd service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Githubd is the gRPC service githubd exposes on its unix socket. apid
// is the only caller in v1.0 (the dashboard and CLI dial apid, not
// githubd). Multi-host (Gate-A) replaces the socket with mTLS; this
// ADR-012 surface is per-host.
type GithubdClient interface {
	// GetInstallState reports whether the GitHub App is installed for an
	// account and returns the installation_id + default_branch once
	// installed. NOT_INSTALLED is the launch state for every account
	// until the user finishes the OAuth dance.
	GetInstallState(ctx context.Context, in *GetInstallStateRequest, opts ...grpc.CallOption) (*GetInstallStateResponse, error)
	// ExchangeOAuthCode turns the GitHub OAuth code returned to the
	// callback URL into an installation record. githubd POSTs to
	// api.github.com/app/installations with the GitHub App JWT, then
	// persists the installation_id onto the account (server-side, no
	// token returned to the dashboard).
	ExchangeOAuthCode(ctx context.Context, in *ExchangeOAuthCodeRequest, opts ...grpc.CallOption) (*ExchangeOAuthCodeResponse, error)
	// ListInstallableRepos returns the catalog of repos the installation
	// has access to (the dashboard repo picker consumes this). Calls
	// api.github.com/installation/repositories with the install token.
	ListInstallableRepos(ctx context.Context, in *ListInstallableReposRequest, opts ...grpc.CallOption) (*ListInstallableReposResponse, error)
	// BindAppRepo associates an app with a repo (and production branch).
	// Persists into app_github_bindings. Idempotent on (app_id, repo).
	BindAppRepo(ctx context.Context, in *BindAppRepoRequest, opts ...grpc.CallOption) (*BindAppRepoResponse, error)
	// UnbindAppRepo removes an app↔repo binding. Webhook events for the
	// repo stop triggering deployments for the unbound app.
	UnbindAppRepo(ctx context.Context, in *UnbindAppRepoRequest, opts ...grpc.CallOption) (*UnbindAppRepoResponse, error)
	// GetAppBinding returns the current binding for an app, or empty
	// fields when the app is not bound to any repo.
	GetAppBinding(ctx context.Context, in *GetAppBindingRequest, opts ...grpc.CallOption) (*GetAppBindingResponse, error)
	// CreateDeploymentFromPush turns a verified GitHub push webhook into
	// a deployment row in apid's `deployments` table. githubd calls this
	// after gatewayd-public forwards the request and the HMAC check passes.
	// Returns the empty deployment_id when no app is bound to the repo
	// (a common case for forks / first-time installs).
	//
	// DEPRECATED (issue #432 phase 5 closure): the inbound-webhook path
	// is HTTP-only (gatewayd-public → /webhooks/github → githubd). The gRPC
	// surface was originally designed for repo-level dispatch but cannot
	// carry per-app build inputs (source_path on disk, source URL for
	// provenance). Issue #432 phase 5 closes the loop with EnqueueBuild
	// below, which carries the per-app build inputs and is the actual
	// tea path. This method stays checked in for the bufconn round-trip
	// test (slice 7) and to keep the gRPC contract additive.
	CreateDeploymentFromPush(ctx context.Context, in *CreateDeploymentFromPushRequest, opts ...grpc.CallOption) (*CreateDeploymentFromPushResponse, error)
	// EnqueueBuild is the githubd → apid bridge for per-app build
	// enqueue (issue #432 phase 5). After the dispatcher fans out the
	// touched apps (slice 1) and stages each app's RootDir subtree into
	// githubd's build-sources dir as a per-app .tar.gz, githubd calls
	// this RPC once per (app, commit_sha). apid creates the deployment
	// row (Kind=DeploymentKindGitHub), the build row, and emits the
	// build_queued pg_notify that builderd LISTENs on. The repo-level
	// CreateDeploymentFromPush above stays as a documented dead-letter
	// path; this RPC is the load-bearing one.
	//
	// Auth: the unix-socket 0660/group-`faas` DAC is the only auth in
	// v1.0 (ADR-015). The transport is insecure credentials over a
	// trusted local path; see pkg/githubdgrpc.Dial.
	EnqueueBuild(ctx context.Context, in *EnqueueBuildRequest, opts ...grpc.CallOption) (*EnqueueBuildResponse, error)
	// WriteCheck pushes a commit-status update back to GitHub via the
	// Checks API (POST /repos/{owner}/{repo}/check-runs). Idempotent on
	// (repo, sha, phase) via the check_runs dedupe row so redelivered
	// webhooks don't create duplicate checks.
	WriteCheck(ctx context.Context, in *WriteCheckRequest, opts ...grpc.CallOption) (*WriteCheckResponse, error)
	// VerifyInstallation confirms an installation_id returned by a
	// GitHub App install callback actually exists for this App. The
	// /oauth/callback handler in apid calls this before persisting
	// the (app → install_id) binding, so a forged callback can never
	// claim an install_id the customer doesn't own (review finding
	// #2 closure). githubd mints the App JWT + GETs
	// /app/installations/{id}; the response includes the install's
	// default_branch (used to seed BindAppRepo on the success path).
	//
	// PR-B adds expected_login: when non-empty, githubd returns
	// verified=false if the install's account.login does not match.
	// This closes the §11 install-takeover hole where any logged-in
	// FaaS account could adopt any installation_id the GitHub App
	// knew about (review finding #2 only closed the
	// install-belongs-to-the-app half; the install-belongs-to-the-user
	// half lands here).
	VerifyInstallation(ctx context.Context, in *VerifyInstallationRequest, opts ...grpc.CallOption) (*VerifyInstallationResponse, error)
	// MintInstallationToken returns a fresh installation token for
	// the given (account, installation_id). The token is the canonical
	// shape githubd's TokenCache hands out (pkg/githubd/tokencache.go)
	// — sealed in transit over the apid↔githubd unix socket, scoped
	// to the single RPC. apid's source-ref deploy handler calls this
	// to authenticate the codeload fetch when no installation is
	// available locally (DEPLOY-PROV-4 / ADR-092, issue #739).
	//
	// Errors:
	//   - NOT_FOUND when the durable install row is missing for the
	//     account (the dashboard `gregale connect` flow has not run).
	//   - UNAVAILABLE when githubd's TokenCache is mid-refresh and the
	//     api.github.com round-trip failed.
	MintInstallationToken(ctx context.Context, in *MintInstallationTokenRequest, opts ...grpc.CallOption) (*MintInstallationTokenResponse, error)
	// StreamSourceRef streams the raw tar.gz archive for a
	// (repo, ref) pair over the durable install's installation
	// token (DEPLOY-PROV-4 / ADR-092, issue #739). apid's
	// handleSourceRefDeploy calls this RPC, pipes the returned
	// bytes into validateAndSpool, and os.Renames the staged
	// file to FAAS_SPOOL_ROOT/<id>.tar.gz.
	//
	// The streaming wire shape is preferred over a unary
	// (io.ReadCloser-shaped) return so a Free-plan tarball that
	// exceeds SourceTarballMaxMB can be rejected mid-flight
	// (server-initiated cancellation) rather than buffered
	// entirely in memory. githubd applies
	// io.LimitReader(max_archive_bytes + 1, …) on the server
	// side; a cap overflow surfaces as a chunk carrying
	// `truncated=true` and the apid handler rolls the spool
	// file back.
	//
	// Errors:
	//   - NOT_FOUND when the durable install row is missing.
	//   - INVALID_ARGUMENT when the (repo, ref) fails
	//     validation.
	//   - UNAUTHENTICATED when the installation token is
	//     rejected by codeload.github.com after one
	//     cache-invalidate + retry (api maps to
	//     503 source_ref_unavailable per ADR-092 §3.7).
	//   - UNAVAILABLE when githubd is down or codeload
	//     returns 5xx.
	StreamSourceRef(ctx context.Context, in *StreamSourceRefRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StreamSourceRefChunk], error)
	// ListRecoveryQueueItems returns operator-safe projections of the durable
	// webhook-delivery inbox and Check Run outbox. Payloads are deliberately
	// excluded because they can contain customer repository metadata.
	ListRecoveryQueueItems(ctx context.Context, in *ListRecoveryQueueItemsRequest, opts ...grpc.CallOption) (*ListRecoveryQueueItemsResponse, error)
	// RetryWebhookDelivery and RetryCheckUpdate move one dead item back to its
	// pending state. Both operations are compare-and-swap writes: active or
	// already-retried items return retried=false and are left untouched.
	RetryWebhookDelivery(ctx context.Context, in *RetryWebhookDeliveryRequest, opts ...grpc.CallOption) (*RetryRecoveryItemResponse, error)
	RetryCheckUpdate(ctx context.Context, in *RetryCheckUpdateRequest, opts ...grpc.CallOption) (*RetryRecoveryItemResponse, error)
}

type githubdClient struct {
	cc grpc.ClientConnInterface
}

func NewGithubdClient(cc grpc.ClientConnInterface) GithubdClient {
	return &githubdClient{cc}
}

func (c *githubdClient) GetInstallState(ctx context.Context, in *GetInstallStateRequest, opts ...grpc.CallOption) (*GetInstallStateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetInstallStateResponse)
	err := c.cc.Invoke(ctx, Githubd_GetInstallState_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *githubdClient) ExchangeOAuthCode(ctx context.Context, in *ExchangeOAuthCodeRequest, opts ...grpc.CallOption) (*ExchangeOAuthCodeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExchangeOAuthCodeResponse)
	err := c.cc.Invoke(ctx, Githubd_ExchangeOAuthCode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *githubdClient) ListInstallableRepos(ctx context.Context, in *ListInstallableReposRequest, opts ...grpc.CallOption) (*ListInstallableReposResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListInstallableReposResponse)
	err := c.cc.Invoke(ctx, Githubd_ListInstallableRepos_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *githubdClient) BindAppRepo(ctx context.Context, in *BindAppRepoRequest, opts ...grpc.CallOption) (*BindAppRepoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BindAppRepoResponse)
	err := c.cc.Invoke(ctx, Githubd_BindAppRepo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *githubdClient) UnbindAppRepo(ctx context.Context, in *UnbindAppRepoRequest, opts ...grpc.CallOption) (*UnbindAppRepoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UnbindAppRepoResponse)
	err := c.cc.Invoke(ctx, Githubd_UnbindAppRepo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *githubdClient) GetAppBinding(ctx context.Context, in *GetAppBindingRequest, opts ...grpc.CallOption) (*GetAppBindingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAppBindingResponse)
	err := c.cc.Invoke(ctx, Githubd_GetAppBinding_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *githubdClient) CreateDeploymentFromPush(ctx context.Context, in *CreateDeploymentFromPushRequest, opts ...grpc.CallOption) (*CreateDeploymentFromPushResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateDeploymentFromPushResponse)
	err := c.cc.Invoke(ctx, Githubd_CreateDeploymentFromPush_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *githubdClient) EnqueueBuild(ctx context.Context, in *EnqueueBuildRequest, opts ...grpc.CallOption) (*EnqueueBuildResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EnqueueBuildResponse)
	err := c.cc.Invoke(ctx, Githubd_EnqueueBuild_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *githubdClient) WriteCheck(ctx context.Context, in *WriteCheckRequest, opts ...grpc.CallOption) (*WriteCheckResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WriteCheckResponse)
	err := c.cc.Invoke(ctx, Githubd_WriteCheck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *githubdClient) VerifyInstallation(ctx context.Context, in *VerifyInstallationRequest, opts ...grpc.CallOption) (*VerifyInstallationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VerifyInstallationResponse)
	err := c.cc.Invoke(ctx, Githubd_VerifyInstallation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *githubdClient) MintInstallationToken(ctx context.Context, in *MintInstallationTokenRequest, opts ...grpc.CallOption) (*MintInstallationTokenResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MintInstallationTokenResponse)
	err := c.cc.Invoke(ctx, Githubd_MintInstallationToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *githubdClient) StreamSourceRef(ctx context.Context, in *StreamSourceRefRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StreamSourceRefChunk], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Githubd_ServiceDesc.Streams[0], Githubd_StreamSourceRef_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamSourceRefRequest, StreamSourceRefChunk]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Githubd_StreamSourceRefClient = grpc.ServerStreamingClient[StreamSourceRefChunk]

func (c *githubdClient) ListRecoveryQueueItems(ctx context.Context, in *ListRecoveryQueueItemsRequest, opts ...grpc.CallOption) (*ListRecoveryQueueItemsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListRecoveryQueueItemsResponse)
	err := c.cc.Invoke(ctx, Githubd_ListRecoveryQueueItems_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *githubdClient) RetryWebhookDelivery(ctx context.Context, in *RetryWebhookDeliveryRequest, opts ...grpc.CallOption) (*RetryRecoveryItemResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RetryRecoveryItemResponse)
	err := c.cc.Invoke(ctx, Githubd_RetryWebhookDelivery_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *githubdClient) RetryCheckUpdate(ctx context.Context, in *RetryCheckUpdateRequest, opts ...grpc.CallOption) (*RetryRecoveryItemResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RetryRecoveryItemResponse)
	err := c.cc.Invoke(ctx, Githubd_RetryCheckUpdate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GithubdServer is the server API for Githubd service.
// All implementations must embed UnimplementedGithubdServer
// for forward compatibility.
//
// Githubd is the gRPC service githubd exposes on its unix socket. apid
// is the only caller in v1.0 (the dashboard and CLI dial apid, not
// githubd). Multi-host (Gate-A) replaces the socket with mTLS; this
// ADR-012 surface is per-host.
type GithubdServer interface {
	// GetInstallState reports whether the GitHub App is installed for an
	// account and returns the installation_id + default_branch once
	// installed. NOT_INSTALLED is the launch state for every account
	// until the user finishes the OAuth dance.
	GetInstallState(context.Context, *GetInstallStateRequest) (*GetInstallStateResponse, error)
	// ExchangeOAuthCode turns the GitHub OAuth code returned to the
	// callback URL into an installation record. githubd POSTs to
	// api.github.com/app/installations with the GitHub App JWT, then
	// persists the installation_id onto the account (server-side, no
	// token returned to the dashboard).
	ExchangeOAuthCode(context.Context, *ExchangeOAuthCodeRequest) (*ExchangeOAuthCodeResponse, error)
	// ListInstallableRepos returns the catalog of repos the installation
	// has access to (the dashboard repo picker consumes this). Calls
	// api.github.com/installation/repositories with the install token.
	ListInstallableRepos(context.Context, *ListInstallableReposRequest) (*ListInstallableReposResponse, error)
	// BindAppRepo associates an app with a repo (and production branch).
	// Persists into app_github_bindings. Idempotent on (app_id, repo).
	BindAppRepo(context.Context, *BindAppRepoRequest) (*BindAppRepoResponse, error)
	// UnbindAppRepo removes an app↔repo binding. Webhook events for the
	// repo stop triggering deployments for the unbound app.
	UnbindAppRepo(context.Context, *UnbindAppRepoRequest) (*UnbindAppRepoResponse, error)
	// GetAppBinding returns the current binding for an app, or empty
	// fields when the app is not bound to any repo.
	GetAppBinding(context.Context, *GetAppBindingRequest) (*GetAppBindingResponse, error)
	// CreateDeploymentFromPush turns a verified GitHub push webhook into
	// a deployment row in apid's `deployments` table. githubd calls this
	// after gatewayd-public forwards the request and the HMAC check passes.
	// Returns the empty deployment_id when no app is bound to the repo
	// (a common case for forks / first-time installs).
	//
	// DEPRECATED (issue #432 phase 5 closure): the inbound-webhook path
	// is HTTP-only (gatewayd-public → /webhooks/github → githubd). The gRPC
	// surface was originally designed for repo-level dispatch but cannot
	// carry per-app build inputs (source_path on disk, source URL for
	// provenance). Issue #432 phase 5 closes the loop with EnqueueBuild
	// below, which carries the per-app build inputs and is the actual
	// tea path. This method stays checked in for the bufconn round-trip
	// test (slice 7) and to keep the gRPC contract additive.
	CreateDeploymentFromPush(context.Context, *CreateDeploymentFromPushRequest) (*CreateDeploymentFromPushResponse, error)
	// EnqueueBuild is the githubd → apid bridge for per-app build
	// enqueue (issue #432 phase 5). After the dispatcher fans out the
	// touched apps (slice 1) and stages each app's RootDir subtree into
	// githubd's build-sources dir as a per-app .tar.gz, githubd calls
	// this RPC once per (app, commit_sha). apid creates the deployment
	// row (Kind=DeploymentKindGitHub), the build row, and emits the
	// build_queued pg_notify that builderd LISTENs on. The repo-level
	// CreateDeploymentFromPush above stays as a documented dead-letter
	// path; this RPC is the load-bearing one.
	//
	// Auth: the unix-socket 0660/group-`faas` DAC is the only auth in
	// v1.0 (ADR-015). The transport is insecure credentials over a
	// trusted local path; see pkg/githubdgrpc.Dial.
	EnqueueBuild(context.Context, *EnqueueBuildRequest) (*EnqueueBuildResponse, error)
	// WriteCheck pushes a commit-status update back to GitHub via the
	// Checks API (POST /repos/{owner}/{repo}/check-runs). Idempotent on
	// (repo, sha, phase) via the check_runs dedupe row so redelivered
	// webhooks don't create duplicate checks.
	WriteCheck(context.Context, *WriteCheckRequest) (*WriteCheckResponse, error)
	// VerifyInstallation confirms an installation_id returned by a
	// GitHub App install callback actually exists for this App. The
	// /oauth/callback handler in apid calls this before persisting
	// the (app → install_id) binding, so a forged callback can never
	// claim an install_id the customer doesn't own (review finding
	// #2 closure). githubd mints the App JWT + GETs
	// /app/installations/{id}; the response includes the install's
	// default_branch (used to seed BindAppRepo on the success path).
	//
	// PR-B adds expected_login: when non-empty, githubd returns
	// verified=false if the install's account.login does not match.
	// This closes the §11 install-takeover hole where any logged-in
	// FaaS account could adopt any installation_id the GitHub App
	// knew about (review finding #2 only closed the
	// install-belongs-to-the-app half; the install-belongs-to-the-user
	// half lands here).
	VerifyInstallation(context.Context, *VerifyInstallationRequest) (*VerifyInstallationResponse, error)
	// MintInstallationToken returns a fresh installation token for
	// the given (account, installation_id). The token is the canonical
	// shape githubd's TokenCache hands out (pkg/githubd/tokencache.go)
	// — sealed in transit over the apid↔githubd unix socket, scoped
	// to the single RPC. apid's source-ref deploy handler calls this
	// to authenticate the codeload fetch when no installation is
	// available locally (DEPLOY-PROV-4 / ADR-092, issue #739).
	//
	// Errors:
	//   - NOT_FOUND when the durable install row is missing for the
	//     account (the dashboard `gregale connect` flow has not run).
	//   - UNAVAILABLE when githubd's TokenCache is mid-refresh and the
	//     api.github.com round-trip failed.
	MintInstallationToken(context.Context, *MintInstallationTokenRequest) (*MintInstallationTokenResponse, error)
	// StreamSourceRef streams the raw tar.gz archive for a
	// (repo, ref) pair over the durable install's installation
	// token (DEPLOY-PROV-4 / ADR-092, issue #739). apid's
	// handleSourceRefDeploy calls this RPC, pipes the returned
	// bytes into validateAndSpool, and os.Renames the staged
	// file to FAAS_SPOOL_ROOT/<id>.tar.gz.
	//
	// The streaming wire shape is preferred over a unary
	// (io.ReadCloser-shaped) return so a Free-plan tarball that
	// exceeds SourceTarballMaxMB can be rejected mid-flight
	// (server-initiated cancellation) rather than buffered
	// entirely in memory. githubd applies
	// io.LimitReader(max_archive_bytes + 1, …) on the server
	// side; a cap overflow surfaces as a chunk carrying
	// `truncated=true` and the apid handler rolls the spool
	// file back.
	//
	// Errors:
	//   - NOT_FOUND when the durable install row is missing.
	//   - INVALID_ARGUMENT when the (repo, ref) fails
	//     validation.
	//   - UNAUTHENTICATED when the installation token is
	//     rejected by codeload.github.com after one
	//     cache-invalidate + retry (api maps to
	//     503 source_ref_unavailable per ADR-092 §3.7).
	//   - UNAVAILABLE when githubd is down or codeload
	//     returns 5xx.
	StreamSourceRef(*StreamSourceRefRequest, grpc.ServerStreamingServer[StreamSourceRefChunk]) error
	// ListRecoveryQueueItems returns operator-safe projections of the durable
	// webhook-delivery inbox and Check Run outbox. Payloads are deliberately
	// excluded because they can contain customer repository metadata.
	ListRecoveryQueueItems(context.Context, *ListRecoveryQueueItemsRequest) (*ListRecoveryQueueItemsResponse, error)
	// RetryWebhookDelivery and RetryCheckUpdate move one dead item back to its
	// pending state. Both operations are compare-and-swap writes: active or
	// already-retried items return retried=false and are left untouched.
	RetryWebhookDelivery(context.Context, *RetryWebhookDeliveryRequest) (*RetryRecoveryItemResponse, error)
	RetryCheckUpdate(context.Context, *RetryCheckUpdateRequest) (*RetryRecoveryItemResponse, error)
	mustEmbedUnimplementedGithubdServer()
}

// UnimplementedGithubdServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGithubdServer struct{}

func (UnimplementedGithubdServer) GetInstallState(context.Context, *GetInstallStateRequest) (*GetInstallStateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetInstallState not implemented")
}
func (UnimplementedGithubdServer) ExchangeOAuthCode(context.Context, *ExchangeOAuthCodeRequest) (*ExchangeOAuthCodeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ExchangeOAuthCode not implemented")
}
func (UnimplementedGithubdServer) ListInstallableRepos(context.Context, *ListInstallableReposRequest) (*ListInstallableReposResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListInstallableRepos not implemented")
}
func (UnimplementedGithubdServer) BindAppRepo(context.Context, *BindAppRepoRequest) (*BindAppRepoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method BindAppRepo not implemented")
}
func (UnimplementedGithubdServer) UnbindAppRepo(context.Context, *UnbindAppRepoRequest) (*UnbindAppRepoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UnbindAppRepo not implemented")
}
func (UnimplementedGithubdServer) GetAppBinding(context.Context, *GetAppBindingRequest) (*GetAppBindingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAppBinding not implemented")
}
func (UnimplementedGithubdServer) CreateDeploymentFromPush(context.Context, *CreateDeploymentFromPushRequest) (*CreateDeploymentFromPushResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateDeploymentFromPush not implemented")
}
func (UnimplementedGithubdServer) EnqueueBuild(context.Context, *EnqueueBuildRequest) (*EnqueueBuildResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method EnqueueBuild not implemented")
}
func (UnimplementedGithubdServer) WriteCheck(context.Context, *WriteCheckRequest) (*WriteCheckResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method WriteCheck not implemented")
}
func (UnimplementedGithubdServer) VerifyInstallation(context.Context, *VerifyInstallationRequest) (*VerifyInstallationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method VerifyInstallation not implemented")
}
func (UnimplementedGithubdServer) MintInstallationToken(context.Context, *MintInstallationTokenRequest) (*MintInstallationTokenResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method MintInstallationToken not implemented")
}
func (UnimplementedGithubdServer) StreamSourceRef(*StreamSourceRefRequest, grpc.ServerStreamingServer[StreamSourceRefChunk]) error {
	return status.Error(codes.Unimplemented, "method StreamSourceRef not implemented")
}
func (UnimplementedGithubdServer) ListRecoveryQueueItems(context.Context, *ListRecoveryQueueItemsRequest) (*ListRecoveryQueueItemsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListRecoveryQueueItems not implemented")
}
func (UnimplementedGithubdServer) RetryWebhookDelivery(context.Context, *RetryWebhookDeliveryRequest) (*RetryRecoveryItemResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RetryWebhookDelivery not implemented")
}
func (UnimplementedGithubdServer) RetryCheckUpdate(context.Context, *RetryCheckUpdateRequest) (*RetryRecoveryItemResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RetryCheckUpdate not implemented")
}
func (UnimplementedGithubdServer) mustEmbedUnimplementedGithubdServer() {}
func (UnimplementedGithubdServer) testEmbeddedByValue()                 {}

// UnsafeGithubdServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GithubdServer will
// result in compilation errors.
type UnsafeGithubdServer interface {
	mustEmbedUnimplementedGithubdServer()
}

func RegisterGithubdServer(s grpc.ServiceRegistrar, srv GithubdServer) {
	// If the following call panics, it indicates UnimplementedGithubdServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Githubd_ServiceDesc, srv)
}

func _Githubd_GetInstallState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetInstallStateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GithubdServer).GetInstallState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Githubd_GetInstallState_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GithubdServer).GetInstallState(ctx, req.(*GetInstallStateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Githubd_ExchangeOAuthCode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExchangeOAuthCodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GithubdServer).ExchangeOAuthCode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Githubd_ExchangeOAuthCode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GithubdServer).ExchangeOAuthCode(ctx, req.(*ExchangeOAuthCodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Githubd_ListInstallableRepos_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListInstallableReposRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GithubdServer).ListInstallableRepos(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Githubd_ListInstallableRepos_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GithubdServer).ListInstallableRepos(ctx, req.(*ListInstallableReposRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Githubd_BindAppRepo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BindAppRepoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GithubdServer).BindAppRepo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Githubd_BindAppRepo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GithubdServer).BindAppRepo(ctx, req.(*BindAppRepoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Githubd_UnbindAppRepo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnbindAppRepoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GithubdServer).UnbindAppRepo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Githubd_UnbindAppRepo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GithubdServer).UnbindAppRepo(ctx, req.(*UnbindAppRepoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Githubd_GetAppBinding_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAppBindingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GithubdServer).GetAppBinding(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Githubd_GetAppBinding_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GithubdServer).GetAppBinding(ctx, req.(*GetAppBindingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Githubd_CreateDeploymentFromPush_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateDeploymentFromPushRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GithubdServer).CreateDeploymentFromPush(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Githubd_CreateDeploymentFromPush_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GithubdServer).CreateDeploymentFromPush(ctx, req.(*CreateDeploymentFromPushRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Githubd_EnqueueBuild_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EnqueueBuildRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GithubdServer).EnqueueBuild(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Githubd_EnqueueBuild_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GithubdServer).EnqueueBuild(ctx, req.(*EnqueueBuildRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Githubd_WriteCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WriteCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GithubdServer).WriteCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Githubd_WriteCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GithubdServer).WriteCheck(ctx, req.(*WriteCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Githubd_VerifyInstallation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifyInstallationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GithubdServer).VerifyInstallation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Githubd_VerifyInstallation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GithubdServer).VerifyInstallation(ctx, req.(*VerifyInstallationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Githubd_MintInstallationToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MintInstallationTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GithubdServer).MintInstallationToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Githubd_MintInstallationToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GithubdServer).MintInstallationToken(ctx, req.(*MintInstallationTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Githubd_StreamSourceRef_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamSourceRefRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(GithubdServer).StreamSourceRef(m, &grpc.GenericServerStream[StreamSourceRefRequest, StreamSourceRefChunk]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Githubd_StreamSourceRefServer = grpc.ServerStreamingServer[StreamSourceRefChunk]

func _Githubd_ListRecoveryQueueItems_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRecoveryQueueItemsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GithubdServer).ListRecoveryQueueItems(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Githubd_ListRecoveryQueueItems_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GithubdServer).ListRecoveryQueueItems(ctx, req.(*ListRecoveryQueueItemsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Githubd_RetryWebhookDelivery_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RetryWebhookDeliveryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GithubdServer).RetryWebhookDelivery(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Githubd_RetryWebhookDelivery_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GithubdServer).RetryWebhookDelivery(ctx, req.(*RetryWebhookDeliveryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Githubd_RetryCheckUpdate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RetryCheckUpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GithubdServer).RetryCheckUpdate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Githubd_RetryCheckUpdate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GithubdServer).RetryCheckUpdate(ctx, req.(*RetryCheckUpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Githubd_ServiceDesc is the grpc.ServiceDesc for Githubd service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Githubd_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "onebox.faas.githubd.v1.Githubd",
	HandlerType: (*GithubdServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetInstallState",
			Handler:    _Githubd_GetInstallState_Handler,
		},
		{
			MethodName: "ExchangeOAuthCode",
			Handler:    _Githubd_ExchangeOAuthCode_Handler,
		},
		{
			MethodName: "ListInstallableRepos",
			Handler:    _Githubd_ListInstallableRepos_Handler,
		},
		{
			MethodName: "BindAppRepo",
			Handler:    _Githubd_BindAppRepo_Handler,
		},
		{
			MethodName: "UnbindAppRepo",
			Handler:    _Githubd_UnbindAppRepo_Handler,
		},
		{
			MethodName: "GetAppBinding",
			Handler:    _Githubd_GetAppBinding_Handler,
		},
		{
			MethodName: "CreateDeploymentFromPush",
			Handler:    _Githubd_CreateDeploymentFromPush_Handler,
		},
		{
			MethodName: "EnqueueBuild",
			Handler:    _Githubd_EnqueueBuild_Handler,
		},
		{
			MethodName: "WriteCheck",
			Handler:    _Githubd_WriteCheck_Handler,
		},
		{
			MethodName: "VerifyInstallation",
			Handler:    _Githubd_VerifyInstallation_Handler,
		},
		{
			MethodName: "MintInstallationToken",
			Handler:    _Githubd_MintInstallationToken_Handler,
		},
		{
			MethodName: "ListRecoveryQueueItems",
			Handler:    _Githubd_ListRecoveryQueueItems_Handler,
		},
		{
			MethodName: "RetryWebhookDelivery",
			Handler:    _Githubd_RetryWebhookDelivery_Handler,
		},
		{
			MethodName: "RetryCheckUpdate",
			Handler:    _Githubd_RetryCheckUpdate_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamSourceRef",
			Handler:       _Githubd_StreamSourceRef_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "onebox/faas/githubd/v1/githubd.proto",
}
