package devpatch

import (
	"os"
	"path/filepath"
	"reflect"
	"strings"
	"testing"

	"github.com/onebox-faas/faas/pkg/api"
)

// nodePlan mirrors the shape Railpack v0.38.0's Node provider generates (see
// testdata): the install step copies package.json and the lockfile from the
// local context, the build step consumes the full local source, and deploy
// copies the build step's "." into /app. buildCommands is spliced into the
// build step.
func nodePlan(buildCommands string) string {
	return `{
  "steps": [
    {"name": "packages:mise", "inputs": [{"image": "ghcr.io/railwayapp/railpack-builder:latest"}], "commands": [{"cmd": "mise install"}]},
    {"name": "install", "inputs": [{"step": "packages:mise"}],
     "commands": [{"path": "/app/node_modules/.bin"}, {"src": "package-lock.json", "dest": "package-lock.json"}, {"src": "package.json", "dest": "package.json"}, {"cmd": "npm ci"}]},
    {"name": "build", "inputs": [{"step": "install"}, {"local": true, "include": ["."]}], "commands": [` + buildCommands + `]}
  ],
  "deploy": {
    "base": {"image": "ghcr.io/railwayapp/railpack-runtime:latest"},
    "inputs": [{"step": "build", "include": ["/root/.cache", "."]}],
    "startCommand": "node server.js"
  }
}`
}

func TestClassifyRailpackPlan(t *testing.T) {
	cases := []struct {
		name string
		plan string
		want api.DevPatchSourceMap
	}{
		{
			name: "node without build script is verbatim",
			plan: nodePlan(`{"src": ".", "dest": "."}`),
			want: api.DevPatchSourceMap{Version: 1, Verbatim: true, ImageDir: "/app",
				RebuildPaths: []string{".gregaleignore", "gregale.yaml", "package-lock.json", "package.json", "railpack.json"}},
		},
		{
			name: "node with build script runs a command on the source",
			plan: nodePlan(`{"cmd": "npm run build"}`),
			want: api.DevPatchSourceMap{Version: 1, Reason: api.DevPatchReasonBuildCommand},
		},
		{
			name: "string-form RUN command counts as exec",
			plan: nodePlan(`"RUN npm run build"`),
			want: api.DevPatchSourceMap{Version: 1, Reason: api.DevPatchReasonBuildCommand},
		},
		{
			name: "string-form COPY command does not",
			plan: nodePlan(`"COPY . ."`),
			want: api.DevPatchSourceMap{Version: 1, Verbatim: true, ImageDir: "/app",
				RebuildPaths: []string{".gregaleignore", "gregale.yaml", "package-lock.json", "package.json", "railpack.json"}},
		},
		{
			name: "unknown command shape is treated as exec",
			plan: nodePlan(`{"weird": true}`),
			want: api.DevPatchSourceMap{Version: 1, Reason: api.DevPatchReasonBuildCommand},
		},
		{
			name: "downstream step transforming the source",
			plan: `{"steps": [
				{"name": "build", "inputs": [{"local": true, "include": ["."]}]},
				{"name": "compile", "inputs": [{"step": "build"}], "commands": [{"cmd": "tsc"}]}
			], "deploy": {"inputs": [{"step": "compile", "include": ["."]}]}}`,
			want: api.DevPatchSourceMap{Version: 1, Reason: api.DevPatchReasonBuildCommand},
		},
		{
			name: "filtered downstream step does not carry the source",
			plan: `{"steps": [
				{"name": "build", "inputs": [{"local": true, "include": ["."]}]},
				{"name": "prune", "inputs": [{"step": "build", "include": ["node_modules"]}], "commands": [{"cmd": "npm prune"}]}
			], "deploy": {"inputs": [{"step": "build", "include": ["."]}]}}`,
			want: api.DevPatchSourceMap{Version: 1, Verbatim: true, ImageDir: "/app",
				RebuildPaths: []string{".gregaleignore", "gregale.yaml", "railpack.json"}},
		},
		{
			name: "no step receives the full source",
			plan: `{"steps": [{"name": "install", "inputs": [{"local": true, "include": ["requirements.txt"]}]}], "deploy": {"inputs": [{"step": "install"}]}}`,
			want: api.DevPatchSourceMap{Version: 1, Reason: api.DevPatchReasonNoSourceLayer},
		},
		{
			name: "source never reaches the deploy image",
			plan: `{"steps": [{"name": "build", "inputs": [{"local": true, "include": ["."]}]}], "deploy": {"inputs": [{"step": "build", "include": ["dist"]}]}}`,
			want: api.DevPatchSourceMap{Version: 1, Reason: api.DevPatchReasonSourceNotDeployed},
		},
		{
			name: "unreadable plan",
			plan: `{"steps": 3`,
			want: api.DevPatchSourceMap{Version: 1, Reason: api.DevPatchReasonPlanUnreadable},
		},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			if got := ClassifyRailpackPlan([]byte(tc.plan)); !reflect.DeepEqual(got, tc.want) {
				t.Fatalf("ClassifyRailpackPlan = %+v, want %+v", got, tc.want)
			}
		})
	}
}

// The testdata plans were generated by `railpack prepare` v0.38.0 (the version
// pinned in images/builder-base.Dockerfile) for minimal sample apps.
func TestClassifyRealRailpackPlans(t *testing.T) {
	cases := []struct {
		file string
		want api.DevPatchSourceMap
	}{
		{"railpack-0.38.0-node-plain.json", api.DevPatchSourceMap{Version: 1, Verbatim: true, ImageDir: "/app",
			RebuildPaths: []string{".gregaleignore", "gregale.yaml", "package-lock.json", "package.json", "railpack.json"}}},
		{"railpack-0.38.0-node-build.json", api.DevPatchSourceMap{Version: 1, Reason: api.DevPatchReasonBuildCommand}},
		{"railpack-0.38.0-py-req.json", api.DevPatchSourceMap{Version: 1, Verbatim: true, ImageDir: "/app",
			RebuildPaths: []string{".gregaleignore", "gregale.yaml", "railpack.json", "requirements.txt"}}},
		// uv sync runs over the full source to install the project itself.
		{"railpack-0.38.0-py-uv.json", api.DevPatchSourceMap{Version: 1, Reason: api.DevPatchReasonBuildCommand}},
	}
	for _, tc := range cases {
		t.Run(tc.file, func(t *testing.T) {
			data, err := os.ReadFile(filepath.Join("testdata", tc.file))
			if err != nil {
				t.Fatal(err)
			}
			if got := ClassifyRailpackPlan(data); !reflect.DeepEqual(got, tc.want) {
				t.Fatalf("ClassifyRailpackPlan = %+v, want %+v", got, tc.want)
			}
		})
	}
}

func TestEvaluate(t *testing.T) {
	verbatim := &api.DevPatchSourceMap{Version: 1, Verbatim: true, ImageDir: "/app",
		RebuildPaths: []string{"package.json", "package-lock.json", "prisma", "*.lock", "railpack.json"}}
	file := func(p string, size int64) Change { return Change{Path: p, Regular: true, Size: size} }
	cases := []struct {
		name       string
		sourceMap  *api.DevPatchSourceMap
		sourceRoot string
		changes    []Change
		want       api.DevPatchPreview
	}{
		{name: "source edit", sourceMap: verbatim, changes: []Change{file("src/app.js", 120), file("views/index.html", 30)},
			want: api.DevPatchPreview{Eligible: true, ChangedPaths: 2, PatchBytes: 150}},
		{name: "deletion counts as a change", sourceMap: verbatim, changes: []Change{{Path: "src/old.js", Deleted: true}},
			want: api.DevPatchPreview{Eligible: true, ChangedPaths: 1}},
		{name: "directories are ignored", sourceMap: verbatim, changes: []Change{{Path: "src", Dir: true}, file("src/a.js", 1)},
			want: api.DevPatchPreview{Eligible: true, ChangedPaths: 1, PatchBytes: 1}},
		{name: "lockfile edit needs a build", sourceMap: verbatim, changes: []Change{file("src/a.js", 1), file("package-lock.json", 9)},
			want: api.DevPatchPreview{Reason: api.DevPatchReasonRebuildInput}},
		{name: "file inside a rebuild directory", sourceMap: verbatim, changes: []Change{file("prisma/schema.prisma", 1)},
			want: api.DevPatchPreview{Reason: api.DevPatchReasonRebuildInput}},
		{name: "glob rebuild input in a subdirectory", sourceMap: verbatim, changes: []Change{file("tools/yarn.lock", 1)},
			want: api.DevPatchPreview{Reason: api.DevPatchReasonRebuildInput}},
		{name: "symlink is unsupported", sourceMap: verbatim, changes: []Change{{Path: "src/link"}},
			want: api.DevPatchPreview{Reason: api.DevPatchReasonUnsupportedEntry}},
		{name: "workspace root strips the prefix", sourceMap: verbatim, sourceRoot: "apps/api",
			changes: []Change{file("apps/api/package.json", 1)},
			want:    api.DevPatchPreview{Reason: api.DevPatchReasonRebuildInput}},
		{name: "changes outside the workspace root need no patch", sourceMap: verbatim, sourceRoot: "apps/api",
			changes: []Change{file("apps/web/package.json", 1), file("apps/api/src/a.js", 4)},
			want:    api.DevPatchPreview{Eligible: true, ChangedPaths: 1, PatchBytes: 4}},
		{name: "too many files", sourceMap: verbatim, changes: manyFiles(api.DevPatchMaxEntries + 1),
			want: api.DevPatchPreview{Reason: api.DevPatchReasonTooLarge, ChangedPaths: api.DevPatchMaxEntries + 1, PatchBytes: int64(api.DevPatchMaxEntries + 1)}},
		{name: "too many bytes", sourceMap: verbatim, changes: []Change{file("assets/big.bin", api.DevPatchMaxBytes+1)},
			want: api.DevPatchPreview{Reason: api.DevPatchReasonTooLarge, ChangedPaths: 1, PatchBytes: api.DevPatchMaxBytes + 1}},
		{name: "no live build", changes: []Change{file("a.js", 1)},
			want: api.DevPatchPreview{Reason: api.DevPatchReasonNoLiveBuild}},
		{name: "non-verbatim build keeps its reason", sourceMap: &api.DevPatchSourceMap{Version: 1, Reason: api.DevPatchReasonBuildCommand},
			changes: []Change{file("a.js", 1)}, want: api.DevPatchPreview{Reason: api.DevPatchReasonBuildCommand}},
		{name: "future source map version", sourceMap: &api.DevPatchSourceMap{Version: 2, Verbatim: true},
			changes: []Change{file("a.js", 1)}, want: api.DevPatchPreview{Reason: api.DevPatchReasonUnsupportedVersion}},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			if got := Evaluate(tc.sourceMap, tc.sourceRoot, tc.changes); got != tc.want {
				t.Fatalf("Evaluate = %+v, want %+v", got, tc.want)
			}
		})
	}
}

func manyFiles(n int) []Change {
	changes := make([]Change, n)
	for i := range changes {
		changes[i] = Change{Path: "src/f" + strings.Repeat("x", i%7) + string(rune('a'+i%26)) + ".js", Regular: true, Size: 1}
	}
	return changes
}
