#!/usr/bin/env python3
"""Package durable entity guest protocol constants from pkg/api/limits.go."""
import argparse
import json
import re
import subprocess
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
NAMES = {
    "DurableEntityRestoreValidationProtocolVersion": ("DurableEntityRestoreValidationProtocolVersion", "DURABLE_ENTITY_RESTORE_VALIDATION_PROTOCOL_VERSION"),
    "DurableEntityRestoreValidationPath": ("DurableEntityRestoreValidationPath", "DURABLE_ENTITY_RESTORE_VALIDATION_PATH"),
    "MaxDurableEntityRestoreValidationBytes": ("DurableEntityRestoreValidationMaxResponseBytes", "DURABLE_ENTITY_RESTORE_VALIDATION_MAX_RESPONSE_BYTES"),
    "DurableEntityProtocolVersion": ("DurableEntityHandlerProtocolVersion", "DURABLE_ENTITY_PROTOCOL_VERSION"),
    "DurableEntityOutboxProtocolVersion": ("DurableEntityOutboxHandlerProtocolVersion", "DURABLE_ENTITY_OUTBOX_PROTOCOL_VERSION"),
    "MaxDurableEntityInvocationBytes": ("DurableEntityHandlerMaxRequestBytes", "DURABLE_ENTITY_MAX_REQUEST_BYTES"),
    "MaxDurableEntitySnapshotBytes": ("DurableEntityHandlerMaxTransitionBytes", "DURABLE_ENTITY_MAX_TRANSITION_BYTES"),
    "DurableEntityHandlerPath": ("DurableEntityHandlerPath", "DURABLE_ENTITY_HANDLER_PATH"),
}
LIMITS = {
    "MaxDurableEntitySnapshotBytes": "transition_bytes",
    "MaxDurableEntityIdentityBytes": "identity_bytes",
    "MaxDurableEntityOutboxPerTransition": "outbox_messages",
    "MaxDurableEntityOutboxPayloadBytes": "outbox_payload_bytes",
    "MaxDurableEntityOutboxBytes": "outbox_bytes",
}


def outputs():
    source = (ROOT / "pkg/api/limits.go").read_text()
    values = {}
    for name in dict.fromkeys([*NAMES, *LIMITS]):
        match = re.search(rf'^[ \t]*{name}[ \t]*=[ \t]*("[^"]*"|\d+(?:[ \t]*<<[ \t]*\d+)?)[ \t]*(?://[^\n]*)?$', source, re.MULTILINE)
        if match is None:
            raise ValueError(f"unsupported durable entity constant: {name}")
        expression = match[1]
        if expression.startswith('"'):
            values[name] = json.loads(expression)
        else:
            parts = expression.split("<<")
            values[name] = int(parts[0]) << (int(parts[1]) if len(parts) == 2 else 0)
    header = "Generated by scripts/gen-durable-entity-contract.py; DO NOT EDIT."
    go = f"// {header}\npackage faas\n\nconst (\n"
    node = f"// {header}\n"
    for name, (go_name, node_name) in NAMES.items():
        value = json.dumps(values[name])
        go += f"\t{go_name} = {value}\n"
        node += f"export const {node_name} = {value};\n"
    go += ")\n"
    go = subprocess.run(["gofmt"], input=go, text=True, capture_output=True, check=True).stdout
    request = {
        "protocol_version": values["DurableEntityOutboxProtocolVersion"], "event": "invoke",
        "entity": {"account_id": "159414db-faa3-436c-b50b-0c6b11e16ee9", "app_id": "fd0b721d-ec7c-44a0-a368-d4e769d996c9",
                   "environment_id": "91b40df9-02eb-456e-bc56-2726847583f9", "tenant_id": "6bbc0b40-4da3-4b65-936c-59a2bc0db9de",
                   "namespace": "reservations", "key": "reservation:123"},
        "request_id": "reserve-123", "payload": {"action": "reserve", "quantity": 2},
        "state": {"data": {}, "version": 0}, "deployment_id": "c5cbb16d-b633-4d19-9603-84be32fb812c",
        "limits": {alias: values[name] for name, alias in LIMITS.items()},
    }
    transition = {
        "data": {"status": "reserved", "quantity": 2}, "result": {"status": "reserved", "quantity": 2},
        "outbox": [{"webhook_id": "6dd283da-3c14-40de-9d47-bb71fb35be9a", "event_type": "reservation.confirmed",
                    "payload": {"reservation_key": "reservation:123", "quantity": 2}}],
    }
    return {
        "sdk/go/durable_entity_contract.go": go, "sdk/node/src/durable-entity-contract.ts": node,
        "sdk/go/testdata/durable-entity-handler-request.json": json.dumps(request, indent=2) + "\n",
        "sdk/go/testdata/durable-entity-handler-transition.json": json.dumps(transition, indent=2) + "\n",
    }


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    for name, content in outputs().items():
        path = ROOT / name
        if args.check:
            if not path.exists() or path.read_text() != content:
                raise SystemExit(f"durable entity contract drift: {name}; run {Path(__file__).name}")
        else:
            path.write_text(content)


if __name__ == "__main__":
    main()
