#!/usr/bin/env python3
"""Package both operation receipt schemas and platform limits in all three SDKs."""
import argparse
import json
import re
import subprocess
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
NAMES = {
    "OperationArtifactUploadDefaultBytes": "UPLOAD_DEFAULT_BYTES",
    "OperationReportIDMaxBytes": "REPORT_ID_BYTES",
    "OperationArtifactNameMaxBytes": "ARTIFACT_NAME_BYTES",
    "OperationMilestonePayloadMaxBytes": "MILESTONE_PAYLOAD_BYTES",
    "OperationMilestoneBatchMaxBytes": "MILESTONE_BATCH_BYTES",
    "OperationMilestonesMaxPerOperation": "MILESTONES",
    "OperationWorkflowStateReportsMaxPerTransaction": "WORKFLOW_STATE_REPORTS",
    "OperationWorkflowStateBatchMaxBytes": "WORKFLOW_STATE_BATCH_BYTES",
    "OperationWorkflowBlockerActorMaxBytes": "WORKFLOW_BLOCKER_ACTOR_BYTES",
    "OperationWorkflowBlockerActionMaxBytes": "WORKFLOW_BLOCKER_ACTION_BYTES",
    "OperationWorkflowBlockerImpactMaxBytes": "WORKFLOW_BLOCKER_IMPACT_BYTES",
    "OperationSubjectIDMaxBytes": "SUBJECT_ID_BYTES",
    "MaxExclusiveRequestBytes": "REQUEST_BYTES",
    "MaxExclusiveIdentityBytes": "IDENTITY_BYTES",
    "MaxExclusiveResultBytes": "RESPONSE_BYTES",
    "MaxExclusiveEffectsPerCommit": "EFFECTS",
    "MaxExclusiveEffectPayloadBytes": "PAYLOAD_BYTES",
    "MaxExclusiveEffectTypeBytes": "TYPE_BYTES",
}


def outputs():
    schema = (ROOT / "pkg/operationinbox/schema.sql").read_text()
    customer_schema = (ROOT / "pkg/operationinbox/customer_schema.sql").read_text()
    limits = (ROOT / "pkg/api/limits.go").read_text()
    values = {}
    for name, alias in NAMES.items():
        match = re.search(rf"^\s*{name}\s*=\s*(\d+)(?:\s*<<\s*(\d+))?\s*$", limits, re.MULTILINE)
        if match is None:
            raise ValueError(f"unsupported limit expression: {name}")
        values[alias] = int(match[1]) << int(match[2] or 0)
    if f"BETWEEN 1 AND {values['RESPONSE_BYTES']}" not in schema:
        raise ValueError("customer schema response bound differs from pkg/api/limits.go")
    if f"BETWEEN 1 AND {values['RESPONSE_BYTES']}" not in customer_schema:
        raise ValueError("customer operation response bound differs from pkg/api/limits.go")
    header = "Generated by scripts/gen-operation-inbox-schema.py; DO NOT EDIT."
    output = {
        # Keep the Go SDK's unit tests self-contained in its nested module.
        "sdk/go/testdata/customer-operation-request.json": (ROOT / "sdk/operation-tests/customer-request-fixture.json").read_text(),
        "sdk/go/testdata/operation-request.json": (ROOT / "sdk/operation-tests/request-fixture.json").read_text(),
        "sdk/go/operation_schema.sql": schema,
        "sdk/go/customer_operation_schema.sql": customer_schema,
        "sdk/python/faas_sdk/operation_schema.sql": schema,
        "sdk/python/faas_sdk/customer_operation_schema.sql": customer_schema,
        "sdk/node/src/operation-contract.ts": f"// {header}\nexport const operationReceiptSchema = {json.dumps(schema)};\n"
        + f"export const customerOperationReceiptSchema = {json.dumps(customer_schema)};\n"
        + "".join(f"export const OPERATION_{key} = {value};\n" for key, value in values.items()),
        "sdk/python/faas_sdk/_operation_contract.py": f"# {header}\n"
        + "".join(f"OPERATION_{key} = {value}\n" for key, value in values.items()),
        "sdk/go/operation_limits.go": f"// {header}\npackage faas\n\nconst (\n"
        + "".join(f"\toperation{key.title().replace('_', '')} = {value}\n" for key, value in values.items())
        + ")\n",
    }
    output["sdk/go/operation_limits.go"] = subprocess.run(
        ["gofmt"], input=output["sdk/go/operation_limits.go"], text=True, capture_output=True, check=True
    ).stdout
    return output


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    for name, content in outputs().items():
        path = ROOT / name
        if args.check:
            if not path.exists() or path.read_text() != content:
                raise SystemExit(f"operation contract drift: {name}; run {Path(__file__).name}")
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content)


if __name__ == "__main__":
    main()
