#!/usr/bin/env bash
# scripts/pre-release-check.sh — Automated pre-release verification gate for Gregale FaaS.
#
# Verifies:
#  1. Materializes the production split-box manifest from its topology
#     template and validates the generated release identity.
#  2. Computes the generated manifest hash from the exact bytes that will be
#     published with the signed bundle.
#  3. Unit test suite passes cleanly across all packages.
#  4. Local canonical daemon tarball build simulation.
#  5. Builds the canonical daemon bundle against those exact generated bytes.
#
set -euo pipefail

REPO_ROOT=$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)
MANIFEST_TEMPLATE="${1:-$REPO_ROOT/deploy/manifest/production/gcp-live.template.yaml}"
CURRENT_GIT_SHA=$(git -C "$REPO_ROOT" rev-parse HEAD)
RUNTIME_BASES_ENV="${RUNTIME_BASES_ENV:-}"
MANIFEST_PATH=$(mktemp "${TMPDIR:-/tmp}/gregale-production-manifest.XXXXXX.yaml")
SIM_OUT_DIR=""
cleanup() {
  rm -f "$MANIFEST_PATH"
  if [[ -n "$SIM_OUT_DIR" ]]; then
    rm -rf "$SIM_OUT_DIR"
  fi
}
trap cleanup EXIT

echo "============================================================"
echo "  Gregale Pre-Release Candidate Verification Gate"
echo "============================================================"
echo "Manifest template: $MANIFEST_TEMPLATE"

if [[ ! -f "$MANIFEST_TEMPLATE" ]]; then
  echo "[-] ERROR: Manifest template not found: $MANIFEST_TEMPLATE" >&2
  exit 1
fi
if [[ -z "$RUNTIME_BASES_ENV" || ! -f "$RUNTIME_BASES_ENV" ]]; then
  echo "[-] ERROR: set RUNTIME_BASES_ENV to the generated digest-pinned runtime contract." >&2
  exit 1
fi

echo ""
echo "[1/5] Materializing and validating production deployment manifest..."
"$REPO_ROOT/scripts/materialize-release-manifest.sh" \
  --template "$MANIFEST_TEMPLATE" \
  --git-sha "$CURRENT_GIT_SHA" \
  --runtime-bases-env "$RUNTIME_BASES_ENV" \
  --output "$MANIFEST_PATH"
go run "$REPO_ROOT/cmd/gregalectl" manifest validate --file="$MANIFEST_PATH"
echo "[+] Manifest validation passed."

echo ""
echo "[2/5] Checking generated release identity..."
echo "  Current HEAD: $CURRENT_GIT_SHA"

MANIFEST_GIT_SHA=$(grep 'git_sha:' "$MANIFEST_PATH" | awk '{print $2}' | tr -d '"' | tr -d "'")
echo "  Manifest SHA: $MANIFEST_GIT_SHA"

if [[ "$CURRENT_GIT_SHA" != "$MANIFEST_GIT_SHA" ]]; then
  echo "[-] ERROR: generated manifest git_sha does not match current HEAD." >&2
  exit 1
fi
echo "[+] Git SHA alignment confirmed."

echo ""
echo "[3/5] Computing release manifest hash..."
if command -v sha256sum >/dev/null 2>&1; then
  RAW_HASH=$(sha256sum "$MANIFEST_PATH" | awk '{print $1}')
elif command -v shasum >/dev/null 2>&1; then
  RAW_HASH=$(shasum -a 256 "$MANIFEST_PATH" | awk '{print $1}')
else
  echo "[-] ERROR: Neither sha256sum nor shasum found." >&2
  exit 1
fi
MANIFEST_HASH="sha256:$RAW_HASH"
echo "  generated manifest hash=$MANIFEST_HASH"

echo ""
echo "[4/5] Running Go unit test suite..."
go -C "$REPO_ROOT" test ./pkg/... ./cmd/... ./guest/...
echo "[+] Unit test suite passed."

echo ""
echo "[5/5] Testing canonical daemon bundle build..."
SIM_OUT_DIR=$(mktemp -d "${TMPDIR:-/tmp}/gregale-preflight-bundle.XXXXXX")

GIT_SHA="$CURRENT_GIT_SHA" \
MANIFEST_FILE="$MANIFEST_PATH" \
OUT_DIR="$SIM_OUT_DIR" \
"$REPO_ROOT/scripts/build-canonical-tarball.sh"

if [[ -f "$SIM_OUT_DIR/release.tar.gz" && -f "$SIM_OUT_DIR/release-manifest.json" ]]; then
  echo "[+] Canonical tarball built successfully: $(ls -lh "$SIM_OUT_DIR/release.tar.gz" | awk '{print $5}')"
else
  echo "[-] ERROR: Canonical tarball build failed to produce release artifacts." >&2
  exit 1
fi

echo ""
echo "============================================================"
echo "  Pre-Release Check Summary: ALL CHECKS PASSED (GREEN)"
echo "============================================================"
echo ""
echo "Next Operator Steps:"
echo "1. Tag and push an explicitly pre-1.0 release candidate (e.g. v0.1.7-rc.1):"
echo "   git tag -a v0.1.7-rc.1 -m \"Release candidate v0.1.7-rc.1\""
echo "   git push origin v0.1.7-rc.1"
echo "2. Download production-manifest.yaml from the GitHub release for deployment."
echo "3. Install the signed release bundle across the fleet."
echo "4. Run deep diagnostic verification:"
echo "   gregalectl doctor --deep"
echo "============================================================"
