#!/usr/bin/env bash
# scripts/install-go.sh — install Go (pinned) into the image at /usr/local/go.
#
# ADR-111 + ADR-005: image bakes a Go toolchain at a specific version so the
# compiled daemons are reproducible across boxes. Version matches CI's
# pinned GO_VERSION (1.26.9) so the gofmt byte-equivalence gate holds.
#
# Pattern: curl + sha256 + tar (no `curl | tar -xz`; mirrors the
# codeql-go-clear-text-logging-obfuscator-barrier lesson).
set -euo pipefail

GO_VERSION="${GO_VERSION:-1.26.9}"
# SHA-256 of go1.26.9.linux-amd64.tar.gz from https://go.dev/dl/.
# Pinned; CI install-golang uses the same value (action v5).
GO_SHA="42d158b4d8f7b61ac0a830567c940a86098fb7aac52e467a5ebec03ef5cc2f8d"
URL="https://go.dev/dl/go${GO_VERSION}.linux-amd64.tar.gz"

TMP="$(mktemp -d)"
trap 'rm -rf "${TMP}"' EXIT

echo "install-go: downloading go ${GO_VERSION}…"
curl --fail --silent --show-error --location --retry 3 --retry-delay 2 \
    -o "${TMP}/go.tar.gz" "${URL}"

echo "${GO_SHA}  ${TMP}/go.tar.gz" | sha256sum --check --strict

# Remove any prior install at /usr/local/go (idempotent re-build).
rm -rf /usr/local/go
tar -C /usr/local -xzf "${TMP}/go.tar.gz"

# Add to PATH for the rest of the build. The image's /etc/profile.d/go.sh
# is generated by build-base.sh.
ln -sf /usr/local/go/bin/go /usr/local/bin/go
ln -sf /usr/local/go/bin/gofmt /usr/local/bin/gofmt

echo "install-go: $(go version)"
