package main

import (
	"bytes"
	"encoding/json"
	"net/http"
	"net/http/httptest"
	"os"
	"path/filepath"
	"strconv"
	"strings"
	"testing"

	"github.com/onebox-faas/faas/pkg/api"
)

func TestRenderGithubSetupWorkflow(t *testing.T) {
	workflow := renderGithubSetupWorkflow("api", "acme/api", "release/canary", githubSetupRolloutStandard, nil, "")
	for _, want := range []string{
		"generated by `gregale github setup`",
		"branches:\n      - \"release/canary\"",
		"if: ${{ github.event_name != 'workflow_dispatch' || github.ref == 'refs/heads/release/canary' }}",
		"name: ${{ 'production' }}",
		"environment: ${{ '' }}",
		"tags:\n      - \"v*\"",
		"poyrazK/faas/.github/actions/deploy@v0",
		"# Action: poyrazK/faas/.github/actions/deploy@v0",
		`wait: "true"`,
		"concurrency:\n  group: gregale-${{ github.repository }}-api-${{ 'default' }}",
		"cancel-in-progress: false",
		"PR previews are managed by the connected GitHub integration.",
	} {
		if !strings.Contains(workflow, want) {
			t.Errorf("workflow does not contain %q:\n%s", want, workflow)
		}
	}
	if strings.Contains(workflow, "pull_request:") {
		t.Fatal("production workflow must not deploy on pull_request events")
	}
	if strings.Contains(workflow, `rollout: "safe"`) {
		t.Fatal("standard production workflow must not opt into safe rollout")
	}
}

func TestRenderGithubSetupWorkflowSafeRollout(t *testing.T) {
	workflow := renderGithubSetupWorkflow("api", "acme/api", "main", githubSetupRolloutSafe, nil, "")
	for _, want := range []string{
		"# Balanced health-gated rollout; available on Pro/Scale.",
		`rollout: "safe"`,
		`wait: "true"`,
	} {
		if !strings.Contains(workflow, want) {
			t.Errorf("safe workflow does not contain %q:\n%s", want, workflow)
		}
	}
}

func TestRenderGithubSetupWorkflowRoutesMappedBranches(t *testing.T) {
	workflow := renderGithubSetupWorkflow("api", "acme/api", "main", githubSetupRolloutStandard, map[string]string{
		"staging": "staging",
		"qa":      "default",
		"main":    "production",
	}, "")
	for _, want := range []string{
		"branches:\n      - \"main\"\n      - \"qa\"\n      - \"staging\"",
		"github.ref == 'refs/heads/main' || github.ref == 'refs/heads/qa' || github.ref == 'refs/heads/staging'",
		"name: ${{ github.ref == 'refs/heads/main' && 'production' || github.ref == 'refs/heads/staging' && 'staging' || 'production' }}",
		"environment: ${{ github.ref == 'refs/heads/main' && 'production' || github.ref == 'refs/heads/staging' && 'staging' || '' }}",
		"group: gregale-${{ github.repository }}-api-${{ github.ref == 'refs/heads/main' && 'production' || github.ref == 'refs/heads/staging' && 'staging' || 'default' }}",
	} {
		if !strings.Contains(workflow, want) {
			t.Errorf("mapped workflow does not contain %q:\n%s", want, workflow)
		}
	}
	if strings.Contains(workflow, "refs/heads/qa' && 'default'") {
		t.Fatal("default scope must omit the registered project environment input")
	}
}

func TestRenderGithubSetupWorkflowEscapesExpressionBranchNames(t *testing.T) {
	workflow := renderGithubSetupWorkflow("api", "acme/api", "main", githubSetupRolloutStandard, map[string]string{
		"release/o'hara": "staging",
	}, "")
	for _, want := range []string{
		`- "release/o'hara"`,
		`github.ref == 'refs/heads/release/o''hara'`,
	} {
		if !strings.Contains(workflow, want) {
			t.Errorf("quoted workflow does not contain %q:\n%s", want, workflow)
		}
	}
}

func TestRenderGithubSetupWorkflowPinsDeployAction(t *testing.T) {
	sha := "f1e2d3c4b5a6987654321098765432109abcdef0"
	workflow := renderGithubSetupWorkflow("api", "acme/api", "main", githubSetupRolloutStandard, nil, sha)
	for _, want := range []string{
		"# Action: poyrazK/faas/.github/actions/deploy@" + sha,
		"uses: poyrazK/faas/.github/actions/deploy@" + sha,
	} {
		if !strings.Contains(workflow, want) {
			t.Errorf("pinned workflow does not contain %q:\n%s", want, workflow)
		}
	}
	if strings.Contains(workflow, "@v0") {
		t.Fatalf("pinned workflow still uses moving tag:\n%s", workflow)
	}
}

func TestCmdGithubSetupRestoresWorkflowWhenPolicyUpdateFails(t *testing.T) {
	for _, existed := range []bool{false, true} {
		t.Run(strconv.FormatBool(existed), func(t *testing.T) {
			repoDir := t.TempDir()
			if err := os.Mkdir(filepath.Join(repoDir, ".git"), 0o755); err != nil {
				t.Fatal(err)
			}
			t.Chdir(repoDir)
			path := filepath.Join(repoDir, defaultGithubSetupWorkflow)
			previous := []byte("name: existing\n")
			if existed {
				if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
					t.Fatal(err)
				}
				if err := os.WriteFile(path, previous, 0o644); err != nil {
					t.Fatal(err)
				}
			}
			srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
				if r.Method == http.MethodGet && r.URL.Path == "/v1/apps/api/github" {
					_, _ = w.Write([]byte(`{"connected":true,"installation_id":42,"repo_full_name":"acme/api","production_branch":"main"}`))
					return
				}
				if r.Method == http.MethodPatch && r.URL.Path == "/v1/apps/api/github/deployment-policy" {
					http.Error(w, "policy update failed", http.StatusInternalServerError)
					return
				}
				http.NotFound(w, r)
			}))
			defer srv.Close()
			t.Setenv("FAAS_API", srv.URL)
			t.Setenv("FAAS_TOKEN", "fp_live_test")
			args := []string{"api"}
			if existed {
				args = append(args, "--force")
			}
			if code := cmdGithubSetup(args); code == 0 {
				t.Fatal("setup succeeded despite failed policy update")
			}
			data, err := os.ReadFile(path)
			if existed {
				if err != nil || !bytes.Equal(data, previous) {
					t.Fatalf("workflow after rollback = %q, %v", data, err)
				}
			} else if !os.IsNotExist(err) {
				t.Fatalf("new workflow remained after rollback: %q, %v", data, err)
			}
		})
	}
}

func TestValidGithubSetupRollout(t *testing.T) {
	for _, tc := range []struct {
		value string
		want  bool
	}{
		{githubSetupRolloutStandard, true},
		{githubSetupRolloutSafe, true},
		{"", false},
		{"balanced", false},
	} {
		if got := validGithubSetupRollout(tc.value); got != tc.want {
			t.Errorf("validGithubSetupRollout(%q) = %t, want %t", tc.value, got, tc.want)
		}
	}
}

func TestGithubSetupPreviewServicePolicy(t *testing.T) {
	for _, tc := range []struct {
		value string
		want  bool
	}{
		{githubSetupPreviewServicesDeny, true},
		{githubSetupPreviewServicesAllowMarked, true},
		{"allow", false},
		{"", false},
	} {
		if got := validGithubSetupPreviewServicePolicy(tc.value); got != tc.want {
			t.Errorf("validGithubSetupPreviewServicePolicy(%q) = %t, want %t", tc.value, got, tc.want)
		}
	}
	patch := githubSetupPolicyPatch(false, false, 0, "", nil, githubSetupPreviewServicesDeny)
	if patch == nil || patch.PreviewServicePolicy == nil || *patch.PreviewServicePolicy != githubSetupPreviewServicesDeny {
		t.Fatalf("preview service policy patch = %+v", patch)
	}
}

func TestGithubSetupWorkflowPathRejectsEscape(t *testing.T) {
	for _, path := range []string{"/tmp/workflow.yml", "../workflow.yml", "..", "."} {
		if _, err := githubSetupWorkflowPath(path); err == nil {
			t.Errorf("githubSetupWorkflowPath(%q) accepted repository escape", path)
		}
	}
	if got, err := githubSetupWorkflowPath(".github/workflows/gregale.yml"); err != nil || got != filepath.Join(".github", "workflows", "gregale.yml") {
		t.Fatalf("valid workflow path = %q, err = %v", got, err)
	}
}

func TestCmdGithubSetupBindsAndIsIdempotent(t *testing.T) {
	repoDir := t.TempDir()
	if err := os.Mkdir(filepath.Join(repoDir, ".git"), 0o755); err != nil {
		t.Fatal(err)
	}
	t.Chdir(repoDir)

	var bindRequest api.InstallBindRequest
	var bindCalls int
	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Content-Type", "application/json")
		switch {
		case r.Method == http.MethodGet && r.URL.Path == "/v1/apps/api/github":
			_, _ = w.Write([]byte(`{"connected":true,"installation_id":42,"repo_full_name":"acme/api","production_branch":"main"}`))
		case r.Method == http.MethodPost && r.URL.Path == "/v1/apps/api/github/bind":
			bindCalls++
			if err := json.NewDecoder(r.Body).Decode(&bindRequest); err != nil {
				t.Errorf("decode bind request: %v", err)
			}
			_, _ = w.Write([]byte(`{"binding_id":"bind-1","repo_full_name":"acme/api","production_branch":"trunk"}`))
		case r.Method == http.MethodPatch && r.URL.Path == "/v1/apps/api/github/deployment-policy":
			var patch api.GitHubDeploymentPolicyPatch
			if err := json.NewDecoder(r.Body).Decode(&patch); err != nil || patch.ProductionTrigger == nil || *patch.ProductionTrigger != "actions" {
				t.Errorf("invalid setup policy patch: %+v, %v", patch, err)
			}
			_, _ = w.Write([]byte(`{"project_id":"project-1","production_trigger":"actions"}`))
		default:
			http.NotFound(w, r)
		}
	}))
	defer srv.Close()
	t.Setenv("FAAS_API", srv.URL)
	t.Setenv("FAAS_TOKEN", "fp_live_test")

	oldOut, oldJSON := osStdout, jsonOutput
	var out bytes.Buffer
	osStdout, jsonOutput = &out, false
	t.Cleanup(func() { osStdout, jsonOutput = oldOut, oldJSON })

	args := []string{"api", "--repo", "acme/api", "--production-branch", "trunk", "--deploy-branches", "main=production,staging=staging"}
	if code := cmdGithubSetup(args); code != 0 {
		t.Fatalf("first setup exit = %d, output = %s", code, out.String())
	}
	workflowPath := filepath.Join(repoDir, defaultGithubSetupWorkflow)
	workflow, err := os.ReadFile(workflowPath)
	if err != nil {
		t.Fatalf("read generated workflow: %v", err)
	}
	if !strings.Contains(string(workflow), `- "trunk"`) || !strings.Contains(string(workflow), `- "staging"`) || !strings.Contains(string(workflow), `&& 'staging' || '' }}`) || strings.Contains(string(workflow), "pull_request:") {
		t.Fatalf("unexpected workflow:\n%s", workflow)
	}
	if bindRequest.InstallationID != 42 || bindRequest.RepoFullName != "acme/api" || bindRequest.ProductionBranch != "trunk" || bindRequest.DeployBranches["main"] != "production" {
		t.Fatalf("bind request = %+v", bindRequest)
	}
	if bindCalls != 1 {
		t.Fatalf("bind calls after first setup = %d", bindCalls)
	}

	out.Reset()
	if code := cmdGithubSetup(args); code != 0 {
		t.Fatalf("idempotent setup exit = %d, output = %s", code, out.String())
	}
	if bindCalls != 2 {
		t.Fatalf("bind calls after second setup = %d", bindCalls)
	}
	workflowAgain, err := os.ReadFile(workflowPath)
	if err != nil {
		t.Fatal(err)
	}
	if !bytes.Equal(workflow, workflowAgain) {
		t.Fatal("idempotent setup changed the workflow")
	}
	if !strings.Contains(out.String(), "already matches") {
		t.Fatalf("expected idempotent receipt, got %s", out.String())
	}
}

func TestCmdGithubSetupUsesSavedDeployBranchMappings(t *testing.T) {
	repoDir := t.TempDir()
	if err := os.Mkdir(filepath.Join(repoDir, ".git"), 0o755); err != nil {
		t.Fatal(err)
	}
	t.Chdir(repoDir)
	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Content-Type", "application/json")
		switch {
		case r.Method == http.MethodGet && r.URL.Path == "/v1/apps/api/github":
			_, _ = w.Write([]byte(`{"connected":true,"installation_id":42,"repo_full_name":"acme/api","production_branch":"main","deploy_branches":{"staging":"staging"}}`))
		case r.Method == http.MethodPatch && r.URL.Path == "/v1/apps/api/github/deployment-policy":
			_, _ = w.Write([]byte(`{"project_id":"project-1","production_trigger":"actions"}`))
		default:
			http.NotFound(w, r)
		}
	}))
	defer srv.Close()
	t.Setenv("FAAS_API", srv.URL)
	t.Setenv("FAAS_TOKEN", "fp_live_test")

	oldOut, oldJSON := osStdout, jsonOutput
	var out bytes.Buffer
	osStdout, jsonOutput = &out, false
	t.Cleanup(func() { osStdout, jsonOutput = oldOut, oldJSON })

	if code := cmdGithubSetup([]string{"api"}); code != 0 {
		t.Fatalf("setup exit = %d, output = %s", code, out.String())
	}
	workflow, err := os.ReadFile(filepath.Join(repoDir, defaultGithubSetupWorkflow))
	if err != nil {
		t.Fatalf("read generated workflow: %v", err)
	}
	for _, want := range []string{`- "staging"`, `&& 'staging' || '' }}`} {
		if !strings.Contains(string(workflow), want) {
			t.Errorf("setup omitted saved mapping %q:\n%s", want, workflow)
		}
	}
}

func TestCmdGithubSetupDryRunDoesNotWriteOrCallAPI(t *testing.T) {
	repoDir := t.TempDir()
	if err := os.Mkdir(filepath.Join(repoDir, ".git"), 0o755); err != nil {
		t.Fatal(err)
	}
	t.Chdir(repoDir)
	called := false
	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		called = true
		http.Error(w, "unexpected network call", http.StatusInternalServerError)
	}))
	defer srv.Close()
	t.Setenv("FAAS_API", srv.URL)
	t.Setenv("FAAS_TOKEN", "fp_live_test")

	oldOut, oldJSON := osStdout, jsonOutput
	var out bytes.Buffer
	osStdout, jsonOutput = &out, false
	t.Cleanup(func() { osStdout, jsonOutput = oldOut, oldJSON })

	sha := "f1e2d3c4b5a6987654321098765432109abcdef0"
	if code := cmdGithubSetup([]string{"api", "--repo", "acme/api", "--production-branch", "main", "--rollout", "safe", "--pinned-sha", sha, "--dry-run"}); code != 0 {
		t.Fatalf("dry-run exit = %d, output = %s", code, out.String())
	}
	if called {
		t.Fatal("dry-run made an API request")
	}
	if _, err := os.Stat(filepath.Join(repoDir, defaultGithubSetupWorkflow)); !os.IsNotExist(err) {
		t.Fatalf("dry-run created workflow, stat err = %v", err)
	}
	if !strings.Contains(out.String(), "Generated workflow:") {
		t.Fatalf("dry-run did not show generated workflow: %s", out.String())
	}
	if !strings.Contains(out.String(), `rollout: "safe"`) || !strings.Contains(out.String(), "rollout:            safe") {
		t.Fatalf("dry-run did not show safe rollout mode: %s", out.String())
	}
	if !strings.Contains(out.String(), "uses: poyrazK/faas/.github/actions/deploy@"+sha) {
		t.Fatalf("dry-run did not render pinned Action SHA: %s", out.String())
	}
}
