// commands/completion_powershell.go — Tier A8 / ADR-083.
//
// `gregale completion powershell` emits a PowerShell snippet that
// registers an argument completer via Register-ArgumentCompleter.
// The completer reads the cliCommands manifest at emit time
// (hard-coded into the snippet) and walks $words to figure out
// which position the cursor is at, then offers the right set.
//
// PowerShell's completion model is the most different of the four
// — there's no per-shell flag value parsing built in. The completer
// must parse $wordToComplete manually. The snippet below implements
// that as a single switch on the command name; the verb/flag tables
// are inline string literals.

package main

import (
	"fmt"
	"io"
	"strings"
)

func cmdCompletionPowershell() int {
	w := osStdout
	renderPowershellHeader(w)
	for _, c := range customerCliCommands() {
		renderPowershellCommand(w, c)
	}
	renderPowershellFooter(w)
	return 0
}

func renderPowershellHeader(w io.Writer) {
	_, _ = fmt.Fprintln(w, "# powershell completion for gregale — generated by `gregale completion powershell`.")
	_, _ = fmt.Fprintln(w, "# Install: gregale completion powershell | Out-String | Invoke-Expression")
	_, _ = fmt.Fprintln(w)
	_, _ = fmt.Fprintln(w, "function __gregaleCacheSlugs($kind) {")
	_, _ = fmt.Fprintln(w, "  $path = gregale completion completion-cache-path 2>$null")
	_, _ = fmt.Fprintln(w, "  if (-not $path -or -not (Test-Path $path)) { return @() }")
	_, _ = fmt.Fprintln(w, "  try {")
	_, _ = fmt.Fprintln(w, "    $json = Get-Content $path -Raw | ConvertFrom-Json")
	_, _ = fmt.Fprintln(w, "    if ($json.$kind) { return @($json.$kind | ForEach-Object { $_.slug }) }")
	_, _ = fmt.Fprintln(w, "  } catch {}")
	_, _ = fmt.Fprintln(w, "  return @()")
	_, _ = fmt.Fprintln(w, "}")
	_, _ = fmt.Fprintln(w)
	_, _ = fmt.Fprintln(w, "Register-ArgumentCompleter -Native -CommandName 'gregale' -ScriptBlock {")
	_, _ = fmt.Fprintln(w, "  param($wordToComplete, $commandAst, $cursorPosition)")
	_, _ = fmt.Fprintln(w)
	_, _ = fmt.Fprintln(w, "  $tokens = $commandAst.ToString() -split '\\s+'")
	_, _ = fmt.Fprintln(w, "  $previousToken = if ($tokens.Count -gt 1 -and $tokens[-1] -eq $wordToComplete) { $tokens[-2] } else { $tokens[-1] }")
	_, _ = fmt.Fprintln(w, "  if ($previousToken -eq '--app') {")
	_, _ = fmt.Fprintln(w, "    foreach ($s in __gregaleCacheSlugs 'apps') {")
	_, _ = fmt.Fprintln(w, "      if ($s -like \"$wordToComplete*\") { [System.Management.Automation.CompletionResult]::new($s, $s, 'ParameterValue', $s) }")
	_, _ = fmt.Fprintln(w, "    }")
	_, _ = fmt.Fprintln(w, "    return")
	_, _ = fmt.Fprintln(w, "  }")
	_, _ = fmt.Fprintln(w, "  if ($previousToken -eq '--org') {")
	_, _ = fmt.Fprintln(w, "    foreach ($s in __gregaleCacheSlugs 'orgs') {")
	_, _ = fmt.Fprintln(w, "      if ($s -like \"$wordToComplete*\") { [System.Management.Automation.CompletionResult]::new($s, $s, 'ParameterValue', $s) }")
	_, _ = fmt.Fprintln(w, "    }")
	_, _ = fmt.Fprintln(w, "    return")
	_, _ = fmt.Fprintln(w, "  }")
	_, _ = fmt.Fprintln(w, "  if ($tokens.Count -lt 2) {")
	for _, c := range customerCliCommands() {
		_, _ = fmt.Fprintf(w, "    if (%q -like \"$wordToComplete*\") { [System.Management.Automation.CompletionResult]::new(%q, %q, 'ParameterName', %q) }\n",
			c.Name, c.Name, c.Name, escapePS(c.Short))
	}
	_, _ = fmt.Fprintln(w, "    return")
	_, _ = fmt.Fprintln(w, "  }")
	_, _ = fmt.Fprintln(w)
}

func renderPowershellCommand(w io.Writer, c cliCommand) {
	_, _ = fmt.Fprintf(w, "  if ($tokens[1] -eq '%s') {\n", c.Name)
	// Subcommand completion: always rendered when the command has
	// any subcommands. The earlier `len(c.Positionals) == 0` gate
	// suppressed subcommand completion for commands like `app` that
	// have BOTH subcommands (scale/rename/security) AND a <slug>
	// positional — inconsistent with bash/zsh/fish.
	if len(c.Subcommands) > 0 {
		_, _ = fmt.Fprintf(w, "    if ($tokens.Count -eq 2) {\n")
		for _, s := range c.Subcommands {
			_, _ = fmt.Fprintf(w, "      if (%q -like \"$wordToComplete*\") { [System.Management.Automation.CompletionResult]::new(%q, %q, 'ParameterName', %q) }\n",
				s.Name, s.Name, s.Name, escapePS(s.Short))
		}
		_, _ = fmt.Fprintln(w, "      return")
		_, _ = fmt.Fprintln(w, "    }")
	}
	// Top-level positional: closed-set (plan) or slug cache (app,
	// invoke, metrics, slo, wake-timeline — driven by hasSlugFirst).
	if len(c.ClosedSet) > 0 {
		for _, v := range c.ClosedSet {
			_, _ = fmt.Fprintf(w, "    if (%q -like \"$wordToComplete*\") { [System.Management.Automation.CompletionResult]::new(%q, %q, 'ParameterValue', %q) }\n",
				v, v, v, v)
		}
	} else if c.hasSlugFirst() {
		_, _ = fmt.Fprintln(w, "    foreach ($s in __gregaleCacheSlugs 'apps') {")
		_, _ = fmt.Fprintln(w, "      if ($s -like \"$wordToComplete*\") { [System.Management.Automation.CompletionResult]::new($s, $s, 'ParameterValue', $s) }")
		_, _ = fmt.Fprintln(w, "    }")
	}
	// Flags.
	for _, f := range c.Flags {
		_, _ = fmt.Fprintf(w, "    if ('--%s' -like \"$wordToComplete*\") { [System.Management.Automation.CompletionResult]::new('--%s', '%s', 'ParameterName', %q) }\n",
			f.Name, f.Name, f.Name, escapePS(f.Short))
	}
	_, _ = fmt.Fprintln(w, "    return")
	_, _ = fmt.Fprintln(w, "  }")
	_, _ = fmt.Fprintln(w)
}

func renderPowershellFooter(w io.Writer) {
	_, _ = fmt.Fprintln(w, "}")
}

// escapePS doubles single-quotes for PowerShell single-quoted strings.
// PowerShell uses the same escape as bash for single quotes (”).
func escapePS(s string) string {
	return strings.ReplaceAll(s, "'", "''")
}
