// commands/completion_zsh.go — Tier A8 / ADR-083.
//
// `gregale completion zsh` emits a zsh completion script. The
// script uses #compdef gregale (the autoload directive zsh
// recognises on $fpath) and a single _gregale function that
// walks COMP_WORDS to figure out which position the cursor is
// at, then dispatches to a per-command _gregale_<cmd> helper.
//
// Zsh's _arguments is the most concise of the four backends —
// it lets us declare the spec inline and zsh handles the
// per-position completion dispatch. The downside is that the
// _arguments form for 50+ commands is verbose; we emit it anyway
// because it matches user expectations (every zsh completion
// looks like this) and the size cost is a one-time file write.
//
// All string literals rendered into the shell script use
// double-quote escaping (escapeZshDQ). Single quotes cannot
// represent apostrophes inside a description (the existing
// `Rotate the alert's webhook secret` literally broke zsh -n
// parsing) without a `'\''` sequence — but zsh's _arguments
// treats everything between the apostrophes as one shell token,
// so the escape sequence silently swallows the rest of the
// argument line. Double-quoted strings escape `"`, `\`, `$`,
// `` ` `` and embed any other byte verbatim, including `'` and
// parens, so all of our Short descriptions render cleanly.

package main

import (
	"fmt"
	"io"
	"strings"
)

func cmdCompletionZsh() int {
	w := osStdout
	renderZshHeader(w)
	for _, c := range cliCommands {
		renderZshCommand(w, c)
	}
	renderZshFooter(w)
	return 0
}

func renderZshHeader(w io.Writer) {
	_, _ = fmt.Fprintln(w, "#compdef gregale")
	_, _ = fmt.Fprintln(w, "# zsh completion for gregale — generated by `gregale completion zsh`.")
	_, _ = fmt.Fprintln(w, "# Install: gregale completion zsh > \"${fpath[1]}/_gregale\"")
	_, _ = fmt.Fprintln(w)
	_, _ = fmt.Fprintln(w, "_gregale_cache_slugs() {")
	_, _ = fmt.Fprintln(w, "  local kind=\"$1\"")
	_, _ = fmt.Fprintln(w, "  local path=\"$(gregale completion-cache-path 2>/dev/null)\"")
	_, _ = fmt.Fprintln(w, "  [[ -z \"$path\" || ! -r \"$path\" ]] && return 1")
	// sed slice rather than grep -E with literal braces — grep
	// treats '{' as a quantifier metacharacter and rejects it.
	_, _ = fmt.Fprintln(w, "  sed -n \"/\\\"$kind\\\":\\[/,/]/p\" \"$path\" 2>/dev/null \\")
	_, _ = fmt.Fprintln(w, "    | grep -oE '\"slug\":\"[^\"]+\"' \\")
	_, _ = fmt.Fprintln(w, "    | sed -E 's/.*\"slug\":\"([^\"]+)\".*/\\1/'")
	_, _ = fmt.Fprintln(w, "}")
	_, _ = fmt.Fprintln(w)
	_, _ = fmt.Fprintln(w, "_gregale() {")
	_, _ = fmt.Fprintln(w, "  local -a commands")
	_, _ = fmt.Fprintln(w, "  commands=(")
	for _, c := range cliCommands {
		_, _ = fmt.Fprintf(w, "    \"%s:%s\"\n", c.Name, escapeZshDQ(c.Short))
	}
	_, _ = fmt.Fprintln(w, "  )")
	_, _ = fmt.Fprintln(w)
	_, _ = fmt.Fprintln(w, "  if (( CURRENT == 2 )); then")
	_, _ = fmt.Fprintln(w, "    _describe 'command' commands")
	_, _ = fmt.Fprintln(w, "    return 0")
	_, _ = fmt.Fprintln(w, "  fi")
	_, _ = fmt.Fprintln(w)
}

// renderZshCommand emits one _gregale_<cmd> function per cliCommand.
// Each _arguments token is emitted as its own double-quoted shell
// word, so descriptions containing apostrophes (e.g. "the app's URL")
// or unbalanced parens ("day (YYYY-MM-DD)") parse cleanly.
func renderZshCommand(w io.Writer, c cliCommand) {
	_, _ = fmt.Fprintf(w, "  _gregale_%s() {\n", c.Name)
	_, _ = fmt.Fprintln(w, "    _arguments \\")
	// Subcommand verbs (e.g. alerts.list, alerts.add).
	for _, s := range c.Subcommands {
		_, _ = fmt.Fprintf(w, "      \"%s:%s\" \\\n", s.Name, escapeZshDQ(s.Short))
	}
	// Flags (e.g. --app <slug>).
	for _, f := range c.Flags {
		_, _ = fmt.Fprintf(w, "      \"--%s[%s]\" \\\n", f.Name, escapeZshDQ(f.Short))
		if len(f.ClosedSet) > 0 {
			_, _ = fmt.Fprintf(w, "      \"--%s:option:(%s)\" \\\n", f.Name, strings.Join(f.ClosedSet, " "))
		}
	}
	// Closed-set positional (e.g. `plan`).
	if len(c.ClosedSet) > 0 {
		_, _ = fmt.Fprintf(w, "      \"1:plan:(%s)\" \\\n", strings.Join(c.ClosedSet, " "))
	} else if c.hasSlugFirst() {
		_, _ = fmt.Fprintln(w, "      \"1:slug:($(_gregale_cache_slugs apps))\" \\")
	}
	_, _ = fmt.Fprintln(w, "      && return 0")
	_, _ = fmt.Fprintln(w, "  }")
}

// renderZshFooter closes the _gregale function and dispatches to
// the per-command helper. The dispatch is a case statement on
// $words[2] (the first arg after `gregale`).
func renderZshFooter(w io.Writer) {
	_, _ = fmt.Fprintln(w, "  case \"$words[2]\" in")
	for _, c := range cliCommands {
		_, _ = fmt.Fprintf(w, "    %s) _gregale_%s ;;\n", c.Name, c.Name)
	}
	_, _ = fmt.Fprintln(w, "  esac")
	_, _ = fmt.Fprintln(w, "}")
	_, _ = fmt.Fprintln(w)
	_, _ = fmt.Fprintln(w, "_gregale \"$@\"")
}

// escapeZshDQ backslash-escapes the four byte sequences that are
// special inside a double-quoted zsh string: backslash itself,
// double-quote, dollar, and backtick. Every other byte — including
// single quotes, parens, brackets, and `!` — passes through
// verbatim, so the result is safe to embed in either the
// `_describe` array or the `_arguments` token list. We do NOT
// touch `!` because interactive shells expand history on it but
// completion scripts run under `zsh -n` (parse-only) and under
// compsys (which does not interpret history).
func escapeZshDQ(s string) string {
	var b strings.Builder
	b.Grow(len(s) + 8)
	for i := 0; i < len(s); i++ {
		switch s[i] {
		case '\\', '"', '$', '`':
			b.WriteByte('\\')
		}
		b.WriteByte(s[i])
	}
	return b.String()
}
