// commands/completion_fish.go — Tier A8 / ADR-083.
//
// `gregale completion fish` emits a fish completion script. Fish's
// `complete -c gregale` form is the most declarative of the four
// backends: each spec lives on its own line and fish handles the
// per-position matching. The downside is verbosity — fish has no
// equivalent of zsh's _arguments; we emit one `complete` call per
// (command, subcommand, position) tuple.
//
// Install path: gregale completion fish > ~/.config/fish/completions/gregale.fish
// (or the per-user ~/.config/fish/completed/ if the operator has
// migrated the path).

package main

import (
	"fmt"
	"io"
	"strings"
)

func cmdCompletionFish() int {
	w := osStdout
	renderFishHeader(w)
	for _, c := range customerCliCommands() {
		renderFishCommand(w, c)
	}
	renderFishFooter(w)
	return 0
}

func renderFishHeader(w io.Writer) {
	_, _ = fmt.Fprintln(w, "# fish completion for gregale — generated by `gregale completion fish`.")
	_, _ = fmt.Fprintln(w, "# Install: gregale completion fish > ~/.config/fish/completions/gregale.fish")
	_, _ = fmt.Fprintln(w)
	_, _ = fmt.Fprintln(w, "function __gregale_cache_slugs")
	_, _ = fmt.Fprintln(w, "  set -l kind $argv[1]")
	_, _ = fmt.Fprintln(w, "  set -l path (gregale completion completion-cache-path 2>/dev/null)")
	_, _ = fmt.Fprintln(w, "  if test -z \"$path\"; or not test -r \"$path\"")
	_, _ = fmt.Fprintln(w, "    return 1")
	_, _ = fmt.Fprintln(w, "  end")
	// sed slice rather than grep -E with literal braces — fish's
	// grep treats '{' as a quantifier metacharacter and rejects it.
	_, _ = fmt.Fprintln(w, "  sed -n \"/\\\"$kind\\\":\\[/,/]/p\" \"$path\" 2>/dev/null \\")
	_, _ = fmt.Fprintln(w, "    | sed -E \"s/.*\\\"$kind\\\":\\[//; s/\\].*//\" \\")
	_, _ = fmt.Fprintln(w, "    | grep -oE '\"slug\":\"[^\"]+\"' \\")
	_, _ = fmt.Fprintln(w, "    | sed -E 's/.*\"slug\":\"([^\"]+)\".*/\\1/'")
	_, _ = fmt.Fprintln(w, "end")
	_, _ = fmt.Fprintln(w)
	_, _ = fmt.Fprintln(w, "function __gregale_cache_ids")
	_, _ = fmt.Fprintln(w, "  set -l kind $argv[1]")
	_, _ = fmt.Fprintln(w, "  set -l path (gregale completion completion-cache-path 2>/dev/null)")
	_, _ = fmt.Fprintln(w, "  if test -z \"$path\"; or not test -r \"$path\"")
	_, _ = fmt.Fprintln(w, "    return 1")
	_, _ = fmt.Fprintln(w, "  end")
	_, _ = fmt.Fprintln(w, "  sed -n \"/\\\"$kind\\\":\\[/,/]/p\" \"$path\" 2>/dev/null \\")
	_, _ = fmt.Fprintln(w, "    | sed -E \"s/.*\\\"$kind\\\":\\[//; s/\\].*//\" \\")
	_, _ = fmt.Fprintln(w, "    | grep -oE '\"id\":\"[^\"]+\"' \\")
	_, _ = fmt.Fprintln(w, "    | sed -E 's/.*\"id\":\"([^\"]+)\".*/\\1/'")
	_, _ = fmt.Fprintln(w, "end")
	_, _ = fmt.Fprintln(w)
	_, _ = fmt.Fprintln(w, "function __gregale_cache_project_environments")
	_, _ = fmt.Fprintln(w, "  set -l project $argv[1]")
	_, _ = fmt.Fprintln(w, "  set -l path (gregale completion completion-cache-path 2>/dev/null)")
	_, _ = fmt.Fprintln(w, "  if test -z \"$path\"; or not test -r \"$path\"")
	_, _ = fmt.Fprintln(w, "    return 1")
	_, _ = fmt.Fprintln(w, "  end")
	_, _ = fmt.Fprintln(w, "  grep -oE '\"project_slug\":\"[a-z0-9-]+\",\"slug\":\"[a-z0-9-]+\"' \"$path\" 2>/dev/null \\")
	_, _ = fmt.Fprintln(w, "    | grep -F -- \"\\\"project_slug\\\":\\\"$project\\\",\" \\")
	_, _ = fmt.Fprintln(w, "    | sed -E 's/.*\"slug\":\"([^\"]+)\".*/\\1/'")
	_, _ = fmt.Fprintln(w, "end")
	_, _ = fmt.Fprintln(w)
	_, _ = fmt.Fprintln(w, "function __gregale_context_words")
	_, _ = fmt.Fprintln(w, "  set -l words (commandline -opc)")
	_, _ = fmt.Fprintln(w, "  if test (count $words) -eq 0")
	_, _ = fmt.Fprintln(w, "    return")
	_, _ = fmt.Fprintln(w, "  end")
	_, _ = fmt.Fprintln(w, "  set -l normalized $words[1]")
	_, _ = fmt.Fprintln(w, "  set -l after_separator 0")
	_, _ = fmt.Fprintln(w, "  for word in $words[2..-1]")
	_, _ = fmt.Fprintln(w, "    if test $after_separator -eq 0; and string match -q -r -- '^(--json|-j)(=.*)?$' $word")
	_, _ = fmt.Fprintln(w, "      continue")
	_, _ = fmt.Fprintln(w, "    end")
	_, _ = fmt.Fprintln(w, "    set normalized $normalized $word")
	_, _ = fmt.Fprintln(w, "    if test $word = --")
	_, _ = fmt.Fprintln(w, "      set after_separator 1")
	_, _ = fmt.Fprintln(w, "    end")
	_, _ = fmt.Fprintln(w, "  end")
	_, _ = io.WriteString(w, "  printf '%s\\n' $normalized\n")
	_, _ = fmt.Fprintln(w, "end")
	_, _ = fmt.Fprintln(w)
	renderFishAppSlugPosition(w)
	_, _ = fmt.Fprintln(w)
	renderFishEnvironmentProjectLookup(w)
	_, _ = fmt.Fprintln(w)
	_, _ = fmt.Fprintln(w, "function __gregale_context_environment_slugs")
	_, _ = fmt.Fprintln(w, "  set -l project (__gregale_environment_project)")
	_, _ = fmt.Fprintln(w, "  if test -n \"$project\"")
	_, _ = fmt.Fprintln(w, "    __gregale_cache_project_environments $project")
	_, _ = fmt.Fprintln(w, "  else")
	_, _ = fmt.Fprintln(w, "    __gregale_cache_slugs environments")
	_, _ = fmt.Fprintln(w, "  end")
	_, _ = fmt.Fprintln(w, "end")
	_, _ = fmt.Fprintln(w)
	_, _ = fmt.Fprintln(w, "function __gregale_project_environment_option")
	_, _ = fmt.Fprintln(w, "  set -l words (__gregale_context_words)")
	_, _ = fmt.Fprintln(w, "  set -l current (commandline -ct)")
	_, _ = fmt.Fprintln(w, "  set -l previous $words[-1]")
	_, _ = fmt.Fprintln(w, "  if not contains -- $previous --from --to; and not string match -q -r -- '^--(from|to)=' $current")
	_, _ = fmt.Fprintln(w, "    return 1")
	_, _ = fmt.Fprintln(w, "  end")
	_, _ = fmt.Fprintln(w, "  __gregale_environment_project >/dev/null")
	_, _ = fmt.Fprintln(w, "end")
	_, _ = fmt.Fprintln(w)
	renderFishProjectEnvironmentPosition(w)
	_, _ = fmt.Fprintln(w)
	renderFishProjectArgumentPosition(w)
	_, _ = fmt.Fprintln(w)
	renderFishProjectArgumentChoices(w)
	_, _ = fmt.Fprintln(w)
	renderFishBuildIDPosition(w)
	_, _ = fmt.Fprintln(w)
	renderFishDeploymentIDPosition(w)
	_, _ = fmt.Fprintln(w)
	_, _ = fmt.Fprintln(w, "complete -c gregale -f -n __gregale_app_slug_position -a \"(__gregale_cache_slugs apps)\"")
	_, _ = fmt.Fprintln(w, "complete -c gregale -f -n __gregale_project_environment_option -a \"(__gregale_context_environment_slugs)\"")
	_, _ = fmt.Fprintln(w, "complete -c gregale -f -n __gregale_project_environment_position -a \"(__gregale_context_environment_slugs)\"")
	_, _ = fmt.Fprintln(w, "complete -c gregale -f -n __gregale_project_argument_position -a \"(__gregale_cache_slugs projects)\"")
	_, _ = fmt.Fprintln(w, "complete -c gregale -f -n __gregale_project_argument_position -a \"(__gregale_project_argument_choices)\"")
	// Org-scoped and app-scoped leaf parsers accept these flags across
	// nested command families. Keep their values cache-backed even when
	// the parent cliCommand does not duplicate every leaf flag.
	_, _ = fmt.Fprintln(w, "complete -c gregale -f -n \"__fish_prev_arg_in --app\" -a \"(__gregale_cache_slugs apps)\"")
	_, _ = fmt.Fprintln(w, "complete -c gregale -f -n \"__fish_prev_arg_in --org\" -a \"(__gregale_cache_slugs orgs)\"")
	_, _ = fmt.Fprintln(w, "complete -c gregale -f -n __gregale_build_id_position -a \"(__gregale_cache_ids builds)\"")
	_, _ = fmt.Fprintln(w, "complete -c gregale -f -n __gregale_deployment_id_position -a \"(__gregale_cache_ids deployments)\"")
	_, _ = fmt.Fprintln(w)
}

func fishCompletionPathCondition(command cliCommand, path []string) string {
	conditions := []string{fmt.Sprintf("test \"$words[2]\" = %q", command.Name)}
	for i, token := range path {
		conditions = append(conditions, fmt.Sprintf("test \"$words[%d]\" = %q", i+3, token))
	}
	return strings.Join(conditions, "; and ")
}

func fishCompletionPositionCondition(command cliCommand, position cliCompletionPosition) string {
	conditions := []string{fishCompletionPathCondition(command, position.Path)}
	contextCount := len(position.Path) + 1 + position.Position
	conditions = append(conditions, fmt.Sprintf("test $position -eq %d", contextCount))
	return strings.Join(conditions, "; and ")
}

func fishAppSlugPositionCondition(position cliAppSlugCompletionPosition) string {
	conditions := []string{fmt.Sprintf("test \"$words[2]\" = %q", position.Command)}
	for i, token := range position.Path {
		conditions = append(conditions, fmt.Sprintf("test \"$words[%d]\" = %q", position.PathOffsets[i]+2, token))
	}
	for _, offset := range position.RequiredPositionOffsets {
		conditions = append(conditions, fmt.Sprintf("test -n \"$words[%d]\"", offset+2))
	}
	conditions = append(conditions, fmt.Sprintf("test $position -eq %d", position.WordOffset+1))
	return strings.Join(conditions, "; and ")
}

func renderFishAppSlugPosition(w io.Writer) {
	_, _ = fmt.Fprintln(w, "function __gregale_app_slug_position")
	_, _ = fmt.Fprintln(w, "  set -l words (__gregale_context_words)")
	_, _ = fmt.Fprintln(w, "  set -l position (count $words)")
	for _, position := range appSlugCompletionPositions() {
		_, _ = fmt.Fprintf(w, "  if %s\n", fishAppSlugPositionCondition(position))
		_, _ = fmt.Fprintln(w, "    return 0")
		_, _ = fmt.Fprintln(w, "  end")
	}
	_, _ = fmt.Fprintln(w, "  return 1")
	_, _ = fmt.Fprintln(w, "end")
}

func renderFishEnvironmentProjectLookup(w io.Writer) {
	command := projectCompletionCommand()
	_, _ = fmt.Fprintln(w, "function __gregale_environment_project")
	_, _ = fmt.Fprintln(w, "  set -l words (__gregale_context_words)")
	for _, context := range projectCompletionContexts() {
		projectIndex := 2 + len(context.Path) + context.Position
		_, _ = fmt.Fprintf(w, "  if %s; and test -n \"$words[%d]\"\n", fishCompletionPathCondition(command, context.Path), projectIndex)
		_, _ = fmt.Fprintf(w, "    printf '%%s\\n' $words[%d]\n", projectIndex)
		_, _ = fmt.Fprintln(w, "    return 0")
		_, _ = fmt.Fprintln(w, "  end")
	}
	_, _ = fmt.Fprintln(w, "  return 1")
	_, _ = fmt.Fprintln(w, "end")
}

func renderFishProjectEnvironmentPosition(w io.Writer) {
	command := projectCompletionCommand()
	_, _ = fmt.Fprintln(w, "function __gregale_project_environment_position")
	_, _ = fmt.Fprintln(w, "  set -l words (__gregale_context_words)")
	_, _ = fmt.Fprintln(w, "  set -l position (count $words)")
	for _, completion := range projectCompletionPositions() {
		if completion.Role != cliCompletionEnvironmentSlug {
			continue
		}
		projectIndex := 2 + len(completion.Path) + completion.ProjectPosition
		_, _ = fmt.Fprintf(w, "  if %s; and test -n \"$words[%d]\"\n", fishCompletionPositionCondition(command, completion), projectIndex)
		_, _ = fmt.Fprintln(w, "    return 0")
		_, _ = fmt.Fprintln(w, "  end")
	}
	_, _ = fmt.Fprintln(w, "  return 1")
	_, _ = fmt.Fprintln(w, "end")
}

func renderFishProjectArgumentPosition(w io.Writer) {
	command := projectCompletionCommand()
	_, _ = fmt.Fprintln(w, "function __gregale_project_argument_position")
	_, _ = fmt.Fprintln(w, "  set -l words (__gregale_context_words)")
	_, _ = fmt.Fprintln(w, "  set -l position (count $words)")
	for _, completion := range projectCompletionPositions() {
		if completion.Role != cliCompletionProjectSlug {
			continue
		}
		_, _ = fmt.Fprintf(w, "  if %s\n", fishCompletionPositionCondition(command, completion))
		_, _ = fmt.Fprintln(w, "    return 0")
		_, _ = fmt.Fprintln(w, "  end")
	}
	_, _ = fmt.Fprintln(w, "  return 1")
	_, _ = fmt.Fprintln(w, "end")
}

func renderFishProjectArgumentChoices(w io.Writer) {
	command := projectCompletionCommand()
	_, _ = fmt.Fprintln(w, "function __gregale_project_argument_choices")
	_, _ = fmt.Fprintln(w, "  set -l words (__gregale_context_words)")
	_, _ = fmt.Fprintln(w, "  set -l position (count $words)")
	for _, completion := range projectCompletionPositions() {
		if completion.Role != cliCompletionProjectSlug || len(completion.Choices) == 0 {
			continue
		}
		_, _ = fmt.Fprintf(w, "  if %s\n", fishCompletionPositionCondition(command, completion))
		_, _ = fmt.Fprintf(w, "    printf '%%s\\n' %s\n", strings.Join(completion.Choices, " "))
		_, _ = fmt.Fprintln(w, "    return 0")
		_, _ = fmt.Fprintln(w, "  end")
	}
	_, _ = fmt.Fprintln(w, "  return 1")
	_, _ = fmt.Fprintln(w, "end")
}

func renderFishBuildIDPosition(w io.Writer) {
	command, _ := lookupCliCommand("build")
	_, _ = fmt.Fprintln(w, "function __gregale_build_id_position")
	_, _ = fmt.Fprintln(w, "  set -l words (__gregale_context_words)")
	_, _ = fmt.Fprintln(w, "  set -l position (count $words)")
	for _, completion := range command.expandedCompletionPositions() {
		if completion.Role != cliCompletionBuildID {
			continue
		}
		_, _ = fmt.Fprintf(w, "  if %s\n", fishCompletionPositionCondition(command, completion))
		_, _ = fmt.Fprintln(w, "    return 0")
		_, _ = fmt.Fprintln(w, "  end")
	}
	_, _ = fmt.Fprintln(w, "  return 1")
	_, _ = fmt.Fprintln(w, "end")
}

func renderFishDeploymentIDPosition(w io.Writer) {
	_, _ = fmt.Fprintln(w, "function __gregale_deployment_id_position")
	_, _ = fmt.Fprintln(w, "  set -l words (__gregale_context_words)")
	_, _ = fmt.Fprintln(w, "  set -l position (count $words)")
	for _, command := range deploymentCompletionCommands() {
		for _, completion := range command.expandedCompletionPositions() {
			if completion.Role != cliCompletionDeploymentID {
				continue
			}
			_, _ = fmt.Fprintf(w, "  if %s\n", fishCompletionPositionCondition(command, completion))
			_, _ = fmt.Fprintln(w, "    return 0")
			_, _ = fmt.Fprintln(w, "  end")
		}
	}
	_, _ = fmt.Fprintln(w, "  return 1")
	_, _ = fmt.Fprintln(w, "end")
}

func renderFishCommand(w io.Writer, c cliCommand) {
	subcommandWord := c.completionSubcommandWord()
	// Top-level command (when no subcommand matches).
	if len(c.Subcommands) == 0 {
		_, _ = fmt.Fprintf(w, "complete -c gregale -f -n \"__fish_use_subcommand\" -a %q -d %q\n",
			c.Name, c.Short)
	} else {
		verbList := make([]string, 0, len(c.Subcommands))
		for _, s := range c.Subcommands {
			verbList = append(verbList, s.completionSpellings()...)
		}
		_, _ = fmt.Fprintf(w, "complete -c gregale -f -n \"__fish_use_subcommand\" -a %q -d %q\n",
			c.Name, c.Short)
		// Subcommand completion.
		_, _ = fmt.Fprintf(w, "complete -c gregale -f -n \"__fish_seen_subcommand_from %s; and test (count (commandline -opc)) -eq %d\" -a \"%s\"\n",
			c.Name, subcommandWord, strings.Join(verbList, " "))
		for _, parent := range c.Subcommands {
			if len(parent.Subcommands) == 0 && len(parent.Flags) > 0 {
				flagCount := subcommandWord + 1
				if parent.FlagsAfterPositionals {
					flagCount += len(parent.Positionals)
				}
				condition := fmt.Sprintf("__fish_seen_subcommand_from %s; and %s; and test (count (commandline -opc)) -ge %d", c.Name, fishSeenSubcommand(parent), flagCount)
				for _, f := range parent.Flags {
					renderFishFlag(w, condition, f)
				}
			}
			if len(parent.Subcommands) == 0 {
				continue
			}
			childWord := subcommandWord + 1
			if parent.SubcommandsAfterPositionals {
				childWord += len(parent.Positionals)
			}
			childWords := make([]string, 0, len(parent.Subcommands))
			for _, child := range parent.Subcommands {
				childWords = append(childWords, child.completionSpellings()...)
			}
			_, _ = fmt.Fprintf(w, "complete -c gregale -f -n \"__fish_seen_subcommand_from %s; and %s; and test (count (commandline -opc)) -eq %d\" -a \"%s\"\n",
				c.Name, fishSeenSubcommand(parent), childWord, strings.Join(childWords, " "))
			for _, child := range parent.Subcommands {
				leafFlagsCount := childWord + 1
				if child.FlagsAfterPositionals {
					leafFlagsCount += len(child.Positionals)
				}
				for _, f := range child.Flags {
					condition := fmt.Sprintf("__fish_seen_subcommand_from %s; and %s; and %s; and test (count (commandline -opc)) -ge %d", c.Name, fishSeenSubcommand(parent), fishSeenSubcommand(child), leafFlagsCount)
					renderFishFlag(w, condition, f)
				}
			}
		}
	}
	// Closed-set positional (plan).
	if len(c.ClosedSet) > 0 {
		_, _ = fmt.Fprintf(w, "complete -c gregale -f -n \"__fish_seen_subcommand_from %s\" -a \"%s\"\n",
			c.Name, strings.Join(c.ClosedSet, " "))
	}
	// Flags.
	for _, f := range c.Flags {
		renderFishFlag(w, fmt.Sprintf("__fish_seen_subcommand_from %s", c.Name), f)
	}
}

func fishSeenSubcommand(sub cliSub) string {
	return "__fish_seen_subcommand_from " + strings.Join(sub.completionSpellings(), " ")
}

func renderFishFlag(w io.Writer, condition string, f cliFlag) {
	option := "-l " + f.Name
	if f.ShortName != "" {
		if f.ShortName == f.Name {
			option = "-s " + f.ShortName
		} else {
			option += " -s " + f.ShortName
		}
	}
	arguments := []string{option}
	if cliFlagTakesValue(f) {
		arguments = append(arguments, "-r")
	}
	if len(f.ClosedSet) > 0 {
		arguments = append(arguments, "-a", fmt.Sprintf("%q", strings.Join(f.ClosedSet, " ")))
	}
	if cliFlagUsesEnvironmentValues(f) {
		arguments = append(arguments, "-a", `"(__gregale_context_environment_slugs)"`)
	}
	if cliFlagUsesFilePathValues(f) {
		// -F restores path suggestions after -f has disabled them for
		// the other Gregale options.
		arguments = append(arguments, "-F")
	}
	_, _ = fmt.Fprintf(w, "complete -c gregale -f -n %q %s -d %q\n", condition, strings.Join(arguments, " "), f.Short)
}

func renderFishFooter(w io.Writer) {
	// No-op: fish has no main completion function.
}
