// commands/completion_fish.go — Tier A8 / ADR-083.
//
// `gregale completion fish` emits a fish completion script. Fish's
// `complete -c gregale` form is the most declarative of the four
// backends: each spec lives on its own line and fish handles the
// per-position matching. The downside is verbosity — fish has no
// equivalent of zsh's _arguments; we emit one `complete` call per
// (command, subcommand, position) tuple.
//
// Install path: gregale completion fish > ~/.config/fish/completions/gregale.fish
// (or the per-user ~/.config/fish/completed/ if the operator has
// migrated the path).

package main

import (
	"fmt"
	"io"
	"strings"
)

func cmdCompletionFish() int {
	w := osStdout
	renderFishHeader(w)
	for _, c := range customerCliCommands() {
		renderFishCommand(w, c)
	}
	renderFishFooter(w)
	return 0
}

func renderFishHeader(w io.Writer) {
	_, _ = fmt.Fprintln(w, "# fish completion for gregale — generated by `gregale completion fish`.")
	_, _ = fmt.Fprintln(w, "# Install: gregale completion fish > ~/.config/fish/completions/gregale.fish")
	_, _ = fmt.Fprintln(w)
	_, _ = fmt.Fprintln(w, "function __gregale_cache_slugs")
	_, _ = fmt.Fprintln(w, "  set -l kind $argv[1]")
	_, _ = fmt.Fprintln(w, "  set -l path (gregale completion completion-cache-path 2>/dev/null)")
	_, _ = fmt.Fprintln(w, "  if test -z \"$path\"; or not test -r \"$path\"")
	_, _ = fmt.Fprintln(w, "    return 1")
	_, _ = fmt.Fprintln(w, "  end")
	// sed slice rather than grep -E with literal braces — fish's
	// grep treats '{' as a quantifier metacharacter and rejects it.
	_, _ = fmt.Fprintln(w, "  sed -n \"/\\\"$kind\\\":\\[/,/]/p\" \"$path\" 2>/dev/null \\")
	_, _ = fmt.Fprintln(w, "    | sed -E \"s/.*\\\"$kind\\\":\\[//; s/\\].*//\" \\")
	_, _ = fmt.Fprintln(w, "    | grep -oE '\"slug\":\"[^\"]+\"' \\")
	_, _ = fmt.Fprintln(w, "    | sed -E 's/.*\"slug\":\"([^\"]+)\".*/\\1/'")
	_, _ = fmt.Fprintln(w, "end")
	_, _ = fmt.Fprintln(w)
	// Org-scoped and app-scoped leaf parsers accept these flags across
	// nested command families. Keep their values cache-backed even when
	// the parent cliCommand does not duplicate every leaf flag.
	_, _ = fmt.Fprintln(w, "complete -c gregale -f -n \"__fish_prev_arg_in --app\" -a \"(__gregale_cache_slugs apps)\"")
	_, _ = fmt.Fprintln(w, "complete -c gregale -f -n \"__fish_prev_arg_in --org\" -a \"(__gregale_cache_slugs orgs)\"")
	_, _ = fmt.Fprintln(w)
}

func renderFishCommand(w io.Writer, c cliCommand) {
	// Top-level command (when no subcommand matches).
	if len(c.Subcommands) == 0 {
		_, _ = fmt.Fprintf(w, "complete -c gregale -f -n \"__fish_use_subcommand\" -a %q -d %q\n",
			c.Name, c.Short)
	} else {
		verbList := make([]string, 0, len(c.Subcommands))
		for _, s := range c.Subcommands {
			verbList = append(verbList, s.Name)
		}
		_, _ = fmt.Fprintf(w, "complete -c gregale -f -n \"__fish_use_subcommand\" -a %q -d %q\n",
			c.Name, c.Short)
		// Subcommand completion.
		_, _ = fmt.Fprintf(w, "complete -c gregale -f -n \"__fish_seen_subcommand_from %s\" -a \"%s\"\n",
			c.Name, strings.Join(verbList, " "))
	}
	// Closed-set positional (plan).
	if len(c.ClosedSet) > 0 {
		_, _ = fmt.Fprintf(w, "complete -c gregale -f -n \"__fish_seen_subcommand_from %s\" -a \"%s\"\n",
			c.Name, strings.Join(c.ClosedSet, " "))
	}
	// Slug cache completion for any command whose first positional
	// is the <slug> marker (app, invoke, metrics, slo, wake-timeline).
	// Driven by cliCommand.hasSlugFirst — no hardcoded name list.
	if c.hasSlugFirst() {
		_, _ = fmt.Fprintf(w, "complete -c gregale -f -n \"__fish_seen_subcommand_from %s\" -a \"(__gregale_cache_slugs apps)\"\n",
			c.Name)
	}
	// Flags.
	for _, f := range c.Flags {
		_, _ = fmt.Fprintf(w, "complete -c gregale -f -n \"__fish_seen_subcommand_from %s\" -l %s -d %q\n",
			c.Name, f.Name, f.Short)
	}
}

func renderFishFooter(w io.Writer) {
	// No-op: fish has no main completion function.
}
