// commands/completion_bash.go — Tier A8 / ADR-083.
//
// `gregale completion bash` emits a bash 3.2-compatible completion
// script. The script:
//
//   1. Registers a single completion function for the `gregale`
//      command via `complete -F __gregale gregale`.
//   2. On each TAB, walks COMP_WORDS to figure out whether the
//      user is completing the top-level command, a subcommand, a
//      flag, or a flag value (closed-set enum).
//   3. Reads the slug cache via `gregale completion completion-cache-path` and
//      `gregale completion-cache-list <kind>` — two thin subcommands
//      that print the path or the cached slugs to stdout.
//
// Bash 3.2 ships with macOS — no `mapfile`, no associative arrays,
// no `[[ -v arr ]]`. We stick to `compgen -W` (whitespace-split
// word lists) and `case` for dispatch.
//
// The script is ~120 lines including the per-command dispatch
// table. Rendering is O(N) over cliCommands (≈ 50 entries) and
// emits no external state. Output to stdout so the user can
// `source <(gregale completion bash)` directly.

package main

import (
	"fmt"
	"io"
	"strings"
)

func cmdCompletionBash() int {
	w := osStdout
	renderBashHeader(w)
	for _, c := range customerCliCommands() {
		renderBashCommand(w, c)
	}
	renderBashFooter(w)
	return 0
}

// renderBashHeader writes the script prologue: shebang, the
// completion function signature, the dispatch table walker, and
// the helpers that read the slug cache via the binary.
//
// The function name `__gregale` is the conventional prefix for
// private completion helpers (see bash-completion upstream
// conventions). `__gregale_cache_path` and `__gregale_cache_slugs`
// are the bridge functions that talk to the binary.
//
// Slug-cache extraction is sed-based (slice from "<kind>":[ to the
// next "]") rather than grep -E with literal braces — bash 3.2's
// grep rejects unescaped '{' as a malformed quantifier, and even
// escaped "\{" requires careful shell-quoting. sed -n is portable
// across bash 3.2 / zsh / fish callers and never trips on the
// brace characters that appear throughout JSON.
func renderBashHeader(w io.Writer) {
	_, _ = fmt.Fprintln(w, "# bash completion for gregale — generated by `gregale completion bash`.")
	_, _ = fmt.Fprintln(w, "# Source via: source <(gregale completion bash)")
	_, _ = fmt.Fprintln(w, "# Or install: gregale completion bash > ~/.local/share/bash-completion/completions/gregale")
	_, _ = fmt.Fprintln(w)
	_, _ = fmt.Fprintln(w, "__gregale_cache_path() {")
	_, _ = fmt.Fprintln(w, "  gregale completion completion-cache-path 2>/dev/null")
	_, _ = fmt.Fprintln(w, "}")
	_, _ = fmt.Fprintln(w)
	_, _ = fmt.Fprintln(w, "__gregale_cache_slugs() {")
	_, _ = fmt.Fprintln(w, "  local kind=\"$1\"")
	_, _ = fmt.Fprintln(w, "  local path=\"$(__gregale_cache_path)\"")
	_, _ = fmt.Fprintln(w, "  if [ -z \"$path\" ] || [ ! -r \"$path\" ]; then return 1; fi")
	_, _ = fmt.Fprintln(w, "  sed -n \"/\\\"$kind\\\":\\[/,/]/p\" \"$path\" 2>/dev/null \\")
	_, _ = fmt.Fprintln(w, "    | sed -E \"s/.*\\\"$kind\\\":\\[//; s/\\].*//\" \\")
	_, _ = fmt.Fprintln(w, "    | grep -oE '\"slug\":\"[^\"]+\"' \\")
	_, _ = fmt.Fprintln(w, "    | sed -E 's/.*\"slug\":\"([^\"]+)\".*/\\1/'")
	_, _ = fmt.Fprintln(w, "}")
	_, _ = fmt.Fprintln(w)
	_, _ = fmt.Fprintln(w, "__gregale() {")
	_, _ = fmt.Fprintln(w, "  local cur prev words cword")
	_, _ = fmt.Fprintln(w, "  if type _get_comp_words_by_ref >/dev/null 2>&1; then")
	_, _ = fmt.Fprintln(w, "    _get_comp_words_by_ref -n = cur prev words cword")
	_, _ = fmt.Fprintln(w, "  else")
	_, _ = fmt.Fprintln(w, "    cur=\"${COMP_WORDS[COMP_CWORD]}\"")
	_, _ = fmt.Fprintln(w, "    prev=\"${COMP_WORDS[COMP_CWORD-1]}\"")
	_, _ = fmt.Fprintln(w, "    words=(\"${COMP_WORDS[@]}\")")
	_, _ = fmt.Fprintln(w, "    cword=$COMP_CWORD")
	_, _ = fmt.Fprintln(w, "  fi")
	_, _ = fmt.Fprintln(w)
	// App and organization slugs are also accepted as values for flags
	// on nested command families. Keep this check ahead of the command
	// dispatch so it works even where cli_meta only documents the parent
	// verb and the leaf parser owns the flag set.
	_, _ = fmt.Fprintln(w, "  if [ \"$prev\" = \"--app\" ]; then")
	_, _ = fmt.Fprintln(w, "    local slugs=\"$(__gregale_cache_slugs apps)\"")
	_, _ = fmt.Fprintln(w, "    COMPREPLY=( $(compgen -W \"$slugs\" -- \"$cur\") )")
	_, _ = fmt.Fprintln(w, "    return 0")
	_, _ = fmt.Fprintln(w, "  fi")
	_, _ = fmt.Fprintln(w, "  if [ \"$prev\" = \"--org\" ]; then")
	_, _ = fmt.Fprintln(w, "    local slugs=\"$(__gregale_cache_slugs orgs)\"")
	_, _ = fmt.Fprintln(w, "    COMPREPLY=( $(compgen -W \"$slugs\" -- \"$cur\") )")
	_, _ = fmt.Fprintln(w, "    return 0")
	_, _ = fmt.Fprintln(w, "  fi")
	_, _ = fmt.Fprintln(w)
	_, _ = fmt.Fprintln(w, "  local cmd=\"${words[1]}\"")
	_, _ = fmt.Fprintln(w, "  local sub=\"${words[2]}\"")
	_, _ = fmt.Fprintln(w)
}

// renderBashCommand emits one `if [ "$cmd" = "<name>" ]; then ... fi`
// block per cliCommand. The block handles subcommand completion,
// flag completion, and closed-set value completion for that command.
//
// The dispatch is nested case statements rather than a flat word
// table because bash case has no native string-set membership
// check that maps cleanly to a slice in Go.
func renderBashCommand(w io.Writer, c cliCommand) {
	_, _ = fmt.Fprintf(w, "  if [ \"$cmd\" = %q ]; then\n", c.Name)
	subcommandWord := c.completionSubcommandWord()
	slugWord := c.completionSlugWord()
	// `app` is the one slug-first command: offer the cached slug before
	// its verbs so `gregale app <TAB>` does not return early with only
	// `scale`, `rename`, and the other subcommands.
	if c.hasSlugFirst() && c.SubcommandsAfterPositionals {
		_, _ = fmt.Fprintf(w, "    if [ $cword -eq %d ]; then\n", slugWord)
		_, _ = fmt.Fprintln(w, "      local slugs=\"$(__gregale_cache_slugs apps)\"")
		_, _ = fmt.Fprintln(w, "      COMPREPLY=( $(compgen -W \"$slugs\" -- \"$cur\") )")
		_, _ = fmt.Fprintln(w, "      return 0")
		_, _ = fmt.Fprintln(w, "    fi")
	}
	// Subcommand completion.
	if len(c.Subcommands) > 0 {
		verbList := make([]string, 0, len(c.Subcommands))
		for _, s := range c.Subcommands {
			verbList = append(verbList, s.Name)
		}
		_, _ = fmt.Fprintf(w, "    if [ $cword -eq %d ]; then\n", subcommandWord)
		_, _ = fmt.Fprintf(w, "      COMPREPLY=( $(compgen -W %q -- \"$cur\") )\n", strings.Join(verbList, " "))
		_, _ = fmt.Fprintln(w, "      return 0")
		_, _ = fmt.Fprintln(w, "    fi")
	}
	// Closed-set positional completion (today: `plan`).
	// The ClosedSet IS the positional — `plan` has no Positionals
	// field because its allowed values ARE the closed set, not a
	// free-form <slug>. We gate on ClosedSet alone.
	if len(c.ClosedSet) > 0 {
		_, _ = fmt.Fprintf(w, "    if [ $cword -eq 2 ]; then\n")
		_, _ = fmt.Fprintf(w, "      COMPREPLY=( $(compgen -W %q -- \"$cur\") )\n", strings.Join(c.ClosedSet, " "))
		_, _ = fmt.Fprintln(w, "      return 0")
		_, _ = fmt.Fprintln(w, "    fi")
	}
	// Slug cache completion for any command whose first positional
	// is the <slug> marker (app, invoke, metrics, slo, wake-timeline).
	// Driven by cliCommand.hasSlugFirst — no hardcoded name list.
	if c.hasSlugFirst() && !c.SubcommandsAfterPositionals {
		_, _ = fmt.Fprintf(w, "    if [ $cword -eq %d ]; then\n", slugWord)
		_, _ = fmt.Fprintln(w, "      local slugs=\"$(__gregale_cache_slugs apps)\"")
		_, _ = fmt.Fprintln(w, "      COMPREPLY=( $(compgen -W \"$slugs\" -- \"$cur\") )")
		_, _ = fmt.Fprintln(w, "      return 0")
		_, _ = fmt.Fprintln(w, "    fi")
	}
	// Flag completion (works at every cword after the verb/sub).
	if len(c.Flags) > 0 {
		flagList := make([]string, 0, len(c.Flags))
		for _, f := range c.Flags {
			flagList = append(flagList, "--"+f.Name)
		}
		_, _ = fmt.Fprintln(w, "    case \"$cur\" in")
		_, _ = fmt.Fprintln(w, "      -*)")
		_, _ = fmt.Fprintf(w, "        COMPREPLY=( $(compgen -W %q -- \"$cur\") )\n", strings.Join(flagList, " "))
		_, _ = fmt.Fprintln(w, "        return 0")
		_, _ = fmt.Fprintln(w, "        ;;")
		_, _ = fmt.Fprintln(w, "    esac")
	}
	_, _ = fmt.Fprintln(w, "    return 0")
	_, _ = fmt.Fprintln(w, "  fi")
	_, _ = fmt.Fprintln(w)
}

// renderBashFooter writes the script epilogue: the top-level
// fallback (complete with all top-level command names when no
// subcommand yet), the `complete -F` registration, and the helper
// that loads bash-completion's `_get_comp_words_by_ref` if it's
// already on the fpath.
func renderBashFooter(w io.Writer) {
	_, _ = fmt.Fprintln(w, "  # Top-level: complete all known commands.")
	_, _ = fmt.Fprintln(w, "  if [ $cword -eq 1 ]; then")
	commands := customerCliCommands()
	allCmds := make([]string, 0, len(commands))
	for _, c := range commands {
		allCmds = append(allCmds, c.Name)
	}
	_, _ = fmt.Fprintf(w, "    COMPREPLY=( $(compgen -W %q -- \"$cur\") )\n", strings.Join(allCmds, " "))
	_, _ = fmt.Fprintln(w, "    return 0")
	_, _ = fmt.Fprintln(w, "  fi")
	_, _ = fmt.Fprintln(w, "}")
	_, _ = fmt.Fprintln(w)
	_, _ = fmt.Fprintln(w, "complete -F __gregale gregale")
}
