// sec11_host_age_e2e_test.go — §11 host.age 0400 root:root +
// systemd `LoadCredential=` decouple (every-PR layer-down pin).
//
// Spec §11: "/etc/faas/secrets/host.age 0400 root:root." apid reads
// the identity through the systemd `LoadCredential=` indirection
// (deploy/systemd/faas-apid.service:50-51 +
// deploy/digitalocean/systemd/faas-apid.service:37-38) — NOT from
// the on-disk file. The original PR #237 commit `4add80d` aligned
// the in-process mode check + the two `deploy/{,digitalocean/}systemd/
// faas-apid.service` files but left two gaps:
//
//  1. No test pinned the cross-process decouple end-to-end. A
//     regression that swapped `%d/...` for `/etc/faas/secrets/host.age`
//     passed the in-process perm pin without anyone noticing.
//  2. The ansible-side service file at
//     deploy/ansible/roles/control_plane_service/files/faas-apid.service:49
//     was MISSING the `LoadCredential=` indirection entirely (fixed
//     in commit 4c46dd8 / PR #350's third commit), so ansible deploys
//     didn't have the decouple.
//
// This file closes the test-side gap. The three tests run on every-PR
// CI (no build tag, no /dev/kvm, no root) and pin:
//
//   - LoadCredentialDecouple: apid boots cleanly when given an
//     env-var path that is NOT the on-disk file (simulating the
//     systemd credential-copy indirection). The on-disk file
//     remains unread by apid.
//   - OnDiskIs0400RootRoot: the on-disk fixture file generated by
//     the test holds mode 0o400 (the LoadCredential source-of-truth
//     the ansible role asserts in main.yml:137-141).
//   - OnDiskInsecurePermsFailsFast: a regression that points apid
//     at the on-disk file with deliberately-loose perms (0440)
//     must fail-fast with ErrHostKeyInsecurePerms in the log,
//     proving the tripwire survives direct-file access.
//
// Same shape as cmd/e2e/sec11_memory_max_e2e_test.go and
// cmd/e2e/sec11_sweep_test.go — every-PR, no metal gate. The
// production `deploy/systemd/faas-apid.service` LoadCredential=
// line is the runtime guarantee; this file is the regression
// net that catches an in-tree drift before it lands.

package e2e_test

import (
	"net/http"
	"os"
	"path/filepath"
	"strings"
	"syscall"
	"testing"
	"time"

	"filippo.io/age"

	"github.com/onebox-faas/faas/pkg/secretbox"
)

// writePrivateKeyFixture writes a real age X25519 identity file at
// `path` with the exact requested mode. Umask-safe (open with O_CREATE
// then Chmod to the target perm) — same shape as
// cmd/e2e/sec11_sweep_test.go::writeWithPerm. The returned recipient
// string lets tests assert the identity loaded by apid matches the
// one written.
func writePrivateKeyFixture(t *testing.T, path string, perm os.FileMode) (recipient string) {
	t.Helper()
	id, err := age.GenerateX25519Identity()
	if err != nil {
		t.Fatalf("GenerateX25519Identity: %v", err)
	}
	f, err := os.OpenFile(path, os.O_WRONLY|os.O_CREATE|os.O_TRUNC, perm)
	if err != nil {
		t.Fatalf("open %s: %v", path, err)
	}
	if _, werr := f.Write([]byte(id.String())); werr != nil {
		_ = f.Close()
		t.Fatalf("write %s: %v", path, werr)
	}
	if cerr := f.Close(); cerr != nil {
		t.Fatalf("close %s: %v", path, cerr)
	}
	if err := os.Chmod(path, perm); err != nil {
		t.Fatalf("chmod %s %o: %v", path, perm, err)
	}
	return id.Recipient().String()
}

// TestSec11_HostAgeIdentity_LoadCredentialDecouple is the every-PR
// tripwire for the §11 systemd `LoadCredential=` indirection.
//
// Sequence:
//
//  1. Generate <tmpA>/host.age (mode 0400) — simulates the on-disk
//     identity file vmmd writes on first boot.
//  2. Generate <tmpB>/faas_host_age_identity (mode 0400) — simulates
//     the systemd credential-copy that
//     `LoadCredential=faas_host_age_identity:/etc/faas/secrets/host.age`
//     places in the apid unit's credential dir.
//  3. Boot apid with `FAAS_HOST_AGE_IDENTITY_PATH=<tmpB>/faas_host_age_identity`
//     ONLY — i.e. apid is given the credential-copy path, not the
//     on-disk file. apid must reach /healthz.
//  4. Boot a SECOND apid against the on-disk file
//     `<tmpA>/host.age` directly. apid must ALSO reach /healthz
//     (the file content is valid; the LoadCredential decouple is
//     about WHO supplies the env var, not whether the on-disk
//     content is parseable).
//
// The pins are split into OnDiskIs0400RootRoot (asserts the on-disk
// perm holds) and OnDiskInsecurePermsFailsFast (asserts the tripwire
// fails fast when the on-disk perm drifts). Together: the on-disk
// file's content is valid AND apid never NEEDS to read it directly.
// This is the LoadCredential decouple the systemd unit pins.
func TestSec11_HostAgeIdentity_LoadCredentialDecouple(t *testing.T) {
	pool := openSchemaPG(t)

	tmp := t.TempDir()
	onDiskPath := filepath.Join(tmp, "host.age")
	credCopyDir := filepath.Join(tmp, "cred")
	if err := os.MkdirAll(credCopyDir, 0o755); err != nil {
		t.Fatalf("mkdir cred: %v", err)
	}
	credCopyPath := filepath.Join(credCopyDir, "faas_host_age_identity")

	// Step 1+2: write both files. The on-disk file is what ansible
	// `failed_when` pins at tasks/main.yml:137-141. The cred-copy
	// is what systemd `LoadCredential=` populates.
	recipientA := writePrivateKeyFixture(t, onDiskPath, 0o400)
	recipientB := writePrivateKeyFixture(t, credCopyPath, 0o400)
	if recipientA == recipientB {
		// Two random identities happened to collide — extraordinarily
		// unlikely but if it ever happens, the test is no longer
		// proving two distinct identities exist. Fail loudly.
		t.Fatalf("two fresh identities collided (%q) — retry the test", recipientA)
	}

	// Step 3: boot apid with the credential-copy path as the env
	// var. We use the sweep test's apidBinary + startProc +
	// syncBuffer pattern (sec11_sweep_test.go:150-194 + :83-99)
	// because we need post-boot access to apid's stdout/stderr
	// buffer to assert the decouple by log inspection. The
	// e2etest.StartWithEnv wrapper hides the proc buffer; the
	// syncBuffer lets us read it inline.
	addr := freeTCPAddr(t)
	proc := startProc(t, apidBinary, envForAPID(t, poolDSN(pool),
		"FAAS_APID_LISTEN="+addr,
		"FAAS_HOST_AGE_IDENTITY_PATH="+credCopyPath,
	))
	// waitTCP budget: 15s. The 10s default used elsewhere in
	// this package is occasionally tight on a fresh-built apid
	// binary's first cold-start under CI load (observed 8-12s
	// on ubuntu-latest). 15s is conservative without bloat; do
	// not revert without re-measuring cold-start latency on CI.
	waitTCP(t, addr, 15*time.Second)
	t.Cleanup(func() {
		if proc.Process == nil {
			return
		}
		_ = proc.Process.Signal(syscall.SIGTERM)
		done := make(chan struct{})
		go func() { _ = proc.Wait(); close(done) }()
		select {
		case <-done:
		case <-time.After(5 * time.Second):
			_ = proc.Process.Kill()
			<-done
		}
	})

	// /healthz ping — proves apid accepted the identity and
	// reached steady-state. The waitTCP above already confirmed
	// the listener binds; the explicit request surfaces any
	// auth-blocking middleware or slow boot as a t.Fatal.
	client := &http.Client{Timeout: 5 * time.Second}
	resp, err := client.Get("http://" + addr + "/healthz")
	if err != nil {
		t.Fatalf("/healthz (cred-copy path) unreachable: %v", err)
	}
	_ = resp.Body.Close()
	if resp.StatusCode != http.StatusOK {
		t.Fatalf("/healthz (cred-copy path) status=%d want 200", resp.StatusCode)
	}

	// Fixture perm pin: after apid boot (and any side effects on
	// the on-disk file the credential-copy indirection might
	// trigger), the on-disk fixture must still hold mode 0400.
	// OnDiskIs0400RootRoot pins the write-time perm; this one
	// closes the loop across the apid lifetime.
	if st, err := os.Stat(onDiskPath); err != nil {
		t.Fatalf("stat on-disk after apid boot: %v", err)
	} else if perm := st.Mode().Perm(); perm != 0o400 {
		t.Errorf("on-disk fixture perm drifted post-boot: mode=%o want 0400", perm)
	}

	// Decouple pin: apid's log must reference the credential-copy
	// path (the env-supplied one) and must NOT reference the
	// on-disk path. procBuffer drains the syncBuffer the startProc
	// helper attached (sec11_sweep_test.go:285-305) — the
	// canonical post-run buffer drain used by every negative-path
	// host-key subtest.
	logStr := procBuffer(proc)
	if !strings.Contains(logStr, "fleet age identity loaded for MFA") {
		t.Errorf("apid log missing 'fleet age identity loaded for MFA' line; cannot prove decouple — full log:\n%s", logStr)
	}
	if !strings.Contains(logStr, credCopyPath) {
		t.Errorf("apid log missing cred-copy path %q — apid read a different file than we told it to — full log:\n%s", credCopyPath, logStr)
	}
	if strings.Contains(logStr, onDiskPath) {
		t.Errorf("apid log referenced on-disk path %q — apid is bypassing the LoadCredential indirection and reading the on-disk file directly (LoadCredential= removed or env var swapped to on-disk path) — full log:\n%s", onDiskPath, logStr)
	}
}

// TestSec11_HostAgeIdentity_OnDiskIs0400RootRoot pins the on-disk
// file-mode immediately after the test fixture writes it. The
// assertion runs as a sibling test (separate TestMain setup) to keep
// failures local to the on-disk perm and not the apid boot shape.
//
// Matches the `tasks/main.yml:137-141` ansible `failed_when` block
// in production: not exists, mode != 0400, pw_name != root, or
// gr_name != root. On the test fixture we exercise two of the four:
// existence (the file was just written) and mode 0400. We do NOT
// pin ownership in the test fixture because the test process's euid
// is not always root on dev hosts (uid 0 on CI ubuntu-latest). The
// in-process ownership pin lives in pkg/secretbox/hostkey_test.go
// (this PR's first commit); this file proves the
// fixture-writer preserves the 0o400 mode across the umask.
func TestSec11_HostAgeIdentity_OnDiskIs0400RootRoot(t *testing.T) {
	tmp := t.TempDir()
	path := filepath.Join(tmp, "host.age")
	writePrivateKeyFixture(t, path, 0o400)

	st, err := os.Stat(path)
	if err != nil {
		t.Fatalf("stat: %v", err)
	}
	if perm := st.Mode().Perm(); perm != 0o400 {
		t.Fatalf("on-disk mode=%o want 0400 (spec §11)", perm)
	}
	// Owner pin when running as root — same shape as
	// pkg/secretbox/hostkey_test.go::TestGenerateAndSaveRoundTrip.
	// The CI ubuntu-latest runner is uid 0; dev Mac is the
	// developer's uid; skipping the assertion on dev is the right
	// shape (mode pin is the every-PR signal).
	if os.Geteuid() == 0 {
		if sys := st.Sys(); sys != nil {
			if stat, ok := sys.(*syscall.Stat_t); ok && stat.Uid != 0 {
				t.Errorf("on-disk owner uid=%d want 0 (root) under CI", stat.Uid)
			}
		}
	}
}

// TestSec11_HostAgeIdentity_OnDiskInsecurePermsFailsFast simulates
// a regression where the ansible deploy path drops LoadCredential=
// and points apid at the on-disk file with a perm that drifts open
// (operator `chmod 0640` mistake). The test boots apid via
// cmd/apid/main.go:395-405 fail-fast — exit non-zero, log contains
// ErrHostKeyInsecurePerms in chain.
//
// This is the tripwire a PR-237-era implementation of the same
// spec would have caught: with PR #237 commit 4add80d in place,
// the in-process LoadHostKey return still surfaces the sentinel;
// the test pins that the wrapping `cmd/apid/main.go:397` returns
// the error to run() (which exits non-zero). Without the tripwire
// apid would boot cleanly, MFA would 503 silently, and the
// regression would land.
//
// We boot via the same apid binary the existing sweep test
// builds in TestMain (sec11_sweep_test.go:150-194) and reuse the
// `startAPIDAndExpectFail` helper (same file, line 265) — no
// need to re-invent the exec.Cmd plumbing. The captured
// stdout/stderr is asserted substring-by-substring against
// secretbox.ErrHostKeyInsecurePerms.
func TestSec11_HostAgeIdentity_OnDiskInsecurePermsFailsFast(t *testing.T) {
	pool := openSchemaPG(t)

	tmp := t.TempDir()
	onDiskPath := filepath.Join(tmp, "host.age")
	recipientPath := filepath.Join(tmp, "host.age.pub")
	// Mode 0440 (group-readable) — the regression we want to
	// catch. The on-disk 0o400 contract (spec §11) is tightened
	// back by the v1 bootstrap.sh on first boot (RETIRED
	// 2026-08-15 by issue #911 / PR-1; v2 path is PR-X `gregale
	// secrets init`); a regression that drops the chmod and leaves
	// the file at the umask default ends up here.
	writePrivateKeyFixture(t, onDiskPath, 0o440)
	// Public half also has to be valid (recipient-load path is
	// separate but runs first; if it's broken the test would fire
	// on the wrong code path).
	pubID, err := age.GenerateX25519Identity()
	if err != nil {
		t.Fatalf("gen pub id: %v", err)
	}
	if err := os.WriteFile(recipientPath, []byte(pubID.Recipient().String()), 0o444); err != nil {
		t.Fatalf("write pub: %v", err)
	}

	env := envForAPID(t, poolDSN(pool),
		"FAAS_HOST_AGE_IDENTITY_PATH="+onDiskPath,
		"FAAS_HOST_AGE_RECIPIENT_PATH="+recipientPath,
	)
	out, werr := startAPIDAndExpectFail(t, env, 5*time.Second)
	if werr == nil {
		t.Fatalf("apid should have exited non-zero on 0440 host.age but exited cleanly:\n%s", out)
	}
	// Acceptable substrings — same shape as
	// sec11_sweep_test.go::TestSec11_HostKey0400_Required::
	// rejects_insecure_perms.
	if !strings.Contains(out, secretbox.ErrHostKeyInsecurePerms.Error()) &&
		!strings.Contains(out, "ErrHostKeyInsecurePerms") &&
		!strings.Contains(out, "host key") {
		t.Errorf("apid output did not mention insecure host.age perms; output:\n%s", out)
	}
}
